### ISSUE TITLE
Update client-side Blazor debugging instructions page to allow for Edge

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10163]
When you hit Shift-Alt-D in a client-side Blazor app you see a page with instructions for running Chrome with remote debugging enabled so that you can debug your client-side Blazor app in the browser. These same instructions now work with the Chromium based version of Edge, so we should update these instructions to no longer be Chrome specific.

**Comment by jbomhold3** [comment]
Edge Chromium still reports as  Chrome. so detecting it is unreliable that might not break once edge comes out of dev. The vendor is even still reporting as Google Inc. How about including the instructions for both.   Is this approach is good I will send a pr for it

MonoDebugger.ts
line 29   console.error('Currently, only Chrome Or Edge Dev is supported for debugging.');

BlazorMonoDebugProxyAppBuilderExtensions.cs 

line 97 ... Ensure Chrome or Edge Dev is running .....

Windows  lines 147 - 151     Order Because Edge is still in dev
   return $@"<p>Close any instance of this browser, then press Win+R and enter the following:</p>
   <p><strong><code>""%programfiles(x86)%\Google\Chrome\Application\chrome.exe"" --remote-debugging-port=9222 {appRootUrl}</code></strong></p>";
   <p><strong><code>""%programfiles(x86)%\Microsoft\Edge Dev\Application\msedge.exe"" --remote-debugging-port=9222 {appRootUrl}</code></strong></p>";

Linux does not need any changes as there is not edge chromium for Linux.

Mac lines 157 - 161
    return $@"<p>Close all Chrome instances, then in a terminal window execute the following:</p>
                          <p><strong><code>open /Applications/Google\ Chrome.app --args --remote-debugging-port=9222 {appRootUrl}</code></strong></p>";
                          <p><strong><code>open /Applications/Microsoft\ Edge\ Dev.app --args --remote-debugging-port=9222 {appRootUrl}</code></strong></p>";
