### ISSUE TITLE
Enable overriding authentication schemes for SignInManager<T>

### ISSUE THREAD

**Issue by BickelLukas** [aspnet/AspNetCore#10202]
### Is your feature request related to a problem? Please describe.
SignInManager<T> uses the schemes from IdentityConstants directly in multiple methods. This makes it very cumbersome to use if not using the default authentication scheme.

### Describe the solution you'd like
Provide a virtual Property that specifies the scheme that will be used in the SignInManager. This way I can override this Property and don't have to copy the logic of all the methods just to override the scheme.

**Comment by blowdart** [comment]
Could you explain what are you trying to achieve, rather than what you want changed in SignInManager?

**Comment by BickelLukas** [comment]
I am trying to sign the user in to a different Cookie Scheme that the default one thats created by Identity. 

The reason is that we have a seperate login for Admins in our application and to achieve that I created a second Cookie Scheme for the Admin Cookies.

```cs
            services.AddIdentity<ApplicationUser, ApplicationRole>();

            services.AddIdentityCore<AdminUser>()
                .AddRoles<AdminRole>()
                .AddUserManager<AdminUserManager>()
                .AddSignInManager<AdminSignInManager>();

...

            services.AddAuthentication()
                .AddCookie(AuthenticationSchemes.AdminScheme, o =>
                {
                    o.LoginPath = new PathString("/Admin/Login");
                });
```

Now when I call `SignInAsync` in the `AdminSignInManager` I want to sign in to `AuthenticationSchemes.AdminScheme` instead of `IdentityConstants.ApplicationScheme` since that is used by the `ApplicationUser`

**Comment by blowdart** [comment]
What's the reasoning behind having a second cookie scheme, rather than, say, a claim on the user?

Honestly you're pretty far outside what we'd see as typical use once you start adding multiple identity configurations, so it's unlikely we'd make this change.

**Comment by BickelLukas** [comment]
The reasoning is because we need to support signing in to both schemes simultaneously (user impersonation for admins) and we need different lifetimes for Admin and Application Cookie.

**Comment by blowdart** [comment]
I can understand your scenario, but this isn't a supported scenario I'm afraid, and not something we're going to support.

**Comment by slaneyrw** [comment]
Another scenario is that there is an intermediate cookie state between passing First/Second factors and being fully authenticated.

We need to pass "Ideal User" checks before the user is considered fully authenticated 

- Is Two Factor setup
- Is email entered and/or confirmed
- Is phone entered and/or confirmed
- Does password need to be rotated ( expired, etc )
- Profile information missing

If the SignInManager uses the default authentication scheme after passing First/Second factors then we have to create many authorization policies as we have to interrogate the state of the user with the default scheme in order to secure pages they can't access until the state is correct.  It's a lot more straight forward to create a "partial sign in" cookie scheme out of the SignInManager's PasswordSignInAsync or TwoFactorSignInAsync.
