### ISSUE TITLE
Public parameters in Components don't result in warnings

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#10244]
Just tried to add `public `access modifier for property that have `[Parameter]` attribute. This was not allowed in previous versions of Blazor. Is this something that is now allowed to do?

eg.
```
[Parameter]
public bool IsDisabled { get; set; }
```

**Comment by montyclt** [comment]
I used `[Parameter]` in public properties without any problem. There is any reason to keep parameter properties protected?. I only tried it inhering from a class, so my public parameter was on "code-behind" class. I understand that I cannot use private properties in my "code-behind" class because the component class (that extends the "code-behind" class) need to access to the properties.

**Comment by mkArtakMSFT** [comment]
We do not enforce parameters to not be public. However we recommend these to not be public, so that the state of components can't be set in unsupported ways.

You should, however received a warning message, and it seems that the Analyzer didn't work as expected here. We're going to look into that as part of this issue.

**Comment by mkArtakMSFT** [comment]
This is going to be obsolete when we do https://github.com/aspnet/AspNetCore/issues/8825
