### ISSUE TITLE
Add new lifecycle event that runs after page loads but before AfterRender

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10262]
### Describe the bug
A new life cycle method which can be called after web page load and before AfterRender life cycle method. This is useful to process the javascript actions which make sure the components rendered properly in AfterRender.
Is there any way to achieve this? Can anyone share the concerns?

### Additional context
i have used VS2019 Preview3
.NET Core SDK Preview 5.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmuthukumar23.
Prerendering is already supported and it's enabled on the server-side blazor project. We've enabled client-side blazor prerendering and are going to provide a sample as soon as that ships.

**Comment by danroth27** [comment]
This issue was opened by the folks at Syncfusion. Updating the title to clarify their ask.

**Comment by kmuthukumar23** [comment]
Hi @danroth27 

We have attached the issue repro sample for your reference. In that sample we can see the blink during the component is rendered. 

https://muthukumar3032.azurewebsites.net/syncfusion-sample/

[blazorPreRender.zip](https://github.com/aspnet/AspNetCore/files/3187075/blazorPreRender.zip)

Please suggest us how we prevent this.

**Comment by fs86** [comment]
> Please suggest us how we prevent this.
I would like to know that too.

**Comment by Lupusa87** [comment]
#7708

**Comment by danroth27** [comment]
@kmuthukumar23 With server-side Blazor apps the .NET based components are prerendered on the server. You see a delay before your JS based components render because the JS code is executed after the connection with the server is established. 

You could potentially reduce this delay by running any required JS code client-side after the prerendered response loads. 

Hypothetically you could also try to run your JS server-side as part of the prerendering step, but this would likely be complicated and difficult for you and your users to setup (requires installing node on the server, perf & consistency issues, etc.)

I'm not sure how introducing a new component lifecycle event would help any of this. Why is the existing AfterRender event not sufficient?

**Comment by Knudel** [comment]
Or you could introduce an OnPrerenderInit() and OnPrerendeInitAsync and the current OnInit and OnInitAsync are javascript save (how it was).

**Comment by ajithr** [comment]
@danroth27 The pre-render life cycle method need to be trigger at the time of JSRuntime completely initialized. So, that it will be useful to call the jsinterop and process client side functionalities before the components will render in the browser.

**Comment by danroth27** [comment]
@javiercn Thoughts on this?

**Comment by javiercn** [comment]
Prerender runs on the server, where there is no JavaScript environment available. There is nothing we can do about the blink at the framework level. 

Its up to the component developer to inject the required JavaScript after the prerendered components in order to minimize/prevent the flickering.

> You could potentially reduce this delay by running any required JS code client-side after the prerendered response loads.

As @danroth27 mentions, that's the best approach to take

**Comment by javiercn** [comment]
@kmuthukumar23 Based on what I see from the components in your repro, they don't produce any meaningful content during prerendering, likely because most of the rendering logic is performed in JavaScript. There are a couple of things you can do about it:
* Better support prerendering scenarios by moving the rendering logic from JavaScript to .NET.
  * You could strike a middle-ground and prerender a basic (meaningful) version that gets prerendered and an enhanced version that gets updated after the first version. If you keep the look and feel the same between both versions there should be no flickering. You could even use some visual styles on the prerendered version to indicate the component is not fully loaded and not fully ready to interact with, and once JavaScript is available, enhance the component.
* You could completely bail-out of prerendering the component by rendering a placeholder with a loading animation or similar, and waiting for the connection and the data to be available in order to render the component.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
