### ISSUE TITLE
[Feature Request] Atomic operation for ChangeEmailAsync and SetUserNameAsync

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore#10260]
### Background
Many systems use email as username.

### Problem
If I need to change a username or email, I need to change both. So I need to make two calls:
````csharp
_userManager.ChangeEmailAsync(...);
_userManager.SetUserNameAsync(...);
````

If one of those two calls fail, then the user's account will be left in an inconsistent state. At worst, he'll lose his account.

There is also the possibility of someone else using the new email address during those two change operations - which would then leave two accounts in an inconsistent state.

### Workaround
This race condition can be avoided by dealing with the underlying `IdentityDbContext` directly. But that requires significant effort (because `UserManager` does much more than just set entity properties).

### Solution
We need a new method that performs the operation atomically. For example:

````csharp
_userManager.ChangeEmailAndUsernameAsync(...);
````

It should run within a transaction, and if either sub-operation fails, then the entire thing should fail.

**Comment by blowdart** [comment]
The reason this happens is because Email and Username are separate concepts, even though the templates treat them then same. Identity simply doesn't do this, it's not as if these two things are special, you can't do any atomic changes.

You either have to abandon using the store and drop down to EF and use transactions, or write manual rollbacks. 

I am afraid there's no plans to improve this for now.

**Comment by lonix1** [comment]
I realise they are separate concepts - but my point is that in many systems they are the same concept, so it would be nice to have support.

Doing this directly in EF with change tokens, authentication, authorization, and all that machinery is a pain.

Anyways, thanks for your reply, and I hope you'll reconsider if enough devs ask for this.
