### ISSUE TITLE
Webassembly-multithreading has to be high priority

### ISSUE THREAD

**Issue by salarzobir** [aspnet/AspNetCore#10343]
I want to do projection transformation for thousends of features in map using blazor webassembly, but because it is single-threaded i have to do this in backend server.

I want to send this .dll to the browser and do the heavy work their using multithreading.
Multithreading is already works in Rust-Webassembly and C++.
If Blazor will not have multithreading then there is no much difference between Blazor and Javascript. For me the main feature that i want to use in blazor is multithreading.

As alternative maybe something like C++ interop that works with multithreading can do the work.

Please give this feature a high priority.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. I'd recommend following up with https://github.com/mono/mono, since that's the runtime we're using, and support for multithreading is entirely determined by what that runtime supports.

AFAIK, only Chrome has so far shipped support for the WebAssembly threading proposal.

Closing as external.

**Comment by IngweLand** [comment]
https://github.com/mono/mono/issues/12453
