### ISSUE TITLE
Question: Will signalR support gRPC?

### ISSUE THREAD

**Issue by darrenfurr** [aspnet/AspNetCore#10403]
My understanding is that SignalR supports TCP binding, but is it in the roadmap to for signalR to implement gRPC? 

I'd like to continue to use signalR interfaces, hubs, etc, but have it use gRPC under the covers. IE: Instead of WebSockets it uses HTTP/2.

Thanks.

**Comment by shirhatti** [comment]
Assuming I understood correctly, it sounds like you want an HTTP/2 transport for SignalR and your request doesn't really involve gRPC. As such I'm deferring to SignalR folks to take a stab at answering that.

**Comment by anurse** [comment]
No, we don't have plans to integrate gRPC and SignalR tightly like this. We may develop an HTTP/2 transport in the future, but it's not a high priority right now.

**Comment by nvcken** [comment]
Hope this would help https://github.com/Cysharp/MagicOnion

**Comment by SeanChristopherConway** [comment]
@nvcken How is your experience with this?

**Comment by nvcken** [comment]
Sorry @SeanChristopherConway , just quick search for reference.

**Comment by nmocruz** [comment]
seems like there's a gRPC-Web support (not sure if still experimental) websockets to overcome some limitation on http2 native support on the browser. this support requires a websocket enabled server.
Maybe signalr can help enabling the client streaming and the bidirectional part that is not fully supported by browsers. 
But because they are completely technologies, maybe  have signalr support for a transport/format using protobuf,  and in the grcp serve a way to enable the websocket, so people could using with the grpc-Web in browsers.
