### ISSUE TITLE
[Question] How to add Custom JsonConverter to Blazor Client application

### ISSUE THREAD

**Issue by redradist** [aspnet/AspNetCore#10404]
I have created my own custom JsonConverter for custom data structure ... But I can use it only with JsonConvert.DeserializeObject directly
It would be nice somehow to register in Blazor Client Application Custom JsonConverter
But using services.AddMvc() it is not possible because is not found anywhere in assembly as extension method

How to add custom JsonConverter ?

**Comment by SteveSandersonMS** [comment]
It depends what you're trying to do. In what way do you want the framework to make use of your converter?

Is it when you call HTTP methods like `Http.GetJsonAsync`? If so, that's never going to use Json.NET converters since it doesn't use Json.NET internally. It uses SimpleJSON (which is something we're in process of changing currently - we're moving to the new System.Text.Json library everywhere).

If you want to use Json.NET to deserialize HTTP responses, consider replacing calls to `Http.GetJsonAsync` with `Http.GetStringAsync` and passing the string to your chosen deserializer.

**Comment by redradist** [comment]
Okay, thanks !!

Seems like Http.GetStringAsync is exactly what I want ...
But I'm curious why you have not added customization point for JsonConverter ?
Also it is not obvious why you have different Json converter on Server side and Front-End side. On server side it is possible to add option to NewtonsoftJson:

`csharp
services.AddMvc().AddNewtonsoftJson(...)
`
But on Front-End side it is not possible ( It would be nice to have possibility to add same service as on Back-End as on Front-End side ...
