### ISSUE TITLE
Test cancellation of SignalR .NET Client startup

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#10432]
Prior to https://github.com/aspnet/AspNetCore/pull/10140, cancelling the token passed into SignalR's HubConnection.StartAsync() would cancel the hub handshake, but it would not cancel negotiate requests or calls to ITransport.StartAsync() which previously didn't even take a CancellationToken as a parameter.

We should add tests to verify that HubConnection.StartAsync() cancels both long-running negotiate requests, and long-running attempts to start all the built-in transports.

**Comment by BalintFarkas** [comment]
@halter73 I worked with @danielloczi on the PR fixing this issue. I volunteer to create the unit tests - may I? :)

**Comment by halter73** [comment]
Yes, please! Thanks. Ping me if we need any early help or feedback.

**Comment by anurse** [comment]
Hey @BalintFarkas do you expect to be able to do the tests in the next week or so? Just want to get an idea of the timing here and on if we need to jump in. Keep us posted!

**Comment by BalintFarkas** [comment]
Hey @anurse , definitely, I was planning to begin work this weekend.

Can you maybe point me to an unit test that's similar to the ones I'll be writing here, to use as a template/best practice? If you don't have time I'll find one myself, no problem :)

**Comment by anurse** [comment]
So [HttpConnectionTests.ConnectionLifecycle.cs](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/csharp/Client/test/UnitTests/HttpConnectionTests.ConnectionLifecycle.cs) is where I would start since this is related to the connection lifecycle methods (`Start`/`Stop`/etc.). There are a number of tests related to `StartAsync` in there. We also have some tests for cancellation already (i.e. the places where the cancellation token **was** previously checked).

There's a `TestHttpHandler` class that lets you register handlers for the various outgoing HTTP request triggered by the client (such as the negotiate request). And there's a component called [`SyncPoint`](https://github.com/aspnet/AspNetCore/blob/master/src/Shared/SyncPoint/SyncPoint.cs) which pairs up two `TaskCompletionSource`s to make an easy-to-use "marker" point to ensure the client gets to a certain point before you do something (such as cancelling the cancellation token). For example, a possible test could be something like this rough pseudo-code:

```csharp
var syncPoint = new SyncPoint();
var testHttpHandler = new TestHttpMessageHandler(autoNegotiate: false);
testHttpHandler.OnNegotiate(async (request, cancellationToken) => {
	// Wait here for the test code to cancel the "outer" token
	await syncPoint.WaitToContinue();

	// Cancel
	cancellationToken.ThrowIfCancellationRequested();
});

// This was our hack around not having 'await using' pre-C# 8...
await WithConnectionAsync(
	CreateConnection(testHttpHandler),
	async (connection) => {
		var cts = new CancellationTokenSource();

		// Kick off StartAsync but don't wait for it.
		var startTask = connection.StartAsync(cts.Token);
 		
		// Now, we wait for the connection to get to the "WaitToContinue" call above.
		await syncPoint.WaitForSyncPoint();
		// You could test here that startTask is still running and not cancelled..

		// Now cancel the CTS and "release" the Sync Point so the negotiate handler can keep going
		cts.Cancel();
		syncPoint.Continue();

		// Now expect start to be cancelled
		await Assert.ThrowsAsync<OperationCancelledException>(() => startTask);
	});
```

There are of course a number of other places where cancellation could occur, and the scenarios @halter73 mentioned above. There are also functional tests [here](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs) which run against the server [here](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/csharp/Client/test/FunctionalTests/Startup.cs). You can make a "fake" `/some-test-hub/negotiate` endpoint that never returns, for example, to test that triggering the CTS causes the client to stop even if the negotiate request is in progress.

Also, feel free to start with some simple tests and open a draft PR. We're happy to help with other edge cases and answer questions you have about the test infrastructure!

**Comment by BalintFarkas** [comment]
Thank you - I'll send my draft PR later this week!

**Comment by anurse** [comment]
Hey @BalintFarkas, we do want to get these tests in before preview 7 (which closes at the end of June). If you even just submit an initial PR with some tests (to get that sweet sweet contributor cred ;)) we can take it from there. By next week we'll probably have to just take this on ourselves. Sorry we missed the original recognition! If we aren't able to get you recognized in the tests, we'll try to keep an eye out for any other contributions you make and make double-sure we don't squash them out ;P.

**Comment by BalintFarkas** [comment]
Hey @anurse, thanks for the ping, got me focused wonderfully. :) You know how it is with developer teams and deadlines...
Here's my branch: https://github.com/visionary-broadcast-engineering/AspNetCore/tree/10432
I'm busy working on it right now.

Thanks for looking out for the community! :)

**Comment by BalintFarkas** [comment]
@anurse In the interest of not wasting any further time, I've added test CanCancelStartingConnectionAfterNegotiate based on the pseudocode you've provided. Does this look OK?

By the way I really like the SyncPoint mechanism, we'll adopt it for our own tests.

**Comment by anurse** [comment]
Test code only so we can probably get this in as part of preview 9.

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/AspNetCore/pull/12846
