### ISSUE TITLE
HttpContext Method use Http Enum

### ISSUE THREAD

**Issue by Jlalond** [aspnet/AspNetCore#10517]
### Is your feature request related to a problem? Please describe.
Currently today Method in [HttpRequest](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/HttpRequest.cs#L26) is exposed as a string. I'd like to propose also using the HttpMethod Enum. Any use of Action Filter or middleware has to do a string comparison of the method, and I believe exposing the enum would improve the experience of writing these.

### Describe the solution you'd like
Add HttpMethod to the value

### Describe alternatives you've considered
Current day, leaving it as a string

### Additional context
The string makes it easier to handle situations where a method isn't passed in, so there are few potential issues, if there is no value passed in, HttpMethod would need to be set to None, and exposing both the enum and the string would add some additional overhead.

If this is approved I can tackle exposing this Enum.

**Comment by Eilon** [comment]
BTW there's no limit to valid values of HTTP methods - you can have one called "JACOB" if you want, and it's perfectly valid. So, if there were an enum, you'd still have to have an "Unknown" value and fall back to a string.

See https://tools.ietf.org/html/rfc2616#section-5.1.1

**Comment by Jlalond** [comment]
Totally understandable, the enum would only cover the case of HTTP verbs, I see some precedence [here](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/HttpMethods.cs), in the case that the string isn't any of the enums, I think unknown is fine. The property would explicitly be `HttpMethod` and if I sent in "JACOB" That's fine, it's an unknown http method, but not an unknown method. That difference makes sense to me, but I'm also not an expert.

**Comment by anurse** [comment]
As @Eilon says, we don't want to use an enum becuase the field is freeform. I _believe_ we do some string interning kind of logic here though so that you can be confident that if the request provides `GET`, the value of this property will be the exact string instance in `HttpMethods.Get`. So you can optimally check for equality (with the same performance that checking an enum would have) using `ReferenceEquals`. In fact, there are utility methods in `HttpMethods` that you should use for this purpose:

```csharp
if (HttpMethods.IsGet(request.Method)
{
	// ...
}
```

This gives you the performance expectations of an enum with the flexibility of a string.

Closing as we don't plan to expose an enum here given the options we currently provide.
