### ISSUE TITLE
Blazor: The comments added to the html can ruin the markup with a pre tag

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#10587]
### Describe the bug
Blazor automatically adds markup to the final html in the form of empty comments `<!--!-->` this is usually not a problem. However, in the case of the `<pre />` tag it can be. When creating a component that encapsulates the `<pre />` tag in it, extra lines are added to the rendered output in the html.

### To Reproduce
1. Create a component that has a pre tag (and in my case which makes it worse a code tag)
2. Render the ChildContent inside the pre (and code)
3. Consider setting the background color of the pre tag to make the issue more visible
4. You can also see this in action at: https://chanan.github.io/BlazorStyled/
5. Editing the html in the browser dev tools, removing the extra `<!--!-->` tags fixes the output

### Expected behavior
I am not sure if this possible as I assume Blazor uses them for something, but removing those extra tags would be great

### Screenshots
![image](https://user-images.githubusercontent.com/472554/58498693-cdf5c380-813b-11e9-9abe-df50d91017bc.png)

### Additional context
3.0.0-preview5

**Comment by egil** [comment]
It would be nice if the comments could be removed from the output, if not from all generated code, then from select components that match certain conditions.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chanan.
@SteveSandersonMS any thoughts?

**Comment by SteveSandersonMS** [comment]
Your problem isn't the comment nodes. Comment nodes don't affect the layout. Your problem is with **whitespace text nodes** inside your components.

If you have a component `CodeBlock.razor`:

```razor
<pre style="color: white; background-color: blue;">
    @ChildContent
</pre>

@functions {
    [Parameter] RenderFragment ChildContent { get; set; }
}
```

... and use it like this:

```razor
<CodeBlock>
    This is my code
    And another line
</CodeBlock>
```

... then you have leading and trailing whitespace in both places. This shows up in the UI. This isn't unique to Blazor, but is an aspect of HTML generally: https://stackoverflow.com/questions/14946908/how-can-i-ignore-leading-and-trailing-linebreaks-within-an-html-code-block-usi In some cases it's trickier to work around with Blazor components than it would be with plain HTML, but the underlying principle is the same.

You can avoid the whitespace, e.g.:

```razor
<pre style="color: white; background-color: blue;">@ChildContent</pre>

@functions {
    [Parameter] RenderFragment ChildContent { get; set; }
}
```

... and use it like this:

```razor
<CodeBlock>This is my code
And another line</CodeBlock>
```

I know it's annoying to have to format your source code like that. One possible alternative would be to use Razor comments to hide the whitespace from the browser:

```razor
<CodeBlock>@*              
*@This is my code
Another line@*
*@</CodeBlock>
```

Arguably we should consider stripping whitespace from the start/end of `RenderFragment` but it's not an easy choice to make. Sometimes you might be using the whitespace on purpose because you need it.

---

**Sidenote:** The comment nodes are how Blazor tracks which part of the DOM corresponds to which Blazor components. To avoid having them, we'd need to invent and implement a totally different way of tracking this, which would be a significant block of work that could cause issues in other areas. I'm not sure we'd have any reason to do this for the forseeable future, as the comment nodes don't cause problems in known cases, or at least not mainstream ones.

**Comment by egil** [comment]
@SteveSandersonMS that makes sense.

With regards to the comment nodes. I have a special scenario (showing output generated from components), where I take generated HTML via element.innerHTML in JavaScript, strip out the Blazor comment tags and pretty-print the code, and then insert it into another location on the page using JavaScript. That should not cause a problem, right? 

My guess is, that I actually _have_ to remove the Blazor comments when I copy the code around, otherwise I will mess up the tracking.

**Comment by SteveSandersonMS** [comment]
@egil I can't anticipate any specific problems this would cause. I don't think you'd have to remove anything if you're only inserting a *textual* representation of the HTML.
