### ISSUE TITLE
Blazor - How to read .json file in client side synchronous way or have any callback function for Http.GetJsonAsync method

### ISSUE THREAD

**Issue by pandiyaraj678** [aspnet/AspNetCore#10602]
In blazor client side application, can read and data from json file async way.

```
protected override async Task OnInitAsync()
{
        DBModel data = await Http.GetJsonAsync<DBModel>("sample-data/data.json");
}
```

But i want to do it in synchronous approach, because i need to do route the page after data fetch completed.  I have tried like this below code

```
protected override void OnInit()
{
        DBModel data = Http.GetJsonAsync<DBModel>("sample-data/data.json");
        UriHelper.NavigateTo('Dashboard');
}
```

Getting below error message

Error CS0029 - Cannot implicitly convert type System.Threading.Tasks.Task<Application1.Models.DBModel>' to 'Application1.Models.DBModel'

Or advice how to route a page after data fetch got success. Is any callback handler available for achieve my case?

Thanks in advance.

**Comment by enetstudio** [comment]
What is wrong with this:

protected override async Task OnInitAsync()
{
        DBModel data = await Http.GetJsonAsync<DBModel>("sample-data/data.json");
  
        UriHelper.NavigateTo('Dashboard');
}

 UriHelper.NavigateTo is called only after the GetJsonAsync is completed.

**Comment by enetstudio** [comment]
What is wrong with this:
`
protected override async Task OnInitAsync()
{
DBModel data = await Http.GetJsonAsync("sample-data/data.json");
UriHelper.NavigateTo('Dashboard');
}
`
UriHelper.NavigateTo is called only after the GetJsonAsync is completed.

**Comment by enetstudio** [comment]
What is wrong with this:
```
protected override async Task OnInitAsync()
{
DBModel data = await Http.GetJsonAsync("sample-data/data.json");
UriHelper.NavigateTo('Dashboard');
}
```
UriHelper.NavigateTo is called only after the GetJsonAsync is completed.

**Comment by wrkettlitz** [comment]
I advice you to take some time to learn more about async/await. https://www.youtube.com/watch?v=2moh18sh5p4

**Comment by enetstudio** [comment]
@wrkettlitz, won't it be easier if you'd bother yourself to explain what is wrong with this code... Please do it if you can, so that I'll be sure that I need some practice, or just remove the link.

**Comment by wrkettlitz** [comment]
Await = stop here and wait for the task to finish and return the result (if any)

 I assume you want the value for data before you want to go the a different page, so what you had before is already correct.

**Comment by enetstudio** [comment]
Await = stop here and wait for the task to finish and return the result (if any)

No, no ,no:  await means yield execution to the calling code ( don't block) while the task is in progress. When the task completes, continue execution; that is, call UriHelper.NavigateTo('/Dashboard') synchronously. 

Now read what you wrote again:
Await = stop here and wait for the task to finish and return the result (if any)

Oh, yeah, stop here and wait for the task to finish !!! How long to wait (TO BLOCK) a year or two ?
You must be joking, ain't you !

The rest of your post is really obscure...however, it seems as though you are the one who should spend some time practicing the asynchronous programming model and Blazor. I do hope that you're not the presenter in the video. Please, remove your advertisement. You should have not try to belittle me just in order to post this video.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by pandiyaraj678** [comment]
> What is wrong with this:
> 
> ```
> protected override async Task OnInitAsync()
> {
> DBModel data = await Http.GetJsonAsync("sample-data/data.json");
> UriHelper.NavigateTo('Dashboard');
> }
> ```
> 
> UriHelper.NavigateTo is called only after the GetJsonAsync is completed.

@enetstudio :  Actually i am using client side blazor application, your solution not work with my scenario.

Page restricted and some time after only data assigned specified parameter

**Comment by pandiyaraj678** [comment]
Finally, i solve this issue by following way in my project

`
    protected async Task<DBModel> GetData()
    {
        return await Http.GetJsonAsync<DBModel>("sample-data/data.json");
    }

    protected override async Task OnInitAsync()
    {
        DBModel data = await GetData();
        Console.WriteLine(DBModel data.PersonalData[0].Name); // Used to ensure data fetch or not
        UriHelper.NavigateTo("Dashboard");
    }
`

Above way page routing happened once data fetch complete.

Thanks guys, sharing your valuable suggestion.

**Comment by enetstudio** [comment]
@pandiyaraj678, this is not my solution. This is your code, a copy of your code, which is why it is "("Dashboard")" instead of "("/Dashboard")". Do you get it ? I just copy paste your code, and said that there is nothing wrong with it. This is how it should be, though I would design my code much differently.

Anyhow, your new code snippet, which you say is working, is actually the first code snippet  implemented in two methods, and thus, if it works as two methods, it should work as a single combined method. 

And that is what I've said that there in nothing wrong with your code...

 As suggested above, you'd better post such questions in StackOverflow

Good day...

**Comment by pandiyaraj678** [comment]
> @pandiyaraj678, this is not my solution. This is your code, a copy of your code, which is why it is "("Dashboard")" instead of "("/Dashboard")". Do you get it ? I just copy paste your code, and said that there is nothing wrong with it. This is how it should be, though I would design my code much differently.
> 
> Anyhow, your new code snippet, which you say is working, is actually the first code snippet implemented in two methods, and thus, if it works as two methods, it should work as a single combined method.
> 
> And that is what I've said that there in nothing wrong with your code...
> 
> As suggested above, you'd better post such questions in StackOverflow
> 
> Good day...

As per below documentation, i have used route as ("Dashboard")

https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#uri-and-navigation-state-helpers
