### ISSUE TITLE
Localization not working after changing rootnamespace

### ISSUE THREAD

**Issue by chrsas** [aspnet/AspNetCore#10639]
I have found issue https://github.com/aspnet/AspNetCore/issues/2645, but with my Asp.Net Core sample, it still does not work https://github.com/chrsas/LocalizationTest.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrsas.
We're currently busy with wrapping up our upcoming release and we  will try to investigate this in the next milestone. In the meantime, StackOverflow may be a good place to start from, in case you'll get faster help there. Appreciate your understanding.

**Comment by hishamco** [comment]
This can be fixed used `RootNamespaceAttribute`. Have a look to the docs https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/troubleshoot-aspnet-core-localization?view=aspnetcore-2.2#root-namespace-issues

**Comment by hishamco** [comment]
@mkArtakMSFT this has been answer and there's no respond from the author

**Comment by chrsas** [comment]
@hishamco You can see the file in my repo, `RootNamespaceAttribute` has been used, But it doesn't work.
https://github.com/chrsas/LocalizationTest/blob/master/LocalizationTest/AssemblyInfo.cs

**Comment by hishamco** [comment]
Let me check your sample, and get back to you ..

**Comment by hishamco** [comment]
After checking your sample, the first issue I notice which is unrelated is the order of localization middleware was wrong, please check this docs https://docs.microsoft.com/en-us/aspnet/core/fundamentals/troubleshoot-aspnet-core-localization?view=aspnetcore-2.2

The second thing which I can't confirm yet because I'm not unable to run the ASPNET.Core Extensions source, is that may be there's a bug in the basename. I made your app running well, but I need to check few tests cases before I confirm and send a PR for it

**Comment by chrsas** [comment]
@hishamco Thanks for your reply, waiting for your good news.

**Comment by hishamco** [comment]
@chrsas If I'm not wrong there's a bug which may not obvious, I will prepare a PR for it. 

Now to make your application works fine, I need to add `NewResourceManagerStringLocalizerFactory` as a workaround, here is the code:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IStringLocalizerFactory, NewResourceManagerStringLocalizerFactory>();
    services.AddLocalization();
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

```csharp
public class NewResourceManagerStringLocalizerFactory : ResourceManagerStringLocalizerFactory
{
    public NewResourceManagerStringLocalizerFactory(IOptions<LocalizationOptions> localizationOptions, ILoggerFactory loggerFactory) : base(localizationOptions, loggerFactory)
    {

    }

    protected override string GetResourcePrefix(TypeInfo typeInfo, string baseNamespace, string resourcesRelativePath)
    {
        if (typeInfo == null)
        {
            throw new ArgumentNullException(nameof(typeInfo));
        }

        if (string.IsNullOrEmpty(baseNamespace))
        {
            throw new ArgumentNullException(nameof(baseNamespace));
        }

        if (string.IsNullOrEmpty(resourcesRelativePath))
        {
            return typeInfo.FullName;
        }
        else
        {
            return baseNamespace + "." + resourcesRelativePath + TrimPrefix(typeInfo.FullName, baseNamespace + ".");
        }
    }
    private static string TrimPrefix(string name, string prefix)
    {
        if (name.StartsWith(prefix, StringComparison.Ordinal))
        {
            return name.Substring(prefix.Length);
        }

        return name;
    }
}
```

@ryanbrandenburg correct me if I'm wrong

**Comment by ryanbrandenburg** [comment]
@hishamco I don't know what behavior it is that you think is a bug. Please describe the scenario, expected behavior and actual behavior.

**Comment by hishamco** [comment]
You can check @chrsas demo, the localizer not able to find the resources if the rootnamespace and namespace of the generic localizer type changed. Have a look to https://github.com/chrsas/LocalizationTest/blob/master/LocalizationTest/Controllers/ValuesController.cs#L8, the `GetResourcePrefix()` for the `ValuesController` will be `LocalizationTest.Abc.Resources.Abc.Controllers.ValuesController` which is wrong because the prefix is the assembly name not the base name

**Comment by hishamco** [comment]
@mkArtakMSFT could you please move this to the Extensions repo while the issue isn't related to the localization middleware

**Comment by hishamco** [comment]
@pranavkm this need to be close
