### ISSUE TITLE
Blazor add DataContext

### ISSUE THREAD

**Issue by mgochmuradov** [aspnet/AspNetCore#10755]
I personally (and most of my colleagues) prefer using MVVM style programming.
I am currently building a new Blazor app with MVVM in mind and here is what I have:
```razor
@page "/login"
@inherits PageBase<AppLoginViewModel>

<h1>Please Login to continue</h1>

<form>
    <fieldset disabled="@ViewModel.IsBusy">
        <div class="modal-body">
            <div class="form-group">
                <label for="username">Username</label>
                <input bind="@ViewModel.Username" class="form-control" type="text" id="username" name="username" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input bind="@ViewModel.Password" class="form-control" type="password" id="password" name="password" />
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" disabled="@(!ViewModel.CanLogin)" onclick="@ViewModel.OnLoginAsync">Login</button>
        </div>
    </fieldset>
</form>
```
As you can see **I have to repeate ViewModel** in every binding like: `@ViewModel.xxx`

### Describe the solution you'd like
A better approach would be to have an ability to set DataContext/BindingContext of any tag, or even of an entire component.
So the code above could be written as:
```razor
@page "/login"
@inherits PageBase<AppLoginViewModel>

<h1>Please Login to continue</h1>

<form dataContext="@ViewModel">
    <fieldset disabled="@IsBusy">
        <div class="modal-body">
            <div class="form-group">
                <label for="username">Username</label>
                <input bind="@Username" class="form-control" type="text" id="username" name="username" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input bind="@Password" class="form-control" type="password" id="password" name="password" />
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" disabled="@(!CanLogin)" onclick="@OnLoginAsync">Login</button>
        </div>
    </fieldset>
</form>
```

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

This is not something we're likely do to, because the drawbacks would be too severe, plus the complexity would be too high. Once you're in a `dataContext` region, you'd lose the ability to reference things outside that object (without yet another syntax), plus the compiler would have to become way smarter still to know where to inject the "data context" prefix into expressions like `onclick="@(() => DoSomething(Name))"` - would it interpret that as `ViewModel.DoSomething(Name)` or `ViewModel.DoSomething(ViewModel.Name)` or `DoSomething(ViewModel.Name)`? It's too ambiguous.

As an alternative, I'd recommend just creating short aliases for things if you want your code to be shorter. For example, define a property like:

```
    private MyViewModel vm => ViewModel;
```

... and then all your expressions in the markup can be reduced to `bind="@vm.Name"` etc, without any ambiguity.
