### ISSUE TITLE
Environment Tag Helper in client-side Blazor

### ISSUE THREAD

**Issue by sunshiyun** [aspnet/AspNetCore#10753]
### Is your feature request related to a problem? Please describe.
I'm am trying to make different behaviors in Blazor application (both on server side and client side), based on the runtime environment of server-side Blazor. 
I found out that environment tag helper can be used to configure multiple environments in ASP.NET Core, but environment tag helper seems not to work in client-side Blazor.

### Describe the solution you'd like
It will be helpful if environment tag helper can be supported in Blazor.

### Describe alternatives you've considered
Client-side appsetting.json or other editable config file to which environment configurations can be added.

### Additional context
None.

**Comment by SteveSandersonMS** [comment]
Blazor (i.e., `.razor` files) doesn't have tag helpers at all, because it's a completely different rendering technology. It doesn't produce HTML strings, which tag helpers do, but rather produces structured markup.

If you're trying to make a single set of Blazor components that work on both server-side Blazor and client-side Blazor, and sometimes have differing behaviors, the recommended approach is to use [dependency injection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2). 

Both server-side and client-side Blazor have their own separate DI configurations (in their respective `Startup` classes), so you can define some interface `IMyThing` that is consumed by your components, and then define two different concrete types (`MyServerSideThing` and `MyClientSideThing`) that are supplied in the two different environments.

If you simply want to know whether your code is running server-side or client-side, an even simpler approach is to evaluate `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))`. If it's `true`, you're running client-side, and if it's `false` you're running server-side.

**Comment by sunshiyun** [comment]
@SteveSandersonMS Thank you for answering.
I'm sorry I didn't made it clear in my discription. I mean "SolutionName.Server" by "server-side Blazor", and "SolutionName.Client" by "client-side Blazor".

What I'm trying to do is to make different behaviors on different environments (Development or Product). It can be done simply on "server-side Blazor" as line 31 in the following code by using IHostingEnvironment in StartUp.cs and other classes:
https://github.com/aspnet/samples/blob/136b4bb35ba8001b230bd21c8ac632c4b572bb41/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Server/Startup.cs
or by writing environment value in appsettings.json and using Microsoft.Extensions.Configuration to get it.

But when I tried to do the same thing on client side by using IHostingEnvironment and environment tag helper, I didn't find any way to get the environment value (Development or Product) or configuration values in appsettings.json from server side. 
So is there any way to pass server configuration to Blazor client?
