### ISSUE TITLE
P2P references from netcoreapp3.0 projects to netcoreapp2.x targeting projects results in missing assemblies in build output

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#10859]
1. Create a new 3.0 (preview6) targeting AspNetCore Web Application (Controllers) project
2. Create a new 2.1 targeting AspNetCore Web Application (Controllers) project with individual auth
3. Reference the 2.1 project from 3.0.
4. Build the 3.0 project and run it.

Expected:
This should run (maybe?)

Actual:
The build output for the 3.0 project is missing EF binaries. Consequently running fails with a type load exception:

```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Comment by pranavkm** [comment]
cc @JunTaoLuo \ @natemcmaster. My guess is this has to do with the trimming \ lifting in the shared fx. Is this a scenario that's meant to work?

**Comment by natemcmaster** [comment]
The reason is simpler than that. In 2.x when using the implicit PackageReference version for Microsoft.AspNetCore.App, the SDK sets `PrivateAssets="All"` on Microsoft.AspNetCore.App. This means the 3.0 app is not going to transitively get a reference to everything that was in Microsoft.AspNetCore.App 2.x.

https://github.com/dotnet/sdk/blob/b68e3d4ae9362281551b30d961f717e2593e76b6/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L95-L98


I believe the fix we should recommend here is for the 3.0 app to add a PackageReference to EF Core.

**Comment by natemcmaster** [comment]
By the way, I would be okay closing this as by-design, and a result of #3755. Thoughts @Pilchie ?

**Comment by Pilchie** [comment]
Yes, I agree.
