### ISSUE TITLE
CascadingValue is null if you navigate directly to the page

### ISSUE THREAD

**Issue by sbuchok** [aspnet/AspNetCore#10874]
Here is the setup:

MainLayout
```
<MessageBanner ref="MessageBanner"></MessageBanner>

<CascadingValue Value="@MessageBanner">
            @Body
</CascadingValue>

@functions{
    protected MessageBanner MessageBanner;
}
```

I use this as a toaster of sorts so that I can display messages when different actions happen. This way I have it on the MainLayout and expose it to be Cascaded to all other Components.

I have found this works great, however I have noticed that if I open a new tab and go directly to a page (say a password reset page), this seems to break and MessageBanner is always null.

I'm not trying to use MessageBanner on Init of the component, but within a button click event. 

If you need more information, please let me know.

Thanks

**Comment by SteveSandersonMS** [comment]
If you could post repro steps (i.e., a minimal amount code that's still enough for us to run it), we can certainly investigate. From what you've posted above I can't guess what's causing the issue I'm afraid!

**Comment by sbuchok** [comment]
I'll put something together tonight. Thanks for the quick reply back.

**Comment by sbuchok** [comment]
Ok, so I was slightly off in what is happening. I have attached a solution that shows the issue. Here is what I found.

On the loading of the Index Page, text is auto set for the Shared Component (the component that I have set to Cascade to be available on all other pages). If I click the button that sets text for the Shared Component, there is a null reference error. However, if I navigate to another page (using NavLink) and click the button on that page (Test Page), I have a reference to the component and the text is set as expected. If I now navigate back to the Index Page (using NavLink) and click the button, it now works as expected.

So, it seems like the Shared Component loads, however it is not available to any Child Components until you navigate which causes it to be available ... somehow. 

After looking a little more at some of the other bugs, this seems like it is similar to (if not the same): https://github.com/aspnet/AspNetCore/issues/5675

In that example however, the person is trying to use the Cascading control OnInit, before rendering is complete. In my example, I am trying to use it after rendering is complete within an event.

Please let me know if there is more I can do to help or clarify anything.

Thanks


[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3259276/WebApplication1.zip)

**Comment by sbuchok** [comment]
Since apparently it looks like this won't get fixed for quite some time, is there a workaround for this?

**Comment by SteveSandersonMS** [comment]
I've checked the repro sample and identified the issue. The problem is that you're trying to refer to a field populated by `ref` before the rendering is completed. `ref` fields are only guaranteed to be initialized once the first render is completed.

Specifically, in `MainLayout.razor`, you have:

```razor
<SharedCom ref="Shared" Text="This text will change when button clicked"></SharedCom>
<hr />


<CascadingValue Value="@Shared">
    @Body
</CascadingValue>
```

... where the `CascadingValue` is being given the value of a field that is not necessarily yet populated.

There are several ways you can avoid this problem. One of them is to only render the `CascadingValue` (and `@Body`) once the field is populated, e.g.:

```razor
<SharedCom @ref="Shared" Text="This text will change when button clicked"></SharedCom>
<hr />

@if (Shared != null)
{
    <CascadingValue Value="@Shared">
        @Body
    </CascadingValue>
}

@functions
{
    protected SharedCom Shared;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            StateHasChanged();
        }
    }
}
```

This uses the `firstRender` parameter we're introducing in preview 9. If you're using an older version of Blazor, you'll need to track that flag yourself.

Alternatively, instead of passing `SharedCom` as a cascading value, pass some other object that exposes the desired APIs. For example, instead of having your pages receive an instance of `SharedCom`, have them receive the `MainLayout`:

```cs
    public class Index_Page : ComponentBase
    {
        [CascadingParameter]
        public MainLayout Layout { get; set; }

        protected void Click_Event()
        {
            Layout.SetText("Index Page");
        }
    }
```

... and then put the method you want onto the layout:

```razor
<SharedCom @ref="Shared" Text="This text will change when button clicked"></SharedCom>
<hr />

<CascadingValue Value="@this">
    @Body
</CascadingValue>

@functions
{
    protected SharedCom Shared;

    public void SetText(string text)
    {
        Shared.SetText(text);
    }
}
```

This latter technique will perform a bit better than the first one, as it only has to render the layout once.

**Comment by sbuchok** [comment]
Thanks Steve, I'll try this out.
