### ISSUE TITLE
[blazor] url enconding sometimes not working with UriHelper.NavigateTo

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#10887]
1. Create blazor page(just replace `counter` page from basic vs blazor template): 
```html
@page "/counter"
@page "/counter/{search}"
@inject IUriHelper UriHelper

<p>
This search has problems with encoding:<br>
<input type="search" 
       value="@Search" 
       placeholder="enter here: `тест`"
       oninput="@(e=> UriHelper.NavigateTo($"/counter/{e.Value.ToString()}") )" />
</p>
<p>
    <input type="search" 
           value="@Search" 
           placeholder="enter here: `тест`"
       oninput="@(e=> UriHelper.NavigateTo(e.Value.ToString()) )" />
</p>

<p>Search: @Search</p>
@functions {
    [Parameter]
    public string Search { get; set; } = string.Empty;
}

```
2. Write any not latin text, for ex. `тест` in the `second` `input` field, 
page will be navigated to the `/тест` (in the browser url)
and in the input 
you'll see 'тест'
3. Write any not latin text, for ex. `тест` in the `first` `input` field, 
page will be navigated to the `/counter/тест` (in_ the browser url)
and in the input 
you'll see `%D1%82%D0%B5%D1%81%D1%82` instead of `тест`

---

To solve this issue, needed, somewhere for ex. in basic method of blazor component `OnParametersSet`
call decode method for all params, like: 
```csharp
 protected override void OnParametersSet() {
        base.OnParametersSet();
        // do the same for all params
        Search = System.Net.WebUtility.UrlDecode(Search); 
    }
```

**Comment by mkArtakMSFT** [comment]
Let's investigate this for couple of hours and understand what's going on here. If it turns out to be a feature we don't have, we'll move this to 3.1.

**Comment by SteveSandersonMS** [comment]
Sorry, I've been unable to reproduce this. It's like that this was fixed implicitly as part of some other changes we made since this was first reported. With the current code in `master` (which will ship in preview 8), I was able to type non-Latin characters in Chrome, Firefox, and Edge. They appeared correctly in the URL too:

![image](https://user-images.githubusercontent.com/1101362/61444689-cab0d400-a943-11e9-8761-2b606ff9f4ab.png)

If you're still able to reproduce this with 3.0.0-preview7 or later, please let us know!

**Comment by campersau** [comment]
I guess this was the fix which is in preview7: https://github.com/aspnet/AspNetCore/pull/8759
