### ISSUE TITLE
@bind-value on its own results in an error.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#10967]
Edit: At this point we only want to support `@bind-value` on its own. See below comment for more details.

### Describe the bug
Writing `<input @bind-custom="SOMEVALUE" />` results in an `RZ9991` error.

### Expected behavior
No errors and things just work.

### Screenshots
![image](https://user-images.githubusercontent.com/2008729/59066070-0ba4cb80-8863-11e9-92f9-7e20f912acdc.png)

### Additional context
Users can workaround this issue by adding a `@bind-custom:event="SOMEEVENT"` to the input element: `<input @bind-custom="SOMEVALUE" @bind-custom:event="SOMEEVENT" />`

@danroth27 this is worth including in the known issues list.

**Comment by ajaybhargavb** [comment]
Spoke to @SteveSandersonMS. This is by design. To add some context,
We currently infer the default event by looking at the `[BindInputElement]` that matches the given tag. See https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/BindAttributes.cs#L16.

Since we only currently specify that attribute for `value`, it will not work for any arbitrary suffix like `custom`.

Having said that, we still want to support the following case,
`<input @bind-value="Blah" />`

I'm changing the title to reflect this.
