### ISSUE TITLE
CookieAuthenticationEvents RedirectToLogin "previous" identity - QUESTION

### ISSUE THREAD

**Issue by generik0** [aspnet/AspNetCore#10983]
I need to log into an audit trail whenever a user has logged out of the system.
We have an angular app on top of an aspnetcore using cookies.

The user is automatically logged out when the cookie expires. So this works well :-)

Our implementation of CookieAuthenticationEvents catches the "RedirectToLogin". But the context (RedirectContext<CookieAuthenticationOptions> context) does not have the information of the user. Or should i say the user in the expired cookie. The identity has null values for most of the fields.

Is there any way to fix the (ex)user out so i can log its autologout?

**Comment by Tratcher** [comment]
You would have to copy the code that runs before the expiration check:
https://github.com/aspnet/AspNetCore/blob/b34acc9e86b186aa7fbe64bb2651f82116433ec7/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L124-L134

It wouldn't work for the SessionStore scenario, the user would have been deleted from the store.

**Comment by generik0** [comment]
@Tratcher copy the code? 
You mean i can do an override of one of the methods calling EnsureCookieTicket that is calling ReadCookieTicket where the code you have is.

I can not simply copy the code to the RedirectToLogin, as the cookie is already gone..

Isn't there a method that CookieAuthenticationHandler that handles the expired cookie?

**Comment by Tratcher** [comment]
Cookies expire in two ways.
1) There is a timestamp encrypted in the cookie that is checked in the code I linked above. These cookies are present on the request but do not populate the ClaimsIdentity. You can still read these cookies manually by calling Options.CookieManager.GetRequestCookie and Options.TicketDataFormat.Unprotect yourself.
2) The timestamp in the standard cookie format. This is enforced by the client and the server has no knowledge of when these expire. Note the auth cookie does not set this timestamp by default so that the browser will delete the cookie on close.

**Comment by generik0** [comment]
@Tratcher I understand now. 
Since the cookie is expired, the RedirectToLogin and all the other calls already do not havethe cookie anymore. It is "gone"

All i can do is add another cookie with he information I need, or, have some server side caching.

Thanks for your help :-)
