### ISSUE TITLE
Adding HTTP header with empty string value yields confusing error

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [aspnet/AspNetCore#11032]
### Describe the bug
Some legacy code in .NET Framework has an HTTP header with an empty string as value. When porting the same code to .NET Core, the exception System.ArgumentException: 'Value does not fall within the expected range.' is thrown.

### To Reproduce
1. Using a blank project with ASP.NET Core 2.2
2. Run this code (replace the WriteAsync Hello World):

            app.Run(async (context) =>
            {
                context.Response.Headers.Add("test", "");
            });

4. See error below

### Expected behavior
The header was perhaps unnecessary and maybe even invalid. But the message "Value does not fall within the expected range" isn't really helpful, the offending header name isn't even mentioned, and if the response is sent outside of your own code (like the example above - do a write and you'll get it, though) you don't even get a meaningful stacktrace and you cannot possible know what the relevant request was. So the issue gets really hard to track down.

I had to decompile Microsoft.AspNetCore.Server.IIS.dll and put the generated PDB alongside it in the nuget cache to get on my way.

### Screenshots

![image](https://user-images.githubusercontent.com/668160/59190782-e7583000-8b7d-11e9-9ae2-a6feef7aab3f.png)

### Additional context

Perhaps a guard statement could be added here: to avoid confusing any future developers.

https://github.com/aspnet/AspNetCore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/Core/IISHttpContext.cs#L388

But in the same time, it feels like the exception is a native one, and thus this may be the wrong repo to discuss it in.

**Comment by anurse** [comment]
Native exceptions like this a converted from error codes returned by the native code. The error code returned here is `E_INVALIDARG`, which gets converted to this generic argument exception (because the code is all we have to go on).

One thing we could do is "pre-check" the argument and throw a more useful `ArgumentException` with a message (like `Header value cannot be an empty string`) **before** calling the native code.

Putting this in the backlog and marking "help wanted"/"good first issue" since this would be a great opportunity for a new contributor!
