### ISSUE TITLE
Error: Server returned handshake error: Handshake was canceled.

### ISSUE THREAD

**Issue by robcube** [aspnet/AspNetCore#11089]
1. Followed instructions in creating a SignalR project in .NET Core 2.2
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio
2. Everything works on local IIS Express -- Windows 7, Visual Studio 2019
3. Published to server, Windows 2008R2, IIS 7.5
4. URL is HTTPS -- https://dw.example.com
5. Added Debug logic in both client (configureLogging(signalR.LogLevel.Trace)) and server ("Microsoft.AspNetCore.SignalR": "Debug", "Microsoft.AspNetCore.Http.Connections": "Debug")

Using Chrome Dev Tools (FYI - IE11 has same thing); console output:
Information: Normalizing '/chatHub' to 'https://dw.example.com/chatHub'.
signalr.js:2440 Debug: Starting HubConnection.
signalr.js:2440 Debug: Starting connection with transfer format 'Text'.
signalr.js:2440 Debug: Sending negotiation request: https://dw.example.com/chatHub/negotiate
signalr.js:2440 Debug: Selecting transport 'ServerSentEvents'
signalr.js:2440 Trace: (SSE transport) Connecting
signalr.js:2436 Information: SSE connected to https://dw.example.com/chatHub?id=MoeAzDS7OtmeAylCN_vQEA
signalr.js:2440 Debug: Sending handshake request.
signalr.js:2440 Trace: (SSE transport) sending data. String data of length 32.
signalr.js:1624 POST https://dw.example.com/chatHub?id=MoeAzDS7OtmeAylCN_vQEA 404 (Not Found)
(anonymous) @ signalr.js:1624
DefaultHttpClient.send @ signalr.js:1583
HttpClient.post @ signalr.js:1563
(anonymous) @ signalr.js:2342
step @ signalr.js:2273
(anonymous) @ signalr.js:2254
fulfilled @ signalr.js:2245
Promise.then (async)
step @ signalr.js:2247
(anonymous) @ signalr.js:2248
__awaiter @ signalr.js:2244
sendMessage @ signalr.js:2329
(anonymous) @ signalr.js:3452
step @ signalr.js:3364
(anonymous) @ signalr.js:3345
(anonymous) @ signalr.js:3339
__awaiter @ signalr.js:3335
ServerSentEventsTransport.send @ signalr.js:3447
HttpConnection.send @ signalr.js:2648
(anonymous) @ signalr.js:1765
step @ signalr.js:1708
(anonymous) @ signalr.js:1689
fulfilled @ signalr.js:1680
Promise.then (async)
step @ signalr.js:1682
(anonymous) @ signalr.js:1683
__awaiter @ signalr.js:1679
HubConnection.start @ signalr.js:1750
(anonymous) @ chat.js:16
chat.js:19 Error: Not Found
(anonymous) @ chat.js:19
Promise.catch (async)
(anonymous) @ chat.js:18
signalr.js:2440 Trace: (SSE transport) data received. String data of length 36.
signalr.js:2430 Error: Server returned handshake error: Handshake was canceled.
ConsoleLogger.log @ signalr.js:2430
HubConnection.processHandshakeResponse @ signalr.js:2006
HubConnection.processIncomingData @ signalr.js:1948
HubConnection.connection.onreceive @ signalr.js:1730
eventSource.onmessage @ signalr.js:3412
signalr.js:2430 Error: Connection disconnected with error 'Error: Server returned handshake error: Handshake was canceled.'.

I used .NET Framework SignalR with no issues. Only issue is .NET Core SignalR.

Thanks!

**Comment by BrennanConroy** [comment]
Is your server multi-instance? AspNet Core SignalR requires sticky sessions in that case. It looks like you have multiple servers and half of the SSE transport is on one and the other half is on another.
________________________________

**Comment by robcube** [comment]
Sorry, am not exactly clear by what's "sticky sessions" are. And it being multi-instance as if it's in a server farm? What are you noticing that presumed you to ask me those questions?

**Comment by BrennanConroy** [comment]
The reason I'm wondering about multi-instance is that SSE makes two requests after negotiation.

One will be the long running "streaming" request which gets messages from the server. The other is a POST request whenever it sends a message to the server.

In your logs above, the streaming request looks like it successfully connected to the "correct" server because it didn't 404 and it was able to receive "Server returned handshake error: Handshake was canceled." which is a message from the server if the client is connected to it.

However, the POST request is trying to send a message (handshake) to the server and immediately 404's, which happens when you try to connect to a server that doesn't know about the connection ID in the query string.

Which leads me to suspect that you have multiple servers without sticky sessions because otherwise the POST would not 404 and would be successful.

It is possible if you're having DNS issues to connect with one of the requests and not the other, but if that was the case I wouldn't expect a 404.

**Comment by robcube** [comment]
That's odd since I only have one server here. Tried creating it in VS code. Works locally (Windows 7, IISExpress v10+), but not on the server. Is it because IIS is old with it being v7.5?

**Comment by BrennanConroy** [comment]
Could you provide the server logs? It would be useful to see what they say and if they match what the client is observing.

Another thing you could try is using the LongPolling transport instead of ServerSentEvents and see if you get a similar issue.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by robcube** [comment]
Finally back on this --- here are the relevant pieces of the IIS logs. Let me know if you need anything else. (IPs changed to protect the innocent)

2019-07-02 12:23:17 10.10.10.10 GET /Recent - 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 200 0 0 8913
2019-07-02 12:23:17 10.10.10.10 GET /js/recent.js - 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 200 0 0 686
2019-07-02 12:23:19 10.10.10.10 GET /lib/aspnet-signalr/signalr.js - 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 200 0 0 1467
2019-07-02 12:23:19 10.10.10.10 GET /lib/aspnet-signalr/signalr.js.map - 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 404 0 0 249
2019-07-02 12:23:19 10.10.10.10 POST /recentHub/negotiate - 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 200 0 0 280
2019-07-02 12:23:19 10.10.10.10 POST /recentHub id=qDAK27soX68TjfZmUSTEMg 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 404 0 0 234
2019-07-02 12:23:35 10.10.10.10 GET /recentHub id=qDAK27soX68TjfZmUSTEMg 443 - 50.50.50.50 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/75.0.3770.100+Safari/537.36 200 0 0 15329

**Comment by anurse** [comment]
Sorry, IIS logs weren't actually what we were looking for. We need the SignalR server logs, see our [diagnostics guide](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2) for more information on collecting this information.

Do you have multiple app pools or multiple instances of an app pool? If you have multiple processes on the server running the same application that would be the same as having multiple servers. SignalR requires that all requests for a single connection go to the same physical server process, otherwise you'll get these kinds of 404 errors.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
