### ISSUE TITLE
StackExchange.Redis.StrongName in AspNetCore.SignalR.Redis is discontinued

### ISSUE THREAD

**Issue by jlorek** [aspnet/AspNetCore#11093]
The package Microsoft.AspNetCore.SignalR.Redis (<= 1.1.5) references StackExchange.Redis.StrongName (1.2.6). This package was discontinued by StackExchange about 9 month ago in favour of StackExchange.Redis, which is now strong named by default (https://github.com/Azure/aspnet-redis-providers/issues/107).

This reference causes problems when using other libraries, that already adopted the new StackExchange.Redis package. Other parts of AspNet Core seem to already have made transition to the new package. Any plans for the SignalR.Redis package?

**Comment by anurse** [comment]
Yes, we added a new package [`Microsoft.AspNetCore.SignalR.StackExchangeRedis`](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.StackExchangeRedis) in ASP.NET Core 2.2 (and the upcoming 3.0 release). We had to add a new package rather than upgrading the existing package because the `StackExchange.Redis` package changed package IDs, which is a breaking change. The older `Microsoft.AspNetCore.SignalR.Redis` package is discontinued in 3.0.

The APIs your app uses should be identical between the two, but be aware that if any other packages in your app reference the older `StackExchange.Redis.StrongName` package you could have both loaded into the app.

See https://github.com/aspnet/Announcements/issues/322 for details on this change.
