### ISSUE TITLE
In patch builds, tests aren't always running against latest bits

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#11169]
Due to the way we generate baselines and attempt to minimize dependency updates via eng/targets/ResolveReferences.targets, test projects do not always run against the latest patch.

Solution:
We need to disable transitive project references in test projects. By adding direct references, the `<Reference>` resolution will get the latest assemblies into the test project.

**Comment by natemcmaster** [comment]
Here is a proposed fix for the Extensions repo. https://github.com/aspnet/Extensions/pull/1834 The same approach would work here too, but it's worth considering alternatives as mentioned in https://github.com/aspnet/Extensions/pull/1834#issuecomment-501544173

**Comment by BrennanConroy** [comment]
We ran into a scenario where we wanted to fix a flaky test which required minor product changes, but the product changes themselves were not patch-worthy. But because of the restrictions in place, the test would remain flaky because it will still be using the baseline package(s).
https://github.com/aspnet/AspNetCore/pull/14337

**Comment by dougbu** [comment]
This is no longer a thing because we're not using PatchConfig.xml except in 'release/2.1' anymore. Changing that branch for this does not seem worthwhile.
