### ISSUE TITLE
Validation not showing inline for string[] value - Showing in Summary only

### ISSUE THREAD

**Issue by leonmills** [aspnet/AspNetCore#11259]
While trying to validate a select list with multiple items ( asp-for is bound to string[] ) I was unable to get the inline validation to work - it would only appear in the validation summary

Using 2.2

**Example of Issue**: [select-list-issue.zip](https://github.com/aspnet/AspNetCore/files/3293998/select-list-issue.zip)

Press submit in this working razor page project to see issue in action - text box included for comparison to show that validation on other control is working as expected:

When pressing submit validation fires and picks up the lack of value in the select list but the validation error only appears in the summary

![select-problem](https://user-images.githubusercontent.com/51363004/59562422-6f2db680-9024-11e9-8aab-262acee8beff.png)

**Property in Razor Page Model:**

```
[BindProperty]
[StringArrayRequired(ErrorMessage = "Choose an item from select list")]
public string[] SelectedListItems { get; set; }
```

**Extract from HTML:**
```
 <div asp-validation-summary="All" style="color:red;" ></div>
    <form method="post">
        <p>Inline Validation for Selectlist:  <span asp-validation-for="SelectedListItems" style="color:red;"></span></p>
        <select multiple asp-for="SelectedListItems" asp-items="Model.ListItems"></select>
        <p>Inline Validation for textbox:  <span asp-validation-for="TextValue" style="color:red;"></span></p>
        <input type="text" asp-for="TextValue" />
        <br /> <br /> <input type="submit" />
    </form>
```
### Expected behavior
Validation should appear inline and in the summary

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @leonmills.
We'll get to this after 3.0 release as we're focused on critical issues only.

**Comment by ryanbrandenburg** [comment]
This seems to be confusion about how client-side validation works.

The `StringArrayRequiredAttribute` you've created only works for client-side validation because that's all the parts of it you've implemented. In order for it to work with client-side validation (jquery-validation and jquery-validation-unobtrusive) you need that attribute to also implement `IClientModelValidator`, and have `AddValidation` add the attributes which matter to the given html tag. Then you ALSO need to wire up these new attributes using JS [as described here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#custom-client-side-validation).

Given that, I'm closing this. If you have more trouble after this let us know.
