### ISSUE TITLE
HTTP2: Send trailers with data

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#11270]
Kestrel is sending HEADERS and DATA together in a TCP packet, followed by HEADERS (trailers) in the next TCP packet.

![image](https://user-images.githubusercontent.com/303201/59571328-9f925500-90f7-11e9-921e-1b4f3bd889b9.png)

The C-Core gRPC server sends HEADERS, DATA and HEADERS (trailers) in a single TCP packet.

![image](https://user-images.githubusercontent.com/303201/59571418-7f16ca80-90f8-11e9-91cc-99c643ff3c86.png)

So..

1. Do more TCP packets equal less performance?
2. Should Kestrel combine packets?

// @Tratcher @steveharter @davidfowl

**Comment by JamesNK** [comment]
Relevant code?

https://github.com/aspnet/AspNetCore/blob/b528fd0a46422d2625ef690e89bf04557bbd7286/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L318-L326

**Comment by Tratcher** [comment]
Theory: It's likely this is the result of two passes through the loop. The first pass picks up the data before the pipe is complete [here](https://github.com/aspnet/AspNetCore/blob/b528fd0a46422d2625ef690e89bf04557bbd7286/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L337). The second pass picks up the complete status and sends the trailers. 

In most cases there's going to be a non-trivial time gap between the data write and the call to Complete that sends the trailers. What pattern would you use to prevent the data from being available before calling Complete? GetMemory, Advance, but no call to FlushAsync? Even in that case we'd have to tweak Http2FrameWriter.WriteDataAsync not to flush.

**Comment by JamesNK** [comment]
> GetMemory, Advance, but no call to FlushAsync?

Yes, gRPC does that for calls with a single message response. I expect that FlushAsync would always result in separate packets.

> Even in that case we'd have to tweak Http2FrameWriter.WriteDataAsync not to flush.

That's what I thought. There would be a new version of `WriteDataAsync` that didn't flush which would be called in the code above (line 322).

**Comment by halter73** [comment]
> What pattern would you use to prevent the data from being available to the read loop before calling Complete? GetMemory, Advance, but no call to FlushAsync?

Yes.

> > Even in that case we'd have to tweak Http2FrameWriter.WriteDataAsync not to flush.
> 
> That's what I thought. There would be a new version of WriteDataAsync that didn't flush which would be called in the code above (line 322).

I don't think [line 322](https://github.com/aspnet/AspNetCore/blob/5f2760e9bcff03d98210221505da1afe510e64f7/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L322) where Http2OutputProducer.ProcessDataWrites() calls Http2FrameWriter.WriteDataAsync() needs to change.

We want to ensure the Http2OutputProducer.ProcessDataWrites() doesn't wake up at all meaning [the call to PipeReader.ReadAsync()](https://github.com/aspnet/AspNetCore/blob/5f2760e9bcff03d98210221505da1afe510e64f7/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L314) shouldn't complete until the entire response body is available.

This should already work because Kestrel's internal [HttpResponsePipeWriter.Advance()](https://github.com/aspnet/AspNetCore/blob/5f2760e9bcff03d98210221505da1afe510e64f7/src/Servers/Kestrel/Core/src/Internal/Http/HttpResponsePipeWriter.cs#L23) calls [HttpProtocol.Advance()](https://github.com/aspnet/AspNetCore/blob/5f2760e9bcff03d98210221505da1afe510e64f7/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1345) which in turn calls [Http2OutputProducer.Advance()](https://github.com/aspnet/AspNetCore/blob/5f2760e9bcff03d98210221505da1afe510e64f7/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L219) which shouldn't flush.

We just need to ensure that we can signal the end of the response body and flush to observe backpressure at the same time. CompleteAsync() should work for that.

@jkotalik

**Comment by Tratcher** [comment]
@halter73 I don't follow. CompleteAsync isn't doing anything new, it's just doing it earlier than normal. The traces above show that the current model is splitting frames, presumably due to a flush somewhere, so how do we prevent that?

**Comment by halter73** [comment]
> so how do we prevent that?

You said it yourself. "GetMemory, Advance, but no call to FlushAsync." The backpressure problem I bring up is unavoidable if we want to buffer indefinitely in order to avoid early flushes. We should have logic to always call FlushAsync after a certain amount of data is written.

Kestrel will do the final flush by calling WriteStreamSuffixAsync after the middleware exits. This no-ops if the middleware already called CompleteAsync. If middleware for whatever reason wanted to observe if there was backpressure due to flow control or something, the middleware would have to call CompleteAsync itself to observe Http2OutputProducer's `_dataWriteProcessingTask`.

**Comment by Tratcher** [comment]
@JamesNK want to retry this scenario with CompleteAsync?

**Comment by JamesNK** [comment]
I'm not advocating that Kestrel never flush data out before the response completes. I think for small responses (which will cover most API responses) it is a good optimization.

**Comment by JamesNK** [comment]
CompleteAsync also outputs two packets.

![image](https://user-images.githubusercontent.com/303201/59806142-7c5de480-9347-11e9-91f8-ea52efca8c71.png)

**Comment by halter73** [comment]
> I'm not advocating that Kestrel never flush data out before the response completes.

I didn't think you were advocating that. The point I'm trying to make is that the "GetMemory, Advance, but no call to FlushAsync" pattern leaves when to flush completely up to the application not Kestrel. If the app doesn't call FlushAsync or WriteAsync, Kestrel cannot by contract flush on your behalf.

Kestrel can and does coalesce flushes if they are two frequent, but you can still end up with multi-frame responses as you observed, so having a way for the application to easily buffer and prevent flushing is great, but the *application* needs to have the logic "to always call FlushAsync after a certain amount of data is written" not Kestrel.

> CompleteAsync also outputs two packets.

We'll need to investigate that. I don't think theres any reason in principle this shouldn't be combined into a single flush/packet given the current design.
