### ISSUE TITLE
Remove `on` prefix from blazor events

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#11340]
Follow up to @SteveSandersonMS's comment [here](https://github.com/aspnet/AspNetCore/issues/10893#issue-452468712). 

> Also I think we should drop on from these event names, as it feels less obvious than @bind:event="input". The on prefix is a bit of a historical oddity in HTML/JS generally, e.g., more recent APIs like addEventListener don't use on prefixes for event types.

Current,
```cshtml
<input @bind-value="@someText" @bind-value:event="oninput" />
```
Proposed,
```cshtml
<input @bind-value="@someText" @bind-value:event="input" />
```

@danroth27 @SteveSandersonMS @rynowak

**Comment by SteveSandersonMS** [comment]
Note that if/before we do this, we need to verify we can safely remove the `on` prefix from the event names in the `AddAttribute` calls. That is, the TS code needs to be able to receive and make use of event handler names that don't have an `on` prefix. Otherwise it's going to be super weird that we have the prefix in some cases and not others.

Failing that, I'm leaning towards keeping the `on` prefix, as it's not harmful, and in terms of attribute names is less likely to clash with unrelated things.

**Comment by danroth27** [comment]
> I'm leaning towards keeping the "on" prefix

OK, let's go ahead and close this then
