### ISSUE TITLE
Debugging Blazor Server-Side app disconnects the client

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#11383]
When Debugging a Blazor Server-Side application, it's quite common to hit a breakpoint and stay in that mode for some time. While the service is in that `Blocked` mode, the Blazor client will still try to `ping` the server, but get no response, which will eventually result the client getting disconnected.

We should set the timeout value for Development environment to a quite long time, to avoid this issue during development.

**Comment by mkArtakMSFT** [comment]
@anurse what do you do for SignalR in this case? If you hit a breakpoint on the server, what will happen to the client?

**Comment by anurse** [comment]
We [disable our "timeout" scavenging logic on the server](https://github.com/aspnet/AspNetCore/blob/04c3192d3cec396a9f2343fb5407d6777349b9df/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs#L150) when the debugger is attached. That prevents the server from terminating the connection (due to a long pause at a breakpoint).

We don't do anything from the client though, it's definitely still possible to have the client terminate the connection due to a lack of pings from the server. In theory, what you'd want to do is to communicate to the client that you're in Development mode and shouldn't time out. However disabling the timeout altogether in Development mode is probably not a great idea either. It's a tricky situation to be in, and I don't think we have a good clear solution yet.

**Comment by mkArtakMSFT** [comment]
Dupe of https://github.com/aspnet/AspNetCore/issues/11444
