### ISSUE TITLE
Server side Blazor in preview6 does not allow to edit .razor pages on the fly

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#11489]
### Describe the bug
When taking the `Blazor (server side)` template, it's not possible to edit .razor files during compilation (The app only shows the old content).

### To Reproduce
1. Using `ASP.NET Core 3.0` with `SDK 3.0.100-preview6-012264`.
2. Run the server side Blazor example project.
3. Edit e.g. `<button class="btn btn-primary" @onclick="@IncrementCount">Click me</button>` to `<button class="btn btn-primary" @onclick="@IncrementCount">Test me</button>` in the `Pages\Counter.razor` file.
4. Press `F5`.
5. See that the app doesn't change the button text.

### Expected behavior
For the example: The application runs again after pressing `F5` and shows `Test me` instead of `Click me` on the button.

### Screenshots
Before:
![image](https://user-images.githubusercontent.com/9639361/60000162-ef2ad080-9663-11e9-9181-de23e02d209f.png)

After:
![image](https://user-images.githubusercontent.com/9639361/60000271-29946d80-9664-11e9-9842-f4e5eb0843ab.png)

How it should look like/How it looks like after restaring:
![image](https://user-images.githubusercontent.com/9639361/60000372-5ba5cf80-9664-11e9-9d51-6fc6b26773d8.png)

### Additional context
* It's independent of using IIS or not as well as independent of the build environment set to `Release` or `Debug`.
* Running the app with `STRG` + `F5` doesn't change a thing either.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeppPenner.
We plan to address this as part of https://github.com/aspnet/AspNetCore/issues/5456 work.

**Comment by danroth27** [comment]
To clarify, if you're using the latest Visual Studio Preview (https://visualstudio.com/preview) you should be able to run the app *without* debugging (Ctrl-F5), edit files in the project including .razor files, and then VS will rebuild and restart the app automatically so that you can just refresh the browser to see the change. If this isn't working for you with the latest bits please let us know!

Support for Live Reload (#5456) is about removing the need to refresh the browser manually and also considering ways to update the app without having to completely restarting it. This work is still on our backlog and is not planned for the current release.

**Comment by SeppPenner** [comment]
> To clarify, if you're using the latest Visual Studio Preview (https://visualstudio.com/preview) you should be able to run the app without debugging (Ctrl-F5), edit files in the project including .razor files, and then VS will rebuild and restart the app automatically so that you can just refresh the browser to see the change. If this isn't working for you with the latest bits please let us know!

That's what isn't working... I adjusted the button text as described above and tried this with building in `Release` and `Debug`, running it on IIS or not, starting it with `F5` and `Ctrl-F5`. If you want, I can check this again tomorrow and provide the Visual Studio version, too. However, I'm quite sure that I have the latest preview installed.

**Comment by danroth27** [comment]
@SeppPenner Thanks for these additional details!

Auto-rebuilding the app will only work in VS if you're not running under the debugger (Ctrl-F5) and you're running on IIS Express. And you need the latest VS preview: 16.2.0 Preview 2.0. Please double check that you're doing all those things and let us know if it's still not working.

**Comment by SeppPenner** [comment]
@danroth27 Okay, it seems like I accidently didn't use the preview version (I have VS2017, VS2019 and VS2019 latest preview installed) but the regular VS2019. When using the 16.2.0 Preview 2.0 with `Ctrl-F5`, changing things works, but it shows `Failed to reconnect to the server.`. I guess that's the issues @mkArtakMSFT was referring to.

**Comment by genifycom** [comment]
This is NOT working for me in VS 2019 Version 16.2.0 Preview 4.0 (DotNetCore 3.0.0-preview7-27912-14). I am using the standard Blazor Server App.

When you start without debugging the app start. I modify some text and save the file (NavMenu.razor line 2).

The change is detected and the browser says "Attempting to reconnect to the server.".
VS 2019 Version 16.2.0 Preview 4.0 completes the Build successfully.
The browser indicates "Failed to reconnect to the server."

A retry using the retry button has no effect.

I am using Ctrl-F5 (run without debugging)
I am using IISExpress
I am using the Preview >= 16.2 Preview 2,

Is it timing out?

**Comment by danroth27** [comment]
Hi @genifycom. You need to manually refresh the browser after making a change. Visual Studio will take care of detecting the change, rebuilding the app, and restarting the dev web server at which point any state associated with the browser session will be lost and you'll see that "Failed to reconnect to the server page". The Retry button is only helpful if the state is still there on the server, which it isn't, because the server was restarted. So, in summary, the dev flow is 1. edit, 2. save, 3. refresh the browser. We plan to make some changes to the Retry button UI to make this clearer.

Also, please be sure to update to the latest Visual Studio Preview (16.3 Preview 1).

**Comment by genifycom** [comment]
Awesome. Thank you. I see the 16.3 today and will install.

Thank you for the refresh instructions. Confirmed that this works.

**Comment by AdmiralSnyder** [comment]
@danroth27 is that Ctrl-F5 Refreshing behaviour documented in one of the blog posts?
