### ISSUE TITLE
SignalR - HubProtocol user ID - where to put it ?

### ISSUE THREAD

**Issue by iniside** [aspnet/AspNetCore#11480]
I need to write custom client for SignalR (for Unreal Engine). So far I was able to send simple messages by manually constructing the required json. 

The main functionality I need though, is sending messages from/to specific users. 
Is there some specific field I need to add to json to achieve that ? I

**Comment by BrennanConroy** [comment]
In order to get users you will need to configure auth on the server and configure your client to send the correct auth token/cookie/etc. when it makes requests.

You can read up about the auth system in Asp.Net Core here: https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-2.2

And for more specific auth related to SignalR here: https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2

If you would like to see a simplified example of auth with SignalR you can take a look at a sample here: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/samples/JwtSample/Startup.cs and the client code here: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/samples/JwtClientSample/Program.cs#L32
