### ISSUE TITLE
Blazor - Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by selimhur** [aspnet/AspNetCore#11561]
I want to change bootstrap theme with material css, when i include js files
i am getting errors

![image](https://user-images.githubusercontent.com/40705565/60124191-c30d6d80-9791-11e9-86b3-70025a071098.png)

if i remove 
<script src="_framework/blazor.server.js"></script>

it is working, 
what is the reason for the error

![image](https://user-images.githubusercontent.com/40705565/60124465-56df3980-9792-11e9-8668-dc38b736e1df.png)

**Comment by SteveSandersonMS** [comment]
I'm afraid the information above isn't enough to have any idea what's going on among all those different JS files.

If you're able to provide minimal repro steps we could have a look.

**Comment by selimhur** [comment]
AspNetCoreProject And Html Template : https://github.com/selimhur/aspnetblazor

![image](https://user-images.githubusercontent.com/40705565/60203971-8d7e8800-9856-11e9-8463-8ad71c045692.png)

![image](https://user-images.githubusercontent.com/40705565/60203995-9ff8c180-9856-11e9-98c0-e6a8123d9d83.png)

**Comment by SteveSandersonMS** [comment]
This seems to be a usage issue concerning the third-party JavaScript APIs. There are various reports of the error you've mentioned in connection with bootstrap material design and other SPA frameworks. Examples:

 * https://stackoverflow.com/questions/30604758/cannot-read-property-open-of-undefined
 * https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/issues/70

Since this seems to be an external issue and there's no specific reason to think it's a bug in Blazor, it's not something I'd be able to debug for you. I hope that seems reasonable.

If you are able to track this down and find there is a specific bug in Blazor, please let us know. For example, if you can give steps to reproduce the bug *without* using the third-party JS libraries, that would point to there being some problem in Blazor.
