### ISSUE TITLE
An asp-route should convert kebab case to camelcase

### ISSUE THREAD

**Issue by bradlis7** [aspnet/AspNetCore#11613]
### Describe the bug
An action parameter by default is camelCased, but HTML attributes use kebab-case. When I use `asp-route-my-variable`, it does not bind it to `myVariable` parameter.

### To Reproduce

Controller action:

```
public IActionResult MyAction(string myVariable) {
  return Content(myVariable);
}
```

MyAction.cshtml:

```
<a asp-action="MyAction" asp-route-my-variable="test">Link</a>
```

### Expected behavior
It should set the parameter correctly.

**Comment by javiercn** [comment]
That's by design, that is not how the `asp-route-*` tag helper works. What you put after `asp-route-` is interpreted as the route parameter, that should match what you define on the route within `{}` and gets bound to the variable on the method. 

You can use `{my-variable}` in your route parameter definition and [FromRoute(Name = "my-variable")] to make it bind to myVariable.
