### ISSUE TITLE
Blazor: Ability for services to detect when JSRuntime is available and safe to invoke

### ISSUE THREAD

**Issue by egil** [aspnet/AspNetCore#11741]
### Services that depend on JavaScript should be able to detect when it is available
When creating a Blazor service that depend on JavaScript via `IJSRuntime`, it would be great to be able to detect when the JavaScript runtime is available to interact with.

Otherwise users (components) of my services will have to remember to always wait to call functionality on the service in their `OnAfterRender()` methods. If the service is used in multiple places in the render hierarchy and has a lifetime of `Singleton` or `Scoped`, then the user will sometimes get the experience that the service works in other stages of the component life cycle, because another component higher up in the render tree has it embedded as well. Thats a bad user experience.

### Example usage
I have a service that surfaces the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) API to components. It allows components to subscribe to an event that will notify them, if the page they are rendered on, changes its visibility state.

Under the hood, the service uses JavaScript to subscribe to the browsers implementation of the Page Visibility API the first time a user/component subscribes to the services event. If a user subscribes correctly during their `OnAfterRender` lifecycle method where the JSRuntime is available to the service, they will have to make sure that they only subscribe one time, even if their component is rendered multiple times.

When I use it in my own components, I have a custom lifecycle method called `OnAfterFirstRender` that only fires after the first render. That prevents multiple subscriptions to the services event.

### Possible solution
Without much knowledge of how and when the JSRuntime is ready, my current best suggestion for a solution is to add an `event EventHandler<JSRuntimeReadyEventArgs> OnJSRuntimeReady` event to the `IJSRuntime`.

**Comment by ApocDev** [comment]
Possibly pull in IComponentContext and check IsConnected?

This is the fix that was suggested in Gitter to another (unrelated) issue.

**Comment by egil** [comment]
> Possibly pull in IComponentContext and check IsConnected?

@ApocDev can you provide a little more info on the work-around you are suggesting?

**Comment by enetstudio** [comment]
@egil, I'm almost sure that I've seen such code in Blazor framework. But I do not remember where. My guess is that it was in a bootstrapping code; perhaps in code used in services.AddServerSideBlazor() or related...

**Comment by Joe4evr** [comment]
+1 for `OnAfterFirstRender` or similar.

**Comment by jbomhold3** [comment]
OnAfterFirstRender requests keep getting shot down because they are not wanting to add LifeCycles...
Their issue is that it is easy enough to just add a bool to your component to control the first run. 

However, it's not pretty or convenient. This is part of the attraction to frameworks. We save time writing boilerplate code and get to focus on our code. I don't want to have to add bool isFirstRun = true;    if(isFirstRun) { logic; isFirstRun = false } otherlogic to all components I need a one time run after render on. I rather just override OnAfterFirstRender() {logic;} . To me, it's far cleaner, has an implied understanding at first glance. Stuff I want to run once after render will be here.  
This is nothing new Angular, Vue, React(probably others I got tired of checking). All have a life cycle hook at this exact point mounted or on ngAfterViewInit.  I think this is a worth wild LifeCycle to add and will require minaul effort to do so. There's already a closed PR that does this.   @danroth27 @SteveSandersonMS @javiercn
