### ISSUE TITLE
Using RenderStaticComponentAsync in default template results in exception

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11799]
Steps

* Create a new blazor template `dotnet new blazorserverside`
* Edit `_Host.cshtml` and replace `RenderComponentAsync` with `RenderStaticComponentAsync`
* `dotnet run`

This results in an exception:

```C#
InvalidOperationException: GetAuthenticationStateAsync was called before Initialize.
Microsoft.AspNetCore.Components.Server.Circuits.FixedAuthenticationStateProvider.GetAuthenticationStateAsync()
Microsoft.AspNetCore.Components.CascadingAuthenticationState.OnInit()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
```

**Comment by SteveSandersonMS** [comment]
This is because `StaticComponentRenderer` doesn't use the same circuit initializing logic that `RemoteRenderer` does (via `DefaultCircuitFactory`). In turn, this is because static prerendering doesn't involve creating a circuit at all.

Suggested fix:

To avoid having to keep remembering to duplicate initialization logic across the two types of server-side execution environments, I suggest we have some static class `StandardServiceInitialization` in the `M.A.Components.Server` project, with a static method `InitializeServices(HttpContext httpContext, string uriAbsolute, string baseUriAbsolute)`. It can then find and initialize both `FixedAuthenticationStateProvider` and `RemoteUriHelper` and anything else we add to the "standard" set of services in the future.

We then call this from both `DefaultCircuitFactory` and `StaticComponentRenderer.PrerenderComponentAsync` (replacing the existing calls from those places that initialize the services).
