### ISSUE TITLE
AddClass method to RenderTreeBuilder

### ISSUE THREAD

**Issue by montyclt** [aspnet/AspNetCore#11817]
### Is your feature request related to a problem? Please describe.
I'm creating a component that need to add one or two classes depending on condition.

### Describe the solution you'd like
Add new method to `RenderTreeBuilder` that check if class exist in element, and if exists, add it next to the existing classes.

```cs
builder.OpenElement(0, "div");
builder.AddClass(1, "color-green");
builder.AddClass(2, "bg-red");
builder.CloseElement(); // <div class="color-green bg-red"></div>

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

This is not something we want to do in the forseeable future, because for performance, the `RenderTreeBuilder` tries not to have expensive operations like this where we can avoid it (doing this would involve scanning backwards to find other attribute nodes and mutating them). Also, we try to minimize coupling to HTML-specific concepts such as CSS classes.

I would recommend amending your builder logic to do the necessary buffering of CSS class names and then emit a single attribute at the end.
