### ISSUE TITLE
System.Collections.Generic namespace not being picked up in .razor files

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11856]
It looks like we add a using statement for the System.Collections.Generic namespace in the generated code from a .razor file, but it's not getting picked up in intellisense. If you manually type an `IList<T>` it works, but intellisense will fight you.

![2a2FLhT8tF](https://user-images.githubusercontent.com/1874516/60609047-a5ce3580-9d75-11e9-99b7-5035bf9ad29b.gif)

**Comment by NTaylorMullen** [comment]
This is most likely a combination of a projection buffer issue along side the innability to ctrl . add usings.

**Comment by danroth27** [comment]
> along side the inability to ctrl . add usings in Razor documents

Please note that the generated code already has a using statement for System.Collections.Generic. Intellisense just doesn't seem to know about it.

**Comment by ajaybhargavb** [comment]
@NTaylorMullen, should we follow up on this with the Completion team or WTE?

**Comment by ajaybhargavb** [comment]
@danroth27, I tried this out and it looks like it is working as expected. 
![repro](https://user-images.githubusercontent.com/1579269/62485706-51521780-b772-11e9-95a7-a3e6a27fddec.gif)

The reason it completes to `System.Collections.IList` is because it thinks you are trying to write the non-generic version of the type which is in a different namespace not in scope.
The reason this still works in cs files is because of the ability to auto add usings. Notice how it auto added `using System.Collections` even though it wasn't necessary.
![repro2](https://user-images.githubusercontent.com/1579269/62486015-0684cf80-b773-11e9-8096-5e5537172c31.gif)

There is no actual bug here, it is just that since we don't support auto adding using statements, we have a slightly different behavior than a regular cs file. This is something we have to live with until we implement that feature.

**Comment by ajaybhargavb** [comment]
Closing this. Please reopen if there is any action item here for us.
