### ISSUE TITLE
Blazor app crashes in use null as @key="@..."

### ISSUE THREAD

**Issue by ZergZe** [aspnet/AspNetCore#11892]
### Describe the bug
Data sources may contain null as item.
@key feature in this case crashes application.

### To Reproduce
```
<ul>
    @foreach(var str in DataSource) {
        <li @key="@str">@str</li>
    }
</ul>

@code {
    string[] DataSource = new string[] { null, "String 1", "String 2" };
}
```

### Actual Result

```
ArgumentNullException: Value cannot be null.
 Parameter name: value
Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.SetKey(object value)
```

### Expected behavior
null value can't be used as key (since several null item would be indistinguishable), so, key may be ignored for this li elemen. It should not crash app. It should not require workaround.

### Possible workaround

```
    @foreach(var str in DataSource) {
        @if(str != null) {
            <li @key="@str">@str</li>
        } else {
            <li>@str</li>
        }
    }
```

**Comment by SteveSandersonMS** [comment]
This is as expected. If you want to use `key`, you really should find something distinct for each of your items, otherwise it's not meaningful. We throw if you pass `null` because otherwise developers wouldn't realise if they were in a situation where `key` couldn't work.

If you want to, you can do something like `@key="@(someValue ?? new object())"` or `@key="@(someValue ?? "fixed value")"`, depending on how you want those items to be treated. Using `new object()` would cause the framework to drop and recreate the descendants on each render, whereas using `"fixed value"` would cause the keys to be ignored for those items.
