### ISSUE TITLE
ASP.Net Core 2.1 SPA Node Based Project Templates have out of date dependencies which cause build/publish failures on macOS with latest versions of node (e.g. 10.16 LTS)

### ISSUE THREAD

**Issue by iantoalms** [aspnet/AspNetCore#11922]
### Describe the bug
The 2.1.x React and Angular templates have indirect dependencies on the (Mac specific) fsevents package.  There are no binary packages available for version 1.1.2 of the fsevents package when used with node 10.x and above, so npm tries to build the package from source using node-gyp.  The node-gyp build process requires the xcode tools to be installed, so this will frequently cause a build failure. Even if the xcode tools are installed, the node-gyp build process will regularly fail.

The dependency tree for fsevents:

Ians-Work-MacBook-Pro-15:ClientApp iantoal$ npm ll fsevents
React21700@0.1.0
│ /Users/iantoal/Projects/Test/React21700/ClientApp
│ This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).
└─┬ react-scripts@1.0.17
  │ Configuration and scripts for Create React App.
  │ git+https://github.com/facebookincubator/create-react-app.git
  │ https://github.com/facebookincubator/create-react-app#readme
  ├── fsevents@1.1.2 
  │   Native Access to Mac OS-X FSEvents
  │   git+https://github.com/strongloop/fsevents.git
  │   https://github.com/strongloop/fsevents
  └─┬ webpack-dev-server@2.9.4
    │ Serves a webpack app. Updates the browser on changes.
    │ git+https://github.com/webpack/webpack-dev-server.git
    │ https://github.com/webpack/webpack-dev-server
    └─┬ chokidar@1.7.0
      │ A neat wrapper around node.js fs.watch / fs.watchFile / fsevents.
      │ git+https://github.com/paulmillr/chokidar.git
      │ https://github.com/paulmillr/chokidar
      └── fsevents@1.1.2  deduped
          Native Access to Mac OS-X FSEvents
          git+https://github.com/strongloop/fsevents.git
          https://github.com/strongloop/fsevents

### To Reproduce
1) Install node.js LTS 10.16
2) Install dotnet core 2.1.700
3) Create a folder to install the project into e.g. TestReact21700
4) dotnet new react
5) dotnet publish - You may see a popup to install the Xcode commandline tools if they arent already installed.  These need to be installed to enable node-gyp to build the fsevents package on the fly. You'll need to restart your console to successfully build after installing the Xcode tools.

You will see a failure like the following:
[output.txt](https://github.com/aspnet/AspNetCore/files/3363349/output.txt)

### Expected behavior
Everything builds and publishes fine.

### Additional context
If you use an older version of node (e.g. 8.16) you will never hit this issue.  The 1.1.2 version of fsevents is explicitly not supported with 10.x and is very old.

Another workaround is to use: npm install fsevents@latest

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT we might want to get the opinions of a PM, but I'm fairly certain this is known and expected. As I recall we recommend node 8 for 2.1 and 2.2, so problems encountered on 10 aren't something we'll react to. The recommendation if this causes you trouble is to either downgrade node or do as @iantoalms suggests and update the offending packages.

**Comment by mkArtakMSFT** [comment]
Isn't this waht we use in 2.2, or am I looking at something different?

https://github.com/aspnet/AspNetCore/blob/2c9e5c9356d641cba280718cb7a21489ddc31954/src/Middleware/SpaServices/src/package-lock.json#L8

**Comment by ryanbrandenburg** [comment]
Hmm, that's interesting because it contrasts with https://github.com/aspnet/AspNetCore/blob/15c5dfec2e08787c32ece978139addb944c39494/src/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/package-lock.json#L506

I think these differ because the package-lock.json's are generally created and checked in on a developers machine rather than in any kind of controlled environment (so the dev might have a newer or older version of node than what is supported). The installed node/npm version would seem to present another area of danger with checking the lock files in (the other being that people might not know to re-generated and check in the lock file when they change the package.json (or just forget)).

I thought there was an issue somewhere where we explicitly stated which versions of npm we were supporting/recommending for 2.2, but I can't seem to find it now. The closest I could find was https://github.com/aspnet/templating/pull/582#issuecomment-400838566.

**Comment by mkArtakMSFT** [comment]
Thanks @ryanbrandenburg.
@iantoalms, please stick with the `Node 8` release to unblock yourself.
