### ISSUE TITLE
Require setting of KnownNetworks or/and KnownProxies when ForwardLimit is set to null.

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore#11980]
Documentation for `ForwardedHeadersOptions.ForwardLimit Property` currently [contains](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.forwardedheadersoptions.forwardlimit?view=aspnetcore-2.2) these commens:

>Set to `null` to disable the limit, but this should only be done if `KnownProxies` or `KnownNetworks` are configured.

I [asked](https://github.com/aspnet/AspNetCore.Docs/issues/13116) for more detailed description of the security issues. However, I got the reply to my request #11949 :

> Generally we don't do this for security issues because people simply don't read the docs and we'd rather everyone was as safe as possible.

So if ASP.NET Core wants to be strict and consistent, there should be check for the secure combination of `ForwardedHeadersOptions` settings and exception should be thrown in case the combination is not fine.

**Comment by blowdart** [comment]
@Tratcher thoughts?

**Comment by anurse** [comment]
Throwing an exception here would be a breaking change. We could consider squeezing that in to preview 8. Given the security aspect here I'm not opposed to the idea (but would like to hear @Tratcher 's thoughts). 

The only case I can see where unlimiting `ForwardLimit` while also not restricting `KnownProxies` and `KnownNetworks` would be if my app is running on an entirely trusted closed network. It still seems reasonable to require at least `KnownNetworks` in that case, since you should hopefully be able to specify the CIDR(s) that are valid in that scenario.

A less breaking alternative would be to log a warning (or even an error, without actually throwing something). But I think that's probably not really necessary here.

**Comment by Tratcher** [comment]
Conceptually I agree, but people end up with pretty complex configs and being overly prescriptive would likely prevent them from using this middleware. We focus on secure defaults and try to explain the implications of changing them. 

Also, the security implications are only as severe as how you utilize the results. It's one thing if you're using the client IPs for telemetry, but quite another if you're trying to use them as an allow/deny list for authorization. Given there are a variety of other ways to spoof client IPs (e.g. VPNs), there are practical limits to how far you should trust them.

**Comment by anurse** [comment]
Triage decision: We try to have relatively secure defaults but validating every permutation isn't really feasible. Docs are pretty clear here. Closing as we don't intend to take action.
