### ISSUE TITLE
Select best cnd location in tools.ps1

### ISSUE THREAD

**Issue by wu-yafeng** [aspnet/AspNetCore#11989]
When I run **restore.cmd**,the processor will install .NET Core SDK from server: [https://dotnetcli.azureedge.net](https://dotnetcli.azureedge.net)

but it's not a best location for china,it seems use https://download.visualstudio.microsoft.com/download/pr/4e73514f-0646-4600-bdc2-38c90fc207b6/22ad70cbe1a254177e6d7b7f7e7425f8/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip is better? Maybe other cdn in china.

I think it should auto select cdn server by ``user location`` or ``computer culture``

**Comment by anurse** [comment]
`dotnetcli.azureedge.net` does generally select the appropriate CDN server by location. It's possible that doesn't include china though. Is it just that the download is slow or does it not complete?

We can't reliably download from the download center link because we sometimes use unreleased SDKs which aren't available from `download.visualstudio.microsoft.com`.

**Comment by wu-yafeng** [comment]
The download is very slow and dose not complete most time.
The download speed only 5KB/s when download SDK in browser by url `dotnetcli.azureedge.net`
