### ISSUE TITLE
ConnectionState.getNextInvocationId() Null pointer exception

### ISSUE THREAD

**Issue by mashahbazi** [aspnet/AspNetCore#11995]
After I figured the error #6898 and as said it's error fixed in 3.0.0-preview3. but now is start to send NullPointerException on invoke
Attempt to invoke virtual method 'java.lang.String com.microsoft.signalr.HubConnection$ConnectionState.getNextInvocationId()' on a null object reference
I check hubConnectionState to be HubConnectionState.CONNECTED before calling method invoke.

**Comment by anurse** [comment]
cc @mikaelm12

**Comment by mikaelm12** [comment]
Yeah, please post the version of the Java client that you are using, If you're not on preview 6, then I'd first recommend updating to use that. Preview 7 is coming out next week and it also has some updates to the Java client but they shouldn't directly effect the scenario you mention.

Preview 6  version com.microsoft.signalr:signalr:3.0.0-preview6.19307.2  https://search.maven.org/artifact/com.microsoft.signalr/signalr/3.0.0-preview6.19307.2/jar
Note this when looking for the jars on search.maven.org this wont come up as the latest version since we changed our versioning to use dots rather than dashes.

**Comment by mikaelm12** [comment]
And if you could also include the full stack trace that would be helpful as well!

**Comment by mashahbazi** [comment]
yeap, I'm update and my version is `3.0.0-preview6.19307.2`. And I said my stack trace for you it's very simple.when you invoke it get null. this is fabric crashlytics log.
`com.microsoft.signalr.HubConnection.invoke + 586 (HubConnection.java:586)`
before this trace is in my code.

**Comment by mikaelm12** [comment]
After a quick investigation, it looks like we need some more locking. Moving this into preview 8

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/AspNetCore/pull/12078

**Comment by mikaelm12** [comment]
Also related though - https://github.com/aspnet/AspNetCore/issues/12138

**Comment by mashahbazi** [comment]
error occurred in preview 8 again
