### ISSUE TITLE
Adding custom request header in 2.2

### ISSUE THREAD

**Issue by tharidu** [aspnet/AspNetCore#12114]
I'm in the process of updating a ASP .Net core 2.1 app to 2.2. I have enabled `InProcessHosting` to the web project as well. For CSP purposes we are adding a custom header to all requests using a middleware using ,

`context.Request.Headers.Add(new KeyValuePair<string, StringValues>)` 

method. In runtime, from this code we get an exception 
`System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.HttpSys.Internal.RequestHeaders' to type 'System.Collections.Generic.IDictionary[System.String,System.Object]`

This work as expected in 2.1 :)

However, when I use `context.Request.Headers.Add(string, StringValues)` method, it works as expected. Any idea what causes this issue?

**Comment by Tratcher** [comment]
This is an ICollection API.
`Dictionary<TKey,TValue>.ICollection<KeyValuePair<TKey,TValue>>.Add(KeyValuePair<TKey,TValue>)`
Do you have some reason to use that overload rather than IDictionary's `Add(key, value)`?

I see two casts to `string, object` that don't look like they were ever correct. Apparently nobody has ever called this API 😁. 
https://github.com/aspnet/AspNetCore/blob/9c69287ed081b41694d0149274bb3e19ae2704cf/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L113
https://github.com/aspnet/AspNetCore/blob/9c69287ed081b41694d0149274bb3e19ae2704cf/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L128
