### ISSUE TITLE
[Blazor Client side] Please update the docs...

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#12144]
Team;
We need to build our app using Client-Side as Server-side does not fit in our case.
There are so many new features that have been added to client-side in every preview, yet the docs are so behind on the client-side.

PLEASE update the docs, so we can use these new features properly.
Thanks!
..Ben

**Comment by guardrex** [comment]
Hello @BenHayat ...

We continuously update the docs, and they are updated to Preview 6. What specifically did you find that wasn't updated?

**Comment by BenHayat** [comment]
@guardrex ;
Hi Luke;
Thanks for the reply;
I was watching Steve's latest video from the NDC (https://www.youtube.com/watch?v=uW-Kk7Qpv5U)
and during the first half of his video, he was covering lots of nice features and a few times, he referred to these new features that have been added to preview 6. But looking at the client side of the docs, it seems very brief and that's why I was asking to keep the client side along with server side.

Thank you in advance!
..Ben

**Comment by guardrex** [comment]
Thanks ... I'll take a look at that.

I track the preview release work at https://github.com/aspnet/AspNetCore.Docs/issues/10717.

If I find anything in the video that we're missing, I'll get a PR in to address it. Since this is a docs issue, I recommend that you close here (given that this is the engineering repo). I'll add a note and ping you on the tracking issue if I don't find anything additional to cover. If I do find MIA content, I'll get a PR in and ping you on that. I'll take a look at this either on Sunday or Monday, so I'll get back to you soon.

**Comment by BenHayat** [comment]
Thank you Sir;

Sorry I posted in the wrong section. For Blazor doc issues, where should I post in the future?
I'm closing this issue as per your suggestion.

**Comment by guardrex** [comment]
No problem ... each Blazor topic has a **This Page** feedback button at the bottom. That both opens the issue on our docs repo and tags the issue with metadata from that topic for our tracking. That's the best approach.

If you have general docs feedback that doesn't apply to a specific topic, then open an issue right on the repo. It won't have the topic metadata, but that's ok since the feedback doesn't really apply to just one issue. The repo issues are at :point_right: https://github.com/aspnet/AspNetCore.Docs/issues.

If you want to see what we're currently working on, thinking about (triage), and planning, check out the [Blazor Project](https://github.com/aspnet/AspNetCore.Docs/projects/35).

**Comment by BenHayat** [comment]
Ah, great set of info.
Much appreciate your help!

**Comment by guardrex** [comment]
@BenHayat, I'll react here in case anyone else is curious or finds this while searching the issues on this repo.

I just scanned the video. I can't actually watch every bit of it ... we're always 🏃🏃🏃🏃😅 around here and don't have that kind of time :smile:. A few notes ...

* For WebAssembly and related concepts, we cross-link to external resources.
* For Razor-specific constructs, we cross-link to the [Razor syntax topic](https://docs.microsoft.com/aspnet/core/mvc/views/razor?view=aspnetcore-3.0).
* For debugging, troubleshooting, and inspection of .NET objects, these subjects are only lightly covered at this time. Browser dev tools will always be documented in detail by external resources. Blazor-specific debugging scenarios are still in design and testing by the product unit. For example, scenarios in IDEs, such as VS, VS4Mac, and VS Code, are still under construction for debugging scenarios. We don't have anything stable to document at this time. We have an [issue to create a troubleshooting topic](https://github.com/aspnet/AspNetCore.Docs/issues/10746), so we'll get to that later for sure. The only coverage we have at this time is [Debug ASP.NET Core Blazor](https://docs.microsoft.com/aspnet/core/blazor/debug?view=aspnetcore-3.0), and we'll be enhancing that content later, likely after 3.0 RTM.

Everything else is covered AFAIK. Did you set the doc version selector (upper left-hand corner of any docs page) to "3.0 Preview"? It's required to get the Blazor topics to show up in the table of contents. This link will take you right to the top of the Blazor articles :point_right: https://docs.microsoft.com/aspnet/core/blazor/?view=aspnetcore-3.0

If you find something missing, open a new issue using the **This Page** feedback button at the bottom of any topic. That will ping me directly when you open the issue.

**Comment by BenHayat** [comment]
> If you find something missing, open a new issue using the This Page feedback button at the bottom of any topic. That will ping me directly when you open the issue.

Hi Luke;
I understand you're very busy. I will go through the video again and make notes of those features that Steve referred to and then through the "This Page" communicate back to you.
Ye, I always make sure I'm looking at 3.0 preview of the docs.
Thank you for caring!
