### ISSUE TITLE
[Razor] The img tag should work consistently when assigning a hardcoded value or an expression to its src attribute

### ISSUE THREAD

**Issue by BrightSoul** [aspnet/AspNetCore#12161]
Hi everyone,
I'm using ASP.NET Core 2.2.101 on Windows 10 for an MVC application.

### Example 1
Suppose I type the following in a Razor View.
```
<img src="~/logo.svg">
```
The `ImageTagHelper` then correctly renders this fragment of HTML.
```
<img src="/logo.svg">
```
### Example 2
Now, let's move back to the Razor View and use a variable instead of the hardcoded value.
```
@{
  string logo = "~/logo.svg";
}
<img src="@logo">
```
I expected the very same result from before. Instead, it seems the Razor Engine doesn't actually let the `ImageTagHelper` do the processing and it just outputs this fragment of HTML, which is obviously wrong.
```
<img src="~/logo.svg">
```
### Example 3
And for a final example, let's go back to the Razor View again and add the `asp-append-version` attribute to the `img` tag.
```
@{
  string logo = "~/logo.svg";
}
<img src="@logo" asp-append-version="false">
```
Now it's working correctly again: it outputs the correct fragment of HTML.
```
<img src="/logo.svg">
```
### My request
Is it possible to make the `img` tag work consistently? Not every user might know the `asp-append-version` "solution" and this would leave them puzzled (myself included).
What's actually happening with Example 2?

Thanks in advance for your attention.
Moreno

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BrightSoul.
We're currently busy putting the final touches up for the upcoming 3.0 release.
We'll look into this after we're done with 3.0.

**Comment by NTaylorMullen** [comment]
So this is actually by design. In your example 2 the ImageTagHelper is not running on the tag at all (it's a non-TagHelper img tag). As a performance optimization our ImageTagHelper/UrlResolutionTagHelper specifically does not run on all image tags in order to ensure we don't TagHelperify everything in the world. This is also why you see in your example 3 things start to work, the tag becomes a TagHelper and the ImageTagHelper is smart enough to resolve the app relative URL
