### ISSUE TITLE
User always required to login after 20 minutes

### ISSUE THREAD

**Issue by wutever0** [aspnet/AspNetCore#12166]
I'm hoping someone can point me in the right direction with this.

I can't seem, no matter what I try, to increase the time required between user logins more than 20 ~ 30 minutes. This is even if the user is continuously active - so this is not "idle" time it's maximum time between logins. After 20 minutes the user is redirected to the login page to login again.

The strange thing is that when I decrease the CookieOptions.ExpireTimeSpan to something like 10 seconds, it redirects after 10 seconds as expected. I also tested the SlidingExpiration and that works too with the very low ExpireTimeSpan value ( the user keeps working till the total time spent is more than 20 minutes after which it redirects again - as if 20 minutes was the MAX you can ever go without logging in). When I set the ExpireTimeSpan larger than 20/30 minutes doesn't seem to work and it forces me to login again.

I thought this might have something to do with my host server's application pool settings. Maybe the application pool dies after 20 minutes causing the login to be invalid but it happens even when I run the application straight from Visual Studio using IISExpress.

The problem is I don't even know what to try or where to look. I've completely run out of ideas  and I don't know how to debug this if this is a cookie issue.

### To Reproduce
This is an ASP.NET Core 2.1 application.

I set the ExpireTimeSpan to 1 hour and the SlidingExpiry to true. Once I log in I set a stop watch to 15 minutes. At 15 minutes I navigate to one of the pages. After another 15 minutes I navigate to another page but it always redirects me to the login page at this point. I tried this with different scenarios - one time navigating pages every 4 or 5 minutes.. it always redirects to the login page at around 20 ~ 30 minutes (approximate since I lose count sometimes and it takes time to go to the screen and click and then reset my countdown times)

This is my code currently on Startup:

      public void ConfigureServices(IServiceCollection services)
      {
        services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential cookies is needed for a given request.
            options.CheckConsentNeeded = context => false;
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });
         //services.AddSingletons, Transients etc..
        services.AddIdentity<IdentityUser, IdentityRole>()
              .AddDefaultTokenProviders();

        services.Configure<IdentityOptions>(options =>
        {
            // Password settings.
            // Lockout settings.
            // User settings.
        });

        services.ConfigureApplicationCookie(options =>
        {
            options.LoginPath = "/Login";
            //sliding expiration doesn't seem to work, nor does expiretimespan
            options.SlidingExpiration = true;
            options.ExpireTimeSpan = TimeSpan.FromHours(1);
        });

        services.AddMvc(config =>
        {
            var policy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
            config.Filters.Add(new AuthorizeFilter(policy));
        }).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

        services.AddHttpContextAccessor();
    }

This is my Configure:

        app.UseDeveloperExceptionPage();
        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseCookiePolicy();

        app.UseAuthentication();

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });

And I login using this:

    [HttpPost]
    [Route("/Login")]
    [AllowAnonymous]
    public async Task<ActionResult> Login(string returnUrl, LoginFormModel loginFormModel)
    {
        returnUrl = returnUrl ?? Url.Content("~/");

        if (ModelState.IsValid) {
            var result = await _signInManager.PasswordSignInAsync(loginFormModel.Username, loginFormModel.Password, loginFormModel.RememberMe, lockoutOnFailure: true);
            if (result.Succeeded) {
                _logger.LogInformation("User logged in.");
                return LocalRedirect(returnUrl);
            }
       }
   }

### Expected behavior
With the SlidingExpiration set to true and the ExpireTimeSpan set to 1 hour I would expect that well after 30 minutes I would be able to continue working on the app.

### Additional context
Visual Studio 2017
.NET Core SDK (reflecting any global.json):
 Version:   2.1.507
 Commit:    e8520940d7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.507\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

**Comment by ZekeLu** [comment]
I think the reason is that you didn't configure **data protection**. I will copy part of the text from the official document. You can read the full document [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#data-protection)

> ... If data protection isn't configured, the keys are held in memory and discarded when the app restarts.
>
> If the key ring is stored in memory when the app restarts:
> * All cookie-based authentication tokens are invalidated.
> * Users are required to sign in again on their next request.
> * Any data protected with the key ring can no longer be decrypted. This may include CSRF tokens and ASP.NET Core MVC TempData cookies.
>
> To configure data protection under IIS to persist the key ring, use one of the following approaches:
> * Create Data Protection Registry Keys
>     ...
> * Configure the IIS Application Pool to load the user profile
>     ...
> * Use the file system as a key ring store
>     ...
> * Set a machine-wide policy for data protection
>     ...

I have tried the **Configure the IIS Application Pool to load the user profile** option in my own project and it works.

> This setting is in the **Process Model** section under the **Advanced Settings** for the app pool. Set **Load User Profile** to `True`.

The default `Idle Time-out (minutes)` of the IIS application pool is 20. So if you don't change its value and the website is idle for 20 minutes, the IIS worker process will be terminated. And if you don't configure the data protection, the keys held in memory will be discarded. That explains why the user is redirected to the login page after 20 minutes. For the `This is even if the user is continuously active` part, I don't think it will happen. Can you do some investigation after configuring the data protection?

**Comment by wutever0** [comment]
@ZekeLu unfortunately that doesn't seem to be the issue.
Published the application on my local IIS and I even configured the Application Pool `Idle Time-out` to 60 minutes as well as made sure the **Load User Profile** was set to `true` but it still asks for a login at least 30 minutes since the last login.

I will continue to debug this but any tips would be appreciated. Even tips on how to debug it.

**Comment by wutever0** [comment]
Do you think it makes a difference that even the application's homepage (basically http://myapp/) requires a login?

**Comment by ZekeLu** [comment]
> When set to True, keys are stored in the user profile directory and protected using DPAPI with a key specific to the user account. Keys are persisted to the %LOCALAPPDATA%/ASP.NET/DataProtection-Keys folder.
>
> The app pool's setProfileEnvironment attribute must also be enabled. The default value of setProfileEnvironment is true. In some scenarios (for example, Windows OS), setProfileEnvironment is set to false. If keys aren't stored in the user profile directory as expected:
>
> 1. Navigate to the %windir%/system32/inetsrv/config folder.
> 2. Open the applicationHost.config file.
> 3. Locate the <system.applicationHost><applicationPools><applicationPoolDefaults><processModel> element.
> 4. Confirm that the setProfileEnvironment attribute isn't present, which defaults the value to true, or explicitly set the attribute's value to true.

Have you check this?

Please follow these steps to determine whether it is a data protection problem:

1. login your web application
2. stop the IIS application pool
3. make sure the `dotnet.exe` process spawn by the IIS application pool is terminated (the tool [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) is recommended)
4. start the IIS application pool
5. access the protected pages of your web application again.

If login is required, it means that something doesn't survive the restart of the web application. It's very likely that it's a data protection problem.

If login is not required, we are sure that it's not a data protection problem.

In the second case, the next step is to check whether the authentication cookies is sent (that's another reason I can think of). You can use some tools to capture the HTTP traffic ([Fiddler](https://www.telerik.com/fiddler) is recommended). When re-login is required, check the request and see whether the authentication cookies are sent with the request.

If the authentication cookies are not sent, then we know there is something wrong with the cookies.

If the authentication cookies are sent, can you upload your project here so that I can debug it? Please remove all unnecessary source codes and just keep what is required to reproduce this problem.

**Comment by wutever0** [comment]
Following the data protection steps did **not** require another login.. so it does not seem like a data protection problem. The cookies are also being sent normally so that doesn't seem to be the issue either. I'm removing all the unnecessary code right now and will upload after another test - maybe something will change after the code change. Really appreciate your time with this. Thanks.

**Comment by wutever0** [comment]
Ok so I wanted to report back that I finally found what the issue was.
Seems that I have bumped into [this](https://github.com/aspnet/Identity/issues/1880) bug.

In short, it's a bug in ASP.NET Core 2.1 if you are implementing your own IUserStore but not implementing IUserSecurityStampStore, the user is logged out after 30 minutes, even though the cookies did not expire.

A quick fix is increasing the SecurityStampValidation interval to a safely long value like so:
`services.Configure<SecurityStampValidatorOptions>(o => o.ValidationInterval = TimeSpan.FromHours(10));`

I initially approximated the session to 20 - 30 minutes and used "20 minutes" as a keyword in most of the searching. After timing it more precisely today, it is in fact 30 minutes which helped direct me to more relevant search results! Thanks again @ZekeLu for your time.
