### ISSUE TITLE
Hide internal parameter properties in blazor from the IntelliSense

### ISSUE THREAD

**Issue by Stamo-Gochev** [aspnet/AspNetCore#12271]
### Describe the bug
Is there a way to hide an internal property, which has the `[Parameter]`attribute, e.g.:
```
    public class ParentComponentBase : ComponentBase
    {
        [Parameter]
        internal string Value { get; set; }
    }`
```
Using [EditorBrowsable](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=netframework-4.8) does not seem to work either:

```
    public class ParentComponentBase : ComponentBase
    {
        [Parameter]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal string Value { get; set; }
    }
```

### Expected behavior
The internal property is not visible.

### Screenshots
![image](https://user-images.githubusercontent.com/1857705/61369275-73a1f500-a898-11e9-91d4-b55ee4020e88.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Stamo-Gochev.
What do you need this for?

**Comment by Stamo-Gochev** [comment]
@mkArtakMSFT I need this in order to hide an internal setting of a component. The scenario is that a component can be used as a standalone unit, but it can be also integrated in another component, e.g. in a hierarchy. Let's say an editor component can be used in a form, but it can also be used as an editor in a grid component, which requires some internal customizations that are not (currently) relevant to be used in the standalone case.

I think that the `EditorBrowsable` attribute should handle such scenarios as it serves a more general purpose (and my concrete scenario might not be the best use case). Still, it seems like `[Parameter]` props cannot be hidden for some reason.

**Comment by Joe4evr** [comment]
For what it's worth, I've *never* seen `EditorBrowsable` respected within the same project or while there's a direct reference to the source. On top of that, `[Parameter]` properties can be *private* and they're still visible when writing Blazor, ***BUT*** they're going to change that: #8825. That might be the solution you want in the first place.

**Comment by mkArtakMSFT** [comment]
Thanks @Stamo-Gochev.
This is not something we plan to do.

**Comment by SteveSandersonMS** [comment]
@Stamo-Gochev The reason is that there are other ways this can be achieved, and we're not sure that `[EditorBrowsable]` is a desirable way to do it. For example:

 * You could choose *not* to declare any `[Parameter]` property for your internal parameter, and instead receive its value privately by overriding `SetParameters` on the receiving component (read it directly from the incoming `ParameterCollection`)
 * Or, instead of using a parameter for this parent/child communication, have the parent pass an instance of itself to the child so the child can read stuff back from the parent
 * Or, capture the child using a `ref` and then make calls to its public methods to perform the private communication between parent and child

I hope one of those is suitable for your use cases!

**Comment by Stamo-Gochev** [comment]
Thanks @SteveSandersonMS, this makes sense.
