### ISSUE TITLE
Can "Blazor (ASP.NET Core hosted) template" use windows authentication?

### ISSUE THREAD

**Issue by howardgod** [aspnet/AspNetCore#12459]
### Description
I know Blazor client-side can NOT use windows authentication but Blazor side-side can. I wonder could "Blazor (ASP.NET Core hosted) use windows authentication? Even though it's Blazor client-side project, but it still runs on dotnet core back-end.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @howardgod.
Blazor client-side currently has no support for authentication. We'll look into covering that gap post 3.0 release, as part of #12476

**Comment by AYanuseuskaya** [comment]
Good day! I decided to try creating a Blazor WebAssembly App project template. Everything was done as it is written here - https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio. At Press F5 to run the app a blank page opens with an inscription in the upper left corner Loading.
SDK - 3.0.100 - preview8-013656
Visual Studio Community 2019 Preview 16.3.0 Preview 2.0
In Output VS i see - 
Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:49566/_framework/blazor.boot.json]
SyntaxError: Unexpected end of JSON input
    at Object.<anonymous> (http://localhost:49566/_framework/blazor.webassembly.js:1:30734)
    at http://localhost:49566/_framework/blazor.webassembly.js:1:30237
    at Object.next (http://localhost:49566/_framework/blazor.webassembly.js:1:30342)
    at i (http://localhost:49566/_framework/blazor.webassembly.js:1:29088)
The program '' has exited with code -1 (0xffffffff).
The program '[3548] dotnet.exe' has exited with code -1 (0xffffffff).
I tried to run like this - For a Blazor client-side experience, execute the following commands in a command shell:
dotnet new blazorwasm -o WebApplication1
cd WebApplication1
dotnet run
The result is the same. Help, please! I can’t do anything, because I stopped at the very beginning.

**Comment by mkArtakMSFT** [comment]
Hi.

**It looks like you are posting on a closed issue!**
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
