### ISSUE TITLE
Azure SignalR service IHttpContextAccessor context always null

### ISSUE THREAD

**Issue by wpitallo** [aspnet/AspNetCore#12535]
Hi, I have just converted my SignalR  project to use AZure SignalR Service.

I am able to connect, and I can access the context from inside my hub, however, I cannot now access the context from outside of the hub. 

Previously I used  IHttpContextAccessor (see below) and this worked until I made the change to uas Azure SignalR service. Now everything works as it did before but the context being injected using the IHttpContextAccessor is always null. 

Is there another way (or documentation) on how to access the context using Azure SignalR service from outside of the hub?  

```
public class UserHelper
    {
        private readonly IHttpContextAccessor _context;

        public UserHelper(IHttpContextAccessor context)
        {
            _context = context;
        }

    public string GetUserToken()
    {
      return _context.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "access_token")?.Value;
    }
}

**Comment by anurse** [comment]
This is by design. There is no active HTTP request in your application when using Azure SignalR.

If what you're trying to do is access claims on the user, those should have been copied over to the `HubCallerContext.User` property

**Comment by wpitallo** [comment]
Ok cool, thank you!

**Comment by anurse** [comment]
I do think we need to clear up the issues with `IHttpContextAccessor` and SignalR. Even when not using the service, it's very unlikely `IHttpContextAccessor` will be reliable. Because SignalR takes multiple HTTP requests and simulates a persistent connection with them, it's generally an anti-pattern to rely on `HttpContext` at all in a `Hub`. We're also exploring non-HTTP transports for SignalR (like running on a raw TCP or QUIC connection) and those wouldn't ever have an `HttpContext`.

I'll open a docs issue to cover this in more detail so we can have a clearer story. Thanks for pointing out this area of possible confusion!

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/13508

**Comment by wpitallo** [comment]
Yes it was a little confusing, also moving over from SignalR to Azure SignalR the document mentioned the changes there where needed but did not mention anything about the IHttpContextAccessor  if you are using context outside of the hub. It would be cool if there was a uniform way to access User Context across .Net core so not having different ways to access the same thing, it would make writing modular authentication systems for example a bit easier.

**Comment by anurse** [comment]
> It would be cool if there was a uniform way to access User Context across .Net core so not having different ways to access the same thing

I'd say `IClaimsPrincipal` is the uniform representation of a User Context. How you get an `IClaimsPrincipal` is going to change from framework to framework because it's not really something you can abstract away, it depends on exactly how the framework operates.
