### ISSUE TITLE
Different CORS policies for SignalR (1.1.4) and controller actions in ASP.NET Core 2.2 MVC

### ISSUE THREAD

**Issue by iMrTidy** [aspnet/AspNetCore#12564]
I have a CORS policy that I use for a certain controller actions with the help of attributes like [EnableCors("MyCorsPolicy")]. I have another CORS policy that I would like to use solely for a SignalR hub but attributes do not work and the only way to get it working is to use the policy globally which will break the first CORS policy.

How to reproduce:
1. Create a standard ASP.NET Core 2.2 MVC project.
2. Add a SignalR hub.
3. Create CORS policy that allows access from a given domain.
4. Use [EnableCors("MyCorsPolicy")] attribute for the hub.
5. Try connecting to the hub from another domain. In debug mode in browser you will see errors regarding the CORS policy.

**Comment by BrennanConroy** [comment]
The only attribute that works on Hubs in 2.2 is `[Authorize(...)]`.

However in 3.0 we've added support for a bunch more attributes including `EnableCors`! If you can upgrade your app to 3.0 I'd recommend doing that.

If you need to stay on 2.2 you can branch the middleware pipeline so that a specific cors policy will only apply to SignalR routes.

For example:
```csharp
app.Map("/path", c =>
{
    c.UseCors("somePolicy");
    c.UseSignalR(route =>
    {
        route.MapHub<MyHub>("/hub");
    });
});
```

And clients will connect to the hub via "/path/hub".

**Comment by iMrTidy** [comment]
Thank you very much! It works like a charm.
