### ISSUE TITLE
[Question] Azure SignalR Service, options.ConnectionCount and AccessTokenLifetime

### ISSUE THREAD

**Issue by wpitallo** [aspnet/AspNetCore#12587]
Hi @anurse Just wanted to ask a question: For Azure SignalR what are the options.ConnectionCount and AccessTokenLifetime are actually doing?
```
.AddAzureSignalR(options =>
            {
              options.AccessTokenLifetime = TimeSpan.FromDays(1);
              options.ConnectionCount = 5 ;
              options.ClaimsProvider = context => context.User.Claims;
              options.ConnectionString = "xxx";
            });
```

**Comment by anurse** [comment]
That's actually more of a question for the Azure SignalR team (their repo is: https://github.com/azure/azure-signalr) since they control those options.

My understanding is that ConnectionCount refers to the number of connections the **App Server** makes to the **Azure SignalR Service**. It doesn't affect the number of clients you can have connected and you shouldn't need to modify it unless absolutely necessary.

The Access Token Lifetime probably refers to the expiry for the access token provided by the initial `/negotiate` request and again doesn't need to be modified.

There's a pretty good doc about [Azure SignalR Service internals](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-internals) which may help with some of these questions. Basically your app makes a small number of connections out to the Service and the Service funnels all the client messages through those connections to you.

**Comment by wpitallo** [comment]
@anurse, thanks very much, this does help.
