### ISSUE TITLE
Blazor Preview 7 InputSelect Default value

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#12645]
I tried to display a default empty optin in a select so I used;

````html
   <InputSelect @bind-Value="@TicketCreateDto.Type">
            <option selected disabled hidden>Type de demande</option>
            @foreach (var item in (TicketType[])Enum.GetValues(typeof(TicketType)))
            {
                <option value="@((int)item)"> @Enumerations.TicketType[(int)item]</option>
            }
        </InputSelect>
````
Wich isn't working,

I can do it without InputSelect:
````html
 <select name="Type">
            <option selected disabled hidden>Type de demande</option>
            @foreach (var item in (TicketType[])Enum.GetValues(typeof(TicketType)))
            {
                <option value="@((int)item)"> @Enumerations.TicketType[(int)item]</option>
            }
        </select>
````
But in this case I loose the benfit of model validation

Is there a way to define a default option selected with an empty value ?

Thanks.

**Comment by mkArtakMSFT** [comment]
The problem is that you're also trying to bind to a value.
The option you want to statically add there should be part of your data.

While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
