### ISSUE TITLE
IServerAddressesFeature problem

### ISSUE THREAD

**Issue by dafeifei0218** [aspnet/AspNetCore#12755]
Using the .NET Core 2.1 IServerAddressesFeature, you can get ports deployed in IIS, but .NET Core 2.2 is not. How can we solve this problem? InProcess way.

`var features = app.Properties["server.Features"] as FeatureCollection; `
`var port = new Uri(features.Get<IServerAddressesFeature>().Addresses.FirstOrDefault()).Port; `

**Comment by Tratcher** [comment]
In 2.1 you're running with IIS out-of-process mode and the ports show in IServerAddressesFeature are the internal ports used by Kestrel, not the external ports used by IIS.
In 2.2 the default is now IIS in-process mode which didn't initially populate IServerAddressesFeature. @jkotalik that was fixed in 3.0, correct?

**Comment by jkotalik** [comment]
Yeah, I believe that's this was fixed in 3.0 to populate the server address feature but didn't land in 3.0. If you need the server address feature, you can revert back to using out of process or kestrel until 3.0 is released.

**Comment by dafeifei0218** [comment]
Thank you

**Comment by anurse** [comment]
Closing as the question has been answered and we don't have any action to take here.
