### ISSUE TITLE
Problem creating new Angular template project

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#12773]
1.Install Node.js which is recommended for most users.
2.Run open up a normal Command Prompt (do not run as administrator).
3.Create a folder and create an Angular project in it:
      md test1
      cd test1
      dotnet new angular
4. There is an error in command: Couldn't find an installed template that matches the input, searching online for one that does...        

Note: Run dotnet new angular --auth individual/react --auth individual/razor, it works fine.

**Comment by phenning** [comment]
All of the SPA templates are missing the "precedence" property in their template.json.

Dotnet new now 2.1/2.2 templates into the template hive if they were installed via Visual Studio 2019, so this is resulting in dotnet new not being able to resolve which version of the template to create since there are effectively multiple templates which match that short name, so the dotnet new resorts to doing a search and displays the results.

The three Spa templates which ship in .NET 3.0 should have the precedence property added and set similarly to the other web templates.

For example: https://github.com/aspnet/AspNetCore/blob/c703093346c903fc05eb6108c0ef7b8a8205c95c/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/.template.config/template.json#L12

**Comment by phenning** [comment]
Short term workaround until a fix is in is to either explicitly specify the framework via -f, or uninstall the 2.1/2.2 template pack via dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates
