### ISSUE TITLE
[Blazor] Multiple entry-point components in MVC/RazorPages apps does not work

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#12795]
## Describe the bug
*This issue is produced from the discussion in #12630*

Currently in preview-7 you can embed Blazor components in an MVC/RazorPages app by using `endpoints.MapBlazorHub();` and `@(await Html.RenderComponentAsync<Component1>())`.

However with statefull prerendering being removed in #12630, you will have to use the explicit mapping of components, like `endpoints.MapBlazorHub<Counter>("counter");`.

 That would be ok, except that when you add multiple component registrations, the initialization code in `blazor.server.js` throws exceptions because it is trying to find **all** of the registered components in the current page/view.

## How to reproduce
Consider the following scenario:

1. Create a new mvc app
2. Create 2 blazor components: `Component1` and `Component2`
3. Go to **/Home/Index.cshtml** and add the following:
```xml
<component1>@(await Html.RenderStaticComponentAsync<Component1>())</component1>
```
4. Go to **/Home/Privacy.cshtml** and add the following:
```xml
<component2>@(await Html.RenderStaticComponentAsync<Component2>())</component1>
```
5. Add the blazor requirements in _Layout.cshtml:
```html
<head>
<!-- code ommited -->
   <base href="~/" />
<!-- code ommited -->
</head>
<body>
<!-- code ommited -->
   <script src="_framework/blazor.server.js"></script>
</body>
```
6. Add the following to `ConfigureServices` in `Startup.cs`
`services.AddServerSideBlazor();`
7. And finally, add component mapping in `Configure`
```cs
 endpoints.MapBlazorHub<Component1>("component1")
                         .AddComponent(typeof(Component2), "component2");
```

If you try to navigate to /Home/Index or /Home/Privacy you will see the following errors in the console:

**Home.cshtml**
![image](https://user-images.githubusercontent.com/12549761/62273487-56e3f080-b446-11e9-87cc-f8e2513afc48.png)

**Privacy.cshtml**
![image](https://user-images.githubusercontent.com/12549761/62273511-63684900-b446-11e9-8211-7a42b075213e.png)

If you change the hub registration to 
```cs
endpoints.MapBlazorHub();
```
AND you change the components' rendering to
```
@(await Html.RenderComponentAsync<Component1>())
@(await Html.RenderComponentAsync<Component2>())
```

Then everything works fine (in preview-7). However this is going away, according to #12630
This fix is essential to support existing MVC and Razor Pages projects.

**PS**: A similar error occurs if you try to do the same in Client-Side blazor (wasm), which I have already opened an issue for in #12061, (although it got closed)

**Comment by rynowak** [comment]
@SteveSandersonMS - we'll need to think about this.

**Comment by chrdlx** [comment]
Take into consideration (if possible) the scenario where an app needs to instantiate more than one instance of the same component in the same razor page/mvc view.

 Regards!

**Comment by SteveSandersonMS** [comment]
@rynowak Yes. It can be handled currently by using `.Map(...)` to register different hub endpoints for different source pages, but that's pretty complex and few people will manage it.

We could have a different overload of `MapBlazorHub`/`AddComponent` that takes a path.

I'm not sure there's any good way to have the HTML side control which root components should be used while also:

 * Not relying on statefulness on the server
 * Not relying on awkward tricks like dataprotecting a JSON descriptor of the component to be loaded, which would force a completely different registration API compared with what you'd do for client-side Blazor (that might not have any .NET server)

One option would be to change the startup protocol a bit so that the developer registers as many root components and selectors as they want, then when the server sends the "attach root component" messages to the client, they all go as one big message and the client sends back a list of which ones it actually accepts based on which selectors match the DOM. Then the server discards the unused ones. But that seems pretty inefficient.

Anyway, yes, let's discuss this.

**Comment by chrdlx** [comment]
Now that this issue is closed?
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#integrate-components-into-razor-pages-and-mvc-apps

This documentation is still valid? or what we should do to use Blazor components inside Razorpages?

Thanks & Regards

**Comment by javiercn** [comment]
@chrdlx Partially. We have an issue to update the docs. You can render components with parameters statically or server-side components without parameters.

Support for parameters is something we might consider bringing back in the future, although it would work differently by serializing the data into the page and then re-hydrating it.

**Comment by chrdlx** [comment]
@javiercn great!! Is there an example of how we should register several components in startup.cs? I downloaded the latest daily build preview9 yesterday and tried in the default template:

endpoints.MapBlazorHub<Counter>("c1");
endpoints.MapBlazorHub<FetchData>("c2");

this fails at runtime, and the MapBlazorHub() (no parameters) doesn't exist anymore.
thanks & Regards!

**Comment by danroth27** [comment]
@chrdlx See the relevant changes here: https://github.com/aspnet/AspNetCore/pull/13147
