### ISSUE TITLE
JsonSerializer enum serialization differs from Newtonsoft

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#12829]
### Describe the bug
The `System.Text.Json` JsonSerializer will serialize enums with their underlying type rather than the string representation, which is a breaking change from Newtonsoft's behavior.

In addition, there doesn't appear to be a JsonSerializerOption to get matching behavior.

### To Reproduce
1. Using this version of ASP.NET Core `3.0.0-preview7.19365.7`
2. Return an object containing an enum type. In my particular case, I returned GeoJSON using https://github.com/GeoJSON-Net/GeoJSON.Net, from an API controller, like so:

```csharp
        [HttpGet("[action]")]
        public IActionResult Example()
        {
            var geom = new GeoJSON.Net.Geometry.Point(new GeoJSON.Net.Geometry.Position(50, 50));

            return Ok(geom);
        }
```

### Expected behavior
This should return the following JSON:

```json
{"type":"Point","coordinates":[50.0,50.0]}
```

### Expected behavior
With System.Text.Json, it instead returns the following JSON:

```json
{"type":0,"coordinates":{"altitude":null,"latitude":50,"longitude":50},"boundingBoxes":null,"crs":null}
```

Notice in particular that "type" is set to `0`, which is invalid GeoJSON.

**Comment by pranavkm** [comment]
You could configure `JsonOptions` to use `JsonStringEnumConverter` as part of your start up to have it produce the string enum value rather than the numeric value. The library you list specifically adds converters for JSON.NET. 

If you need the serialized behavior to be identical, 

a) you'd  would have to write custom converters for System.Text.Json written in the same vein as the library.
b) continue using Json.Net

/cc @ahsonkhan \ @steveharter

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by chucker** [comment]
>The library you list specifically adds converters for JSON.NET.

Good point; I missed that. Thanks!
