### ISSUE TITLE
asp.net core 2.2 Session BUG

### ISSUE THREAD

**Issue by thinksea** [aspnet/AspNetCore#12864]
### Describe the bug
并发 Session 赋值时丢失数据。

### To Reproduce

1. Using this version of ASP.NET Core '2.2'
2. Run this code '[WebApplication7.zip](https://github.com/aspnet/AspNetCore/files/3465019/WebApplication7.zip)'
3. ERROR：abs(key1) != abs(key2)

### Expected behavior
abs(key1) == abs(key2)

### Screenshots
![Screenshots](https://user-images.githubusercontent.com/6203536/62425678-49608c00-b70e-11e9-9f0a-5dbca1a075b1.png)

**Comment by Tratcher** [comment]
I think I understand. Your page loads two images with different query parameters and each of these requests updates session.
```
    <img src="i?key=key1" />
    <img src="i?key=key2" />
```

Problem: The browser executes these requests in parallel and some of the state changes are lost.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#session-options
"Session state is non-locking. If two requests simultaneously attempt to modify the contents of a session, the last request overrides the first. Session is implemented as a coherent session, which means that all the contents are stored together. When two requests seek to modify different session values, the last request may override session changes made by the first."

This is an intentional design change compared with the ASP.NET 4.x session implementation. In the prior design requests would take a lock on the session and run serially rather than in parallel. This prevented applications from scaling so we decided not to use that model in ASP.NET Core Session. The result is that parallel session modifications are not guaranteed to be safe. If there is critical state that must be maintained in parallel then you should use a database rather than Session.

**Comment by thinksea** [comment]
I think I understand. Thank you very much.
