### ISSUE TITLE
html select value not bound correctly if options are async loaded

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#12905]
If select's options are async loaded in component's **OnInitAsync** lifecycle, the select'value will be reset to default empty unexpectedly.

Although I got answers from developer that it's designed so: https://github.com/aspnet/AspNetCore/issues/12719
I am still wondering why it is so by design. Normally it should be cared by the framework. After some inspections into source code, I found that the source code DO have some mechanism to care about this case by saving value to a custom **'_blazorSelectedValue'** property of select element if there is no matched option:
https://github.com/aspnet/AspNetCore/blob/4921dc3aa3496eb3e9fe73255213ce54a0ba29d6/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts#L248
https://github.com/aspnet/AspNetCore/blob/4921dc3aa3496eb3e9fe73255213ce54a0ba29d6/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts#L348

But it seems that all these protections are not working. And I have no source map for these javascripts to debug.
Could anyone help to answer why the value is lost even framework have preserved it into **'_blazorSelectedValue'** for backup.

@inject HttpClient Http

<select class="custom-select" value="@Value" @onchange="OnChange" @attributes="Attributes">
    @foreach (var category in _items.Where(i => i.Type == CostCenterType.Category))
    {
        <optgroup @key="category.Id" label="@($"{category.Code} - {category.Department}")">
            @foreach (var item in _items.Where(i => i.ParentId == category.Id))
            {
                <option @key="item.Id" value="@item.Id">
                    @($"{item.Code} - {item.Department} ({item.Responsible})")
                </option>
            }
        </optgroup>
    }
</select>

@code {
    [Parameter] int Value { get; set; }
    [Parameter] EventCallback<int> ValueChanged { get; set; }
    [Parameter(CaptureUnmatchedValues = true)] Dictionary<string, object> Attributes { get; set; } = new Dictionary<string, object>();

    IEnumerable<CostCenterDTO> _items = Enumerable.Empty<CostCenterDTO>();

    protected override async Task OnInitAsync()
    {
        string requestUri = "/api/costcenters";
        _items = await Http.GetJsonAsync<IEnumerable<CostCenterDTO>>(requestUri);
        }
    }

    Task OnChange(UIChangeEventArgs e)
    {
        if (int.TryParse((string)e.Value, out int result) && result > 0)
        {
            return ValueChanged.InvokeAsync(result);
        }
        else
        {
            return Task.CompletedTask;
        }
    }
}

**Comment by SteveSandersonMS** [comment]
> After some inspections into source code, I found that the source code DO have some mechanism to care about this case by saving value to a custom '_blazorSelectedValue' property of select element if there is no matched option:

This is part of the mechanism for applying the value to the `<select>` element during rendering, which itself is synchronous. It's not involved in the scenario where you do:

 1. Render a `<select>` whose `value` does not correspond to any `<option>` inside it
 2. Change the set of `<option>` nodes so that one of them now does match the `value`

... because on step 2, you're only changing the option nodes. We don't walk back up the tree to find any `<select>` parent and mutate it. That would be bad for perf (when inserting any fragment or markup block anywhere, we'd have to figure out whether it contains any `<option>` and if so walk back up the tree to look for matches), plus it would potentially lead to inconsistencies if the user had already modified the value in the meantime.

Creating any situation where a `<select>` tries to represent an unrepresentable value is problematic, so I would recommend not doing it. That's why we recommended only displaying the `<select>` once you've loaded its data.

**Comment by campersau** [comment]
I always set the `selected` attribute on the `option` element instead of the `value` on the `select` which works fine.

**Comment by kennywangjin** [comment]
> I always set the `selected` attribute on the `option` element instead of the `value` on the `select` which works fine.

I think this should be more html-standard and make more sense. :) **HTMLSelectElement** has no **value** attribute but only **value** property.

**Comment by SteveSandersonMS** [comment]
@kennywangjin How would you make `@bind` work like that?

**Comment by kennywangjin** [comment]
@SteveSandersonMS I'm using this `select` component everywhere, and I don't want to repeat `option`s' async population action. So I build a component by wrapping this `select` and `bind` can not work here because I am getting `Value` from `parameter` property which could not be bound.
`
[Parameter] int Value { get; set; }
[Parameter] EventCallback ValueChanged { get; set; }`
