### ISSUE TITLE
ResolveStaticWebAssetsInputs adds a lot to build times

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#12942]
Currently, warm-building [1] `ComponentsApp.Server` in VS takes 25-30 seconds on my machine. I recall it was in the < 5s region until quite recently, though it's unclear what changed or when. @javiercn found it's taking ~15s on his machine currently, which is also excessive. Building E2ETests has gone up into the minutes range.

Capturing build logs shows the following as the most expensive parts of warm-building `ComponentsApp.Server`:

 * `_GetProjectReferenceTargetFrameworkProperties` (9 seconds)
 * `ResolveStaticWebAssetsInputs` (11 seconds)
 * `ResolveCustomReferences` (2.5 seconds)

From speaking with @javiercn, I understand the costs of `ResolveStaticWebAssetsInputs` are to do with the depth of the dependency graph, so this would also affect large customer solutions. 

As well as strategising about how we could make this faster, it would be really helpful if we understood why (or *if* - maybe it's only much worse on my machine) this has changed so much recently.

I've put the `area-blazor` label on this so that it shows up in our triage, but it might not be specific to Blazor at all.

[1] *warm-build*: first build the project, then make a trivial whitespace-only tweak to one of the files in it, then ask VS to build that one project only.

**Comment by nguerrera** [comment]
#12933 ?

**Comment by nguerrera** [comment]
It is duplicating msbuild evaluationof project references. Normally the first to call a target on project reference incurs this cost (_Get... TargetFrameworkProperties). But this sets a new global property which forces msbuild to reevaluate.

**Comment by mkArtakMSFT** [comment]
Closing this as part of the issue pointed out by @nguerrera

**Comment by SteveSandersonMS** [comment]
@nguerrera This is only tangential, but since you're here, the second most expensive thing in our build by duration is `_GetProjectReferenceTargetFrameworkProperties`. If I disable `ResolveStaticWebAssetsInputs`, then `_GetProjectReferenceTargetFrameworkProperties` starts to take up the considerable majority of the remaining time.

Is it expected for this to be so expensive? Does it suggest to you that we've got something badly configured?

**Comment by nguerrera** [comment]
I think that is the cost of evaluating all the project references. The target doesn't do that much else. Evaluation (basically determining the state of the project before a target runs: properties and their values, items and their values, etc.) happens once per (project, global property set) tuple. It is expensive. I think of it as basically reinterpreting a big imperative program that mutates this state. When a global property is mutated, this program can have arbitrarily different results, so msbuild has to run it all over again.

If the cost were not in _GetProjectReferenceTargetFrameworkProperties, the evaluation would incur cost would just move to the next in line to run targets on project references, which would be the call to GetTargetPath or Build in ResolveProjectReferences, I believe.

So we have something expensive that has to happen once per (transitive or direct) project reference, and the global property made it happen twice.

Now while evaluation has always been slow, we should ensure it is not slower in 3.0 than before once the double evaluation is fixed. cc @dsplaisted 

Also note that multi-targeting means multi-evaluating. One evaluation for "outer" project, and one per "inner" TargetFramework. So that can also exacerbate the expensiveness of evaluation. Multi-targeted projects are not cheaper than having one project per TFM. They're actually more expensive as there is also an extra outer evaluation to contend with.

**Comment by nguerrera** [comment]
I think it would be interesting for this evaluation cost to be split out in the performance summary. It reports evaluation costs, but in general the performance summary does not provide a good way to get a set of exclusive times that add up to the total time. Things are effectively double counted. See https://github.com/microsoft/msbuild/issues/4189
