### ISSUE TITLE
Use 'appsettings.jsonc' instead of 'appsettings.json' when scaffolding a new project

### ISSUE THREAD

**Issue by Davilink** [aspnet/AspNetCore#13070]
### Describe the solution you'd like
As far has i know, JsonConfigurationProvider support comment in json file, so it would make sens to use the '.jsonc' extension instead of '.json' with file like the 'appsettings.json'.

Otherwise, my code editor (VS Code) warn me that comment is not allowed in JSON file, so i switch the file to jsonc (just to remove the warning). But other person don't know that we can use comment in the file, so with this extension, i may help people to discover that feature.

**Comment by Eilon** [comment]
My only "vote" against this is that I've never heard of that file extension before, so I'm not sure how common it is. Even Google/Bing aren't sure what to make of it when I type `jsonc file extension` because they think I had a typo and meant `json file extension`.

If it's actually a common thing, and well-supported in the most common editors (all VS flavors, other common syntax-aware editors, etc.), I think it's reasonable. Otherwise, it might be too early to change. (Obviously, anyone can change it in their own projects at any time.)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Davilink.
We have not heard enough feedback from the community about this being really important. For now we're closing this issue as we have no immediate plans to support this.
Also, this will be a breaking change to rename the reference in WebHostBuilder to reference these new names.
