### ISSUE TITLE
Microsoft.Extensions.ApiDescription.Server for Preview8 does not contains latest code

### ISSUE THREAD

**Issue by kant2002** [aspnet/AspNetCore#13159]
Looking at the `build\Microsoft.Extensions.ApiDescription.Server.targets` file in the `Microsoft.Extensions.ApiDescription.Server` I see content different from content marked here.

https://github.com/aspnet/AspNetCore/commit/4e4ccdd92a915878491def6b6c51f5881783c4e4

Without that fix, this package cannot be used, due to errors in MSBuild files.

**Comment by kant2002** [comment]
Want to clarify, I download nupkg from https://www.nuget.org/packages/Microsoft.Extensions.ApiDescription.Server unpack and check that content in addition to checking local Nuget content

**Comment by dougbu** [comment]
@kant2002 some of these files changed since we released preview 7 but the preview 7 release includes the fix you mention.

That said, the preview 8 Microsoft.Extensions.ApiDescription.Server.targets file is broken. The problem was found too late for us to address in that release, meaning fcb6575f199f isn't usable without the later 8dd1be947460 fix.

Recommend either sticking with preview 7 (0.3.0-preview7.19365.7) or adding the https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json NuGet feed and using a recent daily build of preview 9 e.g. 3.0.0-preview9.19414.8. Note the preview 9 Microsoft.Extensions.ApiDescription.* packages do no require preview 9 versions of anything else; can use preview 8 versions (or earlier) elsewhere.

**Comment by dougbu** [comment]
Let me know if I'm missing something. Otherwise (if I've answered your questions), please close this issue.

**Comment by kant2002** [comment]
Thanks. It is good that you was aware about the issue. I post just in case. Thanks for quick response
