### ISSUE TITLE
[Blazor] Improve E2E test infrastructure

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#13186]
* The complexity in our infrastructure is going a bit out of hand as we iterate on server-side blazor.
* For multiple-component entry points we needed to change the entry-point for the test as server-side components can't be rendered from static HTML no more.
* This has complicated the infrastructure a bit more to the point it starts becoming unmanageable
* We want to take some time to come up with a better strategy and clean this up, as it impacts our ability to create net E2E tests and maintain existing ones.

One proposal could be to break the test hosts into multiple projects. Right now Components.TestServer is taking all the burden of supporting ServerSide and ClientSide blazor. We could break it into two `Components.ClientTesHost`, `Components.ServerTestHost` and have a set of shared base class for startup both inherit from and that contains most of the shared logic, with the exception of the logic to map the app entry point.

* That way we get rid of using `#server` to discriminate the server app.
* We simply use one host on the server and a different one on the client.
* We don't need any special mechanism to make the apps run.

**Comment by rynowak** [comment]
👍 x a million for the idea of trying to simplify things. I think all of these ideas need some debate and discussion, but I want to make sure we invest in this, and I doubly want to make sure we pick techniques that meet all of our needs.

If possible I'd like to *reduce* the number of projects down to a really small number. It's possible to use different startup classes to fork on this kind of thing rather than different projects.

**Comment by rynowak** [comment]
Moving this to 3.1 just to get it out of our faces for 3.0. We should still treat this as a priority.
