### ISSUE TITLE
30 MB max request body size limit

### ISSUE THREAD

**Issue by dpedrelli** [aspnet/AspNetCore#13221]
Visual Studio 16.3.0 Preview 1.0
ASP.NET Core 2.0 MVC app.
I am trying to upload a file, just over 50 MB.  I tried the following options independently and in conjunction with each other.

I tried using both
`[DisableRequestSizeLimit]` and `[RequestSizeLimit(100_000_000)]`
on my controller action.  Additionally, I tried 

In Program.cs, I tried
`.UseKestrel(options => { options.Limits.MaxRequestBodySize = null; })`

In Startup.cs, I tried
`services.Configure<FormOptions>(x => x.MultipartBodyLengthLimit = 4294967296);`

I tried creating a web.config with
`<requestLimits maxAllowedContentLength="104857600" />`

When I run locally, inside of VS, hosted by IIS Express, I get:

`HTTP Error 404.13 - Not Found
The request filtering module is configured to deny a request that exceeds the request content length.`

If I deploy to Azure and run it from there, I get
`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

**Comment by halter73** [comment]
> HTTP Error 404.13 - Not Found The request filtering module is configured to deny a request that exceeds the request content length.

This does seem to be coming from IIS(Express). Can you share your entire web.config?

**Comment by dpedrelli** [comment]
I do not have a static web.config.  This is the web.config that VS dynamically creates, when I publish the app to Azure.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  
  <system.web>
    
    <httpRuntime maxRequestLength="1048576" executionTimeout="3600" />
  </system.web>
  <system.webServer>
    <security>
      <requestFiltering>
        
        
        <requestLimits maxAllowedContentLength="1073741824" />
      </requestFiltering>
    </security>
    
    
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\SM.Mvc.dll" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" requestTimeout="23:00:00" forwardWindowsAuthToken="false" startupTimeLimit="3600">
      <environmentVariables />
    </aspNetCore>
  </system.webServer>
</configuration>
`

**Comment by dpedrelli** [comment]
Is there an update here?

**Comment by halter73** [comment]
It looks like you're hitting an IIS limit rather than a Kestrel limit. What errors are you seeing specifically?

Do you always see `HTTP Error 404.13` when hosting in IIS Express? Are you still seeing the `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.` on Azure? If so, can you check [Kudu to see if your web.config was published correctly](https://danielhillebrand.com/2017/08/azure-app-service-view-and-edit-the-deployed-web-config-with-kudu/)? While you're in Kudu, you can check the LogFiles directory to see if that tells you anything.

**Comment by dpedrelli** [comment]
@halter73 

I'm uploading an Excel spreadsheet that is 50.2 MB.

When hosting the MVC app on Azure, I simply get:
`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`
Without any error numbers.

When I run the app inside of VS, with IIS Express, and pointing the data connection to an Azure database, I get:
`
HTTP Error 404.13 - Not Found
The request filtering module is configured to deny a request that exceeds the request content length.
Most likely causes:

    Request filtering is configured on the Web server to deny the request because the content length exceeds the configured value.
`

The web.config that I posted, I downloaded from Kudu Services.  I changed the extension to .txt, because github would not allow me to upload a .config file.  Additionally, I tried the MVC config options that I listed in the original post.

Thanks.

**Comment by halter73** [comment]
Have you taken a look at the eventlog.xml and/or stdout_{datetime}.log files in the LogFiles directory? It doesn't look like the request made it to the dotnet process, so I'd look at eventlog.xml first to see if it has any info as to why the request was rejected.

Also, the `<system.web>` section of your web.config shouldn't have any effect since that's used by "classic" System.Web ASP.NET and not ASP.NET Core. That being said, the `<httpRuntime maxRequestLength="1048576" executionTimeout="3600" />` is limiting the request to only 1MB, so maybe that is playing a role.

**Comment by dpedrelli** [comment]
@halter73 
I must have misread the number in web.config.  I looked at it quickly and thought it was much larger.  I had a web.config with a larger number.  Apparently, I put it in wwwroot and it needs to be in the project root.  It works, now.

Thanks.
