### ISSUE TITLE
Getting HTTP stream is blocking rendering

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#13329]
I'm downloading a stream from a WebAPI and I'm trying to run code while the stream is being read.

The code below works fine on Blazor server-side or an console app. But on blazor-client side the stream will first download fully before executing any code.... even just a Console.WriteLine() will just start writing to Console after the stream is done. I'm using the latest .Net Core 3.0 Preview 8...

```
public async IAsyncEnumerable<SomeClass> GetDataAsync()
{
    var serializer = new JsonSerializer();
    using (var stream = await Http.GetStreamAsync("https://localhost:44334/api/values/i"))
    {
        using (var sr = new StreamReader(stream))
        using (var jr = new JsonTextReader(sr))
        {
            while (await jr.ReadAsync()) //<-- Stream is fully download to browser before taking any actions.
            {
                if (jr.TokenType != JsonToken.StartArray && jr.TokenType != JsonToken.EndArray)
                {
                    Console.WriteLine(jsonReader.LinePosition);
                    yield return serializer.Deserialize<SomeClass>(jr);
                }
            };
        }
    }
}
```

I tested this with WireShark to confirm that this is happening.

Is this by design?

**Comment by campersau** [comment]
I guess it is currently by design: https://github.com/aspnet/AspNetCore/blob/e0f95cfa6feec402ea34a605965f356720006513/src/Components/Web.JS/src/Services/Http.ts#L27

But if they switch to the mono implementation (https://github.com/aspnet/AspNetCore/issues/10489), streaming will be support if the browser supports it:
https://github.com/mono/mono/blob/254d6d37580a70fbb4fa072b0b2b16d2984b3bb5/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs#L171-L173

**Comment by enetstudio** [comment]
Lots of thanks and appreciations...@campersau
