### ISSUE TITLE
3.0.0-rc1-19422-14 ActionFilter

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#13566]
_From @phillipbritain on Tuesday, August 27, 2019 10:57:20 PM_

I can't get a custom ActionFilter to fire off it's OnActionExecuting method.

Here is my custom ActionFilter:

```
public class ValidateModelActionFilter : IActionFilter
{
	public void OnActionExecuting(ActionExecutingContext context)
	{
		if (!context.ModelState.IsValid)
		{
			context.Result = new BadRequestObjectResult(context.ModelState);
		}
	}

	public void OnActionExecuted(ActionExecutedContext context)
	{
		// Do something after the action executes.
	}
}
```

And here is where I call it in Startup.cs ConfigureServices:

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddControllers(x => x.Filters.Add(typeof(ValidateModelActionFilter)));
    ...
}
```

_Copied from original issue: dotnet/core#3266_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @scalablecory.
@ryanbrandenburg can you please look into this? Thanks.

**Comment by ryanbrandenburg** [comment]
@phillipbritain I had a replication of this behavior, the problem turned out to be that I was using it in a project of RazorPages. If you create an old-school MVC Controller and hit that endpoint you should run into the filter. For more on this [see here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2#action-filters).

I think that should get you sorted, but if not let us know and please include a little sample applicaiton. Thanks!

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
