### ISSUE TITLE
Shared folder inside blazor project should be placed inside the pages folder

### ISSUE THREAD

**Issue by prince272** [aspnet/AspNetCore#13618]
The shared folder inside the blazor project should be placed in the pages folder.

Eg:
Pages > Shared
Pages > Admin > Products > Index.razor
Pages > Admin > Products > New.razor
Pages > Home > Index.razor

Since blazor is a mixture of c# and html there is no need for controllers to handle requests. You only need to define a service.
Folder structure for blazor will be:

Services > ProductSerivce.cs
Pages > ...

Let me know if you'll like me to create a sample of what I'm talking about. 

Thank you!!!

**Comment by vertonghenb** [comment]
@prince272 If your project gets bigger you'll notice that calling pages like `Index` or `New` is pretty annoying. Since a lot of features (like the products/customers/etc.) have these pages. I do recommend using the folders but still, prefix the page with the feature's name. Unless you want to import namespaces everywhere (which doesn't have decent support in VS at the moment).
e.g.
Product.Index.cs
Product.Create.cs
...

**Comment by prince272** [comment]
Yeah. You're right. A folder structure like that will do.

**Comment by prince272** [comment]
But my main question is, why did you move the shared folder from the pages folder. In razor application the shared folder was inside the pages folder.

**Comment by vertonghenb** [comment]
Because the Layout page//Navmenu is not really a page?

**Comment by prince272** [comment]
Oh okay.

**Comment by prince272** [comment]
We can now close the comment. 

When I first started web programming I asked myself that "where is C# events. Now thanks to blazor events with c# is back in the game".

**Comment by prince272** [comment]
Just calling @onClick welcomed c# events. Before we had to use JavaScript events.
