### ISSUE TITLE
Azure SignalR Service - An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### ISSUE THREAD

**Issue by wpitallo** [aspnet/AspNetCore#13612]
Please can someone help me with what this error means:

Server.Hubs> warn: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[11]
Server.Hubs>       Failed to start connection. Error starting transport 'WebSockets'.
Server.Hubs> fail: Microsoft.Azure.SignalR.ServiceConnection[2]
Server.Hubs>       Failed to connect to '(Primary)https://xxx.service.signalr.net', will retry after the back off period. Error detail: Unable to connect to the remote server. An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. Id:

**Comment by BrennanConroy** [comment]
https://blogs.msdn.microsoft.com/sql_protocols/2009/03/09/understanding-the-error-an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-sufficient-buffer-space-or-because-a-queue-was-full/

Looks like that error generally means there is something using a lot of the networking stack on your machine and so your process is unable to make a new connection.

If that error is being returned by the Service connection then you should move this issue to https://github.com/Azure/azure-signalr so they can figure out if something is wrong with the Service machine.

**Comment by wpitallo** [comment]
Thank you
