### ISSUE TITLE
[Blazor] Order of OnAfterRenderAsync method calls

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#13781]
The _BuildRenderTree_ method is called from the outer most element and can create sub components, which causes the _BuildRenderTree_ method of the sub components to be called. So far so good, this seems reasonable to me. The problem is _OnAfterRenderAsync_ follows the same order, and I think the _OnAfterRenderAsync_ of a component should be called after it was called in all the sub-components.

I'm using this event to call some JavaScript interop after one component is rendered (The only method where is possible as far as I know). But It results that the same method was called before in the parent. Causing the parent to have a non-initialized child in the _OnAfterRenderAsync_.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think the current design is fine.

**Comment by SteveSandersonMS** [comment]
The reason for the current design is that components can add and remove children at any time. There's never any specific time where a component can know that all its descendants have been rendered, as more could still appear. That's why we don't promise that `OnAfterRenderAsync` waits for descendants - it wouldn't be meaningful.

If this is causing an issue for a specific thing you're trying to implement, could you provide more details about the scenario? We might be able to suggest a solution.

**Comment by arivoir** [comment]
I expected the _OnAfterRenderAsync_ to be raised every time a _BuildRenderTree_ method is called, and expected the children to be those just created in the _BuildRenderTree_ method.  Am I wrong? I understand the children could change in subsequent calls to _BuildRenderTree_, but that shouldn’t be a problem since a new _OnAfterRenderAsync_ would be called.

My scenario is a _ListView_ control whose items are virtualized. To create this control I’m using a _ScrollViewer_ control. To really know the dimensions of the control(Mandatory to implement virtualization) it is necessary to perform some JavaScript calls, which get both the width and height as well as scrollX and scrollY of underlying div. The only place where this Javascript  call can be located is in _OnAfterRenderAsync_ method. The problem is when the ListView is initialized the first time, the ScrollViewer was not “initialized” yet. What do you suggest?

**Comment by SteveSandersonMS** [comment]
> I expected the OnAfterRenderAsync to be raised every time a BuildRenderTree method is called, and expected the children to be those just created in the BuildRenderTree method. Am I wrong?

`OnAfterRenderAsync` is raised after each time the DOM is updated, which happens at some point after a `BuildRenderTree` method is called. The actual ordering of `OnAfterRenderAsync` calls within a single batch isn't defined.

> I understand the children could change in subsequent calls to BuildRenderTree, but that shouldn’t be a problem since a new OnAfterRenderAsync would be called.

Yes, there will be another call to `OnAfterRenderAsync` after each render batch that involves your component.

> My scenario is a ListView control whose items are virtualized. To create this control I’m using a ScrollViewer control. To really know the dimensions of the control(Mandatory to implement virtualization) it is necessary to perform some JavaScript calls

Yes, that totally makes sense. You do want your JS interop calls to be inside `OnAfterRenderAsync` and not earlier, because they need to read state from the DOM, and `OnAfterRenderAsync` is what notifies you that the DOM has been updated. So this sounds correct and fine.

I don't know which way round your ListView and ScrollViewer are nested (i.e., which one is inside the other) but in general for virtualization I'd expect a sequence like this:

 * Parent gets rendered, initially empty because it doesn't know how many children to render yet
    * DOM gets updated with empty element for parent
 * Parent's `OnAfterRenderAsync` gets called with the `firstRender` parameter set to `true`
   * Parent uses JS interop to query the dimensions of its element and scroll position
   * Parent re-renders itself, but this time with the desired set of children
 * When `onscroll` later fires on the parent, if the desired set of children has now changed, then the parent re-renders the parent with a different set of children
