### ISSUE TITLE
Support debugging Blazor WASM projects

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#13902]

**Comment by jbomhold3** [comment]
Even if we don't get a full debugging session in VS soon. We need to have a way to enable debugging when the app starts. Right now you have to press the key so it's imposable to debug startup objects. Ig an on init function in the main layout or the index page.

**Comment by ryanbrandenburg** [comment]
This was fixed in https://github.com/aspnet/AspNetCore/pull/17162. There is still some work to do WRT improving the experience of "F5 debugging" so that it "just works", but that's something that will have to happen on the VS side, with possible reactions from us. I believe @danroth27 and possibly @SteveSandersonMS are on deck for that coordination, wherever it may happen.
