### ISSUE TITLE
ASP.NET Core 3.0 Preview 9 integration tests with EF Core are not working

### ISSUE THREAD

**Issue by stevo-knievo** [aspnet/AspNetCore#13918]
### Describe the bug
The integration test is using the application DB provider (SQLite) instead of the InMemory DB provider set up in the customized WebApplicationFactory class. 
I followed Microsoft's documentation "[Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0)" which shows the approach of how to use a [customize the WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#customize-webapplicationfactory).

### To Reproduce
To show the behaviour I used the IntegrationTestsSample with all the updates on the 3.0 docs PR at [#14265](https://github.com/aspnet/AspNetCore.Docs/pull/14265) and create a separate repo. Link to the repo: https://github.com/stevo-knievo/IntegrationTestsSample

Steps to reproduce the behaviour:
1. Pull my [repo](https://github.com/stevo-knievo/IntegrationTestsSample) and run the `Count_Messages_On_Index_Page` test. The test is expecting 5 messages. The test fails because of the `Utilities.InitializeDbForTests(db);` method is seeding the application database (SQLite) instead of integration test database (InMemory). Meaning they are actually 8 message entries.

### Expected behaviour
The integration test should be using the DB provider set up in the customized WebApplicationFactory class. As documented here: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#customize-webapplicationfactory).

### Additional context
```
dotnet --info
3.0.100-preview9-014004
```

cc: @guardrex

**Comment by stevo-knievo** [comment]
@mkArtakMSFT Does adding the milestone mean it is a bug? What is the timeline for 3.1.0-preview? This issue is a real show stopper for me for moving my app completely over to Core 3.0.

**Comment by javiercn** [comment]
@stevo-knievo It does not. Its only part of our process for dealing with issues. I suspect the docs might be out of date and you need to do something like https://github.com/aspnet/AspNetCore/blob/master/src/Identity/test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs#L24-L55 to actually override the database.

This is not a WAF specific problem but a problem with how services are registered in your container. Ultimately the test code is responsible for registering the service with the right overload and at the right time to achieve the desired result. There are two cases for this:
* **The app/framework code unconditionally registers the service:** You need to register the service _AFTER_ the call to ConfigureServices in app code.
* **The app/framework code conditionally registers the service using TryXXX:** You can register the service _BEFORE_ so that the TryXXX call doesn't have any effect.

It is also important to note a couple of differences between generic host and the old WebHost.
* The old WebHost had two DI containers, one for the host and one for the app. The app container would start from the set of host services and then expanded with app service registrations. When the code called UseStartup, the host would record the class and apply the ConfigureServices method at a given point in time. For that reason, you could either register a service _BEFORE_ Startup.ConfigureServices was called to override it if it was using TryXXX and we had to have an extra special hook if the original code was using AddXXX.
* Generic host is new in 3.0 and you can see it in action if you look at the code in the templates under Program.cs. One of the biggest changes for generic host is that there is a single container for the host and the app, and that `Startup.ConfigureServices` runs immediately instead of getting deferred as in the old WebHost. What that means in practice is that when using generic host, you don't get to use the _BEFORE_ option and you always need to call builder.ConfigureServices and replace the service, as the callback will be invoked _AFTER_ the call to Startup.ConfigureServices.

With generic webhost you can simply call builder.ConfigureServices but you are forced to override the service, so in some cases its a bit more work, as you need to replace it from within the container.

**Comment by javiercn** [comment]
Closing this issue as there's no more action to be taken here. There's a separate issue to track the docs update.

**Comment by khteh** [comment]
> @stevo-knievo It does not. Its only part of our process for dealing with issues. I suspect the docs might be out of date and you need to do something like https://github.com/aspnet/AspNetCore/blob/master/src/Identity/test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs#L24-L55 to actually override the database.
> 
> This is not a WAF specific problem but a problem with how services are registered in your container. Ultimately the test code is responsible for registering the service with the right overload and at the right time to achieve the desired result. There are two cases for this:
> 
> * **The app/framework code unconditionally registers the service:** You need to register the service _AFTER_ the call to ConfigureServices in app code.
> * **The app/framework code conditionally registers the service using TryXXX:** You can register the service _BEFORE_ so that the TryXXX call doesn't have any effect.
> 
> It is also important to note a couple of differences between generic host and the old WebHost.
> 
> * The old WebHost had two DI containers, one for the host and one for the app. The app container would start from the set of host services and then expanded with app service registrations. When the code called UseStartup, the host would record the class and apply the ConfigureServices method at a given point in time. For that reason, you could either register a service _BEFORE_ Startup.ConfigureServices was called to override it if it was using TryXXX and we had to have an extra special hook if the original code was using AddXXX.
> * Generic host is new in 3.0 and you can see it in action if you look at the code in the templates under Program.cs. One of the biggest changes for generic host is that there is a single container for the host and the app, and that `Startup.ConfigureServices` runs immediately instead of getting deferred as in the old WebHost. What that means in practice is that when using generic host, you don't get to use the _BEFORE_ option and you always need to call builder.ConfigureServices and replace the service, as the callback will be invoked _AFTER_ the call to Startup.ConfigureServices.
> 
> With generic webhost you can simply call builder.ConfigureServices but you are forced to override the service, so in some cases its a bit more work, as you need to replace it from within the container.

It's not clear to me the flow of the service registrations. If the `Startup.cs` `ConfigureServices` registers the DbContext and then some custom web application factory which derives from `WebApplicationFactory<Startup>` and registers the in-memory DbContext, does the later one "replace" / "overwrite" the real, MySQL for instance, DbContext which was registered in Startup.cs?
