### ISSUE TITLE
Investigate TFMs of Microsoft.AspNetCore.Cryptography.KeyDerivation

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#14023]
Tracking the investigation that started in https://github.com/aspnet/AspNetCore/pull/13571#discussion_r324443496. The package currently targets netcoreapp2.0 and netstandard2.0. We should double check if netcoreapp2.0 TFM is intentional.

**Comment by blowdart** [comment]
That seems quite wrong. It was supposed to be standard2.0

**Comment by HaoK** [comment]
@blowdart I was confused by this as well, what targetting two TFMs actually is saying is that we are cross compiling to take advantage of better APIs (specifically derive bytes) in netcoreapp, but when targetting netstandard, it has to fall back to the old APIs.  I believe this issue is just tracking whether the netcoreapp version should be 3.1 as opposed to 2.0.

See https://github.com/aspnet/AspNetCore/pull/11008 for where we decided we want to cross compile to keep improvements

**Comment by HaoK** [comment]
@JunTaoLuo I'm assuming in all other places where we cross compile we are targeting 3.1?  If so then it seems safe to say that we should do the same here and I can submit a PR with that change

**Comment by JunTaoLuo** [comment]
Correct. Someone can correct me if I'm wrong but I think that's mostly because we expect that users will be using 3.1 packages if they are on netcoreapp3.1 so there's no drawback for targeting the new TFM. I don't know if there's value in supporting apps that target netcoreapp2.0 but uses 3.1 packages.

**Comment by HaoK** [comment]
Does this matter for 3.1 @JunTaoLuo or can we just fix this in master?

**Comment by JunTaoLuo** [comment]
I think this would be the product owner's call. I don't see why we couldn't push this out.

**Comment by HaoK** [comment]
@blowdart ok if we do this in master?

**Comment by blowdart** [comment]
I'm ok with it, but check with @anurse

**Comment by anurse** [comment]
If @blowdart is happy, I'm happy 😉.
