### ISSUE TITLE
In .csproj Link to wwwroot folder can not be open by https.

### ISSUE THREAD

**Issue by Honjoy** [aspnet/AspNetCore#14087]
```xml
  <ItemGroup>
    <Content Include="..\Base\wwwroot\css\**\*.css" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\css\**\*.map" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\css\**\fonts\**" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\js\**\*.js" LinkBase="wwwroot\js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\js\**\*.map" LinkBase="wwwroot\js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

I have file but https://localhost:5001/css/bootstrap/bootstrap.min.css report status 404

**Comment by pranavkm** [comment]
/cc @Tratcher @javiercn 

Would static web assets help in this case?

**Comment by javiercn** [comment]
@pranavkm No, and this is unsupported by design. When doing `dotnet run` no files get copied around. Using LinkBase won't work here. StaticWebAssets would work if they created an RCL for the assets, but that's kind of a hack. Static web assets doesn't support linked content for the same reason.

@Honjoy  what are you trying to achieve?

Closing this as by design. We can reopen if we determine we are missing a feature.

**Comment by Honjoy** [comment]
I reorganize library include .js and .css and have some files write by myself. 
I hope in my case always link they files just like a template.
