### ISSUE TITLE
IDataProtector with no IKeyManager

### ISSUE THREAD

**Issue by bencyoung** [aspnet/AspNetCore#14100]
Is it possible to make use of the data protection APIs without an IKeyManager implementation?

For instance we'd like to use an external encryption service (e.g. HP Voltage) that handles key management/rotation internally. For the application we'd just like to register an IDataProtector interface but we are required to register an IXmlRepository etc else a filesystem one is registered by default

```csharp
                        services.Configure<KeyManagementOptions>(o =>
                        {
                            o.XmlRepository = options.XmlRepository;
                        });
```

Is there any way to use an external encryption service in ASP.NET Core?

**Comment by bencyoung** [comment]
Also e.g. Hashicorp Vault

**Comment by blowdart** [comment]
No. If you look at how the Azure Key Vault protector does it it provides a protector which wraps the key ring, because we don't want the actual master encryption key to come out of Key Vault and be held in memory. Also we create new keys for data protection when they're needed, that's all within KeyManager. If that's what you want an external service to do then you'll have to implement your own IKeyManager.
