### ISSUE TITLE
A clearing of the air for AspNet Core 3.0!

### ISSUE THREAD

**Issue by ErnestHodge** [aspnet/AspNetCore#14111]
We at my job are having a discussion about AspNet Core 3.0.  From my understanding, AspNet Core 2.2 with be supported for about 3 years and core 3.0 will re-branded to 5.0.  

.NetStandard 2.0 will be supported in 3.0 but is not apart of the development for 3.0.  

So I suggested that while 3.0 is coming out of preview in a week we should focus on developing in that rather than trying to fit and fix 2.2.x+ apps up the development stream. 

We are a crossroads as nobody understands what will be supported on .netStandard and what 3.0 will support.  There are times when a developer will create a library that needs to have .net Framework and AspNet Core supported.  

https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.0

States that "ASP.NET Core 3.0 and later will only run on .NET Core"

So can I get pointed to a clear answer on this subject?

Also what restrictions will I have if I start to develop on .Net Core 3.0 and another is still on .Net Core 2.2? Should tell the developers to use .NetStandard 2.0 and above?

**Comment by Eilon** [comment]
@leecow @DamianEdwards

**Comment by DamianEdwards** [comment]
.NET Core & ASP.NET Core 2.2 will not be supported for 3 years. The 2.2 release is a "Current" release and in accordance with the [.NET Core Support Policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) will be end-of-life (EOL) and thus unsupported 3 months after the next Current release is available. In this case, that's 3.0 so the EOL of 2.2 will be December 23rd, 2019.

In contrast. the 2.1 release is an "LTS" or "Long Term Servicing" release and as such is supported for 3 years from the time of its LTS designation. For 2.1, that was 2.1.3 in August 23rd, 2018. So 2.1 will go EOL and thus out of support no sooner than August 23rd, 2021.

In addition, ASP.NET Core 2.1 when running on a supported OS and version of .NET Framework (rather than .NET Core) will be supported indefinitely.

ASP.NET Core 3.0 is indeed only supported when running on .NET Core 3.0. They are, in effect, now tied together. This means that large parts of the ASP.NET Core surface area is now no longer available in packages or when targeting .NET Standard (any version) but rather is only available when targeting .NET Core 3.0

Some parts of ASP.NET Core 3.0 do still target .NET Standard and are available in packages (see all of the `Microsoft.Extensions.*` APIs, and parts of Blazor and SignalR that need to run on client platforms). In these cases, those assemblies run on platforms that support .NET Standard 2.0. This doesn't change the general statement though: ASP.NET Core 3.0 apps now must run on .NET Core 3.0.

Entity Framework Core 3.0 targets .NET Standard 2.1, which will never be implemented/supported by .NET Framework, and as such, EF Core 3.0 will only work on .NET Core 3.0, Xamarin, and a future update to UWP.

If you need to share code/assemblies between ASP.NET Core 3.0 and 2.1/2.2 apps, that code should target .NET Standard 2.0, except for some edge cases where you need that shared code to use APIs in ASP.NET Core itself (e.g. building a Tag Helper) in which case you'll need to have that package multi-target to both .NET Standard 2.0 and .NET Core 3.0, due to the points above.

I hope that helps.

With regards to .NET Standard, .NET Core 3.0

**Comment by ErnestHodge** [comment]
This does clear things up. Thanks You
