### ISSUE TITLE
ASP.NET Core 3.0 3.0.100-preview9-014004-1 controller 405 Method Not Allowed

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#14140]
While with ASP.NET Core 2.2 it works perfectly, with ASP.NET Core 3.0 Preview 9, with the same Controller, I get `405 Method Not Allowed`:

        [HttpPost]
        public async Task<ActionResult<LocalizedString>> Add(ViewModel viewModel)

Why I have to add `[HttpPost("{id}")]` now to get it works?

**Comment by pranavkm** [comment]
Can you include the server logs for the 405? Also a minimal repro would help.

**Comment by vintzl** [comment]
Try with the edit page:

- https://github.com/vintzl/405-Method-Not-Allowed-AND-Custom-PaginatedList

**Comment by rynowak** [comment]
@vintzl - I spent a few minutes playing with this, and the problem is probably that you don't have CORS set up.

![image](https://user-images.githubusercontent.com/1430011/65398499-690a4d00-dd6c-11e9-83f8-ac58fc3b356c.png)

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0#cross-origin-resource-sharing-cors

-- 

I don't see anything here that indicates we have a bug

**Comment by vintzl** [comment]
What about this:

https://github.com/vintzl/405-Method-Not-Allowed-AND-Custom-PaginatedList/blob/master/api-415/Startup.cs#L28

and this:

https://github.com/vintzl/405-Method-Not-Allowed-AND-Custom-PaginatedList/blob/master/api-415/Startup.cs#L40

**Comment by rynowak** [comment]
@vintzl - I can run your app and I get a 200 - what do I need to do to reproduce the problem? Do you have server-side logs from when you're seeing an 405?

**Comment by vintzl** [comment]
Strangely, now it works…
