### ISSUE TITLE
Why not an official template to create a SPA with VueJs ? 

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [aspnet/AspNetCore#14181]
Hi, 

are you planning of providing an official Visual Studio template to create a SPA with ASP.NET core and VueJs similar to the ones existing for ReactJs and Angular ? 

VueJS is having quite a wide adoption and such a template could helpful to the .NET developers adopting VueJS as their SPA framework of choice.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @EnricoMassoneDeltatre.
We do not want to limit the community to a certain set of project templates only. Our vision is that we will be able to provide API level plumbing so that community can build up on top of it integration with vast array of SPA frameworks. That said, we're going to invest in the above mentioned `plumbing` as part of https://github.com/aspnet/AspNetCore/issues/5182 and work / help the community build those templates.
//cc @danroth27

**Comment by tvkit** [comment]
## Developer Survey Results - 2019

[Most Loved, Dreaded, and Wanted Web Frameworks](https://insights.stackoverflow.com/survey/2019#technology-_-most-loved-dreaded-and-wanted-web-frameworks)

![image](https://user-images.githubusercontent.com/28468364/69311867-69538700-0bfb-11ea-8f72-542c1c491e77.png)
