### ISSUE TITLE
[Blazor] What is the right way to display validation errors returned from server after submit?

### ISSUE THREAD

**Issue by xperiandri** [aspnet/AspNetCore#14195]
ValidationSummary is used to display client-side validation.
But where and how to display server-side validation errors in Blazor?

**Comment by javiercn** [comment]
@xperiandri Thanks for contacting us.

You can use `OnSubmit` to perform any validation you require. If you choose to do so you are responsible for handling the validation for the form.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS do you have anything to add here?

**Comment by xperiandri** [comment]
Do you mean that I don't use `OnValidSubmit` and `OnInvalidSubmit` and that way I do validation myself
But if I use `OnValidSubmit` and `OnInvalidSubmit`, then I can call server handling `OnValidSubmit` and update UI by handling `OnInvalidSubmit`, right?

**Comment by javiercn** [comment]
@xperiandri Sorry, I think I'm lost. Can you provide better details about what you are trying to accompllish? Our understanding is that you have an app where you are trying to do an API call or something similar to perform validation in addition to the validation that is performed through data annotations.

Is that the case?

The logic for how the EditForm handles submit can be found here https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web/src/Forms/EditForm.cs#L120-L141

So you need to add a handler to OnSubmit and do something like
```csharp
var isValid = editContext.Validate() && await AdditionalServerValidations(editContext);
if (isValid)
{
    // Logic when valid
}

if (!isValid)
{
    // Logic when invalid
}
```

The EditForm won't call OnValidSubmit or OnInvalidSubmit since you've defined OnSubmit, but it's trivial for you to inline those calls whithin your own OnSubmit delegate.

Does that help clarify things?

Closing the issue as there's no more action to do here, if this is not what you intended to do, feel free to reopen the issue.

**Comment by xperiandri** [comment]
Thanks for that scenario explanation and code. It is very good to know.
My scenario is much simpler and includes 2 steps:
1. Front-end validation and displaying
2. When front-end validation passes and request riches server and I get a response - displaying server errors in Validation Summary:
a) Front-end validation can cover not all cases (thay can be unknown)
b) Server rules can change
c) Non validation errors can occur like network error, etc.

**Comment by aaronhudon-ts** [comment]
Similar issue: https://github.com/aspnet/AspNetCore.Docs/issues/12476

Can we get some clarification on how to implement validation similarly to the IValidatableObject ?  Field-based validation as attributes is way too simple and does not cover enough scenarios.
