### ISSUE TITLE
Scenarios are not running: MvcPlaintext

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14202]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| MvcPlaintext | Windows, Physical, http, KestrelSockets | 9/19/19 7:47:54 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by mkArtakMSFT** [comment]
@sebastienros I think this is related to the other perf related issue which got reported today. Are you looking to all these?

**Comment by sebastienros** [comment]
If I haven't, a dev from MVC should check what is going on. Most of the time it's just about opening the charts (https://aka.ms/aspnet/benchmarks) and checking that this scenario is back up running, then close the issue. Otherwise it's easier a breaking change to react to, or an environment issue (server, sdk/cli) for me to fix.
