### ISSUE TITLE
Circular Reference / Infinite Component Loop

### ISSUE THREAD

**Issue by KSchlobohm** [aspnet/AspNetCore#14205]
### Describe the bug
Tried out the sample template and noticed that I can reference the Index component from the Counter component and the Counter component from the Index component. This causes a circular reference which begins an infinite loop.

### To Reproduce
1. Using the current version of the Blazor Server app template
2. Add the <Index /> component to the Counter.razor file
3. Add the <Counter /> component to the Index.razor file
4. Run the app and see that the page does not load

### Expected behavior
Would be great if this could be detected at build time and stopped as a build error.

**Comment by javiercn** [comment]
Thanks for contacting us @KSchlobohm.

The behavior you see is by design. Blazor doesn't prevent circular references between components in the same way a compiler doesn't prevent you from performing circular method calls. It's up to the developer to prevent those types of situations in the same way it is for regular C# applications.
