### ISSUE TITLE
[Blazor] Check component is running in a mobile device?

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#14239]
I'm writing a popup component and need to figure out if running in a mobile device, for both client and server versions. Alternatively, the size of the window could work.
Any idea?

**Comment by javiercn** [comment]
I would use JS interop to achieve this by looking at the values for `window.visualViewport.width` or `window.visualViewport.height` or looking at the user agent with `window.navigator.userAgent`

I don't think there's anything in that explicitly marks the browser as a "mobile device" and is a discouraged practice.

The best way to do this is with media queries and responsive CSS. If you can't do that, I would rely on the viewPort and use the userAgent as the last resort.

**Comment by arivoir** [comment]
Is it possible to call Js interop before the first render?

**Comment by javiercn** [comment]
@arivoir No. The only place where we guarantee js interop works is inside OnAfterRender. For every other lifecycle method you need to check if the server is connected.

I imagine you are trying to render different UIs depending on whether the app is being viewed on a phone or a PC?

My recommendation is to try and use the same markup for both and different styles and if you truly can't, then maybe use different components and use a parent component that avoids rendering any content until the app is connected. (You can know that is the case by using OnAfterRender on the parent component and triggering a render explicitly from there on the first render by calling StateHasChanged)

You will be missing out in prerendering those pieces of UI, but otherwise it should work.
