### ISSUE TITLE
Dynamic values doesn't update and the initial value has replaced always at runtime

### ISSUE THREAD

**Issue by Naganathan** [aspnet/AspNetCore#14248]
### Describe the bug

I am using VS2019 preview 4.0 and dotnetcore rc1 version 3.0. 

But, I have a bug with the following code. 

```csharp
<Canvas @ref="@canvas" Width="1500" Height="700">
   <Node @ref="node" X="100" Y="100" Width="100" Height="100"></Node>
</Canvas>

@code{
    Node node; 
    Canvas canvas;
    Node node;
    public void UpdateWidth()
    {
        node.Width = 200;
        StateHasChanged();
    }
}
```

In the previous code, I have tried to change the “width” value of the node object, but immediately it reset to initialized value of “100” always. 

It is working fine if I use the code as follows. 

```csharp
<Canvas @ref="@canvas" Width="1500" Height="700">
   <Node @ref="node" X="100" Y="100" Width="@width" Height="100"></Node>
</Canvas>

@code{
    float width = 100; 
    Canvas canvas;
    Node node;
    public void UpdateWidth()
    {
       width = 200;
       StateHasChanged();
    }
}
```

### Expected behavior

Our requirement is providing multiple child elements for root parent like above and we cannot provide property bind options for each property like x, y, width, height, and more for each child or nested child elements like node object.

So, is there any other solution for this issue? Or 

is this a behavior of the Blazor control?

### Additional context

Sample Project : [https://github.com/Naganathan/SampleObjectDragging](url)

**Comment by javiercn** [comment]
Hi,

That's not the idiomatic way of achieving what you want in Blazor. You see the value always go back to ` Width="100"` because that's what it's being defined in the view.

When  UpdateWidth is invoked you set the value for Width of the current child component to 200, but then when StateHasChanged is run the parent page re-renders the component and sets the width to 100 again as defined in the view.

To accomplish what you are trying to achieve you should do something like
```
<Canvas @ref="@canvas" Width="1500" Height="700">
   <Node X="@node.X" Y="@node.Y" Width="@node.Width" Height="@node.Height"></Node>
</Canvas>

@code{
    NodeModel node = new NodeModel{
        Width = 100,
        Height = 100,
        X = 100,
        Y = 100
    };
    Canvas canvas;
    Node node;
    public void UpdateWidth()
    {
        node.Width = 200;
    }
}
```

**Comment by javiercn** [comment]
I'm not sure I understand what you are doing as it is not a trivial component. From what I understand you compute the node being selected when the user click, update the position while you drag it and then i'm not sure what happens when you stop dragging it.

From what I see in your code you might be missing some `@` in the property values https://github.com/Naganathan/SampleObjectDragging/blob/master/Pages/Canvas.razor#L25


> Could you please confirm us that the property should only be updated with property binding for initial rendering nodes?

Bind hooks to OnChange and keeps the attribute value you are binding in sync with the instance you bind it to. If you don't want that behavior don't use `@bind` and simply set the values with `value=@expression`

does that anwer your question?
