### ISSUE TITLE
Blazor, System.Text.Json, JsonConverter and subtype

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#14254]
### Describe the bug
Sub-types are lost from Blazor to controller api.

### To Reproduce

Say I have a `class C` that inherits from `class B`.

    public class B
    {
        public string BName { get; set; }
    }

    public class C : B
    {
        public string CName { get; set; }
    }

`class A` hold a reference of `class B` like this:

    public class A
    {
        public B b {get; set;}
    }

Now, from Blazor, I use an instance of `class C` and put it in `a.b = new C();`, where `a` is an instance of `class A`. Also, I set the `CName` to some string.

Finally, I send, from Blazor, through `await Http.PostJsonAsync<A>("http://localhost:5000/api/", a)` object `a` to the "json controller";

When I retrieve `a` in the controller, `a.b` is not of type `C` but of `B`, so I loose `CName`.

I tried to use `JsonConverter`, but seems that the `C` type "is definitely lost", `a.b` is only seen as `class B`.

### Expected behavior
`a.b` should be of type `C`.

### Additional context
dotnet 3.0.100-preview9-014004

**Comment by javiercn** [comment]
Can you share the signature of the controller method?

.NET Types are not serialized when you serialize data to JSON, hence when the data gets deserialized on the server there's no way it can know the derived type you used on the client-side and tries to use the .NET type defined in the property.

To achieve what you want, you need to write your own converter that persist that information on the client side and knows how to retrieve it on the server side to instantiate the right subclass.

This is not an easy task and not something we would recommend. I suggest you find an alternative way to model the API call/object that avoids using inheritance as that doesn't work well in these scenarios.

**Comment by vintzl** [comment]
>Can you share the signature of the controller method?

Something, very simple, like this:

        [HttpPost]
        public ActionResult Add([FromBody] A a)

> To achieve what you want, you need to write your own converter that persist that information on the client side and knows how to retrieve it on the server side to instantiate the right subclass.

Could you direct me to some documentation?

**Comment by vintzl** [comment]
@javiercn Is there any chance to get this out of the box in dotnet?

Anyway, I really think that you, **have to**, at least, either:

- provide us some documentation [like this one](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.0) (not a "step-by-step walkthrough", **but fair enough**;
- help us to use this easily in Blazor and ASP.NET Core.

Or in the worst case, point us in the right direction (**where are related sources codes**).

**Comment by javiercn** [comment]
@vintzl Unlike the doc you mention this is not a Blazor specific feature but a System.Text.Json feature.

If you really want to do this, (which I would suggest you don't) you need to write a custom JsonConverter. For that, I would suggest you file an issue https://github.com/dotnet/docs/ describing your scenario and get guidance from the core fx docs team on how to achieve that.

You can look through the tests in CoreFX to see samples on how to do this
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/CustomConverterTests.cs

For example, there seems to be a `PersonConverterWithTypeDiscriminator` used in the tests that does what you want.

**Comment by vintzl** [comment]
@javiercn 
> Unlike the doc you mention this is not a Blazor specific feature but a System.Text.Json feature.

I took the page as a "writing sample".

> If you really want to do this, (which I would suggest you don't) you need to write a custom JsonConverter. 

Why do you insist so much on this? What's wrong with it?

Don't you think, as we share the same model between the server side and Blazor, inheritance should be supported? And what about a feature request? Could it be accepted?

Anyway, thank you for your attention.

**Comment by javiercn** [comment]
> Why do you insist so much on this? What's wrong with it?

Because it's hard to get it right and insecure when not done correctly.

> Don't you think, as we share the same model between the server side and Blazor, inheritance should be supported? And what about a feature request? Could it be accepted?

Inheritance is a feature of the programming language, not a feature of the serialization format. There are formats that support this, you could try and use OData to achieve what you want, but it's not Blazor's responsibility how you format your data between application tiers.

There is an inherent impedance between serialized data and object oriented languages as object oriented languages are more expressive than any serialized data. You can observe this impedance when you reach the boundaries of the object oriented model memory. For example, when you need to get/store data in a database or when you need to send/receive data to/from a different service/client. When faced with this impedance you can go two ways:
* Make the transport format more complex to simulate features of the object oriented model like inheritance or the ability to preserve cyclical references.
* Make the model you use for transferring data simpler and constrained to a subset of the functionality that is easily representable in the format used for transferring data.
  * For example, introduce DTOs that clearly and unequivocally define the data in and out of the wire and that can easily map to the data that is being sent to and from a given service. Define a mapping from the DTO to your object model.

The first option (Make the transport format more complex) is represented by things like ORMs, (Entity Framework, NHibernate that try to allow you to retrieve and store data as objects and try to handle the changes transparently) or OData that tries the same thing but in terms of REST services.
* It's doable if you have a framework that does it for you.
* You still need to learn to use that framework appropriately.
* It's very likely that the framework features will covert at most 80-90% of your use cases, at which point you'll have to resort to option 2.

The second option (Make the model simpler) is typically what we recommend as a starting point because:
* It's simpler to implement.
* It's explicit about what data goes in and out.
* It decouples the data coming in and out of a service from the implementation of the service.
* It acts as a contract that you can version without affecting your service implementation.

I hope some of these things resonate with you. If you still insist on going this path, I would suggest that you look into OData or a similar format for your data transfer needs.

Hope this helped.

**Comment by vintzl** [comment]
Again, thank you for your attention.

Now, I need some time to think about all of this.
