### ISSUE TITLE
Direct value changes to a property doesn't work with EventCallback

### ISSUE THREAD

**Issue by ajithr** [aspnet/AspNetCore#14283]
### Describe the bug
When setting a property value directly to the component with its event, the dynamic value changes are not reflected to the property even after `StateHasChanged` called. If we didn't use the event in the component, then it will be working fine. i.e. The dynamic value changes reflected to the property, if the event not bind in the sample.

### To Reproduce

**Counter.razor**
```
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<input type="text" value="@Content" />
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    int currentCount = 0;

    [Parameter]
    public string Content { get; set; }

    [Parameter]
    public EventCallback<string> OnContentChange { get; set; }

    async Task IncrementCount()
    {
        currentCount++;
        Content = "Value " + currentCount.ToString();
        await this.OnContentChange.InvokeAsync(Content);
        StateHasChanged();
    }
}

```

**Index.razor**
```
@page "/"

<Counter @ref="counter" OnContentChange="contentChanged" Content="Value"></Counter>

@code {
    Counter counter { get; set; }
    public void contentChanged(string content)
    {
        // some processing
    }
}
```
- In the above sample, the `Content` property had the direct value - "Value" with `OnContentChange` event.
- When click the button, the Counter component change the `Content` property value dynamically. but, the value changes are not reflected in the UI with Value 1, Value 2... in the textbox.
- If we remove `OnContentChange` event from the sample, it will work perfectly and the textbox will change its value to Value 1, Value 2... based on button click.

### Expected behavior
The dynamic value changes to a property should be maintain with EventCallback when it had direct property. 

### Screenshots

with `OnContentChange` event
![with-event](https://user-images.githubusercontent.com/8641400/65458680-c638f800-de6b-11e9-964f-953610162cf1.gif)

without `OnContentChange` event
![without-event](https://user-images.githubusercontent.com/8641400/65459412-78bd8a80-de6d-11e9-84b1-1769c95a7057.gif)

Is this a know behavior or anything need to be addressed to resolve this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ajithr.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
Every time your parent component re-renders (`Index`), it's re-rendering its child (`Counter`) and writing a value to the `Content` parameter. This keeps overwriting your "direct" changes to the `Content` parameter, so it appears as if your changes are not being applied. They are being applied, but then overwritten.

This only happens when you use the `OnContentChange` event wired up to the parent, because that's what makes the parent get re-rendered.

The solution is not to mutate your `[Parameter]` properties directly. Doing so leads to confusion, because they are getting written from two different places which interfere with each other. Instead, have some other private field on `Counter` that holds the mutable value. During `OnInitializedAsync`, copy the value supplied by the parent into your private field. After that, you're free to mutate the private field within the class, and changes to the `[Parameter]` won't affect it.

If you want, also add an `OnParametersSet` override so you can receive new values for the `[Parameter]` from the parent and implement your own logic to decide whether or not those new values should overwrite your private field.

**Comment by Liander** [comment]
This is my understanding: 
To understand the difference of the two calls you need to know that when `OnContentChange` is not set the framework tests for changes in attribute values being passed to the component, which will always be `Content=”Value”` in this case (not the Content property value of the instance which is changing) and there is no re-rendering (old tree is used) in this case and no overwrite. You will also need to know that you by-pass that test when setting a custom reference to a component, which is done when setting the `OnContentChange` in this case, and the component will always re-render and overwrite. That a delegate by-pass the change detection is the surprising factor. 

@SteveSandersonMS  What do you think of having the ability to only set a delegate at initial-render? This could probably be done in tons of ways, but what about generating a construction guard: like `builder.AddAttribute(builder.IsInitialRender ? ..your delegate.. : IgnoreDelegate)`, and have a static `IgnoreDelegate` marker in the framework to be excluded at re-render calls from change detection tests and `SetParameters`? As a bonus, there won’t be unnecessary additional delegate constructions when setting a lambda expression.
