### ISSUE TITLE
'StartWorkTimer' must be called on the foreground thread.

### ISSUE THREAD

**Issue by eevahr** [aspnet/AspNetCore#14324]
#### Is this a Bug or Feature request?:

Bug

#### Steps to reproduce

Have razor file open, possibly also be in debugging mode.

#### Description of the problem:

Razor language server stops unexpectedly and without any real indication of what triggers the stop.

Expected behavior:
Razor language server to not stop unexpectedly.

Actual behavior:
Razor language server stops unexpectedly.

razor file/log
https://gist.github.com/eevahr/c25c22612563740b9570a9f8871567fb

**Comment by DanJ210** [comment]
It's crashing for me every time I type `itemscope` and `itemtype` when implementing tags for schema.org SEO.

**Comment by NTaylorMullen** [comment]
> It's crashing for me every time I type `itemscope` and `itemtype` when implementing tags for schema.org SEO.

ya I figured out what the issue was. Sadly it's an embarrassingly obvious fix 😢

**Comment by DanJ210** [comment]
Is this thread related to Razor crashing? Because mine's now crashing every time I type. I restart VS Code and as soon as I start typing it's spitting out logs with every word until finally says connection stopped.

**Comment by NTaylorMullen** [comment]
> Is this thread related to Razor crashing? Because mine's now crashing every time I type. I restart VS Code and as soon as I start typing it's spitting out logs with every word until finally says connection stopped.

Given the nature of the issue it can happen any time. If you have a lot of work running in the background it'll probably happen more frequently though

**Comment by tjbortz1s** [comment]
Would you be able to give a little more detail on what was causing the problem?  I'm curious to hear of what was going on.

**Comment by NTaylorMullen** [comment]
> Would you be able to give a little more detail on what was causing the problem? I'm curious to hear of what was going on.

Sure. The gist is we have a timer that will start "calculating" diagnostics after a Razor document has been parsed in the background. Typically that calculation is quite quick; however, in the case that another document parse result gets ready while still calculating diagnostics we have a slight optimization to immediately re-start our timer once the previous calculation has finished.  The problem lied in how we restarted the timer. At the time we were requiring that the timer be restarted on a specific thread (to ensure we don't create 2) but in the restart case we weren't actually restarting it on the appropriate thread which is why things would explode with the error. The fix involved removing the restriction to start the timer on a specific thread because we were already locking on the instantiation of the timer to ensure we didn't create more than one.

Code fix: https://github.com/aspnet/AspNetCore-Tooling/pull/1294/files#diff-f09144ac9f417245aaf102044534295cL90

**Comment by DanJ210** [comment]
I could publish to a GitHub repo and show my really bad code lol but it is very light code, very very small .Net Core PWA. Never had this problem on my project before. I also have a Surface Pro 6, i7, 16GB and definitely not enough running to cause a breakdown with each typed word. Constant breakdown also. It's like I can no longer use VS Code anymore.

**Comment by NTaylorMullen** [comment]
> It's like I can no longer use VS Code anymore.

totally understand, sorry @DanJ210! Stay tuned any we'll have this fixed for 3.1 (not too far away)

**Comment by DanJ210** [comment]
Ok no problem @NTaylorMullen I love VS Code and I appreciate all you guys/girls do to make it great while dealing with us problem preachers lol. Thank you.

**Comment by tjbortz1s** [comment]
> Sure. The gist is we have a timer t... we didn't create more than one.
> 
> Code fix: https://github.com/aspnet/AspNetCore-Tooling/pull/1294/files#diff-f09144ac9f417245aaf102044534295cL90

This bug was preventing me from really being able to use the razor autocomplete features in vscode, so seeing it fixed is great.  Thank you for the explanation as well.
