### ISSUE TITLE
Injected blazor services trigger warnings when using c# 8 nullable reference types

### ISSUE THREAD

**Issue by rpskelton2** [aspnet/AspNetCore#14345]
Turn on the nullable reference types feature for c# 8 and compile a blazor app
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types

You will get CS8618 warnings about injected properties not being initialized.  You could mark it as nullable to get around this but in some instances I would prefer not to and instead do an explicit null check in the component's constructor/initialize.

Warning	CS8618	Non-nullable property 'DocumentContext' is uninitialized.

![image](https://user-images.githubusercontent.com/7995579/65469641-002edd80-de1d-11e9-8987-346a882d9433.png)

**Comment by rynowak** [comment]
Is the screenshot from code you wrote, or from generated code?

If this is code you wrote, then the pattern is to use `protected DocumentContext DocumentContext { get; set; } = default!` This isn't Blazor specific, the same thing would happen in any C# code.

**Comment by Joe4evr** [comment]
When it comes to Razor/Blazor, the compiler is a bit overzealous with its nullable warnings, since much of it revolves around initializating fields *after* object construction (which is what NRTs is supposed to guard against). You can work around this for now by declaring the Nullable Context in your code sections as `#nullable enable annotations` which allows you to use the `?` where you want/need it but skips on the warnings.

**Comment by rpskelton2** [comment]
The screenshot is of a service I created and registered is Startup.cs.

Hopefully we can do a little tweaking of this rule for Blazor.  For example, it would be nice if it recognized that you initialized a variable in the OnInitialized method.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rpskelton2.
This looks like a question about the C# Compiler. Feel free to share your feedback at https://github.com/dotnet/roslyn repo.
