### ISSUE TITLE
AuthenticationMiddleware pipeline issue

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14481]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/733089/authenticationmiddleware-pipeline-issue.html)._

---
Using .net core 2.2 I started to create my own SOAP service with basic authentication. This required build a custom middleware. I did it based on Security project. I used https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs. and my custom service end point responded. 

The issue is that the endpoint is always called. Independently to the authentication success or fail response the next delegate is always called.

Steps to reproduce the problem:
1. Create own SOAP service.
2. Add authentication middleware.
3. Use https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs

If you look into AuthenticationMiddleware class and Invoke method you can see that at the end of this method the next context task is executed even if the previous authentication fails. 

I fixed bug as follows (lines 52 .. 62):

            if (defaultAuthenticate != null)
            {
                var result = await context.AuthenticateAsync(defaultAuthenticate.Name);
                if (result?.Principal != null)
                {
                    context.User = result.Principal;
                }
                if ((bool)result?.Succeeded)            // *** NEW ***
                {
                    await _next(context);
                }
            }
            //await _next(context);                     // *** NEW ***     

My modifications are in lines adorated by comment // *** NEW ***.

Please review the code and make your proposition of this fix.

Kind Regards
Marek

---
#### Visual Studio Feedback System on 9/16/2019, 03:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/24/2019, 10:53 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### marekkubis solved on 9/25/2019, 01:31 AM, 0 votes: 

<p>I understand that your AuthenticationMiddleware always calls the next middleware delegate because that's the 'Create a middleware pipeline with IApplicationBuilder' rule (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.2). And I am not complaining that 'The ASP.NET Core request pipeline consists of a sequence of request delegates, called one after the other.'. I like this approach. The problem, however, is that authentication is a special event. If you are not authenticated, you are not allowed to enter the application. Additionally it is not necessary for SOAP web service authorise the request to show the WSDL document. Based on this assupmtion, I replaced lines 52..62 with the new code:</p><p>if (context.Request.Method.ToLower() == "get" &&</p><p>context.Request.QueryString.ToString().ToLower() == "?wsdl") // *** NEW ***</p><p>{</p><p>await _next(context);</p><p>}</p><p>else</p><p>{</p><p>var defaultAuthenticate = await Schemes.GetDefaultAuthenticateSchemeAsync();</p><p>if (defaultAuthenticate != null)</p><p>{</p><p>var result = await context.AuthenticateAsync(defaultAuthenticate.Name);</p><p>if (result?.Principal != null) { context.User = result.Principal; }</p><p>if ((bool)result?.Succeeded) // *** NEW *** { await _next(context); }</p><p>else</p><p>{</p><p>context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;</p><p>await context.Response.WriteAsync(result?.Failure.ToString());</p><p>}</p><p>}</p><p>}</p>

**Comment by Tratcher** [comment]
Authentication is independent of Authorization. The Authentication middleware is responsible for identifying users. Endpoints then need to check the user (or lack thereof) to enforce authorization. If you want to refuse all non-authenticated users that can be done in a simple middleware after Authentication as you've indicated, and we've added a new Authorization middleware in 3.0 that can be configured like that.

**Comment by blowdart** [comment]
We're closing this issue as the behaviour discussed seems to be by design.

**Comment by MarekAKubis** [comment]
I fully agree with your comment about authentication and authorisation however you menioned only one feature of authentication (identifing users). But authentication is also "a security measure designed to protect a communications system against acceptance of a fraudulent transmission or simulation by establishing the validity of a transmission, message, or originator." And that's what I did. I have added a function that protects the rest of the system from unnecessary trafic as soon as possible. 

You have not convinced me that your solution is bug free because you are allow the execution to continioue even if the user is not authenticated. In my oppinion, this is an error and we cannot say that we can refuse all non-authenticated users later. Sorry, but authentication has already been done, and if it fails, it's over.

At the end of authentication, the process ends and later checking the same layer by layer is not wise. After authentication is autorisation time and this job should be limited to "authorization is a security mechanism used to determine user/client privileges or access levels related to system resources, including computer programs, files, services, data and application features."

In addition, I see that my code contains one topic worth discussing. If authentication fails then instead of 401 unauthorized HttpStatusCode it is better to use 403 Forbidden HttpStatusCode. But this is not obvious for me, even if we look at the http decision scheme. https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses
