### ISSUE TITLE
Visual Studio Tracepoints are not working with Blazor

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#14551]
Using the default template and adding a simple tracepoint:

![image](https://user-images.githubusercontent.com/8482283/65821769-72972780-e23a-11e9-8e10-99bf9113e010.png)

It outputs to the console however the flow of the applications breaks for a moment before it continues automatically:

![image](https://user-images.githubusercontent.com/8482283/65821793-bdb13a80-e23a-11e9-89c9-0719759d7e1a.png)

This renders tracepoint basically unusable. 

( Visual Studio 2019 16.4 )

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Postlagerkarte.
Do you experience this with Blazor WASM or Blazor Server-Side projects?

**Comment by Postlagerkarte** [comment]
Blazor Server-Side

**Comment by pranavkm** [comment]
@Postlagerkarte this isn't something the runtime controls. We recommend filing a VS Feedback issue so that the right team gets to look at it.

**Comment by Postlagerkarte** [comment]
@pranavkm : Since this is my second issue beeing closed with "ask the right team" I like to ask:  Who in the first place makes sure that all Visual Studio features work well with the Blazor technology?  Secondly, I don't understand the distinction between my raised issue #14519 and this issue here.  Isn't the navigation  inside Visual Studio (#14519) something that also is not controlled by the runtime?

**Comment by pranavkm** [comment]
@Postlagerkarte we understand it can be difficult to navigate the many support forums that Microsoft hosts. We appreciate that you took the time and effort to file this issue.

In this case, we tried out your scenario and it does look like it's working just fine:

![TracePoint](https://user-images.githubusercontent.com/174281/66085289-a6699a00-e525-11e9-9e44-f88aff422cde.gif)

Your specific issue appears to be an issue with the debugger. Using the VS Feedback tool should include more specifics about the IDE as well as other diagnostics as part of the bug report, that would help the debugger folks understand what's causing this issue. We would have been happy to transfer the issue to the debugging team if we understood what the underlying cause was, but this seems specific to your IDE environment.

As for your second question, the ASP.NET Core runtime team owns some part of the parsing experience for `.razor` files in the IDE. We've some work planned to improve the experience around things like refactoring and renaming, and go to definition (Ctrl + Click) would be a great addition to it.

**Comment by Postlagerkarte** [comment]
@pranavkm thank you for the detailed response. I really appreciate it!

Indeed the problem with the tracepoints is only occurring under a specific circumstance - but it is easy to reproduce and has nothing to do with individual debugger settings.

Simply add to your example counter.razor file:

`<div ondragover="event.preventDefault();"></div>`

No need to drag anything over that div - for some reason it is enough to have some javascript included in the razor file.

I tested in both Chrome and Edge. The behavior is a bit different since Edge is displaying a different overlay.

Take a look (Chrome):

![test](https://user-images.githubusercontent.com/8482283/66088494-95e40e80-e57b-11e9-97be-290780579003.gif)

**Comment by Postlagerkarte** [comment]
In case anyone got here because of the same issue:

https://developercommunity.visualstudio.com/content/problem/758260/visual-studio-tracepoints-are-not-working-with-bla.html

There is a solution provided for the current behavior in the vs feedback item.
