### ISSUE TITLE
Setting XHR "withCredentials" attribute in SignalR

### ISSUE THREAD

**Issue by jez9999** [aspnet/AspNetCore#14570]
This topic has already been covered, but I wanted to revisit it:

https://github.com/aspnet/SignalR/issues/2110

I don't understand precisely why SignalR needs to use cookies.  My scenario is that I am developing a JavaScript application that can be embedded on any website, and which needs to have a persistent connection to my server to update its UI.  This requires me to specify `access-control-allow-origin: *` as the CORS header, so that requests from any site can access my hub.  However, this gives the error: "The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

As I understand it, SignalR sets `withCredentials` to 'include' so that cookies will be passed by the browser, but in this instance I don't see why cookies need to be passed by the browser; requests are coming in from different domains and existing credentials will not exist for my hub.  Can't there be a mode of operation where SignalR doesn't require the use of cookies, and therefore doesn't require `withCredentials` set to 'include'?

**Comment by DAllanCarr** [comment]
@anurse mentions
> Making this configurable is not likely to help much since SignalR also requires sticky sessions which is generally implemented using Cookies, so disabling the withCredentials flag will cause that to fail

I'm not sure if this is indication enough of whether it could be configurable. So in light of that cookies or no cookies would need to be answered in relationship to the above.

I would you could bypass the browser using whitelist the Authorization header and could also used with wildcard domains.

**Comment by anurse** [comment]
> Can't there be a mode of operation where SignalR doesn't require the use of cookies, and therefore doesn't require `withCredentials` set to 'include'?

Only if you are either: 1) Deploying to a single server only (no load balancer, no failover, etc.) **or** 2) Have a load balancer capable of enabling sticky sessions **without** cookies.

We certainly *can* make it configurable, and likely will (it's also possible to do it  yourself by providing a custom `HttpClient` in the JavaScript client), but in general we haven't found a scenario in which that is the right approach (since having multiple servers is basically essential to modern apps).

Do you have more context on your scenario? Where are you deploying your app? Do you have a load balancer in place?

**Comment by jez9999** [comment]
I'm just deploying it to one server at the moment but in future it could be expanded to multiple as part of a web farm.  Perhaps I'm being dumb, but why does sticky sessions require cookies?  Or at least, why does it require cookies that are stored against the CORS server's domain rather than against the domain the script is running from?

**Comment by anurse** [comment]
> I'm just deploying it to one server at the moment but in future it could be expanded to multiple as part of a web farm

So it would probably be good to find a proper solution now rather than when you do expand to multiple servers.

> why does sticky sessions require cookies?

Sticky sessions need a way to correlate multiple requests as being part of the same session in order to properly route all requests for a single session to the same server. Cookies are the most common way to do this. If there's a session-specific part of the URL, that can be used too.

> why does it require cookies that are stored against the CORS server's domain

The cookies must be stored against the domain that the request is going to. So if your SignalR server is hosted at `example.com`, the cookies must be stored there. Storing them against the domain on which the script is running would mean they wouldn't be sent as part of the SignalR requests and thus wouldn't route properly.

In general, using a `*` in the allowed origins is considered a risky practice. A better practice is to validate the incoming `Origin` header itself against a list of expected/known origins. You can then reflect the original `Origin` request header value back in the `Access-Control-Allowed-Origin` response header. If you *really* want to support a wildcard (`*`), you could just reflect any `Origin` request header value back in the `Access-Control-Allowed-Origin` response header.

**Comment by jez9999** [comment]
Passing it as part of the URL was precisely what I was thinking of: specifically the query string.  The session ID could then be stored in JavaScript cookies couldn't it?

**Comment by anurse** [comment]
We'll look at making this option configurable. I should also point out that none of this matters when using Azure SignalR for scale out. The only place in which `withCredentials` should be disabled is:

1. When using Redis scale-out to support multiple servers, **and**
1. When session affinity is done via the URL

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/15076
