### ISSUE TITLE
BlazorWasm HttpClient can not send cookie?

### ISSUE THREAD

**Issue by BigBigPlant** [aspnet/AspNetCore#14596]
`public async Task<string> GetData()
        {
        
 using (HttpClient httpClient = new HttpClient())
            {
                HttpContent data = new StringContent("{'Category':'2','Currentpage':1,'Url':'/vue/home/show/video/2'}");
                data.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                data.Headers.Add("Cookie",await GetCookie());
                var res = await httpClient.PostAsync(@"https://localhost:44338/api/index/PostVideo", data);
                return await res.Content.ReadAsStringAsync();
            }
        }`

`
 async  Task GetValue()
    {
        Data = await httphelp.GetData();
    }
`

![git1](https://user-images.githubusercontent.com/37919956/65927975-9b800e00-e42e-11e9-81c4-5f9b70356067.PNG)

![git2](https://user-images.githubusercontent.com/37919956/65927982-a20e8580-e42e-11e9-89cf-1e6082658cba.PNG)

![git3](https://user-images.githubusercontent.com/37919956/65927987-a63aa300-e42e-11e9-8fd1-f38a8e1e22d2.PNG)

1. Why BlazorWasm can not send cookie ?
2. Code:"data.Headers.Add("Cookie",await GetCookie());" can not set cookie
3. Why BlazorWasm send Get and Post Request?
4. But in BlazorServer can send cookie and can Get the Data?

**Comment by AdrianJSClark** [comment]
Hi @BigBigPlant, I'm just an enthusiastic developer but was interested in your question so did some research. Hopefully when the experts drop by I've got most of it right!

Behind-the-scenes the `HttpMessageHandler` implementation used by Blazor WebAssembly packages up your call and passes it to [some JavaScript/TypeScript code](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web.JS/src/Services/Http.ts). That JavaScript/TypeScript code then uses the standard `fetch` API in the browser to make the request.

This means that Blazor WASM is restricted to making calls in the way that is allowed by the browser. One of those restrictions are the headers. From [Headers - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Headers):

> For security reasons, some headers can only be controlled by the user agent. These headers include the forbidden header names  and forbidden response header names.

One of the header names which is classified as a "forbidden" header name is `Cookie`. If you want to see the full list of those forbidden header names, this article on MDN lists them: [Forbidden header name - MDN Web Docs Glossary](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).

So Blazor WASM can't set a value for the `Cookie` header because you aren't allowed to set the `Cookie` header on a `fetch` API request.

Blazor Server **can** set the `Cookie` header because it is using the standard, full, .NET Core `HttpClient` and `HttpMessageHandler` implementation, which is all C# code. There's no reliance on the browser

While you can't set custom cookies with Blazor WASM, by default any cookies set by the same-origin (i.e. the server where the Blazor WASM app was loaded from) will be returned back to that server. The setting is part of the [`WebAssemblyHttpMessageHandler`.`DefaultCredentials` property](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Blazor/src/Http/WebAssemblyHttpMessageHandler.cs#L26) which eventually gets passed down to the `fetch` API `Request.credentials` value.

I hope that explains the difference you are seeing between Blazor Server and Blazor WASM.

To work-around your issue I suggest that for Blazor WASM you make a call directly back to your server which can then pass your request on to the target endpoint on your behalf. On the server you'll have access to full .NET Core and will be able to set `Cookie` headers as appropriate.

**Comment by BigBigPlant** [comment]
@AdrianJSClark  Thank you for your answer.
Counld you Tell me how to make a call directly back to your server ?

**Comment by AdrianJSClark** [comment]
You just need to give the path you wish to call. The server name is added automatically.

Using a line from the sample code you provided:
```var res = await httpClient.PostAsync("/api/index/PostVideo", data);```

Obviously you need to have something on the other end to accept the request, for example a WebAPI Controller.

**Comment by BigBigPlant** [comment]
@AdrianJSClark  I know what you mean.Thanks!
 I change the verification to JWT whitout using cookies.
Maybe can Solve the problem of BlazorWasm verification.
