### ISSUE TITLE
3.0. When the application pool is recycled, it crashes directly

### ISSUE THREAD

**Issue by jmk92** [aspnet/AspNetCore#14719]
When we used 3.0, dapper was used in the database, which was normal all the time.
Recently, it has been modified and used asynchronous methods, such as Execute Async and Query Async.
There is no problem after the replacement, but when we manually recycle  the application thread pool.
When accessed with a browser, it was always loaded and unresponsive, and it crashed.
Refreshing is useless, and even restart the application can not be repaired, stop the application pool, but also can not start.
Because the machine has been serving, we have to return the previous version.
View the error log (section)
```
2019-10-03 14:31:54.4023|0|ERROR|Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|Unexpected exception in IISHttpContext.HandleRequest. System.Runtime.InteropServices.COMException (0x80070006): 句柄无效。 (0x80070006 (E_HANDLE))
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.HttpTryCancelIO(IntPtr pInProcessHandler)
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOEngine.Dispose()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
2019-10-03 14:31:54.4178|0|ERROR|Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|Unexpected exception in IISHttpContext.HandleRequest. System.Runtime.InteropServices.COMException (0x80070006): 句柄无效。 (0x80070006 (E_HANDLE))
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.HttpTryCancelIO(IntPtr pInProcessHandler)
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOEngine.Dispose()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()

```

Conditions for triggering
1. Use asynchronous queries
2. servers that have always been requested
3. Recycle it
We also made a comparison. We tested it 4-5 times, and determined that the problem was that the synchronous method did not crash, and the asynchronous method crashed every time.

**Comment by huysentruitw** [comment]
You're saying that the application works fine until you once manually recycle the application pool, after that the application keeps crashing, right?

How do you recover from that situation?

**Comment by jmk92** [comment]
@huysentruitw 
Yes, when we recycle manually, we are not constantly crashing, but have been unresponsive, stuck, occasionally 503 errors, the service is no longer available, can not be restored, we try to restart the website, stop the application pool, restore, still can not be repaired.

We have load balancing in the outer layer. If we switch traffic to another machine, it will automatically recover. You may not be able to recover without switching.

**Comment by jmk92** [comment]
Serious thing, IIS default settings are 1740 minutes of automatic recycling, or we set a time period of recycling, this recycling is automatic, if I did not find this problem, the user did not know, when the machine automatically recycled, the service directly paralysed?

**Comment by jkotalik** [comment]
Are you able to gather more information about what is causing the process to crash? Like getting a crash dump or checking the event log? You mentioned that a library recently changed from sync to async calls? Maybe there is something being thrown on a background thread, which crashes the process?

What usually happens if w3wp.exe crashes too frequently, [rapid failure protection starts](https://weblog.west-wind.com/posts/2006/dec/19/iis-7-and-rapid-fail-protection), and the IIS process will not start again. That is probably the behavior you are seeing.

With regards to the IIS error, it is being logged here: https://github.com/aspnet/AspNetCore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs#L146. This error can occur on shutdown as the app pool is being recycled. This is an expected error, but IMO the error can use a bit of cleanup. cc @davidfowl

**Comment by jkotalik** [comment]
> We also made a comparison. We tested it 4-5 times, and determined that the problem was that the synchronous method did not crash, and the asynchronous method crashed every time.

Can you make sure that all calls to the async methods are awaited and exceptions are caught when invoking it?

**Comment by jmk92** [comment]
@jkotalik 
You reminded me that I only modified the underlying code of the DBA. In the place where I called it, I used System.Threading.Tasks.Result to get the result. I am not sure that all of its upper-level code is asynchronous, most likely Asynchronous method is called in the synchronous method, causing deadlock

**Comment by jmk92** [comment]
@jkotalik  When we all upgraded to asynchronous code, from start to finish, after all processing, test again, no problem.
It seems that calling System.Threading.Tasks.Result in synchronization is an error, which makes me mistakenly think it is equivalent to async/await.
But I think that there may be someone who will make the same mistake in the future. Should it be restricted?

**Comment by jkotalik** [comment]
My general policy is don't call Task.Result. If you don't await the call, calling Task.Result will block until the task has completed. You would need to use some older apis. See https://montemagno.com/c-sharp-developers-stop-calling-dot-result/ for a good summary on why to not call it.

Closing this for now as your issue seems to be resolved. Feel free to continue commenting if you have more issues.
