### ISSUE TITLE
Blazor @ref not updating component

### ISSUE THREAD

**Issue by valincius** [aspnet/AspNetCore#14715]
### Describe the bug
When calling a referenced component's functions, the UI isn't being updated.

### To Reproduce
- Using latest ASP .NET Core

1. Reference a component using `@ref`
2. Call component member function which modifies the DOM

I made a fiddle that can be used to view this issue https://blazorfiddle.com/s/zkmpjypw
Clicking 'Show from component scope' button works just fine but clicking 'Show using ref' doesn't make the alert show.

If running in the debugger, you'll see that the component's function is called and the variables change but the DOM element is unchanged.

### Expected behavior
DOM should reflect changes from `@ref`'d calls

**Comment by valincius** [comment]
Figured out that `StateHasChanged` must be called to get the DOM to register these changes, is there any way this could happen automatically?

**Comment by rynowak** [comment]
It is intentional that we don't do this by default. If you call a method on a .NET object, Blazor isn't involved, that's entirely inside your code. 

Even if we could intercept that, it's not obvious that we should trigger rerendering - we don't know if the method you called impacts the UI in any way.
