### ISSUE TITLE
Endpoint json has missing properties defined inside parent Interface

### ISSUE THREAD

**Issue by DarioDomiDE** [aspnet/AspNetCore#14724]
# Issue Title

Strange Behaviour with returning json. Properties are missing in ActionResult Ok() method, when they was defined inside a parent interface. Problem seems with inheritance of Interfaces only.

I have a object that uses an interface which uses another "parent"-interface. I initialize a new object , set all properties, and all properties can be seen via inspecting variables like expected. But the Endpoint isn't returning the property from parent-interface, only using properties defined inside children interface.

# General
Using
  * C#
  * VS 2019 16.3.2
  * .Net Core SDK 3.0.100

Problem occurs after upgrading from .Net Core 2.1 to .Net Core 3.0. Using .Net 2.1 it was working. 

I have a ASP.Net Core REST endpoint, which return a json in the format:

### Exptected response Datatype (from Swagger):
```
{
  "data": [
    {
      "posts": 0,
      "refCount": 0,
      "onBlacklist": true,
      "name": "string"
    }
  ]
}
```

### What I actually got as response **(missing name property)**:
```
"data": [
    {
      "posts": 123,
      "refCount": 456,
      "onBlacklist": false
      // missing name property here!
    }
]
```

### What I expected as reponse **(with name property)**:
```
"data": [
    {
      "name": "someName",
      "posts": 123,
      "refCount": 456,
      "onBlacklist": false
    }
]
```

### To Reproduce

```
    public interface ISomeRandomTag : ITag
    {
        int Posts { get; set; }
        int RefCount { get; set; }
        bool OnBlacklist { get; set; }
    }

    public interface ITag
    {
        string Name { get; set; }
    }

    public class SomeRandomTag : ISomeRandomTag 
    {
        public string Name { get; set; }
        public int Posts { get; set; }
        public int RefCount { get; set; }
        public bool OnBlacklist { get; set; }
    }

    public IActionResult SomeEndpoint() {
        var someRandomTag  = this.SomeHelperMethod();
        var output = new Dictionary<string, ISomeRandomTag>();
        output.Add("data", someRandomTag);
        Console.WriteLine(output);         // <--- or via Breakpoint to display that "name" is set
        return this.Ok(output);               // <--- "name" property is missing at endpoint response
    }

    private ISomeRandomTag SomeHelperMethod() {
            return  new SomeRandomTag
            {
                  Name = "test",
                  Posts = 123,
                  RefCount = 456,
                  OnBlacklist = false
            };
    }

```

# Solution / Workaround

I figured out, overriding the property from parent class and define it again with `new` solves the problem:

```
    public interface ISomeRandomTag : ITag
    {
        int Posts { get; set; }
        int RefCount { get; set; }
        bool OnBlacklist { get; set; }
        new string Name { get; set; }        // <---- adding this solves the problem
    }

```

Hope I could write it understand-able. Looking forward to solve it. If you guys aren't able to reproduce, I can check if I can setup a reproduce-able project.

**Comment by pranavkm** [comment]
@DarioDomiDE the change in behavior is a result of how System.Text.Json handles polymorphism. If you'd like to retain the 2.x behavior without changing your application code, consider using the Json.NET based formatters in MVC: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support

If you'd like to continue using System.Text.Json, it would be good to understand how polymorphism works with it. Consider:

```C#
class Program
{
    static void Main(string[] args)
    {
        var model = new Model();

        Console.WriteLine(JsonSerializer.Serialize<IModel>(model));
        Console.WriteLine(JsonSerializer.Serialize(model));

        Console.WriteLine(JsonSerializer.Serialize(new Dictionary<string, IModel> { { "key", model } })); // This matches what you have you in your Controller
        Console.WriteLine(JsonSerializer.Serialize(new Dictionary<string, Model> { { "key", model } }));
        Console.WriteLine(JsonSerializer.Serialize(new Dictionary<string, object> { { "key", model } }));
    }
}

interface IModel
{
    string Prop1 { get; set; }
}

class Model : IModel
{
    public string Prop1 { get; set; } = "Value1";
    public string Prop2 { get; set; } = "Value2";
}
``` 

Here's the output:

```
{"Prop1":"Value1"}
{"Prop1":"Value1","Prop2":"Value2"}
{"key":{"Prop1":"Value1"}} // This matches what you have you in your Controller
{"key":{"Prop1":"Value1","Prop2":"Value2"}}
{"key":{"Prop1":"Value1","Prop2":"Value2"}}
```

In effect, if you'd like to use System.Text.Json, you have one of the following options:

a) Ensure the definition and implementation exactly match. Essentially what you did when you added the property to the interface
b) Always use the exact type as part of the serialization contract
c) in this specific case, you could get away with using `object` as your value, since System.Text.Json special cases it - https://github.com/dotnet/corefx/issues/36166

Feel free to file a follow up issue in System.Text.Json. It's valuable feedback for the team to know what the pain points are so that they can either document or improve the experience around it.

**Comment by DarioDomiDE** [comment]
Thx for your detailed explanation :)
