### ISSUE TITLE
ASP.NET Core Scaffolding BUG

### ISSUE THREAD

**Issue by dreamdocker** [aspnet/AspNetCore#14883]
### Describe the bug
Wrong, there is no pedestal to support this item.

### To Reproduce
1. Create an MVC project with VS2019 and ASP.NET Core 3.0.
2. Create an empty directory named [Pages] under the project root directory.
3. In any subdirectory under the [Views] directory, right-click [Add], select [View] option, report an error, and BUG reappears.

### Expected behavior
The [Pages] directory should not affect the creation of MVC views.

### Screenshots

![02](https://user-images.githubusercontent.com/35678049/66555284-fc22ef80-eb80-11e9-9f0c-0c8c9eb07da8.png)
![03](https://user-images.githubusercontent.com/35678049/66555335-1230b000-eb81-11e9-95f2-b6a6cbd23d78.png)

### Additional context
If you delete the [Pages] directory created above, it works fine.

**Comment by javiercn** [comment]
@dreamdocker Thanks for contacting us.

@vijayrkn This seems to be a scaffolding issue. Can you get someone to look at it?

**Comment by dreamdocker** [comment]
@vijayrkn Can this BUG solve it?

**Comment by vijayrkn** [comment]
If you have 'Pages' folder in the App, we assume you are using Razor pages and hence we disable the ability to Scaffold Razor Views to the App. I can see how this can be confusing. 

@danroth27 - Are you okay with enabling the 'Scaffold Views' options for apps using Razor pages? 

Since this is a VS only bug, can you please create an issue from VS -> Help -> Send Feedback -> Report a Problem. 

/cc @deepchoudhery

**Comment by Pilchie** [comment]
Closing as external to this repo.  Please report a VS Feedback item as @vijayrkn suggests.
