### ISSUE TITLE
[Blazor] Error is thrown when component has been disposed before invoking a method from the client-side

### ISSUE THREAD

**Issue by jivanova** [aspnet/AspNetCore#14923]
Related to https://github.com/aspnet/AspNetCore/issues/11641

### Describe the bug

```
There is no tracked object with id '//'. Perhaps the DotNetObjectRef instance was already disposed.
```

When a component has asynchronous client-side logic, sometimes the disposal occurs prior to the invoke of a server method and the error is thrown. The issue is related to more complex scenarios, but I have isolated it in the simplest reproducible project. 

### To Reproduce
Repo https://github.com/jivanova/DotNetObjectRef-Error

All steps described there.

### Expected behavior
To be able to track whether the instance has been disposed and prevent further triggering of methods. 

I have tried to call js dispose function to keep the info that the dotnetinstance has been disposed, but it's not stable solution.

**Comment by javiercn** [comment]
@jivanova Thanks for contacting us.

I don't think there's anything we can do here. The server has full control over the life of the reference. Even if you were to call an "UnsubscribeEvents" method as part of the component disposal there would still be a timeframe in which you could send an interop call and it would go through and fail.

A few alternatives are:
* Simply catch the exception. The component is being disposed and it's going to disappear from the UI.
* Keep track of the dotnet object references separately from the component lifetime and have the parent notify the underlying object that the component it is associated to is being disposed, notify the javascript client that the reference is no longer valid through js interop so that it does appropriate cleanup and have it perform one last call to the server to make sure the object reference gets finally disposed.
