### ISSUE TITLE
What is the right way to Securing a SPA by authorization server before first load using ASP.NET Core 3.0?

### ISSUE THREAD

**Issue by AhmerAli** [aspnet/AspNetCore#14968]
I am using the 'new' project templates for angular v8.0 SPA applications in dotnet core 3.0 by using IDE (Visual Studio 2019).

What I'm trying to do is to securing the SPA itself before the application load first time. That means: When i open up my SPA e.g. https://localhost:44318/ i would like to be redirected to the authorization server immediately instead of clicking some button that will do the authentication.

See project structure:

https://i.stack.imgur.com/l45z6.png

What I've tried yet:

    //Added this to redirect to Identity Server auth prior to loading SPA    
    app.Use(async (context, next) =>
    {
        if (!context.User.Identity.IsAuthenticated)
        {
            await context.ChallengeAsync("Identity.Application");
        }
        else
        {
            await next();
        }
    });

above line I've added before `app.UseSpa`

My Startup.cs:

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
            app.UseDatabaseErrorPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        if (!env.IsDevelopment())
        {
            app.UseSpaStaticFiles();
        }

        app.UseRouting();

        app.UseAuthentication();
        app.UseIdentityServer();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllerRoute(
                name: "default",
                pattern: "{controller}/{action=Index}/{id?}");
            endpoints.MapRazorPages();
        });

        app.Use(async (context, next) =>
        {
            if (!context.User.Identity.IsAuthenticated)
            {
                await context.ChallengeAsync("Identity.Application");
            }
            else
            {
                await next();
            }
        });

        app.UseSpa(spa =>
        {
            // To learn more about options for serving an Angular SPA from ASP.NET Core,
            // see https://go.microsoft.com/fwlink/?linkid=864501

            spa.Options.SourcePath = "ClientApp";

            if (env.IsDevelopment())
            {
                spa.UseAngularCliServer(npmScript: "start");
            }
        });
    }

**Current behaviour:**

When I run my app I'm immediately redirected to my authorization server and routed to https://localhost:44318/Identity/Account/Login?ReturnUrl=%2F but I'm unable to route to my SPA routes and pages. When I click on anchor link on XYZ ideally it's route on home component or if I force to route counter component from url it shows me the below same login page. Kindly help me on this what is I'm doing wrong and what is the right way to secure SPA by authorization server before first load.

**Output**

https://i.stack.imgur.com/dhWSM.png

**Comment by javiercn** [comment]
@AhmerAli Thanks for contacting us.

I don't recommend you do this in your server. I would instead put some logic inside your App component to check whether the user is authenticated and redirect from there.

Otherwise you'll have to "invent" something to make this work and I can tell you already it will not be easy and It'll likely won't work well.

In a SPA like the one in the template only a piece of the server is responsible for the authentication (and that's because the auth server is bundled within the SPA).

The rest of the application should only care about validating JWT tokens and authorizing requests. The client-side code is the one that needs to ensure whether the app is properly authenticated and if not, redirect as a result.

(You can redirect to /authentication/login from within the app to trigger a login flow).

That said, I'm not really sure what you are trying to accomplish here, but in general, you can't really know if the user is authenticated as you don't have access to the browser state from the server.

Hope that helps.

**Comment by AhmerAli** [comment]
@javiercn ok fine but it takes some seconds to redirect to identity server that's why I need to first show login page when user successfully logged in then app redirect to spa.
