### ISSUE TITLE
Blazor Server Side - Page in RCL does not render content

### ISSUE THREAD

**Issue by chassq** [aspnet/AspNetCore#14985]
### Describe the bug
Cannot seem to render page inside RCL. See attached test app. The page in the RCL doe not seen to have a route? If this is supported then what would we be doing wrong?

### To Reproduce
Run the test project and select the counter menu item

### Expected behavior
The counter page will render

[BlazorServerTesting.zip](https://github.com/aspnet/AspNetCore/files/3725034/BlazorServerTesting.zip)

**Comment by javiercn** [comment]
@chassq Thanks for contacting us and thanks for including a repro project.

I took a look at the repro and the issue is that you need to explicitly include additional assemblies for routing purposes. See https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#route-to-components-from-multiple-assemblies for details

**Comment by javiercn** [comment]
I believe the issue has been resolved. If you still run into issues after following the guidance provided, feel free to reopen the issue.
