### ISSUE TITLE
Change IResponseCache output to ValueTask

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#14993]
In ResponseCaching middleware there's no way to replace `IResponseCache` and in the implementation of it (`MemoryResponseCache`), the async methods are just a wrapper on sync methods. So is it better that the output of the methods be ValueTask?

**Comment by javiercn** [comment]
@Kahbazi Thanks for contacting us.

That would be a breaking change, so even if we deemed useful we can't take it until our next major release.

I'm closing the issue as we wouldn't take a change like this unless there is a clear scenario with performance measurements that justify the change.

/cc @anurse

**Comment by Kahbazi** [comment]
Is it a breaking change when both IResponseCache and MemoryResponseCache are internal?

**Comment by anurse** [comment]
Yeah, I'm not clear on what the breaking change issue is. @javiercn can you elaborate? Of course, it doesn't mean for sure that we'd do this change, but I don't think there's a breaking change concern since the type is internal.

**Comment by Kahbazi** [comment]
On the second thought, if there's no plan for the exposing `IResponseCache` the methods could only be sync.

**Comment by anurse** [comment]
Given that right now the only implementation of `IResponseCache` is synchronous, and it's an internal interface, I think we'll keep this sync for now. If we find a need to either a) make `IResponseCache` public or b) make an async implementation, we can change the signature then.

**Comment by Kahbazi** [comment]
I'm little confused on why did you close the issue? 

>  I think we'll keep this sync for now

Do you mean that you want the `IResponseCache` to stay as is or do you want to remove the async methods on `IResponseCache`?

**Comment by anurse** [comment]
Oops, you're right, I misinterpreted that there are already async methods on it.

Having said that, since this is an internal interface, I think that unless we know of performance improvements from switching to ValueTask, it's probably not worth the cost of the change. If this were a public API then it might make more sense, even if we don't have specific perf data, because *some* implementations might be improved. Of course, if it were public, it would also be subject to concerns about breaking changes.

I suppose I'm still just not sure of the value of this change. I'm open to being convinced otherwise though :).

**Comment by anurse** [comment]
I suppose we could be clearer by dropping the async methods entirely. That change would make sense to me. The current implementation is sync-only anyway.

**Comment by Kahbazi** [comment]
> I suppose we could be clearer by dropping the async methods entirely. That change would make sense to me. The current implementation is sync-only anyway.

So should I remove the async methods?

**Comment by anurse** [comment]
That would seem to be reasonable. Assuming it doesn't break anything I've missed :).
