### ISSUE TITLE
Blazor - Identity UI features

### ISSUE THREAD

**Issue by postb99** [aspnet/AspNetCore#15061]
### Describe the bug
Can I use other pages for some sections of Identity UI without being forced to scaffold? (create my own pages starting from Identity logic/code). The MVC scaffold doesn't accomodate a blazor server app.
Why, after changing  asp-page="/Account/Manage/Index" target in _LoginPartial.cshtml, does the link still remain the same?

### To Reproduce
1. Create a work Blazor Server App
2. Edit _LoginPartial.cshtml and change account management path ("asp-page"), create the corresponding Blazor page
3. Login with an user (in my case external provider login)
4. See "Hello UserName" in the top nav, click onto the link

### Expected behavior
Redirection to /Account/MyManager" and not anymore to "/Account/Manage/Index"

### Screenshots
-

### Additional context
Blazor Server + .net core 3

Thanks,

**Comment by javiercn** [comment]
@postb99 Thanks for contacting us.

If I'm understanding this correctly, are you trying to replace parts of the identity UI with "server-side blazor" versions? If that is the case, that is not possible.

If you are simply trying to replace the logic in some page provided by the Identity UI, then that's possible.
* Identity UI is simply a Razor Class Library, so you can place any page on the same path within your project and it will override the page from the library. 
  * I would recommend though, that you scaffold the individual page as a starting point, that way you get to understand the logic before replacing it with your own implementation, this is important because some authentication flows rely on pages passing through some parameters like the return url, etc.
* You can find more information about scaffolding identity UI pages here https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization.


>Why, after changing asp-page="/Account/Manage/Index" target in _LoginPartial.cshtml, does the link still remain the same?

This is likely to the fact that Identity is inside an area. For more information about how areas work with razor pages take a look at:
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.0#areas-with-razor-pages
