### ISSUE TITLE
blazor (server side) javascript interop: Javascript fails because code must run as user-initiated

### ISSUE THREAD

**Issue by Henk7** [aspnet/AspNetCore#15109]
I am running into a problem writing data into the clipboard using server-side blazor. The library https://github.com/lgarron/clipboard-polyfill fails to write a text to clipboard after a button press using server-side blazor under firefox V69, but is works under chrome V77.

With a plain old javascript html page without blazor the clipboard write works in firefox and chrome.

I assume that firefox has the security requirement that clipboard manipulation must happen in code flagged as "user-initiated".

Because server-side blazor goes from user-initiated javascript to server side c# to websocket-event javascript, the "copy to clipboard" javascript code is not flagged as "user-initiated" anymore.

Is there a official way or hack in blazor to execute javascript interop code with the "user-initiated" flag on?

Repo with example: https://github.com/Henk7/BlazorJSUserInitiatedPermission

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Henk7.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
> Is there a official way or hack in blazor to execute javascript interop code with the "user-initiated" flag on?

This is a tricky area and is unfortunately beyond the control of Blazor. As you've observed, this is a browser-implemented deliberate limitation.

To satisfy the browser's requirements, you may need to trigger the clipboard JS call from JS code rather than .NET code, so that it can run synchronously.

If you wanted to have a textbox plus a button that copies the contents of some .NET-generated version of that text to the clipboard, then you might need to implement it like this:

 * Have an `@oninput` event handler on the textbox. In your .NET event handler, take whatever value is being typed and output the .NET-generated version of that text onto some `data-something` attribute on that same textbox. So, the DOM will always contain the text that you *might* copy to the clipboard.
 * On the button that copies to the clipboard, put a JavaScript `onclick` event handler that takes the `data-something` value and copies it to the clipboard. This way, the actual clipboard API call will run synchronously on click.

I know it's inconvenient. There are very few scenarios where this limitation applies, but I'm afraid that clipboard is one of them.
