### ISSUE TITLE
How do you add databinding to dynamic components?

### ISSUE THREAD

**Issue by Joebeazelman** [aspnet/AspNetCore#15164]
`RenderFragment` doesn't appear to support data binding from the parent component.  If it's supported, I haven't seen any examples or documentation on it.  The little that I've been able to find suggests using AddAttribute, but there's numerous incarnations and it's unclear what they do and how they differ.  Also, it's unclear whether AddAttribute literally adds another attribute, uses one already defined, or both for the component being rendered. 

There should be two methods:
AddParameter()
BindToParameter()

AddAttribute is confusing because it's unclear whether you're you're talking about markup or code.

```
@foreach (var designObject in ToolService.DesignObjects)
{
    Console.WriteLine("Binding MouseCoordinate to DesignObject...");
    RenderFragment renderFragment = builder =>
    {
        builder.OpenComponent(0, designObject.GetType()); 
        builder.AddAttribute(1, "Coordinate", designObject.Coordinate);
        builder.CloseComponent();
    };
    <div>
        <div>Before the component</div>
        @renderFragment
        <div>Afterthe component</div>
    </div>
}

```

**Comment by javiercn** [comment]
@Joebeazelman Thanks for contacting us.

There is no concept of Parameter in the RenderTree API, there are only attributes on it.

If you are referring to `@bind` that is a syntactic sugar provided by Razor to define two attributes. One attribute that provides the value to the component, typically
```csharp
builder.AddAttribute(1, "Coordinate", () => designObject.Coordinate))
```
And another attribute that handles the change event.
```csharp
builder.AddAttribute(2, "change", newValue => designObject.Coordinate = newValue);
```
(This is all pseudo-code, it's a bit more complicated under the hood).

Otherwise, the basic overload for AddAttribute should be enough.

**Comment by Joebeazelman** [comment]
In the last example you provided, it's interesting to know how Blazor handles Coordinate which is a struct Auto-property. Since structs are value types, it would be interesting to see how it handles this case.
