### ISSUE TITLE
RenderFragment ignores component's initialized values

### ISSUE THREAD

**Issue by Joebeazelman** [aspnet/AspNetCore#15161]
`RenderFragment` ignores my initialized values.  In the following code, everytime there's a mouse click, a new object is created with the mouse coordinates where the click occurred.  During the rendering section in razor, the markup is generated as expected, but the `Coordinate` parameter is zero. The `CustomText` doesn't have this issue.

This is clearly a bug since it is unexpected and inconsistent. On a side note, why is `RenderFragment` emitting ""?

```
<div><!--!-->
        <!--!--><div>Before the component</div>
        <!--!--><!--!--><text x="0" y="0">Custom Text</text><!--!-->
        <!--!--><div>Afterthe component</div>
    </div>
```

```
TextDesignObject.razor
-----------------------
@Markup

@code
{
        public MarkupString Markup { get; private protected set; }

        public string Style { get; set;  }
        private PointF _coordinate;
        [Parameter]
        public PointF Coordinate { get => _coordinate; set { Console.WriteLine("Coordinate setter called");  _coordinate = value; } }

    public string CustomText { get; set; } = "Custom Text";
    public string FontStyle { get; }

    protected override void OnInitialized() {
        var svgString = new string("<text x=" + Coordinate.X + " y=" + Coordinate.Y + ">" + CustomText + "</text>");
        Markup = new MarkupString(svgString.ToString());
    }
}

Designer.razor
---------------
@foreach (var designObject in ToolService.DesignObjects)
{
    Console.WriteLine("Binding MouseCoordinate to DesignObject...");
    RenderFragment renderFragment = builder =>
    {
        builder.OpenComponent(0, designObject.GetType()); 
        builder.CloseComponent();
    };
    <div>
        <div>Before the component</div>
        @renderFragment
        <div>After the component</div>
    </div>
}


@code {
    [Parameter]
    // Create a new design object based on selected tool
    private void OnDesignPanelClicked(MouseEventArgs e)
    {
        Console.WriteLine("CallingCreateDesignObject...");
        var designObject = ToolService.SelectedTool.CreateDesignObject();
        if (designObject == null) return;
        
        Console.WriteLine("Setting design object to mouse coordinates.");
        designObject.Coordinate = new PointF((float) e.ClientX,  (float) e.ClientY);
        Console.Write(designObject.Coordinate);
        
        Console.WriteLine("Adding new DesignObject");
        ToolService.DesignObjects.Add(designObject);
    }
}

```

**Comment by javiercn** [comment]
@Joebeazelman Thanks for contacting us.

You are not passing in the designObject instance in the render fragment, you are only passing the type.
The coordinate is the default value because you are not passing it as a parameter inside the RenderFragment (which would be the appropriate way to do it).
The text is set in the property setter to a default value and its not defined as a parameter, so its value will always be constant.

You can't pass in a component instance directly in Blazor as that breaks the Blazor rendering model where Blazor itself is responsible for the lifecycle of the components.

To achieve your scenario I suggest you separate your component from your component model and iterate over the list of component models and pass in the parameters to the underlying components from the associated component model.

I would also suggest (based on what I infer you are trying to do, that you give each component a unique identity using `@key=componentModel.key` which will help the renderer produce a better result according to what you are trying to implement.

I would also discourage you from using `MarkupString` directly as that will open an attack vector for XSS.

```
Designer.razor
---------------
@foreach (var designObject in ToolService.DesignObjects)
{
    RenderFragment renderFragment = builder =>
    {
        builder.OpenComponent(0, designObject.ComponentType);
        builder.SetKey(designObject.Key);
        builder.AddAttribute(1, designObject.Coordinates);
        builder.CloseComponent();
    };
    <div>
        <div>Before the component</div>
        @renderFragment
        <div>After the component</div>
    </div>
}
```

**Comment by javiercn** [comment]
Closing the issue as the behavior is by design and not a bug.

**Comment by Joebeazelman** [comment]
Thanks Javier.  My code is based on what I could find on the web.  It didn't make any sense to me either. I was merely trying to dynamically create a list of polymorphic components.  It was unclear whether Blazor supports it or not, but now it's settled. So dynamic creation isn't supported as a first class citizen as I was expecting.
