### ISSUE TITLE
Wrong result using InvokeAsync

### ISSUE THREAD

**Issue by YordanYanakiev** [aspnet/AspNetCore#15254]
### Describe the bug
While trying to send an array of objects from Blazor Client Side project to JavaScript using InvokeAsync - I am actually receiving only 1 object from the array.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.'
2. Run this code 
```

@inherits LayoutComponentBase
@inject IJSRuntime JsRuntime;

<div class="main">
    <div class="top-row px-4">
        <button @onclick="IncrementCount">Click me</button>
    </div>
</div>


@code
{


    private async void IncrementCount()
    {
       
        List<object> cc = new List<object>();

        for( int c = 0; c < 100; c++ )
        {
            cc.Add( new { cccc = c, dfddd = 45, dsfdsf = 54 } );
        }

        Console.WriteLine( cc.ToArray().Length );

        await JsRuntime.InvokeAsync<object>( "sendData", cc.ToArray() );
    }
}

```
**xxxx.js**
```
function sendData( e ) 
{
    console.log(e);    
}

```

3. See error - the console will show only 1 object, not the array

### Expected behavior
To receive the full array of objects

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @YordanYanakiev.
We'll investigate this as soon as we get to it and update this thread.

**Comment by javiercn** [comment]
This is not an issue.

`InvokeAsync` has the following signature `TResult InvokeAsync(string, params object[])` you are passing an array to it, which gets interpreted as individual objects.

When we invoke the JS function we apply the arguments to it, and in your case your function is
```js
function sendData( e ) 
{
    console.log(e);    
}
```

Which binds only the first argument (first element of the array) to the variable e. If you change your function for
```
        function sendData(e) 
        {
            console.log(arguments.length);    
        }
```

you'll see all arguments are there.

You can either keep your code the same and use the arguments "array-like" variable to get to the data or you can wrap the array within an array, which is what should do.

InvokeAsync takes an array of arguments where each element in the array is passed as a parameter to the js function being invoked. The pitfall here is that you are passing an object array and the compiler thinks you are providing the arguments to the function as an array directly (and unwraps tem). If you want to pass an array as an argument to a JS function, it needs to be wrapped within the arguments array. So
```
        await JsRuntime.InvokeAsync<object>( "sendData", new[] { cc.ToArray()} );
```
This only happens because the value being passed in is exactly an object[] instance. In any other cases this should not be a problem, as the compiler will do the appropriate wrapping.

**Comment by YordanYanakiev** [comment]
Good lords. I haven't expected this kind of complexity, since normal logic will point that
 **await JsRuntime.InvokeAsync<object>( "sendData", cc.ToArray() );**
or 
 **await JsRuntime.InvokeAsync<object[]>( "sendData", cc.ToArray() );** 
to be a working solutions.
Thank You kindly for the reply. I will have to study the this ideology seems like.

**Comment by javiercn** [comment]
@YordanYanakiev It's an unfortunate edge case, it only happens with `object[]`. The trade-off is that otherwise you would always have to wrap parameters in an array explicitly.

The generic argument refers to the expected return type of `InvokeAsync`. You can use `InvokeVoidAsync` to avoid having to specify a type parameter if your JS function doesn't return anything.

**Comment by YordanYanakiev** [comment]
Oh. I see. Then it's fine I'll just keep this in mind.
Thank You very much for the clarification and spend time ! :)
