### ISSUE TITLE
Unwanted resources at the output folder

### ISSUE THREAD

**Issue by nefcanto** [aspnet/AspNetCore#15255]
# Describe the bug
I have not used resources in the entire ecosystem of my applications. But when I build my API app, which uses some other libraries of Microsoft and our company's base libraries, I see a couple of country-specific resources being copied to the output directly.

And when I go inside them I see these two files:
`
Microsoft.CodeAnalysis.CSharp.resources.dll    
`
` 
Microsoft.CodeAnalysis.resources.dll
`

How should I get rid of them? How should I know why are they produced at all?

### To Reproduce
It doesn't happen for a single isolated app as I tested. Thus I can't reproduce its steps for my ecosystem. I just know that we do not use Microsoft's way of resource files for globalization. In fact, we are a mono-lingual mono-cultural app.

### Expected behavior
I want the output folder to be clean of French or German or other resources that are not related to us.

### Screenshots
![Capture](https://user-images.githubusercontent.com/12782347/67266404-0e742600-f4bd-11e9-8a8c-3b59039bf5a2.PNG)

### Additional context
dotnet --info results:
![Capture2](https://user-images.githubusercontent.com/12782347/67266464-306da880-f4bd-11e9-824d-51e5d4ff6387.PNG)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You get these because you use transitively reference `Microsoft.CodeAnalysis.CSharp` and `Microsoft.CodeAnalysis` packages likely through the runtime compilation package. You can either remove runtime compilation (if you don't need it), or simply delete the files.
Alternatively, you can reference the runtime compilation package conditionally for `Debug` configuration only. That way your `Release` folder will not have these.
