### ISSUE TITLE
JSON input formatter exceptions should log error not debug

### ISSUE THREAD

**Issue by scottsauber** [aspnet/AspNetCore#15272]
### Describe the bug

Currently when a JSON parsing error occurs, the log level is set to Debug.

See: https://github.com/aspnet/AspNetCore/blob/c39fbb8f12002f61df6c093b0c11e6bd585ee202/src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonInputFormatter.cs#L131

I think this should be set to Error, because this is a critical exception that happens.  Otherwise, this ends up being a silent exception in our application until we turn on the log level to Debug.

In our application, we are upgrading from 2.2 to 3.0.  In 3.0, the new System.Text.Json API's do not convert a string to an integer automatically, like JSON.NET did (see: https://github.com/dotnet/corefx/issues/39473).  We have a React SPA front-end and a ASP.NET Core backend.  The React app is incorrectly sending back a string when it should be an integer, this is wrong and therefore we'd like a way to easily discover these scenarios instead of turning on the Debug Log Level and parsing through all the Debug logs.

### To Reproduce

1. Using this version of ASP.NET Core 3.0
2. Let me know if you need a repro or if you can deduce the problem from the link to the `SystemTextJsonInputFormatter` above

### Expected behavior

Expect that when a `System.Text.Json.JsonException` during parsing that it logs an Error not a Debug message.

### Screenshots
![Screenshot](https://i.imgur.com/lft320b.png)

**Comment by pranavkm** [comment]
Thanks for the issue report @scottsauber. JSON exceptions are recorded in the ModelStateDictionary. If you're using an `ApiController` this should result in an invalid model state response  - a 400 error code that contains a `ValidationProblemDetails` payload. See https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.0#automatic-http-400-responses. If you aren't using an `ApiController`, you should inspect the `ModelStateDictionary` in your controllers before processing the request data.

```C#
public IActionResult Post([FromBody] MyModel model)
{
    if(!ModelState.IsValid)
    {
        return BadRequest();
    }
    ...
}
```

The response should enough content for the client to be able to identify that the input was invalid including hints to what was problematic.

In general, the `Error` severity is reserved for errors that the server was unrecoverable server errors, the ones that result in a 500 response. Logging malformed client input as errors is problematic since it opens the opportunity for a malicious client to overwhelm the server's error logs by spamming it with bad data.
