### ISSUE TITLE
This is still broken on  16.4.0 Preview 2 :: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' 

### ISSUE THREAD

**Issue by mjlant** [aspnet/AspNetCore#15282]
I have seen several issues raised with what appear to be the same cause.

I am simply trying to createa a new Client-Side Blazor app using the Visual Studio Wizard in both most recent versoions of VS 2019 and VS 2019 Preview as well as from the CLI.

I have tried updating everything that I can find in the threads here and in the MS guidance pages that are available. In total, about four hours of hacking my way through a number of issues and I don't think I am any closer to being able to just simply begin working on an app.

As an aside, I have faith that someday all of this will be fixed, but I have been trying off and on for the last six months to experiment with Blazor and I have only once been able to create a Blaozr app and that was about four months ago. It seems that every time I simply try to create an app, there is a mismatch of something and I can't build it. I have never found the process of creating a Blazor Web App to not be broken in some fashion.

So I am stuck. Does anyone have any ideas how I can start building an app? Right now, I would be happy with a .zip file containing a buildable version of the basic demo app that is supposed to be generated when creating a new Blazor app.

**Comment by javiercn** [comment]
@mjlant Thanks for contacting us. 

Lets see if we can get you unblocked. A few things to help you troubleshoot this type of issues are, first making sure you have compatible versions of .NET Core and client-side Blazor.
You can check the version of the templates you have installed by running
```console
dotnet new -u | select-string Microsoft.AspNetCore.Blazor -Context 10
```

It will give you something like 
```console
>   Microsoft.AspNetCore.Blazor.Templates
      Details:
>       NuGetPackageId: Microsoft.AspNetCore.Blazor.Templates
        Version: 3.1.0-preview1.19508.20
        Author: Microsoft
      Templates:
        Blazor WebAssembly App (blazorwasm) C#
      Uninstall Command:
>       dotnet new -u Microsoft.AspNetCore.Blazor.Templates
```

You can run `dotnet --info` to see what SDKs and frameworks you have available on your machine. for example:
```console
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I'm using the latest Blazor templates available on Nuget and the 3.1.0-preview1 SDK. With those two, you should be able to run `dotnet new blazorhosted` and create a new "clean" Blazor template, compile it and run it. The visual studio version that I'm using is 16.4.0 preview 2 (just in case you want to get everything matching).

If you still run into issues after these steps, please add them to the issue so we can help you further.

Hope this helps

**Comment by javiercn** [comment]
We are closing this issue as there's not been any community involvement in the past few days and we believe the question has been answered.

**Comment by MichaelLant** [comment]
I am sorry for the belated response. Too much going on for the last two weeks and I have been unable to touch this. Please note that I am not using the same account as my initial message.

I don't know what this command is: dotnet new -u | select-string Microsoft.AspNetCore.Blazor -Context 10

I am an IDE orientd person, not a CLI person, so I have much to learn. Am I supposed to subsititued something for "select-string". If so, what?

Here is the output of the second command.

```
C:\Users\Michael Lant>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I updated VS 2019 the other day with the latest Blazor templates per the the VS update notifications in the IDE.

Using VS 2019 Preview, with the latest updates applied, here is what I get when I use the IDE to start a Blazor WASM project.

![image](https://user-images.githubusercontent.com/689502/68076244-90e7ca00-fd88-11e9-9a43-8f248641490e.png)

Shouldn't it be creating a .Net Core 3.x based application?

Use VS 2019 Pro and the Blazor templat (found by typing Blazor) into the search box, I get a nimimal Blazor app that won't run because of this:
![image](https://user-images.githubusercontent.com/689502/68076330-8bd74a80-fd89-11e9-8786-bd40524e53b9.png)

So I am still, very much stuck.

**Comment by MichaelLant** [comment]
With hope in my heart, today I installed the latest VS 2019 Build per this article today: `https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-2/`

I installed the latest .Net Core SDK from here: ` https://dotnet.microsoft.com/download/dotnet-core/3.1`

And I tried to install the latest Blazor templates from here: `https://docs.microsoft.com/en-ca/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio`

Initially I received an error about not being able to find the templates in the Telerik Nuget repo. This sort of thing has been an ongoing set of problems for me with VS and the Telerik Nuget repo. I went into VS and disabled the Nuget repo from the Nuget Package Manager interface. Running the command line again yielded this:

`C:\Users\Michael Lant>dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview1.19508.20
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  The content at 'https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0' is not valid XML.
    For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
  Restore completed in 1.12 sec for C:\Users\Michael Lant\.templateengine\dotnetcli\v3.1.100-preview2-014569\scratch\restore.csproj.
`
Creatinga new Blazor client side app caused all of the same problems as I have noted in previous messages.

Next I went into the app shell that was created and tried to update the Blazor Nuget packages. Updating those packages worked, but I ended up with an entirely different set of errors.

![image](https://user-images.githubusercontent.com/689502/68159804-7d6f6700-ff20-11e9-96e3-296edcf08350.png)

I still can't get to even a simple project that I can build and run. Also, still a complete no-go using VS 2019 non-preview to create a Blazor client app.

Any ideas?

Is there a simple Blazor Hello World app that I can pull so that I can at least get started on learnign something untill these installation and configuration issues are resolved.

**Comment by javiercn** [comment]
@mjlant Thanks for trying it out.

I'm not sure what can be happening with your environment. I think that the blazor template didn't get correctly installed.

I've created two solutions for you with the latest nightly packages.
[BlazorHosted.zip](https://github.com/aspnet/AspNetCore/files/3808707/BlazorHosted.zip)
[BlazorWasmStandalone.zip](https://github.com/aspnet/AspNetCore/files/3808708/BlazorWasmStandalone.zip)

You need to add this feed to your nuget config
```
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-windowsdesktop" value="https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json" />
    <add key="aspnet-aspnetcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json" />
    <add key="aspnet-aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
    <add key="aspnet-entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
    <add key="aspnet-extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
    <add key="gRPC repository" value="https://grpc.jfrog.io/grpc/api/nuget/v3/grpc-nuget-dev" />
    <add key="blazor" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1/nuget/v3/index.json" />
  </packageSources>
</configuration>
```
Get the latest nightly SDK from here https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/3.1.1xx/dotnet-sdk-latest-win-x64.zip
Unzip it into a folder and set the following environment variables

```console
$env:DOTNET_ROOT: <<path-to-unzipped-dotnet>>
$env:DOTNET_MULTILEVEL_LOOKUP: 0
$env:Path: <<path-to-unzipped-dotnet>>
```

From that terminal you should be able to do `dotnet run` on the command line and start visual studio from the command line by typing in the path to the solution and pressing enter.

I just tried this on a VM that I have and validated that both work.

**Comment by javiercn** [comment]
Better yet, these are two preview2 templates I created on a clean VM, you shouldn't need any of the above points to restore and run these applications. Give them a try.

[BlazorStandalonePreview2.zip](https://github.com/aspnet/AspNetCore/files/3810594/BlazorStandalonePreview2.zip)
[BlazorHostedPreview2.zip](https://github.com/aspnet/AspNetCore/files/3810595/BlazorHostedPreview2.zip)

**Comment by MichaelLant** [comment]
Thanks Javier. I really appreciate you taking the time to do this. I will work with them tonight.

**Comment by MichaelLant** [comment]
So, some progress...

I opend the Standalone version in VS 2019 Preview. Running it the first time caused my machien to Blue Screen. I restarted the machine and ran it with only VS running. This time it ran, but this is what is presented in the browser:

![image](https://user-images.githubusercontent.com/689502/68261634-bb4ab900-000e-11ea-9344-c3b0d136c031.png)

Pressing on the Reload button causes this to be displayed:


![image](https://user-images.githubusercontent.com/689502/68261574-8e96a180-000e-11ea-9c3e-63a519c29f36.png)

I seem to get a range of result when I run it. Sometimes I see the image above and it shows after I have clicked on the Reload button. Other times, I don't see the Reload button, and instead, I see the following.

![image](https://user-images.githubusercontent.com/689502/68261967-c7834600-000f-11ea-9b63-b2e21788473f.png)

So at least I can build and launch, which is a definite improvement.

**Comment by javiercn** [comment]
> Using VS 2019 Preview 3, I opend the Standalone solution. Running it the first time caused my machine to Blue Screen

I'm not even sure how this is possible, but I think its very likely to be completely unrelated to blazor.

I'm surprised by what you described. I don't know what series of installs/updates your machine has gone through to be in such state. I can't even think where things could have gone wrong. 

As I said, this is very surprising to me as I have installed 5 different VS versions on my box and I haven't ever run into that much trouble.

We will be working on stabilizing Blazor-wasm in the future, so things will get easier, as for example we will likely target a stable .NET version on the server.

The templates can be tricky, one drastic option is to completely delete the `~/.templateengine` folder from your machine as that would cleanup all templates. (I'm saying this for future reference).

The failures you are observing (the 500) and similar are likely due to something going wrong in the compilation. I haven't seen it before as I said, but that's an area that will likely change in the future.

I'm glad that you are unblocked, I'm closing this issue as we don't have any further action to take here.

**Comment by MichaelLant** [comment]
I was very surprised to see the blue screen as well. I have a very stable high end Dell laptop with 32GB of memory. I used it 60+ hours per week and I have never once had it blue screen on me other than sometimes when waking up from Sleep or Hibernate. That problem seems to be an ongoing cat and mouse game between Microsoft and Dell where sometimes new OS updates from MS introduce the behaviour and Dell scrambles to figure out how to fix the problem - sometimes with a BIOS update. Other than that, never a single Blue Screen. Most likely not related, but nonetheless a curious coincidence.

I couldn't possibly recount for you all of the installs, uninstall, updates and such that I have done with VS since I started using this machine with VS 2015. Something sure got messed up though. I currently have installed: VS 2017 Pro and Community, VS 2019 Pro and Preview. I have also had VS 2015 and VS 2017 Enterprise versions as well as previews for VS 2017. I have performed several repairs, uninstalls and reinstalls for most of those versions in attempts to fix things that have somehow become mangled at some point. In general, my experience with uninstalls is that they never really clean up properly or completely. Somewhere along the line, something seems to have been upset that made my use of Blazor Standalone impossible. And somehow, building the Hosted version fixed it. But this too, could be a random, but seemingly related thing, just like the blue screen.

The important thing (for me at least) is that I can now work with Blazor and I am looking forward to an evolving and increasingly stable environment in which to develop Blazor apps.

Thanks again for your help. I would be out of options if not for your help.
