### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation should default add to when using dotnet run 

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore#15281]
In https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0, Runtime compilation is everyone should used features when to development with MVC and Razor Page, It should be default

**Comment by javiercn** [comment]
@TangMonk Thanks for contacting us.

Runtime compilation is mainly a development productivity feature that adds additional dependencies to the app that increase the size in a non-trivial way, which affect the size of the deployed app when this is not a feature that is normally used in production scenarios.

For that reason is not enabled by default and it is unlikely we will do so.

**Comment by TangMonk** [comment]
thanks, I think nuget should support load dependency for different environment, just like `Bundler`, or `npm`
