### ISSUE TITLE
Custom DataAnnotation ValidationAttribute error message is not showing

### ISSUE THREAD

**Issue by PKYADAV** [aspnet/AspNetCore#15301]
**Model Definition:**
        
        [DbRequired]
        [Display(Name = "USER NAME", Prompt = "ENTER USER NAME")]
        public string User_Name
        {
            get { return GetValue(() => User_Name); }
            set { SetValue(() => User_Name, value); }
        }

        [Display(Name = "PASSWORD", Prompt = "ENTER PASSWORD")]
        [DataType(DataType.Password)]
        [DbRequired]
        public string User_Password
        {
            get { return GetValue(() => User_Password); }
            set { SetValue(() => User_Password, value); }
        }

**ValidationAttribute:**

public class DbRequired : RequiredAttribute
    {
        DataContext db;
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
                if ((value == null || value.ToString() == string.Empty || value.ToString() == "0"))
                {
                    return new ValidationResult("USER NAME IS REQUIRED FIELD !");
                }
                else
                {
                    return ValidationResult.Success;
                }
        }
    }

When using builtin **Required** then working fine but when overriding **RequiredAttribute** then error message not displayed:
![image](https://user-images.githubusercontent.com/4301382/60683555-f64cac80-9eb5-11e9-9bdf-8fdd4d935105.png)

**Comment by pranavkm** [comment]
@PKYADAV, copying my comment from https://github.com/aspnet/AspNetCore/issues/10643#issuecomment-543909748

As noted in https://github.com/aspnet/AspNetCore/issues/10643#issuecomment-520236208, on a form submit Blazor's `DataAnnotationsValidator` fails to record validation results that are not associated with a member. `CompareAttribute` does this which results in the buggy behavior you're seeing here.

In 3.1, we're doing a couple of things to address this:

1) Validation results without members now get associated with the model instance. In addition we've added support to `ValidationSummary` to print error messages that are specifically associating with the model. You should be able to do something along the lines of 

```razor
<EditForm Model="myModel" OnValidSubmit="OnSubmit">
    <DataAnnotationsValidator />
    <InputText Name="Password" /> <ValidationMessage For=@(() => myModel.Password)" />
    <InputText Name="ConfirmPassword" /> <ValidationMessage For=@(() => myModel.ConfirmPassword)" />    

    <ValidationSummary Model="myModel" />
    <button class="btn btn-danger" type="submit">Submit</button>
</EditForm>
```

The `ValidationSummary` would additionally display messages produced from models implementing `IValidatableObject` or using custom `ValidationAttribute` \ `CustomValidationAttribute`.

2. In addition, for the 3.1.0-preview2 release, we plan on introducing an experimental package - `Microsoft.AspNetCore.Components.DataAnnotations.Validation` - with an `ComparePropertyAttribute` that behaves like a `CompareAttribute` but produces a valid `MemberName`. It should be a drop in replacement to `CompareAttribute`. Users in 3.0 should be able to copy the type in to their app to resolve the error they're seeing here. Here's the source: https://github.com/aspnet/AspNetCore/blob/c298c94fe1113b64474a3d5fcdef487f02c74991/src/Components/Blazor/Validation/src/ComparePropertyAttribute.cs

This package is marked experimental since our plan is to roll these changes in to CoreFx as part of the 5.0 milestone. Hope this helps.
