### ISSUE TITLE
Passing a JSON string to a custom element in client-side Blazor fails

### ISSUE THREAD

**Issue by ChristianWeyer** [aspnet/AspNetCore#15377]
.NET Core SDK (3.1.100-preview1-014459)
VS 2019 16.4.0 Preview 2.0

Using a web component like Good Map (https://www.webcomponents.org/element/keanulee/good-map) we can simply pass a JSON string for config options into the custom element.
Like this:
https://github.com/thinktecture/blazor-experiments/blob/master/BlazorAppIntegrationDemo/BlazorAppIntegrationDemo/wwwroot/map.html#L21

If using the custom element in a Blazor component like this:
https://github.com/thinktecture/blazor-experiments/blob/master/BlazorAppIntegrationDemo/BlazorAppIntegrationDemo/Pages/Map.razor#L13

... we get an error:
![image](https://user-images.githubusercontent.com/888718/67505391-6fe9ef80-f68b-11e9-8cdf-66f905ef1d5c.png)

Attaching the Chrome debugger we can clearly see what happened:
![image](https://user-images.githubusercontent.com/888718/67505551-c5be9780-f68b-11e9-9d99-f18b7dbd8efd.png)

The expected behavior would be to get the entire JSON string passed in.

Thanks.
-Christian

**Comment by javiercn** [comment]
@ChristianWeyer thanks for contacting us.

I believe the the attribute is likely being HTML encoded.

**Comment by ChristianWeyer** [comment]
Hi @javiercn - will this be changed/fixed? Or how should we handle this?
Thanks!

**Comment by ChristianWeyer** [comment]
If you point me at the code (at least at the area where to look for it) I might look at it if there are viable solutions possible.
Thanks @javiercn

**Comment by javiercn** [comment]
@ChristianWeyer I've confirmed this is an encoding problem. 

I believe this is by design to protect against XSS, but I'll have a chat with the rest of the team to confirm we are doing the right thing here.
For now, I've confirmed that if you HTML encode things it works. Here is a simple sample

```html
<div data-something="{ &quot;json&quot;: &quot;encoded&quot; }">Hello</div>
````

![image](https://user-images.githubusercontent.com/6995051/67556540-38e5ff00-f6c8-11e9-8ade-b8c2bad2bc4f.png)

I believe you need to use double quotes (single quotes is a JS thing, not a JSON thing I believe).

**Comment by ChristianWeyer** [comment]
This works, yes.
Thanks @javiercn for the follow-up to check internally!
