### ISSUE TITLE
How to use azure feature flag in asp.net core Blazor

### ISSUE THREAD

**Issue by ajai1109** [aspnet/AspNetCore#15592]
How to use azure feature flag in asp.net core Blazor

**Comment by javiercn** [comment]
@ajai1109 thanks for contacting us.

Can you provide a bit more details on what you are trying to achieve? We're not sure what "azure feature flag" means in this context.

**Comment by ajai1109** [comment]
I am trying to implement azure feature flags in asp.net core blazor project. Please go through this link https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core for your reference

**Comment by javiercn** [comment]
@ajai1109 There's no specific support on Blazor to do that, and that's not something that the ASP.NET Core team works on.

@bradygaster Can you loop in the right people here so that we can provide guidance or improve the experience for Blazor users?

To get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by danroth27** [comment]
This issue was moved to Azure/AppConfiguration#170
