### ISSUE TITLE
Add compiler error if there's a <script> element inside a component

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#16218]
This addresses a usability issue. We often hear of people trying to put `<script>` elements inside components and being surprised about the effects.

It's almost always a mistake to put a `<script>` element inside a component, because fundamentally, components are about adding and removing things dynamically inside the DOM. `<script>` elements don't work that way, in that once they are added, their effects can never be removed. Similarly, trying to use C# expressions inside a `<script>` content will not work as expected (we can't replace the effects of already-registered JS once the expression changes value). The *only* scenario I can think of where a `<script>` element does something vaguely useful inside a component would be for some kind of debug logging, e.g., `<script>console.log('rendering now')</script>`, but that's not what anyone's been doing AFAIK. What developers really should do is put `<script>` elements into their `index.html`, where they will behave as expected.

**Proposed solution**

We'll make it a compiler error to have `<script>` inside a Blazor component. The error message will say something like:

*Script tags should not be placed inside components because they cannot be updated dynamically. To fix this, move the script tag to the 'index.html' file or another static location. For more information see http://some/link*

... and the help docs that we linked to will also say something like:

*If you need to override this, add an attribute named "suppress-error" with value "BL9992" to the <script> tag, but only if you know what you are doing, as in most cases it would be a mistake to do this*.

**Comment by christostatitzikidis** [comment]
I would like the flexibility and the ability to easily choose. As simple as that.

**Comment by BrainSlugs83** [comment]
For anyone who understands the caveats of the original post, and still wants to do this (e.g. because you value encapsulation, or because of convenience, etc.), **beware**, adding a `<script type="text/javascript" suppress-error="BL9992">` (even an empty one) to your component will cause errors in blazor.server.js, (and I kind of doubt they plan to fix that). 🙄

### But *fear not*, for there's an easy workaround!

In your `Shared` folder, create a component named `ClientScript.razor`, and paste in the following contents:
```
<script type="text/javascript" suppress-error="BL9992">
    @script
</script>

@code {
    [Parameter]
    public RenderFragment script { get; set; }

    protected override bool ShouldRender() => false; // important!!
}
```
Then to use it, it's just
```
<ClientScript>
  <script>
    function MyFunction(id, a, b, c)
    {
      // do something
    }
  </script>
</ClientScript>
```
 - I opted to name the parameter `script` so that you would still get intellisense in Visual Studio, but no warning or error message.

 - The `ShouldRender() => false;` bit is what makes the javascript console error message go away. -- According to the documentation, your component will ALWAYS render the first time, but what this does is prevent it from trying to update the script element on the client (and that's what causes the Blazor.server.js error). -- So this is basically the meat of the solution. 🙂

You're welcome. 👍
