### ISSUE TITLE
Rendering raw HTML content

### ISSUE THREAD

**Issue by SvenEV** [aspnet/AspNetCore#16469]
I'm looking for a way to render raw HTML strings as part of a Blazor component. I tried the following, but like regular Razor, this escapes the HTML tags (so the output is literally the text `<p>Some text</p>` in a cyan div):

```HTML
<div style="background-color: cyan">@MyHtml</div>

@functions{
    public string MyHtml { get; set; } = "<p>Some text</p>";
}
```

Is there already something like `@Html.Raw(...)` in Blazor?

My use case: I have some markdown that is transformed to HTML by sending it to the GitHub API using an HttpClient. I'd like to display the generated HTML in my Blazor component.

**Comment by rvnlord** [comment]
Normally your `HTML helper` would return `IHtmlContent`, so just do this instead:

`public RenderFragment Render() => builder => builder.AddMarkupContent(0, _divIconContainer.IHtmlContentToString());`

    public static string IHtmlContentToString(this IHtmlContent htmlBuilder)
    {
        if (htmlBuilder == null)
            throw new ArgumentNullException(nameof(htmlBuilder));

        var sw = new StringWriter();
        htmlBuilder.WriteTo(sw, HtmlEncoder.Default);
        var htmlStr = sw.ToString();
        sw.Dispose();
        return htmlStr;
    }

and call it like this in your `Component.razor`:

`@Html.Icon(LightIconType.TachometerAltFast).Class(".my-menu-tile-icon").Render()`

Injecting html helpers into razor components is beyond the scope of this answer but if one got this far then one probably did it anyway.

Also dear Microsoft, Blazor is brilliant but do not discontinue support for @Html helpers completely, I find them far more useful then Tags (I prefer to work with C# instead of markup language and I know that a lot of people share this opinion).
