### ISSUE TITLE
Blazor. OnParametersSet fires not as expected

### ISSUE THREAD

**Issue by kpolkovnikov** [aspnet/AspNetCore#16583]
Hi. It's simply component.
**Index.razor:**
```
@page "/"

<MyCoolComponent>
    <Template>
        <div style="background-color:red;height:100px;width:100px;"></div>
    </Template>
</MyCoolComponent>

<button @onclick="DoNothing">Do Nothing</button>

@code {
    private void DoNothing(MouseEventArgs e)
    {

    }
}
```

**MyCoolComponent.razor:**
```
@msg
@Template

@code {
    [Parameter]
    public RenderFragment Template { get; set; }
    string msg;

    protected override void OnParametersSet()
    {
        msg =$"OnParametersSet of MyCoolComponent fires every time on click button on Parent Page, " +
                $"last time in {DateTime.Now.ToString()}. Why?";
    }
}
```

OnParametersSet event of MyCoolComponent fires every time on click button on Parent Page, why?

**Comment by javiercn** [comment]
@kpolkovnikov thanks for contacting us.

A new render fragment delegate gets created on each render (which happens automatically after the event-handler for `DoNothing` runs.

Blazor can't determine that the new RenderFragment delegate is equal to the old render fragment delegate and it believes the parameters for the component have changed, thus invoking OnParametersSet with the new RenderFragment instance.

@SteveSandersonMS can correct me if I'm wrong.

I'm closing this issue as the question has been answered.

**Comment by SteveSandersonMS** [comment]
You're right @javiercn.

Longer term I'm hoping we can find some optimizations where we detect common scenarios where the `RenderFragment` actually is the same. I would guess that if the delegate points to the same `MethodInfo` and `Target`, then it has to be the same. In the scenario posted here, since no variables are captured inside the closure, I would expect the `Target` values to be the same.

It's also possible that future C# compiler improvements will increase the range of cases where delegates are cached (it does this in a few cases already), so we may get some improvements automatically.

**Comment by kpolkovnikov** [comment]
Thank you for the supersonic answer) Is there a workaround in this scenario to prevent the OnParametersSet event from starting, such as by using @key or otherwise?

**Comment by SteveSandersonMS** [comment]
@kpolkovnikov You can override `ShouldRender` to put in custom logic to skip rendering if you think it's unnecessary in certain cases.

**Comment by kpolkovnikov** [comment]
Thank you so much, Steve.
