### ISSUE TITLE
Blazor javascript initialization

### ISSUE THREAD

**Issue by Condra963** [aspnet/AspNetCore#16628]
Hi all,

Can someone explain me why i need to specific call my javascripts that i want to initialize OnAfterRender? Why is there not something implemented that also calls the window load (javascript) or document ready (jquery) after rendering the component? Because now i always have to call each javascript i want to initialize in every blazor component and it's a bit 'annoying'.

This is how i do it now:
```
        protected override Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                return JSRuntime.InvokeVoidAsync("functions.init").AsTask();
            }

            return Task.CompletedTask;
        }
```

FYI: I do not us blazor as a single app implementation, i re-engineered my razor libraries to use blazor components on page that i want it to use. (If this is something necessary to know.)

Thanks for the help!

**Comment by javiercn** [comment]
@Condra963 thanks for contacting us.

I'm not sure what you are trying to accomplish. Are you trying to initialize some function globally? If that's the case you don't need to do anything inside OnAfterRender and you can simply call your initialization function inside the host page by including it on a script tag or by chaining to the promise returned from`Blazor.start`.

An alternative way to do this initialization is to put the logic on the top level App component. In the majority of apps, it only renders once, so that's a potential good candidate for global initialization logic.

The reason OnAfterRender needs to be used for invoking JavaScript is that it is the place where it is guaranteed that JSInterop is available. JS interop is not guaranteed to be available in other events like OnInitializedAsync and OnParametersSetAsync.

Here are some more detail about it.
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#detect-when-a-blazor-app-is-prerendering

In your case, I would if possible simply initialize the libraries/function before blazor gets initialized, and if not possible, just right after.

This snippet shows how to manually start blazor in case you need to initialize your scripts after the DOM is ready (the sample shows something else, but the pattern is the same)
https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#configure-the-signalr-client-for-blazor-server-apps

**Comment by Condra963** [comment]
You have for example bootstrap, when the HTML DOM is loaded, all bootstrap javascripts and all javascripts that you created will be loaded. But when i have elements inside my Blazor components that also needs to be initialized by these javascripts like hooking events and stuff like that i cannot use $(document).ready() of JQuery. I need to call the initlaization function specific for everything that i normally do when $(document).ready() is called.

```
$(document).ready(function () {
    // this is called when the DOM is loaded, but not when the blazor component is loaded.
    window.alertFunctions.init();
});

window.alertFunctions = {
    init: function () {
        // this always need to be called specific from the blazor component, because $(document).ready() is not recalled
        // Now we have to call all initializations of every component that normally will have events and actions initialized on $(document).ready()
        $('.alert').on('close.bs.alert', function(e) {
            e.preventDefault();

            $(this).removeClass('show');
            $(this).addClass('collapse');

            if (!$(this).hasClass('fade')) {
                return;
            }
        });
    },
    show: function(element) {
        for (var i = 0; i < arguments.length; i++) {
            window.alertFunctions.close(arguments[i]);
        }

        $(this).removeClass('collapse');
        $(element).addClass('show');
    },
    close: function(element) {
        $(element).alert('close');
    }
};
```

We have to initialize all events and actions like this:
```
protected override Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        return JSRuntime.InvokeVoidAsync("alertFunctions.init").AsTask();
    }

    return Task.CompletedTask;
}
```

**Comment by javiercn** [comment]
@Condra963 That's somewhat expected if you are wrapping a UI framework library with components.

A potential alternative to doing on the components would be to use the mutation observer API
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver to detect changes on the DOM and init the components at that point.

**Comment by Condra963** [comment]
@javiercn Ok, thanks for the alternative, yesterday i came up with the same thought that there should be another way to initialize it.

**Comment by Condra963** [comment]
@legistek well you can solve it with a simple solution. It's something simular that bootstrap uses.
```
$(document).on('DOMSubtreeModified', function () {
    // what you want to initialize
});
```

instead of

```
$(document).ready(function () {
    // what you want to initialize
});
```

This solved it for me.

**Comment by legistek** [comment]
Ahh, that should help too. Thanks @Condra963!

(But I still think it would make sense to have Blazor be able to run arbitrary JS when it's done with a render rather than have to use an event subscription).

**Comment by Condra963** [comment]
@legistek i don't think that's necessary because normally you would use $(document).ready() or something simular, you just replace it with $(document).on('DOMSubtreeModified'). This also would be requested if we would add and remove DOM elements with javascript directly instead of blazor.

I can be wrong, but i interprete it like this.
