### ISSUE TITLE
VS Code Razor syntax highlighting and intellisense not working

### ISSUE THREAD

**Issue by pheuter** [aspnet/AspNetCore#16669]
### Screenshot
![Annotation 2019-10-30 130044](https://user-images.githubusercontent.com/92698/67880818-c638b180-fb15-11e9-8c52-731f0a550720.png)

### Versions
* Visual Studio Code:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

* **ms-vscode.csharp** extension - 1.21.5
* ASP.NET Core using Blazor Server - 3.0.0

### Additional Context
Same ASP.NET Core Blazor Server app works fine with proper Razor syntax highlighting and intellisense in Visual Studio 2019 v16.3.7

**Comment by NTaylorMullen** [comment]
Hey @pheuter thanks for the report! Honestly shocked coloring was the only issue you encountered with remote development 😄 . We've yet to add full support for remote development and are tracking that work here: https://github.com/aspnet/AspNetCore/issues/14331

That being said, your issue would have reprod even outside of remote development and is due to our language grammar not being complete yet. We're tracking that work here: https://github.com/aspnet/AspNetCore/issues/14287

Closing this for now as a duplicate.
