### ISSUE TITLE
How to change the SignedOutCallbackPath?

### ISSUE THREAD

**Issue by BrianLytle** [aspnet/AspNetCore#16694]
I notice that the SignedOutCallbackPath is hardcoded in the AccountController. Is there a way to use a custom URL for the SignedOutCallbackPath?

**Comment by javiercn** [comment]
@BrianLytle thanks for contacting us.

Can you provide more details on what authentication you are using?

**Comment by BrianLytle** [comment]
Does this help? 

            services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                    .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));

**Comment by blowdart** [comment]
Can you scaffold the b2c controllers into your app, and then redirect from within that?

**Comment by BrianLytle** [comment]
@blowdart - That would be fantastic! However, I don't know how to do that. When you say "scaffold", that leads me to believe you are talking about an automated way to create the controllers.

**Comment by blowdart** [comment]
Hmm apparently you can't, that brings in normal identity. 

@HaoK do we own the B2C templates or does Azure?

**Comment by anurse** [comment]
Right now, your best bet would be to grab the content from GitHub and manually insert it into your app. You should be able to do this with *just* the `AccountController`, as long as you make sure it's in the `AzureADB2C` area, rather than having to take the entire UI. If that doesn't work you probably have to take the entire UI as code and not use the package.

We've already got plans to rethink these in 5.0 as part of https://github.com/aspnet/AspNetCore/issues/12626 .
