### ISSUE TITLE
Blazor WebAssembly debugging instructions have flipped the browser specific user data directory paths

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#16746]
With 3.1 P2 the instructions for Chrome point to the Edge path, and instructions for Edge point to the Chrome path:

![image](https://user-images.githubusercontent.com/1874516/68038623-9e695b00-fc87-11e9-9903-9fff403069a4.png)

**Comment by SteveSandersonMS** [comment]
As part of fixing this, we'd also like to change the behavior so that it only shows the Chrome instructions if you're on Chrome, and only shows the Edge instructions if you're on Edge.

And if you're on neither, it should say that your browser isn't supported (which I think is already the case, or at least it used to.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/17430
