### ISSUE TITLE
Partial view has different render results between views and pages

### ISSUE THREAD

**Issue by heku** [aspnet/AspNetCore#16772]
Per my understanding, partial view should have same render result for MVC Views and Razor Pages, but I found an exception here when not pass a `model` to partial.

I have a simple partial view as below:
```csharp
@model TestModel
<p id="my-partial-view">
    <h1>Views/Shared/_MyPartial.cshtml</h1>
    <h3>ViewData["Message"]: @ViewData["Message"]</h3>
    <h3>Model: @(Model?.ToString()??"Null")</h3>
</p>
```
The `TestMode`:
```csharp
    public class TestModel
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public override string ToString() => ID.ToString("N") + ":" + Name;
    }
```

Same render code in view and page:
```csharp
    @{
        ViewData["Message"] = "Hello, Partial";

        await Html.RenderPartialAsync("_MyPartial");
    }

    <partial name="_MyPartial" />

    @await Html.PartialAsync("_MyPartial")
```

The code in view works, but code in page display error below:

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'WebApplication1.MyRazorPageModel', but this ViewDataDictionary instance requires a model item of type 'WebApplication1.TestModel'.

I can fix this by
```csharp
@{
    ViewData["Message"] = "Hello, Partial";

    await Html.RenderPartialAsync("_MyPartial", (TestModel)null);
}

<partial name="_MyPartial" model="null" />

@await Html.PartialAsync("_MyPartial", (TestModel)null)
```

But seems it is a bug?

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```

**Comment by pranavkm** [comment]
@heku what version of MVC are you using?

**Comment by heku** [comment]
@pranavkm It is asp.net core 3.0 mvc

**Comment by javiercn** [comment]
@heku thanks for contacting us.

@ryanbrandenburg can you investigate this issue?

**Comment by ryanbrandenburg** [comment]
As you've discovered `PartialTagHelper` and `PartialAsync` take an optional "model" parameter. If this isn't provided it defaults to [`ViewData.Model`](https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.ViewFeatures/src/Rendering/HtmlHelperPartialExtensions.cs#L71). RazorPages create their own Model if one is not provided, where-as Views do not. So you run into this because the Partial code is trying to pass in the generated model type when it expects `TestModel`.

As you discovered you can avoid this by explicitly passing a model (even if it's null). You can also resolve this by setting the `@model` on the RazorPage so it doesn't create its own, or in the case you're no longer using the model on that partial by not doing `@model` within the partial.

I believe all of this is working as intended, but @pranavkm can double check my thinking.

**Comment by pranavkm** [comment]
Yup, that sounds about right. The pattern works pretty well when the page and the partial share the same model type, it allows accessing both `ViewData` and the model instance without having to do any additional work. This might be one of the few places where the behavior is a bit rough, but it's working as intended.

**Comment by heku** [comment]
It make sence, thank you for your clarification.
