### ISSUE TITLE
Blazor custom-reconnect docs do not appear to match actual behaviour

### ISSUE THREAD

**Issue by willdean** [aspnet/AspNetCore#16870]
### Describe the bug
The doc page https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0
contains a description of adding a `#components-reconnect-modal` element, and the way in which the framework will embellish the element with various state-dependent classes.  This includes
```
components-reconnect-hide – The client has an active connection, hide the UI.
```
It doesn't appear that this class actually is added in normal operation.  

### To Reproduce

* Add the following element to _host.cshtml in a s/s Blazor app
```
  <div id="components-reconnect-modal"> </div>
```
* Run the app so that it's operating correctly (i.e. it's connected)
* Use the browser's dev tools to inspect the `components-reconnect-modal` div you added.
* Observe that it has no added classes.  The docs imply it should have "components-reconnect-hide"
* If you stop the server, you can observe that the framework *will* correctly change the class of this element - it's just the initial condition which is not handled. 

There is a simple workaround which is to add `class="components-reconnect-hide"` to the element, but the docs don't imply this is necessary, and I'm not clear if this is a doc issue or an actual problem.

### Further technical details
- ASP.NET Core version 
3.0
- Include the output of `dotnet --info`
You really don't want all of that...
  3.0.100 [C:\Program Files\dotnet\sdk]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's [sic - this apostrophe was in the template, honest] version
VS 2019 16.3.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @willdean.
@javiercn did we forget to add this, or things change and the docs need to be updated?

**Comment by javiercn** [comment]
@mkArtakMSFT You beated me :).

I think this might just need a doc update? If you add your own its likely you need to place components-reconnect-hide in the component as a starting point.

I think that the moment you use a custom display you need to handle 3 cases.
* Initial: components-reconnect-modal.
* During reconnection: components-reconnect-modal components-reconnect-show
* After successful reconnection: components-reconnect-modal components-reconnect-hide

```css
.components-reconnect-modal {
  display: none;
}

.components-reconnect-modal.components-reconnect-show {
  display: block;
}
```

We should update the docs to reflect this. We should consider in the future putting this directly on the template instead of the current shenanigans that we do. It's a bit more code but it's much straight-forward

**Comment by willdean** [comment]
`.components-reconnect-modal`
should be
`#components-reconnect-modal'

It's an ID - the states are indicated by classes.

**Comment by javiercn** [comment]
> `.components-reconnect-modal`
> should be
> `#components-reconnect-modal`
> 
> It's an ID - the states are indicated by classes.

Thanks, it was an oversight on my part. I've updated the rule.
