### ISSUE TITLE
SignalR - OnConnectedAsync before OnDisconnectedAsync

### ISSUE THREAD

**Issue by kofifus** [aspnet/AspNetCore#16882]
In my testing I start a SignalR JS client connecting through windows Apache that proxy to a .NET Core SignalR server. Both client and server are localhost.

I then simply let that connection stay without sending anything, about once a minute for reasons I am not sure of, the connection breaks (perhaps because there is no traffic).

What happens then is that the JS client `start()` promise calls it's failure handler  and I then start a 100ms timer which connects (call `start()`) again.

What I see on the server is:
```
OnConnectedAsync Context.ConnectionId =  t.ZvRkrNDTzwvYdk4XrEbi2w
OnConnectedAsync Context.ConnectionId =  leWwH_6qgekplDilfyvNKw
OnDisconnectedAsync Context.ConnectionId = ZvRkrNDTzwvYdk4XrEbi2w
```

That is the `OnDisconnectedAsync` was triggered _after_ the second connection triggered another `OnConnectedAsync` 

As far as timing, sometimes OnDisconnectedAsync arrives just after the second OnConnectedAsync, but on some occasions I've seen almost a 30 seconds gap !

As I need to do specific bookkeeping after each connection/disconnection this really confuses my code.

Is this a bug ? or am I doing / understanding something wrong ?

**Comment by davidfowl** [comment]
Can you make a simple repro and share it with us? It sounds like it could be your app logic but hard to tell with just the description here.

**Comment by kofifus** [comment]
Do you mean this is not expected behavior or is it a possible valid scenario ?

**Comment by BrennanConroy** [comment]
> about once a minute for reasons I am not sure of, the connection breaks

That is definitely unexpected behavior, you should look into what is happening there.



> As far as timing, sometimes OnDisconnectedAsync arrives just after the second OnConnectedAsync, but on some occasions I've seen almost a 30 seconds gap !

Depending on how the client disconnects this can be the expected behavior.

If the client disconnects without notifying the server (i.e. going through a tunnel), then the server has to rely on the keep alive timeout (30 seconds by default) to determine that the connection is gone. And if the client comes back and makes a new connection then as far as the server is concerned there are "2" connections for a little while.

**Comment by kofifus** [comment]
Ok in that case I will close this now and do some more investigation around the connection failure issue
Thank you!
