### ISSUE TITLE
How to use a customized ConnectionHandler to force tcp disconnected after a long time without any action

### ISSUE THREAD

**Issue by stantoxt** [aspnet/AspNetCore#16899]
Hi,when using builder.UseConnectionHandler<MyTcpConnectionHandler>(), I want to forcefully stop tcp connection which has no action for a long time.How can I achieve this?

**Comment by halter73** [comment]
We used to have [IConnectionTimeoutFeature](https://github.com/aspnet/AspNetCore/blob/a159473c5729d4e334954d185c69ac144641685f/src/Servers/Kestrel/Core/src/Features/IConnectionTimeoutFeature.cs) that did this, but @davidfowl removed it in 3.0 with https://github.com/aspnet/AspNetCore/pull/11488 because the HTTPS connection handler no longer uses it. I don't think he was a huge fan of the actual API either, but I agree that it's very useful.

**Comment by davidfowl** [comment]
Use a Timer/CancellationToken and call Abort on the `ConnectionContext`. It's currently broken in SignalR though (https://github.com/aspnet/AspNetCore/issues/5329)
