### ISSUE TITLE
Blazor JS interop and client-side DOM lifetime

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#16897]
### Is your feature request related to a problem? Please describe.
I have client-side rendered graphs in a Blazor application where the raw data is sent using JavaScript interop and then converted to SVG elements using d3. I want to re-render my graph when the browser window is resized.

The problem is that the `"resize"` event is provided globally on `window`. In order for my Blazor component's client-side JavaScript to add the event listener when navigated to and remove it when navigating away, I need some control over the client-side lifetime of the component. I definitely don't want to leak event listeners while the application is running.

Currently, all my client-side JavaScript interop entry points start with an `ensureInitialized()` method call that makes sure the event listener is registered on `window` once and to remove the listener, I have implemented `IDisposable` in the Razor component server-side and fire-and-forget one "last" JS interop call to remove the listener.

That feels both racy and brittle, but it seems to work in practice.

### Describe the solution you'd like
As one option to have better guarantees, the components could carry the client-side methods to call when activating / deactivating the DOM:
```razor
<svg @js-interop-onadded="Graph.Initialize" @js-interop-onremoved="Graph.Cleanup">
</svg>
```
where the `Graph.Initialize` method is available globally on window like all other JS interop methods. The client-side Blazor library would call those methods as part its DOM manipulation. That way all initialization and cleanup is done before the first and after the last JS interop call from Blazor.

**Comment by javiercn** [comment]
@Tragetaschen thanks for contacting us.

I think what you are doing is just fine. The first OnAfterRender can be used for initialization and IDisposable can be used for removal. As an alternative, you can perform an initial call inside the OnAfterRender and setup a mutation observer so that when your root element gets removed it unregisters from all the events. 

That way your cleanup logic is setup on the first call.

This can also go a bit further and setup a mutation observer to detect when a specific attribute gets applied to any element in the dom tree and run the appropriate logic at that time. That way you can have your data-js-interop-onadded="method" data-js-interop-onremoved="method" applied directly from within the client.

**Comment by javiercn** [comment]
Closing this issue as the question has been answered.
