### ISSUE TITLE
Blazor: Support de/serialization of Dictionary<Guid, T>

### ISSUE THREAD

**Issue by cmoncure** [aspnet/AspNetCore#16905]
### Is your feature request related to a problem? Please describe.
Blazor's HttpClient json helper methods do not allow de/serialization of Dictionary types other than `Dictionary<string, T>`.  This prevents me from doing obvious thing such as returning `Dictionary<Guid, T>` from my API without tedious conversions to and from `String`, wasting programmer and CPU time.

### Describe the solution you'd like
Support de/serialization of `Dictionary<Guid, T>` in the new JSON conversion library in Blazor.  Guid is used for keying objects in every modern web app in the universe.  Guid should have first class support in Blazor everywhere it's possible to use Guid.

**Comment by javiercn** [comment]
@cmoncure thanks for contacting us.

This area is going to be subject to big changes in the future. We've provided these methods as a stop gap for allowing people to build their apps, but ultimately we don't plan to ship this methods ourselves, as these HttpClient extensions should be part of the framework as a whole and not a Blazor specific concept.

If Dictionary<Guid, T> is not something that works in System.Text.Json by default and you want to see that improved, I would suggest filing an issue on [dotnet/corefx](https://github.com/dotnet/corefx) so that they can consider that as a future improvement.

**Comment by javiercn** [comment]
I'm closing this issue as the question has been answered.

**Comment by pranavkm** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/40120. 

@ahsonkhan \ @steveharter was this enhancement ported to 3.1?

**Comment by ahsonkhan** [comment]
> was this enhancement ported to 3.1?

No, this is planned for 5.0. S.T.Json currently only supports dictionaries with string keys.
