### ISSUE TITLE
Environment isn't respected in Angular SPA template 

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#16935]
### Describe the bug
Running Angular spa template with `dotnet run -c Release` still runs the app in development mode

### To Reproduce
- dotnet new angular
- dotnet run -c Release

### Expected
- The app runs in production mode

### Actual
- The hosting environment is still set to development

Note: It works fine when publishing and running with `dotnet publish -c Release`

Sdk version 3.0.100

@ryanbrandenburg, please add more details if I missed anything

**Comment by ryanbrandenburg** [comment]
So, it doesn't respect it because of https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Properties/launchSettings.json#L31, but if you remove that line then you have the problem that running `dotnet run -c Release` doesn't actually work, it demands that you do `dotnet publich -c Release` and then run the `exe`. That's not an ideal experience, but it might not be a small change to fix, and no customers have complained yet.

**Comment by javiercn** [comment]
release/debug != production/development. They are orthogonal.

The reason this happens is because you are doing "dotnet run" and that picks up the environment from launchSettings.json, that behavior is expected.

You can run your "Release" app in "Development" and your "Debug" app in "Production".
