### ISSUE TITLE
IApplicationBuilder DI is null

### ISSUE THREAD

**Issue by wangyue2017** [aspnet/AspNetCore#16943]
During the project running, I now use rolysn to dynamically generate the assembly and then applicationparts to add the dynamically generated assembly, but the route does not take effect, and I need to add a new datasource under IApplicationBuilder.Properties, but the di IApplicationBuilder object appears to be null

**Comment by javiercn** [comment]
@wangyue2017 thanks for contacting us.

Could you provide a minimal repro project that illustrates your issue. From the description you provided we can't understand what you are trying to achieve and what your scenario is.

**Comment by wangyue2017** [comment]
` public class DynamicService: IDynamicService
    {
        private const string EndpointRouteBuilder = "__EndpointRouteBuilder";
        private readonly ApplicationPartManager _partManager;
        private readonly IApplicationBuilder _builder;
        //private readonly ServiceProvider.GetRequiredService<ControllerActionEndpointDataSource>();
        public DynamicService(ApplicationPartManager partManager
            , IApplicationBuilder builder
            )
        {
            _partManager = partManager;
            _builder = builder;
        }

        public async Task Regiest()
        {
            #region assembly create
            var file = Directory.GetCurrentDirectory() + "\\TestController.txt";
            string dynamic = "";
            using (var read = new StreamReader(file))
            {
                dynamic = read.ReadToEnd();
            }
            var assemblyPath = Path.GetDirectoryName(typeof(object).Assembly.Location);
            var systems = AssemblyLoadContext.Default
                                                .Assemblies
                                                .Where(o => !o.FullName.Contains("Anonymously Hosted DynamicMethods Assembly"))
                                                .Select(o => MetadataReference.CreateFromFile(o.Location)).ToList();

            var tree = SyntaxFactory.ParseSyntaxTree(dynamic);
            var guid = Guid.NewGuid().ToString();
            var compilation = CSharpCompilation.Create($"{guid}.dll", new[] { tree },
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithOptimizationLevel(OptimizationLevel.Debug),
                references: systems);

            Assembly compiledAssembly;
            using (var stream = new MemoryStream())
            {
                using (var pdf = new MemoryStream())
                {
                    var compileResult = compilation.Emit(stream, pdf);
                    var assemblyBytes = stream.GetBuffer();
                    var pdbBytes = pdf.GetBuffer();
                    compiledAssembly = Assembly.Load(assemblyBytes, pdbBytes);
                }
            }
            #endregion

            _partManager.ApplicationParts.Add(new AssemblyPart(compiledAssembly));

            _partManager.FeatureProviders.Add(new DynamicControllerFeatureProvider());

            _builder.Properties.Keys[EndpointRouteBuilder] = 

           await Task.CompletedTask;
        }
    }`

IApplicationBuilder  is null

**Comment by davidfowl** [comment]
IApplicationBuilder isn't a service you can access via DI.

**Comment by wangyue2017** [comment]
So？I can only define one static class  
`public static class IApplicationTool
{
     public static IApplicationBuilder ApplicationBuilder { set;get; }
}`

` public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseStaticFiles();

            app.UseRouting();

            app.UseHealthChecks("/health", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions()
            {
                ResultStatusCodes =
                {
                    [HealthStatus.Healthy] = StatusCodes.Status200OK,
                    [HealthStatus.Degraded] = StatusCodes.Status200OK,
                    [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable
                },
                AllowCachingResponses = false
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
          IApplicationTool.ApplicationBuilder=app;
        }`

**Comment by javiercn** [comment]
I'm still not 100% sure what you are trying to accomplish here.

I'll give you a few pointers, but this question is more suited for stack-overflow.
* Application parts must be initialized before you try to initialize any service and can't be initialized within a service. There are many things that can/will go wrong if that's the case.
* You seem to be compiling things on the fly, that is not something that we support out of the box and I'm not even sure you'll be able to make it work.
  * Creating an assembly part for the assembly directly is likely the wrong thing to do.
  * You are likely missing things on the generated assembly due to the fact that you are compiling things yourself directly instead of going through the normal SDK compilation flow.

My recommendation is that you try to at least compile everything you might need beforehand and simply perform the loading at the last minute.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.

I'm closing this issue as there's no more action for us to take here.
