### ISSUE TITLE
Blazor: Make it possible to create an instance of ElementReference

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#16967]
### Is your feature request related to a problem? Please describe.
Note: I don't currently need this, so low priority.

`@ref` is used for both referencing to an ElementReference and to a descendant of ComponentBase. This means that if we need a strongly-typed reference to a razor component (for calling C# methods etc from the consuming component) we cannot also pass that reference to JavaScript.

### Describe the solution you'd like
Either automatically wrap IComponent instances with ElementReference when invoking JavaScript, or add something like `ElementReference.Create(IComponent)` (possibly better, because you cannot know if the consumer is expecting an ElementReference or a DotNetObject reference - unless you made DotNetObject a subclass of ElementReference or something).

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

Something like this should suffice your case I think (if I understood correctly your scenario).

```razor
<ChildComponent ref="MyComponent">

@code{

private DotNetObjectReference _myComponentReference;

protected override Task OnAfterRenderAsync(bool firstRender)
{
   if(_myComponentReference != null){
       _myComponentReference.Dispose();
   }
   _myComponentRefernece = DotNetObjectReference.Create(MyComponent);
    await JS.InvokeAsync("setChildReference", _myComponentReference)
}
}

public void Dispose() => _myComponentReference?.Dispose();
```

**Comment by mrpmorris** [comment]
Hi @javiercn 

Not quite. Imagine you have some js you use to do something to an element so you need an ElementReference for that.

But it's also a razor component with methods you need to call, so you need a reference like `MyComponent MyRef`. 

It's currently not possible to get an ElementReference for a razor component if you already have a strongly-typed reference. 

Let me know if you need further clarification.

**Comment by javiercn** [comment]
@mrpmorris I'm not sure I understand your scenario.

Would something like this represent your scenario? (Although it's not possible)
```razor
<ChildComponent ref="MyComponent" ref="MyRef">
```

Where you would have a reference to the child component and an "HtmlReference" to the component too?

**Comment by mrpmorris** [comment]
> @mrpmorris I'm not sure I understand your scenario.
> 
> Would something like this represent your scenario? (Although it's not possible)
> 
> ```
> <ChildComponent ref="MyComponent" ref="MyRef">
> ```
> 
> Where you would have a reference to the child component and an "HtmlReference" to the component too?

Yes. Ways I can think of are

1: Multiple refs.
2: Automatically convert IComponent to ElementReference when invoking JS.
3: Allow creation of ElementReference using an IComponent.

**Comment by javiercn** [comment]
@mrpmorris 

Components are not elements and are not represented in markup as such. This is fundamentally not possible in Blazor for several reasons.
* Components are just marker comments in the generated HTML.
  * This is fundamental as otherwise they would affect the application styles.
* Components are not required to have a "root" element.
  * You can have a component that is defined by a list of HtmlElements, and that's not something we would restrict.
  * There is no 1:1 relationship between component and Html element, so having an "HtmlReference" to a component doesn't make sense.

I know that this is likely not the answer you wanted to receive, but these are fundamental concepts/abstractions of the Blazor application model that we aren't likely to change, as they would impose limitations to existing apps and would be a breaking change.

**Comment by mrpmorris** [comment]
No, that makes perfect sense. Thank you!
