### ISSUE TITLE
WebAPI - Url.Action returns null, worked well in .netcore 2.2

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17005]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804414/webapi-urlaction-returns-null-worked-well-in-netco.html)._

---
[regression] [worked-in:15.7]
Hi, this is my part of code inside a controller:

string activationLinkTemplate = Url.Action(&quot;activate&quot;, &quot;users&quot;, new { userId = LinkTemplateTokens.USER_ID, code = LinkTemplateTokens.LINK_TOKEN }, Request.Scheme);

This worked in previous version (.Net Core 2.2), but now returns null. I really don't know what to do with that.
This part of code should create activation link template like:

&quot;https://mysite.com/api/users/activate?userId=10&amp;code=56785678&quot;
so that use can activate its account. What can I do now?

---
#### Visual Studio Feedback System on 11/4/2019, 00:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@rynowak can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
The Endpoint Routing has introduced a set of breaking changes in ASP.NET Core 3.0.
You can learn more about the specific breaking changes from https://github.com/aspnet/Announcements/issues/120

If this explains the behavior change you see, please let us know.
Otherwise, please provide a minimalistic repro project (ideally hosted as a GitHub repo) so that we can investigate this further.
