### ISSUE TITLE
Intellisense on Blazor

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/806684/intellisense-on-blazor.html)._

---
Intellisense on Blazor is unbearable, it's so slow and sometimes errors and warnings doesn't go away unless you try to rebuild or clean your dlls. please fix this.

---
#### Visual Studio Feedback System on 11/4/2019, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Postlagerkarte** [comment]
Not sure if this is related but I also reported a Blazor intellisense issue to VSfeedback and that issue is "under investigation" for over a month now. 

https://developercommunity.visualstudio.com/content/problem/755821/blazor-no-intellisense-in-the-immediate-window.html

Blazor deserves great tooling support from Visual Studio!

**Comment by javiercn** [comment]
Thanks for contacting us.

We would need more information in order to troubleshoot this. A minimal repro-project that illustrates the issue (we don't know what's at play here, how big the project is, how many components in it, etc) as well as likely some information like a performance trace of visual studio so that we can better understand what is causing the slow down as well as some details about your environment, like what plugins/extensions are you using.

**Comment by oiBio** [comment]
we have pretty much the same problem. we have a relatively large project with ~250 components and its really slow. rebuilding helps almost everytime, sometimes you have to restart vs. often it also help to close & reopen the razor file to get of the error messages.

We have this problem for a long time and we are currently using the 16.4.0 Preview 3 Professional Edition.

**Comment by javiercn** [comment]
@oiBio Could you report this through the "Send feedback dialog in Visual Studio and attach a repro with the report? Here are the steps to follow https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#record-a-repro

**Comment by Postlagerkarte** [comment]
@javiercn : Do you have any idea about why intellisense is not working in the immediate window? ( Default template, just break on the weather service OnInitializedAsync , type ForecastService + . in the immediate window -> nothing is shown)

**Comment by javiercn** [comment]
@Postlagerkarte I have no idea, as that is a tooling issue and I'm not super familiar with the area.

With regards to https://github.com/aspnet/AspNetCore/issues/17002#issuecomment-552845139 I don't think that issue is necessarily tied to this one. We do our best to look at all the issues in a timely fashion, but I hope you understand that sometimes there are multiple teams involved in root causing an issue and we need to balance other things which can sometimes take time,

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
