### ISSUE TITLE
UseReactDevelopmentServer without UseSpa

### ISSUE THREAD

**Issue by Daniel15** [aspnet/AspNetCore#17010]
Is it possible to use `UseReactDevelopmentServer` without `UseSpa`? In dev, I want to use the React dev server, but do not want to return /index.html for everything (which is what `UseSpa` does).

**Comment by javiercn** [comment]
@Daniel15 thanks for contacting us.

@SteveSandersonMS Is this possible?

**Comment by SteveSandersonMS** [comment]
No, sorry. `UseReactDevelopmentServer` is just one of the ways of configuring `UseSpa`, so you can't use the former without the latter.

However just because you're using `UseSpa` doesn't mean you have to return `/index.html` for everything - you could also put other middleware earlier in ASP.NET Core's pipeline to return different responses.
