### ISSUE TITLE
[blazor server vs2019 16.3.9] Compile Success but vs give me cs1503 error 

### ISSUE THREAD

**Issue by git-net** [aspnet/AspNetCore#17114]
i try  write a  abstract class 
```
 public abstract class ComponentBase<TComponent>:ComponentBase where TComponent:ComponentBase<TComponent>
    {
        [Parameter] public  RenderFragment<TComponent> Template1{ get; set; }
      ........
    }
```
 inherits  ,MyComp.razor
```
@inherits ComponentBase<MyComp>

@Template1(this) //cs1503  @Template1(this as MyComp)  cs0039
......
```
compile success. is v3.1 or vs 16.4 resolve it?

**Comment by javiercn** [comment]
@git-net thanks for contacting us.

@rynowak this is on your area. Do you have any idea?

**Comment by javiercn** [comment]
I'm unable to repro this on 3.0, but I'm not sure what you are trying to accomplish. Here is a minimal sample based on your codebase that compiles in Visual Studio and on the command line.

[GenericComponentBase.zip](https://github.com/aspnet/AspNetCore/files/3852031/GenericComponentBase.zip)

I'm closing this issue as I can't repro it. If you still have problems, produce a minimal repro and comment on github so that we can re-evaluate it.

Hope that helps.

**Comment by git-net** [comment]
@javiercn 
i can't download you code,i post my code
 [https://github.com/git-net/GenericComponents](https://github.com/git-net/GenericComponents)
with  some screen picture.
vs19 16.3.9 ,3.0
