### ISSUE TITLE
How to switch between server-side and core-hosted

### ISSUE THREAD

**Issue by mRmEEeZ** [aspnet/AspNetCore#17111]
Hello,

What exactly do i need to change when switching between blazor models ?
and why Client part in core-hosted has to be netstandard rather than netcore ?

Thanks

**Comment by radek7210** [comment]
FYI, Mark Stega published a fully working example showing how to organize the projects to allow easy switch between client-side and server-side Blazor:

https://bitbucket.org/MarkStegaOHI/blazor-cse-sse/src/master/

**Comment by javiercn** [comment]
@mRmEEeZ thanks for contacting us.

Client-side Blazor is still in development and it targets netstandard2.1 for time being. Switching between client-side and server-side Blazor involves organizing your code (with most of it likely inside a class library) and two separate hosts so that you can either run hosted or run server-side Blazor.

The main factor that determines what you use to pick what flavor you use, is the entry point to your app on the initial request, and that can be done switching between MapFallbackToPage and MapFallbackToClientSideBlazor.

Hope that helps.
