### ISSUE TITLE
allow array of subparameter in blazor component, with generic type constraint

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#17194]
### Is your feature request related to a problem? Please describe.

This issue follow this one : https://github.com/aspnet/AspNetCore/issues/17092
I don't know how to really describe this, the idea is to allow have array sub component in a component wich was "automatically" typed with the generic parameter of a parent. Its better to read the issue in link to understand the problem

### Describe the solution you'd like

The solution of @mrpmorris on this comment seem nice : https://github.com/aspnet/AspNetCore/issues/17092#issuecomment-554653567

thanks !

**Comment by javiercn** [comment]
We believe this issue is better described by https://github.com/aspnet/AspNetCore/issues/17200. If you are asking for a different thing, feel free to comment here and we will re-evaluate.

**Comment by julienGrd** [comment]
I don't really know if we speak about the same thing, i will follow the 17200 and see the evolution

**Comment by mrpmorris** [comment]
> We believe this issue is better described by #17200. If you are asking for a different thing, feel free to comment here and we will re-evaluate.

@javiercn I don't think it's the same thing.

This request is to allow the setting of a parameter like `public MySubComponent[] { get; set;} ` as child content.

A good example of this would be a `Grid<T>` which would have a parameter `public Column<T>[] Columns { get; set;} `

```
<Grid Items=People>
  <Columns>
    <Column>@context.FullName</>
  </Columns>
</Grid>
```
At the moment there is no way for `Column<T>` to infer its type from `Grid<T>` because RenderFragments can contain absolutely anything.

This is a request from some kind of [ViewChild] and [ViewChildren] attributes which will let the developer specify only one type of content is allowed (a grid has columns, nothing else).

**Comment by javiercn** [comment]
@mrpmorris You can have templated components that use `RenderFragment<T>` https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#templated-components

**Comment by mrpmorris** [comment]
@javiercn that would be a single item. The request is for an array, at the moment it isn't possible to implement the grid/column example I gave using `RenderFragment<T>`

**Comment by mrpmorris** [comment]
@javiercn Could you reopen this, please? It's almost certainly not the same thing as the issue you linked to. This is a request for an array of strongly typed content, not render fragments.
