### ISSUE TITLE
In Blazor creating the Same Element Multiple times in DOM.

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#17259]
Is there any possibility of appending the same element multiple times in the DOM. I have tried this below case.

```
<button @onclick="clicked">Update DOM</button>

@if(rendered) { 
       <div id="Random_id">Showed in DOM</div> 
 }

@code{` 

     private bool rendered { get; set; } = false
     
     private void clicked() {
        this.rendered = true;
        this.StateHasChanged();
     }
}
```

In this case the same element is not appended in the DOM for multiple times. Any solution for this ?

**Comment by javiercn** [comment]
@Indrajith-Sync thanks for contacting us.

You don't need to call state has changed yourself. Blazor re-renders the entire UI and updates it based on the changes from the previous render (if any).

In your case you are simply rendering a single element conditionally, so that's what you will get. If you want to render multiple elements you would have to do something like keeping a counter of elements to render and writing a foreach loop for them.

```
<button @onclick="clicked">Update DOM</button>

@foreach(var index in Enumerable.Range(0,elementsNumber)) { 
       <div id="Random_@(index)">Showed in DOM</div> 
 }

@code{` 

     private int elementsNumber { get; set; } = 0
     
     private void clicked() {
        this.elementsNumber++;
     }
}
```

**Comment by Indrajith-Sync** [comment]
Thank you for your suggestions...! @javiercn
