### ISSUE TITLE
IHtmlLocalizer<SharedResource> won't work with VS 2019 16.4 Preview 5

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/826526/ihtmllocalizer-wont-work-with-vs-2019-164-preview.html)._

---
[regression] [worked-in:16.4 Preview 2 to 16.4 Preview 5]
Using ASP .Net Core 3.0.

When using **IHtmlLocalizer&lt;SharedResource&gt;** in view (with **AddLocalization(o =&gt; o.ResourcesPath = &quot;Resources&quot;)** in startup.cs) shared localization not work.
If I set AddLocalization(), shared localization work fine but not view localizations that using IViewLocalizer...

Structure :

Project
|--&gt;Resources
|.....| --&gt;Views
|.....| .....| --&gt;Home
|.....| .....| .....| --&gt;Index.fr-fr.resx
|.....| .....| .....| --&gt;Index.en-us.resx
|.....| .....| --&gt;Account
|.....| .....| .....| --&gt;Index.fr-fr.resx
|.....| .....| .....| --&gt;Index.en-us.resx
[...]
|.....| --&gt;SaredResource.cs
|.....| --&gt;SaredResource.fr-fr.resx
|.....| --&gt;SaredResource.en-us.resx

Same code work fine with stable version of VS 2019 (16.3).

---
#### Visual Studio Feedback System on 11/20/2019, 01:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please look into this? Thanks!

**Comment by Safirion** [comment]
Hi,

I don't understand the tag "5.0.0-preview1".

It must be corrected in next release of VS, I don't think it's related to ASP Net core since I use .Net Core 3.0 in both VS 2019 16.3 and VS 2019 16.4 Preview 5 ?

**Comment by ryanbrandenburg** [comment]
@Safirion Please ensure you're reviewed [this documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#resource-file-naming). If you've reviewed that and still have trouble, is it a typo in your structure diagram or the code when it says `SaredResource`, but then your HtmlLocalizer is looking for <SharedResource>?

If neither of those solve your problem please include a GitHub repo which demonstrates the problem.

**Comment by Safirion** [comment]
@ryanbrandenburg Effectively it's a typo. File is correctly named in my project.

I will try to make a demo project tonight.

**Comment by Safirion** [comment]
Fail too with Preview 6.

Project demo:
[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3876439/WebApplication1.zip)

Results :
![image](https://user-images.githubusercontent.com/11511729/69371083-6c07b800-0c9f-11ea-97d1-2f7f3a971953.png)

**Comment by Safirion** [comment]
Any hope that it would be fix before the release of .Net Core 3.1 next week ? 😕

**Comment by ryanbrandenburg** [comment]
I think perhaps there is a disconnect between what you're running locally and what you've included in that ZIP. The Startup.cs of your ZIP never called `UseRequestLocalization` in the Configure method, so I don't believe it ever would have Localized at all or even set your `CurrentCulture`. You need to do something like the following at the top of your `Configure` method:

```C#
var supportedCultures = new string[]{ "en-US", "fr-FR" };
app.UseRequestLocalization(options =>
    options
        .AddSupportedCultures(supportedCultures) 
        .AddSupportedUICultures(supportedCultures)
        .SetDefaultCulture("fr-FR")
        .RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(context =>
        {
            return Task.FromResult(new ProviderCultureResult("fr-FR"));
        }))
);
```

Also, I don't believe it's the cause of your problems but I highly recommend you remove all the ItemGroup's except the one with the `PackageReference`s. The Web Sdk will take care of giving everything the appropriate Compile/Embed/etc status, and it should be unnecessary to modify things further in all but the strangest of cases.

Make those changes then if you're still seeing the behavior produce a new repro (preferably as a GitHub project for easy reference) using the exact code that it reproduced under.

**Comment by Safirion** [comment]
@ryanbrandenburg Thank's for reply.

I've patch the project with your suggestions and create a depo here : https://github.com/Safirion/LocalizationBugDemo

Bug is still present.

**Comment by ryanbrandenburg** [comment]
I was able to replicate this. It seems that when built with VS SharedResource.fr-FR.resx gets saved as `WebApplication.SharedResource.fr-FR` instead of `WebApplication.Resources.SharedResource.fr-FR`. The extra-strange thing is that Index.fr-FR.resx gets saved under the correct resource name regardless. It all seems related to the fact that SharedResource.cs is in the Resources folder. If you move that file out of the Resources folder (taking care to maintain a namespace which still reflects that structure) things work.

That appears to be a bug in VS, possibly related to the way they fold resx files with the same name under the cs file. I'm not sure how is best to report this to them, @mkArtakMSFT will probably know.

**Comment by ryanbrandenburg** [comment]
@Safirion I talked with @mkArtakMSFT offline and we think the best course is for you to report this through the VS Feedback flow. We suggest including a link to this issue in addition to your description of the issue you're facing. We'll close is as an external issue then. Let us know if you don't hear anything for a while.

**Comment by mkArtakMSFT** [comment]
Actually it seems we've made a mistake here. Specifically, this issues was mistakenly moved to us from VS Feedback already. Rather than opening a new issue, the right thing to do would be for us to reopen the original VS Feedback issue and try to redirect it to the correct owners.
I'll do this now.

**Comment by gfurtado** [comment]
I'm having the same problem with the official release VS 2019 16.4. So for now rolled back to VS 2019 16.3.10.

**Comment by pocki** [comment]
I'm having also the same problem. My Solution worked correctly with VS 2019 16.3.x but don't work after upgrade to VS 2019 16.4.0

It works if it gets compiled with Azure Pipeline Hosted Agent (Windows-2019) which is actually using Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core

I created a sample ASP.NET Core 3.0 App: [https://github.com/pocki/AspNetCore30LocalizationSample](https://github.com/pocki/AspNetCore30LocalizationSample)

**Comment by oxyzt** [comment]
I'm having the same problem with the official release VS 2019 16.4.

**Comment by oxyzt** [comment]
I'm having also the same problem with the official release VS 2019 16.4.

**Comment by gfurtado** [comment]
@ryanbrandenburg  @mkArtakMSFT, has this issue been moved to another issue? because this one has already been closed.

**Comment by Safirion** [comment]
@gfurtado Here : https://developercommunity.visualstudio.com/content/problem/826526/ihtmllocalizer-wont-work-with-vs-2019-164-preview.html

**Comment by egrabitt** [comment]
I face this problem, too. I installed VS Community 16.4.1 and now my web app is completely broken because none of the texts are localized anymore! This is totally unacceptable, I'm really desperate. I cannot downgrade because "we actually only make the links available for the paid versions of Visual Studio." [https://developercommunity.visualstudio.com/idea/747782/need-to-be-able-to-downgrade-visual-studio-version.html].
This is really bad, PLEASE provide a solution.

**Comment by Safirion** [comment]
You can downgrade VS using one of these links :
https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release

It's for professional and enterprise version but there is trial, so in waiting for a true solution.

**Comment by egrabitt** [comment]
thanks, but trial won't last very long. VS 16.4.2 has still got the problem.

**Comment by FahaoTang** [comment]
> thanks, but trial won't last very long. VS 16.4.2 has still got the problem.

Mine is also 16.4.2 and I now also encountered the same problem. 
My website was working well previously when user selects languages but now it doesn't work anymore because of this issue:
[Live example](https://kontext.tech/settings?rurl=%2F)

The website is built using Azure DevOps build pipelines (windows 2019 agent). So I believe now this issues also exists in Azure DevOps. 

To summarise, the shared string or HTML localizer now doesn't work when building locally using VS2019 16.4.2 or in Azure DevOps with windows 2019 agent.

**Comment by BenVillalobos** [comment]
Posting a temporary solution for this where I can. It's also posted (along with a bit of context) at microsoft/msbuild#4996

https://github.com/microsoft/msbuild/issues/4806#issuecomment-541018341

**Comment by gfurtado** [comment]
> 
> 
> Posting a temporary solution for this where I can. It's also posted (along with a bit of context) at [microsoft/msbuild#4996](https://github.com/microsoft/msbuild/issues/4996)
> 
> [microsoft/msbuild#4806 (comment)](https://github.com/microsoft/msbuild/issues/4806#issuecomment-541018341)

That solution worked for me, just create file in the root of the solution named: Directory.Build.props and add: 
`<Project>
  <PropertyGroup>    <EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
</Project>`

**Comment by BenVillalobos** [comment]
Okay, so it turns out this was a breaking change we wanted to take as of net core 3.0. For full context and an explanation of how resource names are chosen, see [the issue on MSBuild's side](https://github.com/microsoft/msbuild/issues/4996) and [the dotnet docs issue](https://github.com/dotnet/docs/issues/16964).

**Comment by Safirion** [comment]
Hi,

I don't understand why EmbeddedResourceUseDependentUponConvention is set to "True" by default. If this parameter was added to improve compatibility with old projects, why change the default behaviour and impact all projects created since the begining of .Net Core ?
