### ISSUE TITLE
Signalr Clients.Users Should accept IEnumerable

### ISSUE THREAD

**Issue by MhAllan** [aspnet/AspNetCore#17285]
Clients.Users require IReadOnlyList<string>, The problem is we don't need to create read only collection every time we want to send message to multiple users

### solution
Clients.Users takes IEnumerable<string> parameter

**Comment by anurse** [comment]
We do that because it is often re-enumerated by HubLifetimeManagers and `IReadOnlyList` ensures we have a stable enumerable that won't be too costly to re-enumerate.

Having said that, I'm not opposed to the idea of creating an extension method or default interface member that takes `IEnumerable` and calls `.ToList` in order to pass it down.

**Comment by Marusyk** [comment]
Can we close it?

**Comment by anurse** [comment]
We can! Thanks for the contribution @Marusyk !
