### ISSUE TITLE
Blazor preventDefault with wheel event

### ISSUE THREAD

**Issue by los93sol** [aspnet/AspNetCore#17358]
### Describe the bug
Using @onwheel:preventDefault does not prevent the browser from scrolling in Chrome.

### To Reproduce
```
<div @onwheel="@(e => AddToCounter(1))" @onwheel:preventDefault>@Counter</div>
```
Make sure there's enough content on the page that the browser has vertical scroll bars and it will still end up scrolling.

In Chrome I also see the following in the console...
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
e.onGlobalEvent @ blazor.server.js:8

This works as expected in IE11, is there a workaround or some special way I should define preventDefault in this case?

ASP.NET Core version: 3.1 Preview 3
VS 2019 Preview

**Comment by javiercn** [comment]
@los93sol thanks for contacting us.

@SteveSandersonMS can you take a look at this?

**Comment by SteveSandersonMS** [comment]
Use of `preventDefault` within scroll-type events (including wheel) is discouraged by browsers because it reduces the responsiveness of the site. Chrome started blocking this by default in version 56, and more recently also blocked it for wheel events in version  The reasoning is given in detail at https://developers.google.com/web/updates/2017/01/scrolling-intervention

The recommended alternative is to block default scrolling behaviors using the CSS style `touch-action: none`.

In the future, we could consider changing Blazor's event delegation behavior to pass `{passive:false}`, but I'm reluctant to say we would necessarily do that as it would lead to a loss of responsiveness for everyone. We might need to somehow do this selectively based on whether it looks like you're doing any `preventDefault`, which is more complex to implement.

Hopefully the recommended solution with `touch-action: none` will be sufficient. On that basis I'll close this, but if you don't think this solution is adequate, please comment further with reasons. Thanks!

**Comment by los93sol** [comment]
@SteveSandersonMS Thanks for the response.  I just tried the workaround using touch-action: none; but that doesn't seem to work.  I also read through the article linked and I agree that definitely is the change to Chrome that's causing this particular issue, it looks to me like the css solution may only apply to touch screen scenarios.

My real world use case here is that I have a TimeSpan picker and the user can select milliseconds.  I am attempting to allow the user to simply wheel up/down to to jump through values quickly then there are arrows for fine tuning.
