### ISSUE TITLE
load blazor Webassembly from File System

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#17362]
when creating a deployment of a Blazor 3.1 webassembly app with visual studio, path are relative.
Is there any option or should it be a feature like

contentpath="c.\temp\"

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

I'm not really sure what you are asking from us. It will help us if you can describe your scenario more in depth. What you are trying to achieve and what is not working.

**Comment by hannespreishuber** [comment]
this is not a bug, it is a feature request or a question why this is a wanted behavior

Visual Studio Blazor Webassembly type- publish to file system 
there is a index.html with contains path like "_/…/js". So it is not possible to double click index,html and run the app within the browser

**Comment by javiercn** [comment]
@hannespreishuber 

Is it not possible to change the index.html to the appropriate physical paths? I'm not sure this is even doable without modifying the blazor webassembly js file as in order for this to work it is likely that the assemblies need to be embedded inside the index.html (fetch won't work when loading a file).

@SteveSandersonMS do you have any thoughts?

**Comment by SteveSandersonMS** [comment]
Loading web apps from a `file:///` URL is unfortunately subject to many limitations. Browser vendors have been locking this down more an more, based on the idea that the security model for `file:///` is deeply flawed and it's better not to support it for many features. I wouldn't count on being able to load a Blazor app, or any other nontrivial SPA, from a `file:///` URL.

If you find out that there are specific things we could change to make it better, please let us know and we will consider them.

> Is there any option or should it be a feature like contentpath="c.\temp"

That's not an option, because published apps are meant to be portable across machines. Absolute paths in general don't work for portability. If you need, you can edit the published file to put in whatever absolute path you want.

I'll close this as it's not an area we have specific work planned, but as mentioned, please let us know if you have other specific feature requests. Thanks!
