### ISSUE TITLE
blazor repo 'master' should use 3.1 SDK

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#17422]
Hey @javiercn - as part of your work on figuring out the build/package flows, would you be able to determine what needs to happen to make https://github.com/aspnet/blazor's `master` branch build using the same SDK as in the `aspnetcore` repo's `blazor-wasm` branch? Not sure if this involves more coordination with @wtgodbe.

Alternatively we could bring back the `blazor-wasm` branch in https://github.com/aspnet/blazor, but since we only want to work with one branch there, we should then also remove the `master` branch completely and only have `blazor-wasm`.

I've put this for preview 5 since @javiercn and I discussed and he prefers not to disrupt the preview 4 work for this right now.

cc @mkArtakMSFT - please reassign if you wish!

**Comment by wtgodbe** [comment]
It's easy enough to change the SDK version in Blazor's master branch, if that's what we want to do. I actually just sent @javiercn an email about this exact thing 😆.  It is actually necessary to go back to a 3.x SDK & a 3.x Arcade ASAP in order to get Blazor's master branch publishing to the same feed as AspNetCore's blazor-wasm branch. I think we need to do the following things:

1. Downgrade Blazor's SDK to the same as in AspNetCore's blazor-wasm branch
2. Subscribe Blazor master to Arcade 3.x & run an update
3. Cut off the subscription from Blazor master to AspNetCore master

I can do this work after my morning meetings if we decide it's what we want.

**Comment by SteveSandersonMS** [comment]
@wtgodbe That sounds fantastic. Thanks for looking at this!
