### ISSUE TITLE
Can't get ActionContext in IModelBinderProvider.GetBinder function ,it return  null

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#17449]
I use Asp.net core 3.0
I want to create myselft ModelBinder ,code like this

in start.cs

```
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.TryAddSingleton<IActionContextAccessor, ActionContextAccessor>();

 services.AddControllersWithViews(opt =>
            {
                opt.ModelBinderProviders.Insert(0, new JsonValueProviderFactory.JsonModelBinderProvider());
                opt.ValueProviderFactories.Insert(0, new JsonValueProviderFactory());

            })
```
```
internal class JsonModelBinderProvider : IModelBinderProvider
        {
            private static JsonModelBinder _binder = new JsonModelBinder();

            public IModelBinder GetBinder(ModelBinderProviderContext context)
            {
                var accessor = (IActionContextAccessor)context.Services.GetService(typeof(IActionContextAccessor));

               **//the problem is here ActionContext return null,but this code is work in asp.net core 2.2**
                var ac = (accessor.ActionContext.ActionDescriptor as ControllerActionDescriptor);

                //TODO something
            }


        }

```

**the problem is here ActionContext return null,but this code is work in asp.net core 2.2**
var ac = (accessor.ActionContext.ActionDescriptor as ControllerActionDescriptor);

how can I get ActionContext object????

**Comment by kugarliyifan** [comment]
I want to get Action's all Attribute type in IModelBinderProvider.GetBinder,,how can I do???

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@pranavkm can you please look into this? Thanks!

**Comment by kugarliyifan** [comment]
I think I found other way to fix it,,

**Comment by kugarliyifan** [comment]
I think I found another way to fix it:
```
Endpoint endpoint = h.HttpContext.GetEndpoint();
var attr = endpoint.Metadata.GetMetadata<FromJsonAttribute>();
```
use this code,I can get the Attribute in IModelBinderProvider.GetBinder....

I think the problem is assign accessor.ActionContext property value order is wrong,I found it assign after GetBinder and beforce controller Constructor

**Comment by pranavkm** [comment]
@kugarliyifan changes to [routing in 3.0](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#endpoint-routing-differences-from-earlier-versions-of-routing) result in the `ActionDescriptor` and consequently model binding for parameters to be constructed much earlier than it was in 2.x. 

Generally, we'd recommend against using ambient values such as request or action context when constructing an model binder. Model binders are cached per metadata instance, so using ambient context when constructing it is going to result in incorrect behavior. However, it looks like all you're attempting to get to static metadata about the model. There are a couple of options here that be more idiomatic:

a) MVC uses attributes that implement `IBindingSourceMetadata`. These appear as part of `ModelBinderProviderContext.BindingInfo` which you could then make a decision on. For instance:
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/FromBodyAttribute.cs#L13-L17
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/BodyModelBinderProvider.cs#L81-L82

b) You could write an convention that inspects actions and assigns model binders. See https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-3.0#conventions for details about authoring conventions.

Closing this since we understand what's causing the difference and there are workaround available.
