### ISSUE TITLE
Locking down response during a request

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#17507]
This is related to an issue raised for gRPC - https://github.com/grpc/grpc-dotnet/issues/674

**Background:**

A gRPC response always has a status header/trailer. The status goes in the header if there was no messages written, otherwise it goes in the trailer.

When adding the status, the gRPC server will check `Response.HasStarted` to see if the response has started or not. If it has started then there are messages - so the status goes in the trailer. If it hasn't then the status goes in the header.

The problem is middleware running after gRPC could unknowingly change the frames written. `Response.StartAsync()` will flush headers, and then when the response is ending Kestrel will write a 0 length DATA frame with END_STREAM=true.

```
0.218s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executed endpoint 'gRPC - /DynamicService/DuplexStreaming_ThrowServerError_Error'
0.219s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HLRM8DD50E6J" sending HEADERS frame for stream ID 1 with length 152 and flags END_HEADERS
0.227s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HLRM8DD50E6J" sending DATA frame for stream ID 1 with length 0 and flags END_STREAM
0.228s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request finished in 73.1282ms 200 application/grpc
```

Some clients are very strict about frames. The Java client in the issue believes that if a DATA frame is received, it must be followed by trailing HEADERS. I need a way to prevent that happening.

**Ideas:**

A couple of ideas for a solution:
1. Simple solution could be for the gRPC server library to call `Response.CompleteAsync()` when a gRPC error occurs, to prevent developers messing with the response. However I wonder if there might still be a valid reason to modify headers in middleware, and this solution would prevent that. Also it would be difficult for developers to understand why the middleware can no longer modify the response.
2. When an error is handled in gRPC, modify the context's response features to throw a descriptive message on the server when attempting to modify the response, e.g. `Response.StartAsync()`, `Response.Body`, `Response.BodyWriter`, `Response.AppendTrailer(...)`. More work, and feels potentially flaky. On the other hand the headers can still be modified and there is a descriptive error message.
3. Something else?

What do you think?

**Comment by anurse** [comment]
@Tratcher is going to follow up to figure more out here.

**Comment by ejona86** [comment]
I would expect Java/C/Go to all behave about the same way here, since headers vs trailers are semi-semantically important. The problem is that trailers were basically defined (although only in discussion amongst us? I don't see it in the PROTOCOL-HTTP2 doc)  as "HEADERS with endStream = true". That allows immediate delivery to the application as the frames are received.

This has caused trouble before with proxies, but the proxies ended up changing their implementation without filing a bug (I found out about it later; and there was some grumbling about the grpc implementation). This is something that could be changed, but we'd need to be a bit careful. We could rely on the presence of grpc-status, for example. If grpc-status is set, it is thought to be a trailers. We could then delay delivering the HEADERS in that case until we get the real endStream. There's multiple possible variations with various benefits.

Note, your issue is a bit different that the classic problem because it is pretty important that the middleware doesn't inject actual body data; that would produce quite confusing results (even if it is a grpc-framed message).

**Comment by JamesNK** [comment]
Discussed with @Tratcher and decided that CompleteAsync is the best option here.

Outbound middleware won't be able to modify headers when an exception occurs, but typically that is not something you would try to do anyway.
