### ISSUE TITLE
Accept @page routing and navigation with const string

### ISSUE THREAD

**Issue by bellagita** [aspnet/AspNetCore#17500]
### Enable routing and navigation with const string

Not Only :

    @page "/counter"
     <NavLink class="nav-link" href="counter">

but also:

    public static class Page
    {
        public const string Counter = "/counter";
        public const string FetchData = "/fetchdata";
        public const string Index = "/";
    }
    
    @page Page.Counter
    <NavLink class="nav-link" href=@Page.Counter>

its need only change visual studio razor tools to generate code:

        [Microsoft.AspNetCore.Components.RouteAttribute(Page.Counter)]

thats works fine

**Comment by javiercn** [comment]
@bellagita thanks for contacting us.

Instead of using the `@page` directive you can use the `@attribute` directive and specify the route attribute manually yourself.

That should allow you to use constants.

I'm closing this issue as the question has been answered. If you still run into issues feel free to comment on this issue and we'll re-evaluate.

**Comment by bellagita** [comment]
I try it: works good!

thanks.
