### ISSUE TITLE
Use ArrayPool in PasswordHasher

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#17532]
Can ArrayPool be used in [PasswordHasher](https://github.com/aspnet/AspNetCore/blob/9a1810c1dbe432fc7bc7e8bc68fa22ab787c0452/src/Identity/Extensions.Core/src/PasswordHasher.cs) to improve memory allocation? or it does not have such an impact since the array size of the bytes are low

**Comment by GrabYourPitchforks** [comment]
I strongly recommend against using `ArrayPool` for security-sensitive operations such as password hashing. The reason for this is that if there's a bug in a completely unrelated part of the system that causes a double-return to the pool (say, a race condition in the JSON stack or in the networking stack), the resulting memory corruption could result in password leakage. If you look at the recent commits which have been made to the _System.Security.Cryptography_ project, you'll see that we generally avoid `ArrayPool` in most of those code paths for this same reason.

If you absolutely need to avoid allocations (and in this particular code path it's probably not absolutely necessary), you could consider using `stackalloc`, falling back to a `new byte[]` (instead of `ArrayPool<byte>.Shared.Rent` if the allocation is too large. The DataProtection layer does something similar to this and could be used as a template. But do be cautioned that `stackalloc` introduces its own risks, so folks shouldn't generally shouldn't be encouraged to go down this path unless there's profiling evidence that such a change is worth the risk.

**Comment by blowdart** [comment]
What @GrabYourPitchforks said. There's too much risk for little to no benefit.
