### ISSUE TITLE
Need a way to validate a CSRF token that is not provided via a form field or HTTP header.

### ISSUE THREAD

**Issue by clement911** [aspnet/AspNetCore#17577]
When we implement oauth with a third party, we can provide a 'state' parameter that the oauth provider will pass back to us in our redirect url. This is useful to implement CSRF protection and ensure an attacker is not hitting our redirect url directly.
We want to generate a CSRF token programmatically to populate the state paramater, and then validate it when our redirect url is hit.

Currently there is a `IAntiforgery.ValidateRequestAsync(HttpContext httpContext)`, which works fine if the token is provided in a known form field or header.
However, the redirect url is a simple GET (which is ignored by this method) and in addition we have no control over the name of this parameter.

So, what we would need is a `IAntiforgery.ValidateRequestAsync(HttpContext httpContext, string token)` where we can explicitly pass the token to be validated.

What do you think?
@blowdart

**Comment by javiercn** [comment]
@clement911 thanks for contacting us.

Our OAuth authentication handler already does this. I would suggest you check the code for any of the authentication handlers that does this or use those directly.

**Comment by clement911** [comment]
I see.
Could you point me somewhere?

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L409 for an example.

I would suggest you don't do this on your own. I'm not completely sure what authentication mechanism you are using for your app. I suspect you are using cookies (which is why you are using Antiforgery?) so my first recommendation would be to move away from that, if you use a JWT you don't worry about CSRF.

**Comment by clement911** [comment]
Yes, we are using cookies.
We considered JWT but it seems that there are several severe limitations.
If I understand correctly, any time that you open a new tab (e.g click a permalink), you would have to authenticate again? That doesn't seem like a good user experience unless I'm missing something.

I had a look at the code you shared but I'm really lost.

Is there no API to validate a token that was generated with `AntiforgeryTokenSet GetAndStoreTokens(HttpContext httpContext)`?

**Comment by javiercn** [comment]
> If I understand correctly, any time that you open a new tab (e.g click a permalink), you would have to authenticate again? That doesn't seem like a good user experience unless I'm missing something.

That's not the case depending on how you do it. In most cases you either have a token stored in localStorage or the client can log the user in without user interaction provided they are logged in on the authorization server.

**Comment by clement911** [comment]
Ok, that's good to know and something for us to investigate at some point.
That being said, this is orthogonal to my original question here.

Take [Stripe's oauth](https://stripe.com/docs/connect/oauth-reference) for example.
How do we validate the token that we passed when they redirect back to us?

![image](https://user-images.githubusercontent.com/3426504/70137868-46ab7e80-168f-11ea-9fb9-1b5eac093a7e.png)

**Comment by javiercn** [comment]
@clement911 Use the OAuthHandler that asp.net core provides and it will do it for you. Otherwise, implement your own. The antiforgery support in ASP.NET Core is not suitable for this scenario.

See https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OAuth/src/OAuthHandler.cs for details. There are many already made available by the community https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-3.1 and all are based in the OAuth handler we provide.

If you insist on implementing it yourself, I suggest you look at the implementation of the OAuthHandler or the OpenIdConnectHandler for a strategy on how to manage the state, but I strongly discourage you from implementing your own auth.

As I said, this is not a scenario that our Antiforgery infrastructure is designed for.
