### ISSUE TITLE
Modification to HttpRequest extensions

### ISSUE THREAD

**Issue by Mart-web1** [aspnet/AspNetCore#17582]
### Is your feature request related to a problem? Please describe.
No, this isnt relating to an existing problem, however its related to functionality which I found confusing.

### Describe the solution you'd like
The EnableBuffering method that has been created within the following location extension class
"AspNetCore/src/Http/Http/src/Extensions/HttpRequestRewindExtensions.cs" uses an arbitrary value of 30KB as the maximum size of request which is allowed before the stream uses a temporary file on disk.  This has taken some time to locate this line of code and feels somewhat counter intuitive.  Would suggest the default behaviour is to buffer the stream into memory with the option to overload setting a max size at which point its buffered to disk.

Interested if anyone else has been caught out by this?

**Comment by Tratcher** [comment]
> Would suggest the default behaviour is to buffer the stream into memory with the option to overload setting a max size at which point its buffered to disk.

That's pretty dangerous, people regularly use this to buffer multi-GB uploads which would crash your app if done in memory.

That threshold is configurable in the other overloads.

**Comment by anurse** [comment]
This is by design. You can set the threshold manually via [an overload of `EnableBuffering`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-3.0#Microsoft_AspNetCore_Http_HttpRequestRewindExtensions_EnableBuffering_Microsoft_AspNetCore_Http_HttpRequest_System_Int32_). The API is very commonly used to buffer multi-GB file uploads and our default value is chosen intentionally.
