### ISSUE TITLE
Strange behavior/bug with the new stopPropagation directive

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#17657]
Hello guys, i actually met a problem with the stopPropagation directive which not works in some case.

I originally open this problem to a contextMenu library I use : https://github.com/stavroskasidis/BlazorContextMenu/issues/71

But is definitively a blazor problem. This is the step to reproduce (thanks to @stavroskasidis which investigate the problem)

It seems that it has something to do with combining js events with c# events.
Here are two code samples, one that works (only C# events) and one that doesn't (js plus c# event)

- Sample 1 - Using only C# events (this works)
````
@inject IJSRuntime JsRuntime
<div>
    <div style="width:400px; height:400px; background-color: blue" 
             @oncontextmenu="ParentClick">
        <div style="width:200px; height:200px; margin: auto; background-color: red" 
                       @oncontextmenu="ChildrenClick" 
                       @oncontextmenu:stopPropagation @oncontextmenu:preventDefault>
        </div>
    </div>
</div>

@code{
    protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }

    protected async Task ParentClick()
    {
        //this is not called. Working correctly
        await this.JsRuntime.InvokeVoidAsync("alert", "parent was clicked");
    }
}
````

- Sample 2 - Using a js event on parent but C# on child (this DOESNT work)
````
@inject IJSRuntime JsRuntime
<div>
    <div style="width:400px; height:400px; background-color: blue" 
              oncontextmenu="alert('parent was clicked');">
        <div style="width:200px; height:200px; margin: auto; background-color: red" 
             @oncontextmenu="ChildrenClick" 
             @oncontextmenu:stopPropagation @oncontextmenu:preventDefault>
        </div>
    </div>
</div>

@code{
    protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }
} 
````

Can you help us with this problem ?

thanks !

**Comment by SteveSandersonMS** [comment]
I'm afraid this is working as expected, though I understand it's not the behavior you want.

To maximise performance, Blazor uses an event delegation system. That is, for each type of even you're using, Blazor listens only at the document root and knows how to dispatch events to the right places. This means you can have vast numbers of Razor event handlers being created and destroyed all the time without increasing the strain on the DOM/JS side. Normally, developers don't have to see or think about this because normally it just behaves exactly as expected and desired.

However, this does impose limitations when it comes to interacting with JS events too. For example, since `@oncontextmenu:stopPropagation` is handled inside the delegated listener at the document root, it only prevents propagation through .NET handlers. It can't stop propagation through JS handlers, because they have already run before our delegated listener did.

So, if you want to stop propagation of JS events, you'll need to use JS code to call `event.stopPropagation();`. Hope that makes sense!
