### ISSUE TITLE
Blazor Webassembly Re-Render Component

### ISSUE THREAD

**Issue by FirstcodGit** [aspnet/AspNetCore#17665]
Can we re-render the components in the static method?

### js
_connect.on("ChangeData", (item) => {
    DotNet.invokeMethodAsync("project path", "staticMethod", item);
}

### Razor Component
TestComponent data="dataList"

### Blazor webassembly:
[Parameter] public static List<Data> dataList {get;set;}

[JSInvokable]
public static void staticMethod(List<Data> list)
{
    dataList = list;
    ?TestComponent re-Render
}

**Comment by SteveSandersonMS** [comment]
In order to render a component, you need to have a reference to the component instance you want to render. Your `staticMethod` doesn't have such a reference, so it has no way of saying which component it wants to render.

Instead of doing this, consider replacing it with an instance method on the component itself. The instance method can then simply call `StateHasChanged()` on itself to trigger re-rendering. See docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#instance-method-call

**Comment by FirstcodGit** [comment]
Thanks, I did as in the example;

**Razor**
var newObj = DotNetObjectReference.Create(this);
 jsRuntime.InvokeVoidAsync("Services.alerts", id, newObj);

[JSInvokable]
public async void ReRender(long id)
{
        var response = await Http.DeleteAsync($"https://localhost:44386/Member/{id}");
        //Console.WriteLine(response.StatusCode);
        StateHasChanged();
}
**Js**
newObj.invokeMethodAsync("ReRender", id);
