### ISSUE TITLE
SignalR doesn't use NewtonsoftJsonProtocol when parsing Handshake request

### ISSUE THREAD

**Issue by kroymann** [aspnet/AspNetCore#17694]
### Describe the bug
When configuring SignalR to use the NewtonsoftJsonProtocol via `services.AddSignalR().AddNewtonsoftJsonProtocol()` I would expect _all_ JSON parsing and serialization to use Newtonsoft, but it appears that the initial handshake logic ignores this and uses System.Text.Json to parse the request.  This is problematic for me as there is a client of my service that is passing up a handshake request using single quotes rather than double quotes which leads to this exception:

```
System.Text.Json.JsonReaderException: ''' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader)
   at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseRequestMessage(ReadOnlySequence`1& buffer, HandshakeRequestMessage& requestMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.HandshakeAsync(TimeSpan timeout, IReadOnlyList`1 supportedProtocols, IHubProtocolResolver protocolResolver, IUserIdProvider userIdProvider, Boolean enableDetailedErrors)
```

From reading the code it has become clear to me that the IHubProtocol is not involved in the handshake process, which explains why I hit the exception above, but given that the NewtonsoftJsonProtocol is being touted as the preferred way of maintaining compatibility with clients that require/expect the behavior seen in prior Newtonsoft-based version of SignalR, this feels like an oversight.  As it currently stands I cannot update my service from AspNetCore 2.2 to 3.1 as there is no way to continue supporting this client.  I am working on getting the client updated to use double quotes instead of single quotes, but ideally using the NewtonsoftJsonProtocol should have made that unnecessary.

### To Reproduce
1. Create a simple SignalR app and configure it to use to the NewtonsoftJsonProtocol.
2. Attempt to connect via a client that passes up non-standard JSON (eg. with single quotes)
3. Observe that the handshake fails due to an exception being thrown in System.Text.Json, despite having specified that Newtonsoft should be used instead.

### Further technical details
- ASP.NET Core version 3.1.0

**Comment by davidfowl** [comment]
What client is it?

**Comment by BrennanConroy** [comment]
> there is a client of my service that is passing up a handshake request using single quotes rather than double quotes which leads to this exception

Unfortunately, that is the expected behavior, single quotes around names and values is invalid JSON and not a supported scenario. Before, the client was getting lucky that we were using Newtonsoft internally and it supports everything, so single quotes "worked".

Configuring the protocol for the server/client to use only affects the main protocol messages. Negotiate and Handshake have always been special and are only ever JSON and not affected by any user settings.

**Comment by kroymann** [comment]
> What client is it?

@davidfowl The client is a Unity based game using an addon called "Best HTTP Pro" to handle HTTP and SignalR traffic.  The client is currently using an older version of the "Best HTTP Pro" addon in which the SignalR handshake used a hard-coded text string containing single quotes.  From reading the release notes on newer versions of that addon, I see comments about "Improved AspNet Core 3 compatibility" under a SignalR Core heading, so it seems likely the author of that addon has already addressed this issue in their code.

> Configuring the protocol for the server/client to use only affects the main protocol messages. Negotiate and Handshake have always been special and are only ever JSON and not affected by any user settings.

@BrennanConroy I completedy understand this, especially after digging into the SignalR codebase in order to debug why my game client could no longer connect after I tried updating this server to AspNet Core 3.1.  That said, I wish there was a way to indicate that I want to use Newtonsoft for the negotiation and handshake so that I could update my server without having to first fix the clients.  Eventually once all of the clients have been updated appropriately, I plan to stop using Newtonsoft altogether in order to take advantage of the System.Text.Json performance improvements, but in the meantime I'd still like to be able to benefit from the rest of the performance improvements that came with AspNet Core 3.0.

**Comment by anurse** [comment]
The handshake is expected to be a strictly-conforming JSON object, so we don't allow configuration of the serializer. I don't think we're going to change that since it's pretty clearly defined in the spec as *always* being a JSON message (and [JSON strictly requires the use of `"`](https://www.json.org/json-en.html), regardless of Newtonsoft.Json's permissive behavior).

It is unfortunate that Newtonsoft.Json was this permissive as it means previous versions of SignalR accepted it, but it's going to be very costly to make this flexible again since System.Text.Json doesn't provide any options to permit `'`, so it would require a change to System.Text.Json.

This is just one of the places the Newtonsoft.Json compat layer falls short. Making that configurable would be counter to the design of the handshake message.
