### ISSUE TITLE
WCF client: Type 'System.ServiceModel.FaultException' cannot be serialized.

### ISSUE THREAD

**Issue by y-lobau** [aspnet/AspNetCore#17700]
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
12:54 PM OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

Visual Studio CE 2019 v16.4.0
```
I'm trying to consume WCF service. Proxy-reference was generated using VS Connected Service based on WSDL. Then when running RPC-method on Reference class im getting the following inner exception below. The call to service is fine - i can see it in fiddler.

`Type 'System.ServiceModel.FaultException' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.`

I checked FaultException class - it's public with parameterless constructor:
`...packages\system.servicemodel.primitives\4.7.0\ref\netcoreapp2.1\System.ServiceModel.Primitives.dll`
Looks as a bug to me.

**Comment by blowdart** [comment]
@mconnew does this belong in your [repo](https://github.com/CoreWCF/CoreWCF)?

**Comment by mconnew** [comment]
This is being tracked in dotnet/wcf#3984.  
As mentioned in that issue, passing a FaultException, (or any exception for that matter) isn't something that's generally done in WCF services. It's a bit of an anti-pattern as exceptions are meant for code flow control and not data objects. If you throw a FaultException from a service, it gets turned into a SOAP Fault message and WCF does **not** serialize the FaultException itself. On the client side a FaultException is instantiated with the details from the SOAP Fault and then thrown. Having said that, we do plan to support it because even though it's not a recommended way to do things, strictly speaking there's not a technical reason to not support it, it's just a bit of a strange way to do things.
@blowdart, can you close this issue (I don't have permission to close it) as it's being tracked in the WCF repo.

**Comment by blowdart** [comment]
Closing as external.
