### ISSUE TITLE
@bind="" and @oninput="" issue Blazor

### ISSUE THREAD

**Issue by faisal5170** [aspnet/AspNetCore#17702]
below is my HTML content 

 <input type="text" id="txtSearch" placeholder="Search Titles..." class="form-control" @bind="searchTerm" @oninput="@FilterRecords" />

@code {
    private string searchTerm;

 public async Task FilterRecords(EventArgs args)
    {
//code
    }

but when I press key searchTerm property get previous values like If I press "a" it will take null, if I press "ab" it will take "a", press "abc" will take "ab" etc..
}

**Comment by SteveSandersonMS** [comment]
Yes, this is because the `oninput` event runs before `onchange`, so your `FilterRecords` method runs before the `@bind` handler has run. By default, `@bind` attaches to the `onchange` event.

As an alternative, consider removing `oninput`, and instead use `@bind` with `@bind:event="oninput"`. Then you can put arbitrary logic to react to updates inside the setter of whatever property you're writing to. This is simpler because then you only have one event handler to deal with.

**Comment by faisal5170** [comment]
Thanks, it works, I'm adding a solution below so it will be helpful for others.

<input type="text" id="txtSearch" placeholder="Search Titles..." class="form-control" @bind="SearchTerm" @bind:event="oninput" />

@code {
    private string searchTerm;
    private string SearchTerm
    {
        get { return searchTerm; }
        set { searchTerm = value; FilterRecords(); }
    }

    public void FilterRecords()
    {
        //code
    }
}
