### ISSUE TITLE
Blazor Select binding doesn't bind initial value

### ISSUE THREAD

**Issue by willdean** [aspnet/AspNetCore#17739]
### Describe the bug
In s/s Blazor, a bound variable which is itself initialised to null does not reflect the initial state of a select box.
This bug is #10481 and possibly #9716 but these have been closed as dups or fixed, without it actually being fixed.
I'm going to describe it again: I'm seeing it in 3.1, so it's definitely still around.

### To Reproduce

* Create a default server-side Blazor project in VS (ASP.Net Core 3.1, VS 16.4)
* On some page of the demo app (I use the counter page) add the following markup:
```
<select @bind="SelectionValue">
    <option>Option A</option>
    <option>Option B</option>
</select>
<button @onclick="TestClick">Test Click</button>
```
and the following code
```
    string SelectionValue {get;set;}

    void TestClick()
    {
        Console.WriteLine($"Selection: '{SelectionValue}'");
    }
```

* Start the application in such a way as to be able to see the console
* Navigate to the page but don't touch the select box (it will be showing "Option A")
* Click on the "Test Click" button
* Observe that the bound variable is null (i.e. you get `Selection: ''` printed to the console)
* The only way to actually get "Option A" is to change the selection to Option B and then change it back.

I don't need a work around (it's easy), but this behaviour doesn't feel like the 'principle of least surprise' - it's counter-intuitive that you wouldn't get the displayed value of the selection box in the bound variable.
The fact that the bug's been closed as fixed/dup previously makes me think this wasn't the original intention that it should work like this.

### Further technical details
- ASP.NET Core version 3.1.100
- The IDE  VS16.4 on Win10

**Comment by SteveSandersonMS** [comment]
This is behaving as expected. Using `@bind` on an input/select writes to your model only when the "change" event occurs. It doesn't write to the model just because a `@bind` exists.

In this scenario, you shouldn't have the initial value of `SelectionValue` be something that can't be represented by the dropdown, because then you will have this inconsistent state until the user changes the dropdown value. Instead, set the initial value of `SelectionValue` to correspond to one of the entries in the dropdown, and then everything will be consistent.

Hope that makes sense.

**Comment by willdean** [comment]
Thanks Steve.
