### ISSUE TITLE
The specified deps.json [*.deps.json] does not exist after VS update to 16.4

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/842951/the-specified-depsjson-depsjson-does-not-exist-aft.html)._

---
While following this instruction:
https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio
during running “Add-Migration InitialCreate” in PMC i suffered error: The specified deps.json [RazorPagesMovie\RazorPagesMovie\RazorPagesMovie.deps.json] does not exist.
RazorPagesMovie.deps.json file places in “RazorPagesMovie\RazorPagesMovie\bin\Debug\netcoreapp3.0”

Visual studio Community 2019 v. 16.4

---
#### Visual Studio Feedback System on 12/4/2019, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Could you share a minimal project that reproduces this error?

**Comment by kJacobi** [comment]
I am running into same issue.   I have a core 3.1.100 web api, and I'm using VS 2019 16.5 Preview 1.0. 
I'm trying to add-migration.   I get the following result in package management console:  
![image](https://user-images.githubusercontent.com/15020825/71122432-94a3a480-21ae-11ea-9f2d-0c251b637e97.png)

..I go to check and sure enough the file is there.   I gave full permissions to Everyone so that should be the issue either.  Please help!   Btw, this application is hosted on a TFS server.   I copied the code to my thumb drive and brought it home to my laptop.   I opened it up and added migration without any issue.  It therefore, seems to be some kind of environment issue.   Could it be that it works when not bound to version control?

**Comment by pranavkm** [comment]
@kJacobi can you file a separate issue with a minimal project that reproduces the error?
