### ISSUE TITLE
wrong form action in area 

### ISSUE THREAD

**Issue by sinand** [aspnet/AspNetCore#17785]
I was using
**< form  asp-area="AdminPanel" asp-controller="Login" asp-action="Index"  asp-route-returnurl="@ViewData["ReturnUrl"]" >**

tag and it was giving
**< form method="post" role="form" action="/AdminPanel/Login?returnurl=%2Fadminpanel" >**

After upgrading 2.2 to 3.1 this tag is giving 
**< form action="/Login?returnurl=%2Fadminpanel&amp;area=AdminPanel" method="post" >**

**Comment by javiercn** [comment]
@sinand thanks for contacting us.

Did you change anything in your startup code? We migrated MVC to use endpoint routing and you need to map controllers and pages independently using EndpointRouting.

I suggest you create a new MVC/RazorPages template to see the changes in startup and apply them to your project. For more details here is the [migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio).

If after this it doesn't work, please share a minimal repro project with us so that we can help you.

**Comment by javiercn** [comment]
I'm closing the issue for now as the question has been answered. Feel free to comment with additional information and we'll re-evaluate.

**Comment by sinand** [comment]
[TestProject.zip](https://github.com/aspnet/AspNetCore/files/3955402/TestProject.zip)
Thanks for your answer. I created a test project with 3.1 and add my admin panel scenario.
you can see the problem at the admin panel login page.

**Comment by sinand** [comment]
I changed order of endopint mappings and it is working fine now.
