### ISSUE TITLE
How can I  make blazor server  support IE10?

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#17806]
How can I  make blazor server support IE10 in core 3.0/3.1???

**Comment by javiercn** [comment]
@kugarliyifan thanks for contacting us.

Unfortunately Blazor server doesn't support IE 10 nor IE 11. IE11 can be made to work with some third party polyfills, but it's not something we currently support.

You can try using this third party polyfill and check if it meets your needs https://github.com/Daddoon/Blazor.Polyfill and allows you to make it work in IE10.

Otherwise, IE10 and IE11 is not something that we currently support.

**Comment by sven5** [comment]
I was successful in running Blazor on IE11 with the help of the mentioned Polyfills.
Please read [here](https://github.com/aspnet/AspNetCore/issues/9436)

**Comment by kugarliyifan** [comment]
> I was successful in running Blazor on IE11 with the help of the mentioned Polyfills.
> Please read [here](https://github.com/aspnet/AspNetCore/issues/9436)

OK,,,thank you ....
