### ISSUE TITLE
.Net Core 3.1.0 Hosting Bundle installs Preview 3

### ISSUE THREAD

**Issue by DrGriff** [aspnet/AspNetCore#17817]
Navigate to: [Download .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1)

In the right-hand column "Run apps - Runtime", select the Window's [Hosting Bundle](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.0-windows-hosting-bundle-installer).

When this is executed on an existing Window 2012 that has never had .NET Core installed, we end up with:

- Microsoft .NET core 3.1.0 - Windows Server Hosting
- Microsoft .Net Core Runtime - 3.1.0 Preview 3 (x64)
- Microsoft .Net Core Runtime - 3.1.0 Preview 3 (x86)

It should install the full release version.

**Comment by javiercn** [comment]
@DrGriff thanks for contacting us.

@Pilchie FYI.

@aspnet/build Thoughts?

**Comment by dougbu** [comment]
This is a known issue covered in dotnet/runtime#492 The issue turns out to be relatively minor because the final preview release was almost identical to 3.1 GA. However the branding is disconcerting.

The hosting bundle problem will not recur in 3.1.1. Similar issues mentioned in dotnet/runtime#492 were fixed by republishing the affected installers. (We did not rebuild the hosting bundle due to concerns about invalidating the SHA for the AspNetCore part of the release.)
