### ISSUE TITLE
Class`s namespace in library in name of library`s default namespace not others.

### ISSUE THREAD

**Issue by xyz0822** [aspnet/AspNetCore#17845]
like `OptionsConfigurationServiceCollectionExtensions`  class in `Microsoft.Extensions.Options.ConfigurationExtensions`,why the class`s namespace was _Microsoft.Extensions.DependencyInjection_ and not the 'Microsoft.Extensions.Options.ConfigurationExtensions'?
it has the following confusing:
1:may cause the developer hard to find the real class`s dll in the namespace`s dll.
2:may lead the project`s developer all free to use other`s namespace and may be in a mess in manager of the class`s or library`s namespace.
So does it mean that the namespace such as this is what we disucssed and all agree to do like this?

**Comment by javiercn** [comment]
@xyz0822 thanks for contacting us.

This has been a convention since the inception of asp.net core. We do put some types in special namespaces to support discovery within your startup class without having to pollute Startup.cs with a separate namespace per used primitive.

That improves the main use case for these types which is within the app configuration in Startup.cs

/cc: @davidfowl in case he wants to add something :)
