### ISSUE TITLE
[Blazor Question] How to still use client side addEventListener

### ISSUE THREAD

**Issue by LMSSonos** [aspnet/AspNetCore#17923]
I'm using a bootstrap template (metronic) which has for instance a menu that is collapsible. For that the template makes some plain javascript calls to bind the events. After adding the template to a Blazor solution, the events where not bound. In the original code they have a javascript like this. The code is included in `myscripts.js` which is referenced from the `_Hosts.cshtml`
```
element.addEventListener(type, handler);
```
This event does never fire. If I change the event registration to 
```            
$("body").on('click', "#myid", myfuction());
```
it works. So is there a way to still use addEventListener method with Blazor? Or is there anything else I need to make different?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's still unclear what your specific problem is. You can read detailed documentation about JSInterop in Blazor, which most probably help you resolve your own issue: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1
If, however, you still will be facing an issue which you think may be caused by the framework, please provide a repro project for a further investigation.

**Comment by LMSSonos** [comment]
@mkArtakMSFT thanks for your reply. To reproduce, I use the new Blazor app in VS2019 (c#)

Pages/Index.razor I add this code:
```
<a href="#" id="link1" onclick="test1()">link1</a>
<br />
<a href="#" id="link2">link2</a>
```
In the Pages/_Host.cshtml I add following code (first line exists)
```
    <script src="_framework/blazor.server.js"></script>
    <script>

        function test1() {
            alert("test1 worked");
        }
        function test2() {
            alert("test2 worked");
        }
        document.getElementById("link2").addEventListener("mouseup", test2());

    </script>
```

What now happens is, that link1 works as expected. The "Test2 worked" shows up when the page is loaded without any interaction, but when clicking link2, nothing happens.

When I add jquery and use  ```$("body").on('click', "#link2", test2()); ```  it works as well. Its only the `addEventListener`which does not seem to work as expect (or maybe I do something wrong ;-)

**Comment by pranavkm** [comment]
@SteveSandersonMS could you have a look?

**Comment by SteveSandersonMS** [comment]
`document.getElementById` can only return references to elements that exist within the DOM now. If a new matching element gets added later, that's a new element and your code hasn't added any event handlers to it yet.

The fact that elements can be added and removed dynamically is the whole reason why jQuery has the `.on` function. If you want to add event listeners to all current *and future* matching elements, then you should use `.on` or something like that.

This isn't specific to Blazor but would apply to all technologies that modify the DOM dynamically.

There is a more idiomatic way to approach this in Blazor. Instead of putting your JS code directly inside your `_Host.cshtml` (where it can only run once), consider invoking the initialization logic from a Blazor component's `OnAfterRenderAsync` method, so that component's rendered elements get initialized whenever it is first rendered. Here's a tutorial: https://blazor-university.com/javascript-interop/calling-javascript-from-dotnet/passing-html-element-references/
