### ISSUE TITLE
Advantages of aspnetcore supported Health Checks vs explicit controller HttpGet

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/AspNetCore#17958]
My current aspnetcore application has explicit Web Apis for performing health checks. In other words, I have explicit HttpGets defined in a Web API Controller.

What advantages do I gain by moving to the aspnetcore supported ways of health checks as described in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1

Personally, I like the new approach, but I am wondering if it is currently worth my time to make the changes.

**Comment by pranavkm** [comment]
> What advantages do I gain by moving to the aspnetcore supported ways of health checks

One of the primary advantages is that you could choose to use one of the many health check libraries for your health checks rather than building one from scratch. However if you have something that already works for you, you have to weigh the cost of re-using code over re-testing changes to make sure it works as per as your expectations \ requirements.

**Comment by rynowak** [comment]
If your health check is just "is the server running" - ie you don't check anything in particular and just respond to the ping, then that's functionally equivalent to using `MapHealthChecks()` without registering any checks.

I'd second what @pranavkm said, the health checks system has extensibility and some other nice features that you'd want if you're doing something more in depth. 

if you're happy with what you're doing there's no strong need to change it, it's not wrong.

**Comment by GoFightNguyen** [comment]
Thanks @rynowak and @pranavkm
