### ISSUE TITLE
Question: How to get literal content before child taghelpers modify it?

### ISSUE THREAD

**Issue by katymariehughes** [aspnet/AspNetCore#18107]
I have created a tag helper for code snippets. I want to display the literal markup of any child elements in the output, i.e.

```html 
<code-snippet>
    <btn>Button tag helper</btn>
</code-snippet>
```

should display in the browser as

```html 
<btn>Button tag helper</btn>
```

but instead it displays as 

```html 
<button type="button">Button tag helper</button>
```

because of another button tag helper I have created.

output.GetChildContentAsync().GetContent() appears to execute child tag helpers, but I want the literal markup. How do I do this without having to use the Razor @: plain text directive as below? It makes formatting (esp. auto) difficult.

```html 
<code-snippet>
@{
    @:<btn>Button tag helper</btn>
}
</code-snippet>
```

Thank you!

**Comment by pranavkm** [comment]
@NTaylorMullen would you be able to respond?

**Comment by NTaylorMullen** [comment]
Hey @katymariehughes, it's definitely not ideal but sadly TagHelpers don't allow you to get your child content without invoking it. 

Therefore in order to get the type of result you're expecting you'll have to do something like your `@:` alternative. Here's two other options:
- `&lt;btn&gt;Button tag helper &lt;/btn&gt;`
- `<!btn>Button tag helper </!btn>`
