### ISSUE TITLE
Revisit how application identifier is generated

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2512]
_From @Eilon on Friday, May 5, 2017 11:15:40 AM_

Perhaps in the case of IIS (and thus Antares), ANCM should flow the IIS "app id" so that Data Protection could use it.

cc @blowdart @DamianEdwards @davidfowl @Tratcher 

_Copied from original issue: aspnet/DataProtection#229_

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, May 5, 2017 12:06:16 PM_

This is probably a hosting issue

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, May 5, 2017 1:53:06 PM_

or ANCM + IISIntegration

**Comment by aspnet-hello** [comment]
_From @davidfowl on Saturday, May 6, 2017 12:59:38 AM_

We need to also consider xplat and service fabric scenarios (clusters in general).

/cc @glennc

**Comment by aspnet-hello** [comment]
_From @johnkors on Saturday, May 20, 2017 8:45:57 AM_

Are we talking about [DataProtectionUtilityExtensions](https://github.com/aspnet/DataProtection/blob/rel/1.0.3/src/Microsoft.AspNetCore.DataProtection/DataProtectionUtilityExtensions.cs#L42) ? 

It's by default causing invalidation of cookies when used in conjunction with Octopus, which deploys to a different physical path every deploy. 

@anderaus wrote a piece about the issues here: http://blog.novanet.no/a-pile-of-anti-forgery-cookies/

**Comment by aspnet-hello** [comment]
_From @davidfowl on Saturday, May 20, 2017 10:08:28 AM_

Yes, it's a really bad default.

**Comment by blowdart** [comment]
@muratg We should revisit this again. It slipped past 2.1, so I've put it in 2.2 so it doesn't drop off.

**Comment by natemcmaster** [comment]
It seems we agree the current default is bad, but I don't see a clear proposal for how to fix this, so I spent a little time brainstorming alternatives for the application identifier. 

The only alternative I could think of that is somewhat stable across releases, clusters, and updates to the app is `EntryAssembly.Name + EntryAssembly.PublicKeyToken`. Don't include assembly version because that often changes.

As a part of my brainstorming, I considered a few other alternatives, and here is why I think we should exclude them:

* HostingEnvironment.ContentRootPath. (This is the current default.) As noted, various deployment tech may result in unique content root paths per deployment.
* An entry assembly attribute. This requires adding a new thing to the SDK. Besides, we'd probably set the default value to AssemblyName anyways.
* Anything that looks at the content of the application (such as a hash of the entry assembly). Excluded because this may be consistent across the same app deployed to multiple machines, it will not be consistent between new builds of the same app.
* The IIS or Azure site name. Excluded because not everything is hosted in these environments.

Thoughts @davidfowl @glennc @blowdart?

**Comment by blowdart** [comment]
IIS/Azure would be a good idea, if we detect we're on those platforms, but it'd only work for in-proc, otherwise we'd have to get it added to ANCM

AssemblyName + Strong Name if it exists sounds "ok". Maybe slap some other attributes on there if they exist, company perhaps?

It's overridable anyway.

**Comment by pakrym** [comment]
Do we need to handle some kind of backwards compatibility here?

**Comment by pakrym** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Changing the default will cause a global sign-out for all applications, even those unaffected by the issue. That seems pretty dramatic for a minor release, no? Affected users have a simple workaround of setting the identifier through code.

This seems like something that should wait until 3.0.

**Comment by pakrym** [comment]
Talked to @blowdart. We are going to do this in 3.0.0

**Comment by Tratcher** [comment]
Is the proposal for a change in DataProtection or in Hosting? Note Hosting's ApplicationName is also used by MVC for controller discovery.

**Comment by muratg** [comment]
What's the proposal here? @blowdart

**Comment by blowdart** [comment]
Fix it so it works as it's supposed to. @natemcmaster's suggestions seem like a good start. 

@GrabYourPitchforks  thoughts here?

**Comment by muratg** [comment]
There's a little time left in preview2. If we can't figure out a plan in the next couple days, we'll move this out to preview3.

**Comment by pakrym** [comment]
Do we want to go with `EntryAssembly.Name + EntryAssembly.PublicKeyToken` or something similar to user secret id? Switching default to `EntryAssembly.Name + EntryAssembly.PublicKeyToken` would break all existing apps when migrating to 3.0

**Comment by johnkors** [comment]
So if I change the assembly name of my web app using cookies, it will cause a logout of all my users on deploy...?

**Comment by muratg** [comment]
@blowdart What's your thoughts on this? Ideally, we don't want to break existing apps when they migrate (i.e. logging out all of their users.)  Do you have any alternative way to prevent this?

**Comment by blowdart** [comment]
No, but honestly I don't care about a single logout everyone event when you switch a major version of core. That is frankly a minimal disruption compared to fixing isolation.

**Comment by natemcmaster** [comment]
I wish there was something on a per-project basis which was unique and immutable. Assembly names, file paths, public key tokens, and others are all subject to change. 

Just brainstorming: 'classic' C# project templates use to include a unique `GuidAttribute` in the generated AssemblyInfo.cs file. Although meant for COM, it provides the characteristics we are looking for. What if we relied on an assembly attribute on EntryAssembly instead? We could reuse `GuidAttribute` or another API of our choosing. The assembly attribute from the .csproj file, or generate it in the AssemblyInfo.cs file.

```xml
<!-- This GUID is used to persist keys and protected data across multiple instances of the app. Changing this may break users' cookies or other protected data. -->
<AssemblyGuid>{ABCXYZ123}</AssemblyGuid>
```

```c#
[assembly: Guid("ABCXYZ123")]
```

**Comment by blowdart** [comment]
Oh that's an interesting idea

**Comment by pakrym** [comment]
We already have the prior art on this topic: `UserSecretsId`. Gets generated on project creation and put into `csproj`.

**Comment by muratg** [comment]
Either case, we'll still get to break folks (i.e. cause their users to logout) when they move to 3.0, right? No way around that?

@GrabYourPitchforks What's your thoughts on this?

**Comment by pakrym** [comment]
@muratg this new ID would be added only to new projects that would opt them in into new behaviour. Existing projects would not change.

**Comment by pakrym** [comment]
Ping @blowdart @muratg @Tratcher 

Let's decide on the direction here.

**Comment by muratg** [comment]
@blowdart  please call it as the PM. :)

**Comment by blowdart** [comment]
UserSecrets is a crap prior art because that shouldn't go into production :)

Does deleting AssemblyGuid cause compilation to stop?

Honestly why not combine the two;


<PropertyGroup>
  <AspNetCoreApplicationId>{RANDOMGUIDSETONPROJECTCREATION}</AspNetCoreApplicationId>
</PropertyGroup>

in the csproj?

**Comment by pakrym** [comment]
> Does deleting AssemblyGuid cause compilation to stop?

It shouldn't. Some people just don't care so we should use a sensible default.

> Honestly why not combine the two;
> {RANDOMGUIDSETONPROJECTCREATION}
> in the csproj?

That's what UserSecrets is supposed to be doing (https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.ProjectTemplates/StarterWeb-CSharp.csproj.in#L5) except I'm not sure if it actually gets initialized with a random value on creation.

**Comment by blowdart** [comment]
I think something more specifically named would be better that reusing a COM attribute :)

**Comment by pakrym** [comment]
Oh, sure, I missed that we are talking about actual COM attribute. I was thinking about `DataProtectionApplicationDescriminatorAttribute`

**Comment by blowdart** [comment]
That works :) And fall back to current default if it's not present.

**Comment by pakrym** [comment]
After talking offline with @blowdart and @Tratcher we concluded that having the discriminator to be content root is a more secure default.

There is an easy and documented workaround https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#setapplicationname for customers that want the more relaxed behaviour.

**Comment by johnkors** [comment]
Will affect all customers/users of Octopus,  @paulstovell.
