### ISSUE TITLE
Consider adding timeout on HealthCheck

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2577]
_From @ycrumeyrolle on Friday, October 27, 2017 2:05:58 PM_

Adding a timeout on each healthcheck will avoid a non-responding external resource to cause some problems.

_Copied from original issue: aspnet/Diagnostics#418_

**Comment by mkArtakMSFT** [comment]
@rynowak, @glennc assigned this to you for consideration. Although I feel like this should already be available per each HealthCheck handler.

**Comment by rynowak** [comment]
We're tentatively considering this for post-preview3. The value here would be us providing a consistent experience for configuring a timeout per-health-check. Cancellation in .NET is always cooperative so the onus is on each HC author to honor the cancellation token we provide.

Since we already provide a token, there's no risk if don't do this in this release.

The system as a whole already supports global timeouts:
- pull based health checks (middleware) cancel on request abort
- push based health checks have a configurable global timeout

/cc @xabaril - did you see much demand for configuring timeouts on each health check

**Comment by unaizorrilla** [comment]
Hi @rynowak,

A **timeout** opt-in for _pull based_ can be a good idea. Some checks can took a lot of time before fail, probably you can do on _pull_ the same pattern already used on _push_ based, ie, create a linked token source with cancel after **global configured timeout** and used this on each health check.

There is how timeout is used on BeatPulse for pull based 

https://github.com/Xabaril/BeatPulse/blob/master/src/BeatPulse/Core/BeatPulseService.cs

**Comment by unaizorrilla** [comment]
`await Task.WhenAny(livenessTask, Task.Delay(options.Timeout, cancellationTokenSource.Token)) == livenessTask`

**Comment by JoshKeegan** [comment]
Is this still planned for 3.0.0-preview5?

**Comment by JoshKeegan** [comment]
> 
> 
> Is this still planned for 3.0.0-preview5?

Nevermind, I see it's been moved to the backlog!

Is anyone working on, or planning on working on this?

**Comment by rynowak** [comment]
This has actually already been done. https://github.com/aspnet/Extensions/blob/master/src/HealthChecks/Abstractions/src/HealthCheckRegistration.cs#L163
