### ISSUE TITLE
Apparently Random Error: "Antiforgery token validation failed. The antiforgery cookie token and request token do not match."

### ISSUE THREAD

**Issue by wessleym** [aspnet/AspNetCore#2882]
## Background ##
I have a relatively new ASP.NET Core 2 site.  It's running on just one server (Windows Server 2012 R2, IIS 8.5), and I only restart the site once every few days when I upload an update.  About once a day, a user's request fails due to rejection by the anti-forgery system.  These are POST requests, and there's nothing particularly special about them.  I'm including the anti-forgery value in the POST request, and 99% of the time, POST requests work.  But when they don't, the stdout log says, "Antiforgery token validation failed. The antiforgery cookie token and request token do not match."  I've already posted this question on Stack Overflow and the ASP.NET Core forums, and I haven't gotten any useful answers.

## Errors ##
I've included the relevant portions of the stdout log below.

    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
          Request starting HTTP/1.1 POST [domain redacted] application/x-www-form-urlencoded 234
    info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter[1]
          Antiforgery token validation failed. The antiforgery cookie token and request token do not match.
    Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery cookie token and request token do not match.
       at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
       at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
    info: Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker[3]
          Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'.
    info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
          Executing HttpStatusCodeResult, setting HTTP status code 400
    info: Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker[2]
          Executed action /Index in 2.6224ms
    warn: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[1]
          Antiforgery validation failed with message 'The antiforgery cookie token and request token do not match.'.

For requests that result in the above stdout output, `IAntiforgery.IsRequestValidAsync` agrees by returning false.  Notice the error message "The antiforgery cookie token and request token do not match."  Here's a reduced example of a failed POST request and the associated cookie.

`POST: __RequestVerificationToken=
CfDJ8F9Fs4CqDFpLttT96eZw9WHjWfHO8Yawn35k4Yq3gDK5n1TDJDDiY5o86VQs1_qOVIYBydCizBU4knb7Jmq1-heGhwnMu2KmhUIiAd0xI7Sudv3GX-J0OI6wRfiPL4L1KRs2Pml8dbsDfwemewBqi18`

`Cookie:  .AspNetCore.Antiforgery.ClRyCRmWApY=CfDJ8F9Fs4CqDFpLttT96eZw9WFtJht41WcNrmgshi2pFGwcxhr0_0hvINQc7Yl9Cbjhv-TiSNXeEctyKborLI49AcjHfWIgOmmKkbjOe7QMn8Z0WZtkQy5JcaBHKEGTu1p-La8JL8pZZqZy02Hrswpkh3I`

I've also captured this data a few times after the request has failed with a 400 error (using some error handling middleware):

    AntiforgeryTokenSet tokens = antiforgery.GetTokens(context);
    tokens.CookieToken:  null
    tokens.FormFieldName:  "__RequestVerificationToken"
    tokens.HeaderName:  "RequestVerificationToken"
    tokens.RequestToken:  "CfDJ8F9Fs4CqDFpLttT96eZw9WH33jSw5mM8h7RpEd3vGISQTRkx1rfwm-L2lfkvXKMBc-riESmoTo_fnIjeBbRmOo5KuJHr09f8B75sQ9g_djIVeeaGwMw5KE6W1O2-7Vi03fCnwlTv8l-BWGst76Ln-ZQ"

So here are the three strings:

    POST String:  "CfDJ8F9Fs4CqDFpLttT96eZw9WHjWfHO8Yawn35k4Yq3gDK5n1TDJDDiY5o86VQs1_qOVIYBydCizBU4knb7Jmq1-heGhwnMu2KmhUIiAd0xI7Sudv3GX-J0OI6wRfiPL4L1KRs2Pml8dbsDfwemewBqi18"
    Cookie String:  "CfDJ8F9Fs4CqDFpLttT96eZw9WFtJht41WcNrmgshi2pFGwcxhr0_0hvINQc7Yl9Cbjhv-TiSNXeEctyKborLI49AcjHfWIgOmmKkbjOe7QMn8Z0WZtkQy5JcaBHKEGTu1p-La8JL8pZZqZy02Hrswpkh3I"
    antiforgery.GetTokens(context).RequestToken:  "CfDJ8F9Fs4CqDFpLttT96eZw9WH33jSw5mM8h7RpEd3vGISQTRkx1rfwm-L2lfkvXKMBc-riESmoTo_fnIjeBbRmOo5KuJHr09f8B75sQ9g_djIVeeaGwMw5KE6W1O2-7Vi03fCnwlTv8l-BWGst76Ln-ZQ"

The POST string and cookie string don't match, but in my experience, even with requests ASP.NET Core considers legitimate, they never do.  But strangely, the POST string and `tokens.RequestToken` don't match either.    I would think they should match, although I captured `tokens.RequestTooken` later in the request lifecycle, so maybe that has something to do with it.

## ASP.NET Core 2 on GitHub ##
I decided to look at the source code of ASP.NET Core 2.  I found this file, especially line 145:

https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenGenerator.cs

That line gets the message "The antiforgery cookie token and request token do not match." from this file at line 134:

https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Resources.resx

So I think that's where the message is originating, but I'm still left wondering why this is happening.

## Question ##
Would someone please help me figure out why these anti-forgery tokens aren't validating?  Is it possible the user's Web browser is mangling the cookie or POST data?  Does anyone have experience in this area or any suggestions?  Thank you.

**Comment by Eilon** [comment]
Tagging @blowdart in case you have ideas...

**Comment by blowdart** [comment]
No, if it's a mismatch it's not data protection. So @rynowak is a better target.

**Comment by agrebenyuk** [comment]
Hey guys , any update on this? I have the same issue with Asp Net Core 1 , the issue with submitting Login form .  Another thing that , right before this error I have a warning in the log "warn: Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware[1]
      Parameter count mismatch between X-Forwarded-Host and X-Forwarded-For or X-Forwarded-Proto."  So this is probably related to reverse proxy. Deployed to Azure as  Web App(PaaS) . What is your thoughts on that.

**Comment by wessleym** [comment]
@agrebenyuk, respectfully, I'm not observing any of the behaviors you mentioned.  Maybe you need to start your own issue.

**Comment by agrebenyuk** [comment]
Hi @wessleym , no , I think I have exactly the same issue as you do. My application is load balanced but Antiforgery key is centralized and is stored in AzureBlobStorage. So would  be interesting to follow this thread

**Comment by wessleym** [comment]
That's fine, but anyone at Microsoft, please note that this issue does not involve load balancing or storing keys in AzueBlobStorage.  Please see my original post for a complete description of my issue.

**Comment by twenzel** [comment]
We also face this issue. Sometimes the antiforgery cookie token and request token do not match, but it should. This occurs especially when we have two forms on a page.

**Comment by wessleym** [comment]
The issue as stated in my original post continues to occur in ASP.NET Core 2.1.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wessleym.
Sorry for our late response on this. @javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
Hi,

I've been looking at the issue you mentioned. There are a few things a user could do to cause this. So here are a few questions:
* Does the site allow HTTP and HTTPS traffic? (That will be one thing)
* Users can have a tab open, login with a user in another tab and then when they try to use the original tab antiforgery will fail (due to the cookie changing)

**Comment by wessleym** [comment]
Thank you, @mkArtakMSFT and @javiercn, for your attention to this issue.
1.  No.  It's HTTPS only.
2.  I don't understand this.  What does logging in have to do with anything?  And why would logging in necessarily change any cookie value?

**Comment by javiercn** [comment]
Sorry, I meant Login as when a user logs-in

**Comment by wessleym** [comment]
@javiercn, right.  But why would a user signing into my site change the request validation cookie?  Why would signing in _specifically_ cause such an issue?  Would submitting any POST form cause this problem?

**Comment by javiercn** [comment]
@wessleym The cookie contains information about the user. Originally the tokens are generated for an anonymous user. (Different for each anonymous user). And when the user logs in, the antiforgery tokens get invalidated and a new set of antiforgery tokens specific to the logged in user is generated.

This error can also happen if the user press the back button after a successful login and tries to resend a previous form.

**Comment by wessleym** [comment]
@javiercn, I see.  What you've described doesn't fit my issue for two reasons:
1.  I'm not using ASP.NET Core's authentication system in any way.  I have written my own authentication system separate from ASP.NET Core, and ASP.NET Core has no idea whether the user is signed in or not.
2.  Your test of submitting two forms ("Users can have a tab open, login with a user in another tab and then when they try to use the original tab antiforgery will fail (due to the cookie changing)") works perfectly on my site.

So your scenario doesn't seem to apply me.  I also can't reproduce your back button issue.  But either way, it's concerning to me that ASP.NET Core's anti-forgery system is so flaky that just having two tabs open at once or using a back button can cause it to fail.  But I understand that those concerns really belong in a separate GitHub issue.
For the time being, my issue remains unaddressed.  But thank you for your efforts.

**Comment by javiercn** [comment]
@wessleym Not sure about 1. But essentially ASP.NET Core uses the principal in HttpContext.User to generate the antiforgery token pair, so if that changes the token will change.

> it's concerning to me that ASP.NET Core's anti-forgery system is so flaky that just having two tabs open at once or using a back button can cause it to fail

This is only if the identity of the user changes between the two tabs (as the antiforgery tokens will change) and is actually by design so that you can't log in with a different user, get an antiforgery token pair and use that in another users session to bypass antiforgery.

**Comment by javiercn** [comment]
@wessleym Have you followed the steps described in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#data-protection.

I think that what might be happening is that IIS is stopping or rebooting the site and the keys used to protect the cookie aren't getting persisted and as a result new tokens are being generated with new keys after the site starting again.

**Comment by javiercn** [comment]
One thing you could do here is manually trigger a reboot yourself to see if this causes the issue to surface.

**Comment by wessleym** [comment]
@javiercn, that's interesting about the anti-forgery system using the user to generate the pair.  Thank you for that explanation.  But of course, since I don't use HttpContext.User, that doesn't apply to me.
Regarding restarting, I am certain my site is not restarting.  This is demonstrated by the length of the log file, which can be days long.  The log entries I described in my original post can appear at any point in the log file.  I also wrote a line to log something like, "The site has started," to a distinct file every time the site starts (in the Startup.cs file).  I've observed this file being written only when I intentionally restart the site.
That said, when I do intentionally restart the site, I do see anti-forgery errors because I'm not persisting my keys.  I have persisted keys in the past, but it hasn't helped.  It makes sense to me that I would see these errors when I restart my site.  But site restarts play no part in the error I mentioned in my first post.
Thank you again.

**Comment by KoalaBear84** [comment]
Pfff. I'm investigating a maybe similar issue with this. At first it seemed random, later it seems it only happens when having Chrome DevTools open together with "Enable JavaScript source maps" enabled, INCLUDING a 404 generated by a 'custom' middleware.

I'll try to explain it a clearly a possible what our situation is, as I THINK it is, but I'm not sure this situation is 'fixable' in ASP.NET Core, or that it has to be fixed by excluding .map files, or not sending cookie updates etc.

1. We have enabled `AutoValidateAntiforgeryTokenAttribute`:
```csharp
services.AddMvc(options =>
{
	options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
})
```

2. We use `UseStatusCodePagesWithReExecute`, nothing really special inside this `ErrorController`:
```csharp
app.UseStatusCodePagesWithReExecute("/Error/InvalidRequestWithStatusCode", "?statusCode={0}");
```

But I guess because it is all processed through a real Controller it will alter the Cookie and messing up the expected and send Token.

3. We open a site with a form, which includes a .min.js file, with a source mapping (`//# sourceMappingURL=jsfile.min.js.map`) in it

4. Chrome WILL AUTOMATICALLY download this source mapping file, you WONT see it in the Network tab... But it WILL alter your cookie of the current page!! Which will 'invalidate' the expected one.

I really hope this is the problem you all might be having so that we have found the underlying vague issue and can move on :)

I used Charles proxy, breakpoints and cURL to reproduce this issue. I downloaded a HTTP2 enabled cURL build for Windows:
https://winampplugins.co.uk/curl/ (No idea why it is hosted on a winamp related site)

Path to reproduce:
1. Open site with form
2. Execute curl command like this (replace your URL and ASPSESSION, see browser cookies):
```
curl "https://localhost:44331/lib/parsley.js/parsley.min.js.map" -H "cache-control: no-cache" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.10 Safari/537.36" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en-US,en;q=0.9,nl;q=0.8" -H "cookie: ASPSESSIONID_COOKIE1=VALUE1" -H "cookie: ASPSESSIONID_COOKIE2=VALUE2" -H "cookie: ASPSESSIONID_COOKIE3=VALUE3" -H "cookie: ASPSESSIONID_COOKIE4=VALUE4" --insecure -H "Accept:" -IL
```
3. Replace token cookie value from the cURL output in browser (which is what Chrome will do without you knowing), see `set-cookie: .AspNetCore.Antiforgery.PLlJ9KQhgiA=TAKETHISPART`
4. Post form
5. Receive 400 error:
![image](https://user-images.githubusercontent.com/5886900/47362488-c9b08600-d6d4-11e8-9bb7-a8f48881505b.png)
6. In log something like this:
```
2018-10-23 14:36:08.7609|1|INFO|Microsoft.AspNetCore.Hosting.Internal.WebHost|Request starting HTTP/1.1 POST http://localhost:44331/YourController/YourAction application/x-www-form-urlencoded 317 
2018-10-23 14:36:08.7775|1|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Route matched with {action = "YourAction", controller = "Your"}. Executing action YourApplication.Controllers.YourController.YourAction (YourApplication) 
2018-10-23 14:36:08.7775|1|INFO|Microsoft.AspNetCore.Authorization.DefaultAuthorizationService|Authorization was successful. 
2018-10-23 14:36:08.7905|1|INFO|Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter|Antiforgery token validation failed. The antiforgery cookie token and request token do not match. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery cookie token and request token do not match.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
2018-10-23 14:36:08.7905|3|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'. 
2018-10-23 14:36:08.7905|1|INFO|Microsoft.AspNetCore.Mvc.StatusCodeResult|Executing HttpStatusCodeResult, setting HTTP status code 400 
2018-10-23 14:36:08.7905|2|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Executed action YourApplication.Controllers.YourController.YourAction (YourApplication) in 18.7502ms 
2018-10-23 14:36:08.8039|1|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Route matched with {action = "InvalidRequestWithStatusCode", controller = "Error"}. Executing action YourApplication.Controllers.ErrorController.InvalidRequestWithStatusCode (YourApplication) 
2018-10-23 14:36:08.8039|1|INFO|Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter|Antiforgery token validation failed. The antiforgery cookie token and request token do not match. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery cookie token and request token do not match.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
2018-10-23 14:36:08.8039|3|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'. 
2018-10-23 14:36:08.8268|1|INFO|Microsoft.AspNetCore.Mvc.StatusCodeResult|Executing HttpStatusCodeResult, setting HTTP status code 400 
2018-10-23 14:36:08.8268|2|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Executed action YourApplication.Controllers.ErrorController.InvalidRequestWithStatusCode (YourApplication) in 20.3958ms 
```

**Comment by poke** [comment]
@KoalaBear84 Can you provide access to the project where this happens? Or can you reproduce this in a minimal setup?

**Comment by KoalaBear84** [comment]
@poke Hmm.. Yesterday tried it all with a new project. Didn't succeed in reproducing it. Removed everything, filters etc. No luck. Now stripped to current project until there is almost nothing left.. But I found the problem, still it is a 'strange' thing that it only happens when having DevTools open which causes a 404 being processed by a Controller.

This is the problem:
```csharp
<body>
    @RenderBody()

    <div id="ajaxRequestVerificationToken">
        @Html.AntiForgeryToken()
    </div>
    <script>
        $(document).ajaxSend(function (event, jqxhr, settings) {
            if (settings.type.toUpperCase() != 'POST') return;
            jqxhr.setRequestHeader('RequestVerificationToken', $('#ajaxRequestVerificationToken input').val())
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
```

I use this for Ajax request so it automatically works. And it works.. Except when a 404 occurs after loading the page, and before POST. Somehow the token gets reset/changed by the request Chrome does in the background and it messes it up.

What is the recommended solution for AJAX calls? Is there a problem in ASP.NET Core that needs to be fixed, or can I add an attribute to the ErrorController which processes the 404 so it does not do anything with the AntiForgeryToken? I have no idea what the best solution is. Thanks!

**Comment by FrankHoogmans** [comment]
We're seeing the same strange behavior. Once in a while, a user will get a the exception: "Antiforgery token validation failed. The antiforgery cookie token and request token do not match." when logging in to the website.

About the following question earlier:
> 
> Hi,
> 
> I've been looking at the issue you mentioned. There are a few things a user could do to cause this. So here are a few questions:
> 
>     * Does the site allow HTTP and HTTPS traffic? (That will be one thing)
> 
>     * Users can have a tab open, login with a user in another tab and then when they try to use the original tab antiforgery will fail (due to the cookie changing)

We support only HTTPS.
For the given situation in bullet 2, a different error is thrown, so according to me, that's an **entirely different issue**:
"The provided antiforgery token was meant for a different claims-based user than the current user."
**I think this is by design, and we accept that.**

It seems to happen after a while after the user session and login have timed out, and the user tries to login again, although I'm unable to consistently reproduce the issue (the login/session timeout serverside doesn't seem to be the only cause).

Regarding our solution
We used the examples on https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1
We use the header option in the AddAntiforgery call:
`services.AddAntiforgery(options => options.HeaderName = "X-CSRF-TOKEN");`

We globally registered the AutoValidateAntiForgeryToken filter:
`services.AddMvc(options => 
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute()));`

We also include an AntiForgeryToken in a cookie, according to the example in the webpage above:"
`context.Response.Cookies.Append("CSRF-TOKEN", tokens.RequestToken, 
    new Microsoft.AspNetCore.Http.CookieOptions { HttpOnly = false, Secure = true });`

This token is read by clientside javascript and used in AJAX requests by setting the X-CSRF-TOKEN header.

Hoping to at least find a root cause for when this happens (so something reproducable), since then, we can figure out how to prevent this from happening.

**Comment by javiercn** [comment]
@FrankHoogmans @effyteva @wessleym Do any of you have a minimal repro project we can use to track down this? I've taken a look at the code, but I don't have enough information to determine what's going wrong.

@KoalaBear84 I think your issue is not related to this and is most likely related to https://github.com/aspnet/Mvc/issues/8670 instead

**Comment by wessleym** [comment]
@javiercn, I wish I could give you something that would allow you to reproduce it, but it seems random.  So I can't provide source code or steps to reproduce it.  It's never even happened to me personally but only to my users.  I can see it in the logs.

**Comment by javiercn** [comment]
@weasleym Without a repro is impossible to for us to do more. 

Another situation where this might occur is when a user opens multiple tabs simultaneously (specially if the page takes time to load) where the requests go on simultaneously and the responses are sent concurrently (in which case the two cookies get set at the same time and one of that will cause one of them to fail) but eventually the browser will settle for the last cookie in the response. (Note that this is an unavoidable race condition that happens when there’s no cookie and the user opens multiple tabs simultaneously)

**Comment by effyteva** [comment]
Perhaps setting a MaxAge/Expiration for the cookie would help with this issue?
Does it pose a security risk to set it for a long expiration?

**Comment by javiercn** [comment]
@effyteva That's not an option. It'll make the cookie token persistent (while now it goes away when you close the window as it should) and will have the side-effect of causing errors when the cookie expires. The lifetime of the anti-forgery token must be bound to the session on the browser.

**Comment by javiercn** [comment]
@FrankHoogmans Antiforgery tokens don't "expire" in the traditional way. They are bound to the session on the browser and regenerated automatically on get requests when the identity of the user changes. Only things like data-protection keys can cause the cookie token decryption/integrity check to fail if the keys are not being properly persisted or take a bit of time to propagate, but this is not normally the case.

**Comment by 13sin** [comment]
I solved this problem by testing in incognito mode

**Comment by mkArtakMSFT** [comment]
Closing as we're unable to reproduce the original issue and we haven't received a repro project.

**Comment by wessleym** [comment]
@mkArtakMSFT, I appreciate your time and your stance.  But as my original post stated, this problem is not easily reproducible.  It seems to happen randomly.  I wish I could supply projects, but not only are the projects owned by my paying clients, but they also reliably work in my testing.  It's only in production, maybe every 1,000 requests, that they fail.  So while this GitHub issue may be closed, the real-world issue continues.
@javiercn, while I don't think this my problem since I'm not generally seeing requests so close together and since my page load times are pretty low, would you be able to supply documentation about this?  "Another situation where this might occur is when a user opens multiple tabs simultaneously (specially if the page takes time to load) where the requests go on simultaneously and the responses are sent concurrently (in which case the two cookies get set at the same time and one of that will cause one of them to fail) but eventually the browser will settle for the last cookie in the response. (Note that this is an unavoidable race condition that happens when there’s no cookie and the user opens multiple tabs simultaneously)."

**Comment by javiercn** [comment]
@wessleym I'm not sure what your request for documentation here implies, what are you specifically interested in?

**Comment by wessleym** [comment]
@javiercn, I'm interested in documentation of the problem you mentioned with simultaneous requests.  Does Microsoft document this situation anywhere?

**Comment by omuleanu** [comment]
@KoalaBear84 think I've reproduced something similar to the issue you're describing
https://github.com/aspnet/AspNetCore/issues/6410

**Comment by omuleanu** [comment]
@wessleym do your projects have `@Html.AntiForgeryToken()` in `_Layout.cshtml` ? do 404 results return a view that uses `_Layout.cshtml`,  or just returns a view that has `@Html.AntiForgeryToken()`

**Comment by omuleanu** [comment]
@charlierlee it was the same for me, because `UseStatusCodePagesWithRedirects` was handling the 404 which was returning a view with `_Layout.cshtml` that contained  `@Html.AntiForgeryToken()`, the view wasn't actually rendered in the browser, but it was enough to invalidate the previous token

**Comment by wessleym** [comment]
@omuleanu, I don't think that's my problem because I don't do what you're describing with Html.AntiForgeryToken.  But thanks anyway.

**Comment by CollapsedMetal** [comment]
If it's worth something, iv'e been facing this issue since ASP.NET MVC 5.
As it is described it happens 1 on 1000 times apparently randomly. No matter how hard I try, I still cannot reproduce this behaviour

**Comment by TheCloudlessSky** [comment]
We've been experiencing this problem for several years in a production application on ASP.NET MVC 5 (though similar anti-forgery mechanism to ASP.NET Core). Our application has a few components that are mini-single-page-applications. So, there's a lot of requests via JavaScript that we do that include anti-forgery protection. We've been able to prevent anti-forgery errors by introducing a couple of changes:

1. **Disable HTTP caching on HTML views that are returned to the browser** - If the page *was cached*, the user could hit back and be served a page with a state form token that no longer matches the cookie. Our application is behind authentication and we do caching at many other levels (HTML fragments/views, data layers, etc) so full HTTP caching of a page doesn't make sense for us anyways.
2. **Detect logging in/out of multiple tabs and clearing cookies in the same browser session** - If a user had a stale anti-forger token on a page but logged out with a separate tab, cleared their cookies, and logged back in with another tab, they had the possibility of using that old tab with the stale anti-forgery token. We prevented this from happening by allowing the tabs to communicate when loaded (e.g. via `localStorage` `session` events or using the [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)) and show a message on the "stale" tab. A lot of sites do this similar pattern (e.g. GitHub, AWS Console, etc). This reduced a large majority of our problems.
3. **Prevent form submission double-clicking** - This helped anti-forgery errors caused by double-form submissions on pages like our login if the anti-forgery token happened to be re-generated once logged in.

---

Although this fixed *most* of our problem,s we still have had consistent anti-forgery problems from some of our users. We have a heartbeat-like request that sends useful information for aggregating/reporting later on in the user interface. This heartbeat-like request would continuously fail for certain users meaning that their data was lost and couldn't be reported on. Thankfully, the anti-forgery error was transparent to them but it meant a discrepancy in data for reporting.

In a recent investigation back into this problem, I found some interesting revelation in our logs:

1. When the specific users were having problems some of their heartbeat-like requests were being accepted and validated by our servers but some were failing with anti-forgery mismatch exceptions.
2. When the users that experienced anti-forgery problems first started work in the day, our logs would show *concurrent* requests from them with the *referrer* empty.

Here's what this is caused by:

1. The user logs into the application with an authentication cookie.
2. The user changes their browser setting to **Open a specific page or set of pages** on startup (e.g. in Chrome).
3. They set multiple pages of our application in that list (e.g. `/apples` and `/bananas`).
4. They're done for the day and close their browser.
5. The `__RequestVerificationToken` cookie is cleared because it's only alive for as long as the *browser's session*.
6. The `.ASPXAUTH` cookie is *not* cleared because it has a default expiration of 1 year.
7. The next time the user launches their browser, `/apples` and `/bananas` are launched *concurrently* in our app. This could also be accomplished just by doing something like middle-clicking on a tab more than once, but the pattern seems to fit since this causes the referrer to be empty. Both of those pages render a form with the anti-forgery token (e.g. `@Html.AntiForgeryToken()`).
9. **Both requests** generate a new `__RequestVerificationToken` cookie and send it as part of the response because the request does not have a `__RequestVerificationToken`. When the *form's* token is generated during the request, it's for the unique cookie token per-request.
10. The browser chooses the *last* cookie to be saved, thus causing the *first* tab's form token to be invalidated because it no longer matches the cookie when the tab was loaded. When our heartbeat-like requests are sent from the "bad" tab, anti-forgery exceptions are thrown server-side.

I have some ideas to work around this, though I haven't fully thought them through:

1. Seed the cookie token based on the user's current authentication context (e.g. in our case their internal user session id in our database). Anti-forgery (at least in MVC 5) doesn't have a way to hook into this.
2. Change the anti-forgery token to be the length of the user's authentication session when it's first created. This would prevent it from being cleared in the first place. I'm not a security expert, so I'm not sure if this is a good idea.
3. Somehow detect the form anti-forgery token changes per-tab like we do with stale sessions. Obviously, the form tokens are always unique per-form... so I'm not sure how detecting a "change" could help here.
4. Use a mechanism outside of our web servers (e.g. Redis) to prevent generating the anti-forgery token more than once. This seems expensive because there's no way to hook into *when* ASP.NET generates a new anti-forgery token.

Does anyone else have any ideas on how we could solve this problem? @wessleym I'm not entirely sure if any of this can help solve *your* problem but I hope it may be able to provide some insight.

**Comment by javiercn** [comment]
@TheCloudlessSky The analysis you made is very accurate and have lots of good points. As you point out, there are some failures produced by antiforgery that are systemic due to the limitaitons of the technology.

I would only suggest that you don't tie the antiforgery token cookie to any date and instead leave it as session as it's meant to be deleted when the user closes the browser.

**Comment by andrewgrahamorange** [comment]
We're also seeing this behavior in ASP.NET Core.

After some investigation, we think our problem lies with Google Chrome's prefetch behavior. This is causing 2 requests to be made to our system (a prefetch one and a normal request) and both are setting the antiforgery token. Occasionally, the prefetch request completes execution after the normal request and it is on those occasions that we are seeing this behavior ("The antiforgery cookie token and request token do not match").

Does anyone have any ideas on how we can solve this issue?

**Comment by markphillips100** [comment]
@javiercn  I consistently get this issue due to a particular use case that includes using AspNetCore Identity as the user accounts provider for a process hosting IdentityServer4.

I can reproduce the error with a standard .net core 3.0-preview5 web application using local user accounts and the ForgotPassword/Reset Password process.  

The template's process works by directing the user back to log in page from the Reset Password confirmation page, whereas in my case I expect the user to click a link back to log in page from the original Forgot Password confirmation page.  This is due to the fact that only the original oauth flow can redirect back to the app requesting authentication.

I capitulate that AspNetCore Identity's use case leads the user to avoid the error and mine leads the user into the error potentially occurring.  However, I see no alternative to the use-case that I require.

Is there anyway to trap this specific exception and re-execute a GET request perhaps?

**Steps to reproduce**
You can reproduce both working (standard use-case) and failing (my use-case) use cases consistently using a basic dotnet web app template with local user accounts and email reset password use case.

I followed the docs [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.0&tabs=visual-studio) to create the basic web app with user accounts, and then setup sendgrid for the email.  I already had registered an account prior to setting the sendgrid email so I set the IsEmailConfirmed property in the database to True.

**Environment setup**
DotNet: .net core 3.0-preview5
Server: Windows 10 and Kestrel web server
DevTools: VS2019 v16.1.3


**Working ForgotPassword/ResetPassword process**
1. Launch app
2. Click Login.
3. Click Forgot your password?
4. Enter valid email and submit.
5. Forgot Password Confirmation page shown. (leave this page open).
6. Receive email and click link in email.  Fill out Reset Password form correctly and submit.
7. Reset Password Confirmation page shown with a link to login.
8. At this point, you can either click the Go to Login link on Reset Password Confirmation page or click the Login link in the menu on the Forgot Password Confirmation page.
9. Login page displayed and user can log in with no problems.

**Failing ForgotPassword/ResetPassword process**
1. Launch app
2. Click Login.
3. Click Forgot your password?
4. Enter valid email and submit.
5. Forgot Password Confirmation page shown.
6. **Click the Login link in menu**
7. Receive email and click link in email.  Fill out Reset Password form correctly and submit.
8. Reset Password Confirmation page shown with a link to login.  **Do not click this link**
9. Fill out Login page and submit.
10. AntiForgery error occurs.

**Comment by javiercn** [comment]
Hi. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

I've created a separate issue for tracking here https://github.com/aspnet/AspNetCore/issues/11485

**Comment by MrCsabaToth** [comment]
> If it's worth something, iv'e been facing this issue since ASP.NET MVC 5.
> As it is described it happens 1 on 1000 times apparently random. No matter how hard I try, I still cannot reproduce this behaviour

Same here. For me it's definitely connected to session expiration. Also possibly the IIS server "goes to sleep". Possibly even AJAX is connected. I client has it who leaves his browser open forever and after days of inactivity it happens for him. I try to reproduce it, but I can't. It definitely does happen though, I'm receiving the error call stacks for sure.

**Comment by cihankusmez** [comment]
Same problem :( in .net core 3.0 IIS Server
