### ISSUE TITLE
in IOptionsSnapshot<T>, T must have a public parameterless contstructor

### ISSUE THREAD

**Issue by cilerler** [aspnet/AspNetCore#3078]
I would like to be able to log errors in my option/setting file. If I use DI in it, caller says `in IOptionsSnapshot<GracePeriodManagerServiceSetting>, GracePeriodManagerServiceSetting must have a public parameterless contstructor` how can I make this work?

## GracePeriodManagerService.cs

```csharp
public GracePeriodManagerService(IOptionsSnapshot<GracePeriodManagerServiceSetting> options)
...
```

## GracePeriodManagerServiceSetting.cs
```csharp
    public class GracePeriodManagerServiceSetting
    {
        private readonly ILogger _logger;
        public GracePeriodManagerServiceSetting(ILogger<GracePeriodManagerServiceSetting> logger)
        {
            _logger = logger;
        }
    ...
    }
```

## appsettings.json
```json
{
  "GracePeriodManagerService": {
    "DelayTime": "1 2 3 4 5 6"
  }
}
```

**Comment by fubar-coder** [comment]
I'm in the same boat as you. I guess that the short answer about how to get this work is: You don't. The reasoning **probably** was, that configuring the options should be a lightweight operation, so that it usually doesn't need services which may use some heavy-weight initialization.

**Comment by cilerler** [comment]
I hear you but I believe it should be developers decision and not "opinionated" view.

**Comment by davidfowl** [comment]
Logging from a poco, is kinda code smell no? Why are you logging from your settings object that isn't supposed to have behavior? What does GracePeriodManagerServiceSetting look like?

**Comment by cilerler** [comment]
I don't think so.  

Simple scenario would be a background service I would like to run in specific time based on [crontab string](https://crontab.guru/#1_2_3_4_5).  And I use [ncrontab](https://github.com/atifaziz/NCrontab) where value in **appsettings.json** will be string but I need to extract next date in options.

Now consider that I want to use that setting in multiple places.  It becomes really ugly to implement it.


## appsettings.json
```json
{
  "GracePeriodManagerService": {
    "DelayTime": "1 2 3 4 5"
  }
}
```

## GracePeriodManagerServiceSetting.cs _(the one I have right now)_
```csharp
using System;
using NCrontab;

namespace MyProject.Api.Services.GracePeriodManagerService
{
    public class Setting
    {
        public const string ConfigurationSectionName = nameof(GracePeriodManagerService);

        private string _delayTime;
        public string DelayTime
        {
            get
            {
                if (_delayTime == null)
                {
                    return null;
                }

                try
                {
                    CrontabSchedule crontab = CrontabSchedule.Parse(_delayTime, new CrontabSchedule.ParseOptions { IncludingSeconds = true });
                    DateTime nextOccurrence = crontab.GetNextOccurrence(DateTime.Now);
                    return nextOccurrence.ToString("s");
                }
                catch (CrontabException ce)
                {
                    //_logger.LogError(ce, ce.Message);
                    throw;
                }
                catch (Exception e)
                {
                    //_logger.LogError(e, e.Message);
                    throw;
                }
            }
            set => _delayTime = value;
        }
    }
}
```

**Comment by HaoK** [comment]
To consume services to configure your options, you don't do it in the ctor, you can consume services inside of your `IConfigure[Named]Options<T>`

**Comment by HaoK** [comment]
A generic implementation of this that we do to make this easier is found here to give you a concrete example of what that would look like: https://github.com/aspnet/Options/blob/maestro/master/src/Microsoft.Extensions.Options/ConfigureNamedOptions.cs#L66

**Comment by cilerler** [comment]
@HaoK would you please elaborate on that and provide a working example please?

**Comment by poke** [comment]
@cilerler Could you show exactly what you would like to log and how from your `GracePeriodManagerServiceSetting` class? I agree with David here that logging from the options POCO *is* a sign for code smell. You can probably do this better by moving the logging logic elsewhere.

From the example you have given using the configuration manager, it is unclear though what you are actually trying to do (and how that contradicts David’s comments).

**Comment by HaoK** [comment]
Rough idea of the code you need to consume services would be the following, I do agree with the other comments that this seems like a lot of work just to log stuff here

```C#
// services.AddTransient<IConfigureOptions<GracePeriodManagerServiceSetting>, MyConfigure>();
public class MyConfigure : IConfigureOptions<GracePeriodManagerServiceSetting> {
    public MyConfigure(ILogger<GracePeriodManagerServiceSetting> logger) => _logger = logger;
   public Configure(GracePeriodManagerServiceSetting s) { // use _logger }
}
```

**Comment by poke** [comment]
@HaoK I’m not sure if this is really about *configuring* the options (since there is still a mention of an appsettings.json) but rather consuming the options and then parsing it into a higher level object. And that parsing process could fail and these failures should be logged. At least that’s how I am currently interpreting this.

**Comment by cilerler** [comment]
@poke please locate *GracePeriodManagerServiceSetting.cs* above and look for commented `//_logger.LogError(ce, ce.Message);` lines.  Well you just posted another message and it is exactly what I'm trying to do.

**Comment by HaoK** [comment]
I was mostly just looking at this issue from the context of the title about ` IOptionsSnapshot<T>` requiring a public constructor, it sounds like if this issue moving away from options now, maybe its best to open a new issue, or retitle this one.  I was just visiting issues tagged with repo:Options since they basically haven't been looked at in a while

**Comment by poke** [comment]
@cilerler Well, if that’s how you want to use the pattern, then you are using it incorrectly. The options object is supposed to be a really simple object without any behavior. Having a complex getter there is already wrong (not to mention the fact that your property does not even follow the invariant that it returns the same value you set).

You should understand the options object as a POCO that directly represents the values in your appsettings.json. Since the value is a string in the JSON, it is also a simple string—without any attached logic—in the options object.

I would recommend you to split up your logic into some helper method that is able to parse the options object and then returns whatever complex result you want from that. That helper could be a service that you register with your dependency injection container, so you can access services like logging. In general though, you should think about which parts of your application have the actual responsibility to log stuff. It’s rare that some parsing utilities would have to log. It’s a lot more common that the parsing fails and then you throw an exception, and then one way to handle that exception would be to log it; but you would do this further up in the application stack.

**Comment by cilerler** [comment]
In-case someone find this out and looking for a solution 

**old way**
https://andrewlock.net/delaying-strongly-typed-options-configuration-using-postconfigure-in-asp-net-core/

**new way**
https://www.stevejgordon.co.uk/asp-net-core-2-2-options-validation
