### ISSUE TITLE
Security Implications of using Windows Authentication

### ISSUE THREAD

**Issue by couven92** [aspnet/AspNetCore#3516]
When running an ASP.NET Core application on an IIS-Server on Windows what are the best options for doing Authentication

* using the IIS built-in Windows Authentication (which uses the `X-WWW-Authenticate` header under the hood)
* using a Login page with ASP.NET authentication, using ASP.NET Core Cookie Authentication, and calling the [LogonUserW function](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-logonuserw) via P/Invoke to login the user and create a Windows Identity object from the returned handle

Is this scenario impacted by using a Windows Server in Workgroup mode, i.e. a server which does not use Active Directory? For example, will the authentication negotiation fallback to NTLM if the server is not under AD, because it cannot do Kerberos? *I have been told that NTLM auth is bad?*

Is it better to create a Forms-based login page and doing the authentication locally on the server, instead of exposing Windows Authentication Negotiation to the public Internet?

If using Windows Authentication through IIS, is there a proper way of signing out the user? Returning a `403` will just trigger a new login prompt, right?

If I allow both Anonymous Authentication and Windows Authentication in IIS, I can do both in the same application, right? IIS wil attempt Windows Authentication if it sees a `X-WWW-Authenticate: Negotiate` header, but do nothing if there is none?

----

/cc @blowdart

**Comment by blowdart** [comment]
This is more of a stack overflow question as it's opinion based, but ...

In workgroups in order for this to work, without the login prompt that people generally want integrated auth for you'd have to mirror user accounts and passwords between all machines, a horrendously bad idea, because you'd know everyone's passwords. 

Then you add the internet to the mix, and Integrated/NTLM/Kerberos is also not a great idea in that scenario, although HTTPS only mitigates some of the problems.

So two not great ideas in one. Why do you think you want NTLM/Kerberos here? Why use local windows accounts as your user database? Why not a database of some description, and then forms based authentication? (Heck you don't even have to use ASP.NET identity here, you can roll your own, and just use the cookie based persistence mechanisms we provide).

Mixing and matching Windows auth and anonymous is possible, although remember once you've authed that header will always flow.

**Comment by couven92** [comment]
Oh, I am sorry @blowdart , you're right, I should have posted on StackOverflow or Reddit instead...

> Then you add the internet to the mix, and Integrated/NTLM/Kerberos is also not a great idea in that scenario, although HTTPS mitigates some of the problems.

Well, of course this site would run behind HTTPS width proper HSTS mechanisms eneabled. I'd never expose the Windows Authentication to an unsecure endpoint.

> Why use local windows accounts as your user database?

Well suppose I expose file-server access as part of the site. I'd rather use DACL to control file access and permissions than defining a role-based-permission system in code. This is especially useful when the files to access are also exposed through other services (like SSH login, Windows Fileshare, etc.), in which case a coded role and permission system would not propagte to other unrelated services.

And for database access using a Windows account for database login (e.g. using Integrated Security with SQL Server) could remove the need to authorization logic in code, instead I could define the actual access permissions on the Database object instead. Thus I'd put the resposibility of handling auth and authorization to the Windows Filesystem or the Database server instead of handling it myself.

To be honest, I am much more confident that Windows, SQL Server, and other components are capable of enforcing authorization and permissions than what I would be able to code.

**Comment by couven92** [comment]
Core doesn't do impersonation automatically. From what I understand you can get an instance of NT Identity from the user property and call imporsonate, right?

**Comment by Tratcher** [comment]
That's correct, but it has limitations like no good async support. https://github.com/dotnet/corefx/issues/24977

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
