### ISSUE TITLE
Why are all ASP.NET Core assemblies strong named?

### ISSUE THREAD

**Issue by bitbonk** [aspnet/AspNetCore#3524]
I think I understand why .NET Core assemblies have strong names, as it is explained [here](
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md).

But I don’t see that these reasons also apply to ASP.NET Core. So why are the assemblies of ASP.NET Core strongly named too?

**Comment by Eilon** [comment]
As of right now, all ASP.NET Core assemblies (well, *almost* all) also run on .NET Framework, where strong naming is still important. For that reason, the assemblies are all strong named. And, because the strong name is part of the assembly's identity, it would be a breaking change to remove it at this point.

But, the strong name *private* key that's used is shared *publicly*, it's strong only in the cryptographic sense, and not in any other tangible sense 😄

**Comment by natemcmaster** [comment]
No, we plan to continue the use of strong-names on all ASP.NET Core assemblies.

**Comment by davidfowl** [comment]
Removing them would be a breaking change and would mean that things compiled for previous version won't work. We don't want that.

**Comment by bitbonk** [comment]
> Removing them would be a breaking change and would mean that things compiled for previous version won't work. We don't want that.

Why is it breaking change? Doesn't .NET Core generally ignore strong names?

**Comment by brockallen** [comment]
Can't a 3.0 release make such breaking changes?

**Comment by davidfowl** [comment]
Because we don’t make breaking changes unless there’s a perceived benefit. I don’t see any here.
