### ISSUE TITLE
Url.Action takes attribute routing in to account, but not clear how

### ISSUE THREAD

**Issue by vankampenp** [aspnet/AspNetCore#3636]
1. Description of the problem:
 Url.Action("index", "base", new { loginid = clientKeep.Login, pwd= pwd}, "https");

Returns
`
https://Contoso.com/default.aspx?login=<login>&pwd=<pwd>
`
where the action in the BaseController is:

 ```
        [ HttpGet]
        [AllowAnonymous]
        [Route(""), Route("default.aspx"),Route("index")]
        public async Task<IActionResult> Index([FromQuery] string loginid, [FromQuery] string sessionid)
        {
        }
```
where I would like to have

```
https://Contoso.com?login=<login>&pwd=<pwd>
```
the default.aspx is for backward compatibility.  
I tried to change the order of the routing attributes, but this did not change the result. 
 
I think it should be predicable and controllable which of the routing attributes is used.

Microsoft.AspNetCore.App 2.1.1
Microsoft.NetCore.App 2.1.0

dotnet --info:
Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vankampenp.
@JamesNK, can you please look into this? Do we need to add some documentation to make this clear or is this something we missed? Thanks!

**Comment by poke** [comment]
This happens because when the attribute router matches the routes, matching routes [are sorted](https://github.com/aspnet/Routing/blob/2.1.1/src/Microsoft.AspNetCore.Routing/Internal/LinkGenerationDecisionTree.cs#L30) before being evaluated and only the first result will be used to generate the URL. For the sorting, the comparer will look at the route order and the precedence which [is being calculated](https://github.com/aspnet/Routing/blob/2.1.1/src/Microsoft.AspNetCore.Routing/Template/RoutePrecedence.cs#L15-L20) to give more complex routes a higher precedence.

Since the empty route `""` has no complexity at all, it has a zero precendence, while the non-empty routes have a non-zero precendence. And since all `Route` attribute have the default order of `0`, the two non-empty routes will be preferred over your empty route. And then it’s just a matter of what comes first in the alphabet which is why `default.aspx` wins over `index`.

The fix for this is pretty simple: You just have to set an explicit order on the attributes:

```c#
[Route("")]
[Route("index", Order = 1)]
[Route("default.aspx", Order = 100)] // legacy might as well get an order of 100
public async Task<IActionResult> Index() { … }
```

That way, the empty route will be sorted *before* your other routes, so that’s what’s going to be used to generate the URL for the action.

**Comment by vankampenp** [comment]
@poke Thanks for the excellent and clear answer. Your solution works.
I would have never guest the alphabet  sorting for creating the Url. Basically I assumed that there was a default Order attribute. My bad.

**Comment by rynowak** [comment]
Thanks @poke for the explanation.

I want to also mention about this part:

> And then it’s just a matter of what comes first in the alphabet which is why

This is something we do so that routing has a predictable and consistent behavior when its ambiguous which one to choose. If you're relying on this for correctness then it's not good, but unfortunately not easy to detect. Using `Order` to control the behaviour is the right thing to do.
