### ISSUE TITLE
Implement stable 'channels' for the aspnet runtime and dotnet-install.ps1

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3646]
_From @natemcmaster on Friday, July 27, 2018 8:57:55 AM_

Now that 2.1 is RTM, we should implement channels to match the .NET Core runtime and SDK for dotnet-install.ps1/sh. For example, it's reasonable to expect this to work:
```
dotnet-install -Channel 2.1 -Architecture "x64" -Runtime aspnetcore -NoPath -Verbose
```

**Requirements**
Create a blob here: dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.1/latest.version. This should be a simple text file which contains full version information for the latest stable RTM version of the runtime. Example:
```
2cd777f06183bf5639578ff3a4162cd3f576e989
2.1.2
```

This file should be updated for each servicing release of 2.1

_Copied from original issue: aspnet/Universe#1283_

**Comment by leecow** [comment]
@tonycoelho - excellent! We've certainly talked about the possible need and you've just provided a clear reason to do it :-)

One option would be to use our public azure storage location which serves as our production store. Something like `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/` and the enclosed structure would map to what is on github with releases-index.json at the root and major.minor sub-directories containing the releases.json files. 

Something like the following?

```
https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/
  
  releases-index.json
  2.2/
      releases.json
  2.1/
      releases.json
```

@dleeapho

**Comment by tonycoelho** [comment]
@leecow, the dotnetcli public blob storage account is perfect since we use that already today with the dotnet-install.ps1 script and it is already mirrored on Azure CDN so it's a win/win. Regarding the folder structure, it doesn't really matter to me as long as you continue to set the releases.json URI in the "releases-index" array so that I can discovery it dynamically. So for instance, the new proposed URI, https://dotnetcli.blob.core.windows.net/dotnet/release-metadata would return:

```json
{
  "releases-index": [
    {
      "channel-version": "2.2",
      "latest-release": "2.2.0",
      "latest-release-date": "2018-12-04",
      "product": ".NET Core",
      "support-phase": "current",
      "eol-date": "",
      "releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/2.2/releases.json"
    }
  ]
}
```

And then https://dotnetcli.blob.core.windows.net/dotnet/2.2/releases.json (or similar uri) would return the exact same json structure that is currently located at https://github.com/dotnet/core/blob/master/release-notes/2.2/releases.json.

Thoughts?

**Comment by leecow** [comment]
@tonycoelho, yep that's basically it with one correction. The index will be at https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json. 

Give it a try ... it's all set up :-)

**Comment by tonycoelho** [comment]
@leecow works perfectly! Thank you for the quick turn-around!

**Comment by tonycoelho** [comment]
@leecow actually one more question. On the release download URI it currently points to download.visualstudio.microsoft.com, whereas the official bits are hosted on dotnet.microsoft.com. So for example, the 2.1.6 x64 binaries in the release manifest points to:

https://download.visualstudio.microsoft.com/download/pr/3f6b6def-4e9a-4405-b21f-89f77d1605c4/52be50baa0e9bfa118fe6de80be89ab6/dotnet-runtime-2.1.6-win-x64.zip

and the official download URL on dotnet.microsoft.com is:

https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.1.6-windows-x64-binaries

Do you plan to switch-over to the dotnet.microsoft.com domain for downloads instead of download.visualstudio.microsoft.com?

**Comment by leecow** [comment]
@tonycoelho, there's a redirect of some variety in place which is used from https://dotnet.microsoft.com. All of the download assets on the site are driven from these json files so the final URI used to do the actual download should be the same.

**Comment by tonycoelho** [comment]
@leecow yeah I see now that they are 302ing to download.visualstudio.microsoft.com. Thanks for clarifying!

**Comment by Eilon** [comment]
@natemcmaster , please log a new issue in the appropriate location with the distilled requirements, then close this issue.

**Comment by natemcmaster** [comment]
I'm closing as there is no planned action item here for the ASP.NET Core team.

As @leecow mentioned above, this file can be used to figure out which versions are the latest stable releases: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json. Using tools like `jq` on bash, or the `ConvertFrom-Json` command in PowerShell, you should be able to automatically determine the latest "2.1" release version and pipe that through to the `dotnet-install.ps1/sh` script.

That said, I think it would be nice if the script did that for you, so I've opened up https://github.com/dotnet/cli/issues/10763.
