### ISSUE TITLE
2.2 Preview 3 - DbHealthCheck supported scenario?

### ISSUE THREAD

**Issue by Eneuman** [aspnet/AspNetCore#3687]
We have a MicroService SaaS application running in azure using a Azure SQL Elastic pool for its database. Each customer has their own database because of compliance requirements. 
The connection string is set during dB context creation, based on the customers tenant Id.

We want to create a health check page for the customer, but we only want to run the health check for a specific tenant Id. Tags will help us with this but will the new dbcontext health check support this scenario?

It would be awesome if you could create your own “connection string factory” and override a default one.

**Comment by rynowak** [comment]
/cc @divega @ajcvickers 

How does your code construct a DbContext today to accomplish this?

**Comment by Eneuman** [comment]
We have created a custom IDbContextOptionsBuilder that gets the connectionstring from Azure KeyVault.
Our DbContext then uses it in its override OnConfigure method.

It’s a lot of code just to set the connection string and dbcontext pooling needs to be disabled.

I have always felt that the “one db per tenant” scenario isn’t fully supported today and I’m hoping it will get some more love in later releases :)

**Comment by rynowak** [comment]
Sorry, perhaps I wasn't clear - what does you your code look like that **obtains** a `DbContext` - for instance how does the infrastructure you described know which tenant it belongs to?

**Comment by rynowak** [comment]
One thought that I had here - do you really need the *health checks system* for what you want to accomplish? Does it make more sense for you to retrieve a DbContext as you normally do an call `CanConnectToDatabase`? If your goals are limited to giving users a way to test database connectivity for their tenant, this is a really lightweight way to do that.

Otherwise, it sounds like you could make this work but there are a few thing you will need to know:
1. I assume since you mentioned the `HttpContext` that you're using `IHttpContextAccessor` to get the currently executing request to find the tenant. If this is not the case then I need more information.
2. The health checks service creates its own DI scope and resolved/runs checks in there. It does not share scoped services with the current request.

Assuming you're using the middleware, if your tenant info is assigned to the `HttpContext` before the health checks middleware runs this should all *just work*. If you're calling the health checks service yourself, the same requirements apply - if you're inside a request, then the http context should be picked up and used when your DbContext is created.

I'd also encourage you to think about if there are cases where you want to run health checks for a request that doesn't have a tenant associated. You might want two middleware - one that runs for the app as a whole, and one that runs with per-tenant information.

**Comment by Eneuman** [comment]
Thank you for your elaborated answer.
Yes we are using IHttpContextAccessor to get the AccessToken containing the claims for the user.

As you mentioned, we actually have two use cases. 
1) A customer wants to see the health for their system. That includes their azure database, their azure storage account, some (but not all) of the micro services and perhaps a custom ftp server address where they are receiving files. 
2) We, as a SaaS provider, wants to see the health of all services and databases.

I see our health check model as a organisation chart where our “Maintenace” Micro Service, who is in the top,  starts the checks by calling “check health” for each of our Micro Services. Each MS checks the health of the services that it is using, and soo on. (Our system is using composit services)

Are Health Checks designed for these kind of scenarios or do you think a custom implementation would be better?

**Comment by rynowak** [comment]
Sorry I lost track of this for a few days. 

I think health checks are totally fine for this. We provide the `IHealthChecksService` so that you can call it in ways that make sense for you and show the results any way you want.  I expect that some of your scenarios will require writing some custom `IHealthCheck` implementations. 

Since you will be writing code on both sides (eg: both calling `IHealthChecksService` and implementing checks) you might want to short circuit some of that by just using the abstractions and types yourself. I would still recommend trying to make this work with the built in implementation of the service first. We provide some niceties around logging, timing, cancellation, etc.

-----

If I were in your position I would model this in the following way:

- to check the health of a tenant register the appropriate checks - set up the system in such a way that they automatically detect the correct settings for the tenant based on the `IHttpContextAccessor` - it sounds like you've already got this figured out for the DbContext. Apply a tag to these checks so they are easy to group when calling the service.

- for your overall service monitoring, I'd suggest writing your own checks that loop through the configurations and call the appropriate touch points. You could choose to model this as a composite or not. 

I hope it doesn't seem like I'm asking a lot by suggesting that you author some of your own checks... My recommendation is that you think of them as simple glue code that adapts some underlying API to the health check service.  For an example of this, take a look at [the DbContext health check](https://github.com/aspnet/Diagnostics/blob/release/2.2/src/Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore/DbContextHealthCheck.cs#L14) - it's basically **all** glue code and configuration - all of the real logic in a method that EF added for us.

---

I think I've answered most of the questions here so far, and we can get more concrete if you have some examples or a simple mock up (repo) of what this might look like. Basically if you have some code, I'm happy to take a look and make suggestions.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
