### ISSUE TITLE
session in core 1.1 framework

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/AspNetCore#3693]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/13687 filed by @IsaaasI

I am trying to use session in core 1.1 framework but not work. 
Any one please give me the best suitable way to use session in c# Core 1.1 solution .

The below error I face in my solution.
![image](https://user-images.githubusercontent.com/17950923/47214926-1aa83d80-d3a8-11e8-8c32-4d725c492641.png)

Also I tried to install **Install-Package Microsoft.AspNet.WebApi.Owin -Version 5.2.6**
and give me the below error
![image](https://user-images.githubusercontent.com/17950923/47215071-b3d75400-d3a8-11e8-868f-ff24a01f9c5a.png)

Any suggestion please .

### Further technical details
Operating system: 
IDE: (e.g. Visual Studio 2017 15.7.2)

**Comment by poke** [comment]
Please read the [session state chapter of the documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1#session-state). In order to access the session, you need to access the `Session` property on the `HttpContext` which is an [`ISession`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.isession?view=aspnetcore-1.1) object.

So inside a controller, you need to do for example: `HttpContext.Session.Get("Name")`
