### ISSUE TITLE
.net Core based Razor Library project type

### ISSUE THREAD

**Issue by HolyOne** [aspnet/AspNetCore#3740]
Razor Library is a great idea. But it doesn't do the job of splitting my website to modules well.

I wanted to split my membership folder from my project and put it in a new razor library project. But i see two big challenges.

1) I see that i can't put my css, js and image files in my razor library. (without editing project file and adding some extra code)
2) I wanted to write a simple action which writes some data to my database. Ooops, razor library project is a .net standard project type so I can't reference my entity framework database (or business) layer?

If my web project is a .net core project, shouldnt its sub project type be a .net core project also?

I dont see any reason to use razor library if it can't handle these two simple issues all websites would need.

Am I missing something here?
I think razor project types should be as simple as possible but should also be able to do everything a razor web application can do.

**Comment by pranavkm** [comment]
@HolyOne we are tracking improvements you suggested in (a) as part of https://github.com/aspnet/Razor/issues/2322.

> I wanted to write a simple action which writes some data to my database. Ooops, razor library project is a .net standard project type so I can't reference my entity framework database (or business) layer?

I'm not sure why you are unable to access your EF context since it targets `netstandard2.0` which is what the RCL template targets. However if you need to reference a `.NETCoreApp` targeting project or library, you may edit the project to do so. Our intent is to make Razor Class Libraries be available to reference in as many varieties of projects as we support and `netstandard2.0` is the most common denominator.

**Comment by HolyOne** [comment]
So I should be able to change .net standard project type to core?
If this is possible, can you make an improvement so I dont have to edit the project file?

**Comment by pranavkm** [comment]
@HolyOne that would be feedback to VS tooling. Use the ["Send Feedback"](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) option to do this.

**Comment by mkArtakMSFT** [comment]
Closing this per @pranavkm's comment. Please file feedback to VS.
