### ISSUE TITLE
Routing to same action/page reuses ambient route values

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore#3746]
Let’s assume I’m inside an MVC action with the default routing template (`{controller}/{action}/{id?}`) and the optional `id` route parameter is specified. So my route is for example `/Home/Test/123`.

Now, inside that route, I return a `RedirectToActionResult` to the *same* action, i.e. `return RedirectToPage(nameof(Test))`. When the result is being executed, the current ambient route values are being reused, so I am being redirected to the same route `/Home/Test/123`.

What I would instead (maybe) expected would have been a redirect to `/Home/Test` since I did not specify any route values.

I am not sure if this is the intended behavior or not. When I am redirecting to a different action, the ambient values are correctly ignored. But for consistency, I would probably expect this to be true for the current route as well.

Instead, when I want to clear the `id` argument, I have to explicitly specify it:

```c#
return RedirectToAction(nameof(Test), new { id = (int?)null });
```

The same applies btw. to Razor pages and `RedirectToPage`.

Is this the desired behavior?

**Comment by rynowak** [comment]
This is definitely expected and is a behaviour that's been around for a long time 😆 It's not a feature that I'm in love with, but it exists so that you can put `Url.Action()` in a page/view and have it link back to itself reliably. 

This is probably the most complicated and obtuse piece of code we have in routing: https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L114

**Comment by poke** [comment]
Oh wow, it is very telling when you have more lines of comments than code :sweat_smile: 

Anyway, thanks for the confirmation @rynowak! :smile:

**Comment by achandlerwhite** [comment]
Question: do the ambient route values carry over into the anchor tag helper? I seems like `asp-page` isn't picking it up when I have a custom Pages route convention configured. Thanks!

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
