### ISSUE TITLE
ANCM - How to disable logging of informational messages?

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/AspNetCore#3822]
Other than any other IIS module, the ANCM module is quite a bit busy logging informational messages to the Application log. On servers running thousands of sites, one may want to disable this behavior. Is there any way to accomplish that?

**Comment by muratg** [comment]
@shirhatti please triage.

**Comment by shirhatti** [comment]
Unfortunately, I don't think we have a solution here short of introducing new schema. Based on my reading of the initial comment on how the OP intends to use it, I'd say the ideal solution is to introduce a new schema element that is only settable at the server level and not the application level.

We could use `<handlerSettings>` but that seems to have very little utility since
- We have no intentions of changing the default to disable logging of information messages and most folks wouldn't explicitly go out of their way to set this.
- Our default generated web.config uses `<location path="." inheritInChildApplications="false">`, so there's no point setting it at the server level.

Additionally, you can change the retention of your EventLogs as an additional mitigation.

All said, I think the right decision in this case would be to close this issue. We can re-visit if we have more customers ask for this.
