### ISSUE TITLE
Double files in visual studio, maybe in sln?

### ISSUE THREAD

**Issue by hubeek** [aspnet/AspNetCore#3980]
### Describe the bug
Double files in visual studio, maybe in sln?

### To Reproduce
1. On Mac in terminal create new proj with dotnet new reactredux
2. look in ClientApp and double files will appear but not in the finder

### Screenshots
<img width="190" alt="screen shot 2018-11-08 at 17 59 05" src="https://user-images.githubusercontent.com/1303695/48214338-0be9f080-e380-11e8-8c9e-2b1c27074a6b.png">

### Additional context
Mac Visual studio community edition

**Comment by natemcmaster** [comment]
Hi @hubeek, this doesn't appear to be an issue in ASP.NET Core itself, but rather in how Visual Studio for Mac is interpreting the project. Can you open your issue here instead?

https://developercommunity.visualstudio.com/spaces/41/index.html

You can also report this by going to Help > Report a Problem in Visual Studio for Mac.
