### ISSUE TITLE
Add a manual trigger to dotnet watch to restart?

### ISSUE THREAD

**Issue by g0t4** [aspnet/AspNetCore#4092]
Could we add some key code that we type in to the terminal to force `dotnet watch` to restart the app. I'm thinking along the lines of SIGHUP to trigger dotnet watch to restart. This way if I edit a file not being watched I don't have to Ctrl+C and then run watch again. One use case: when I edit config files like appsettings.json it would be nice to restart without adding a custom rule for this.

**Comment by muratg** [comment]
I don't expect we'll do this.

**Comment by TomasHubelbauer** [comment]
Is the support for Unix signals required only for SIGHUP or it needed for the watch to recognize any kind of input? I would be equally happy to press `R` as I would be to press `Ctrl+C` to force a rewatch. I think this issue should be reopened as I am sure the OP and me aren't the only two people who are annoyed with restarting `dotnet watch` because of config changes and it would improve the developer experience a lot.
