### ISSUE TITLE
Integer converted to String is deserialized the same as Integer in ApiController

### ISSUE THREAD

**Issue by eastjie** [aspnet/AspNetCore#4139]
### Describe the bug
If the integer is converted to string and returned in ActionResult, it is deserialized as number not string in 
HttpResponse.

### To Reproduce

We have tried the following requests with the template API in Visual Studio 2017 (Version 15.9.2). The following requests create the same result : 12

Request 1:
`
 [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return "12";
        }
`
Request 2:
`
[HttpGet("{id}/int")]
        public ActionResult<int> GetInt(int id)
        {
            return 12;
        }
`

It causes problems, if the result is used in client side project, we use Angular, and all the methods in string, e.g. split() in JavaScript/TypeScript throws error.

### Expected behavior
For Request 1, if the returned value is defined as string, the response should be 

> "12"

For Request 2, if the returned value is defined as int, the response should be 

> 12

Thanks very much.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @eastjie.
What's happening here is that the returned "12" text value is being processed by a text formatter. So the response is plan text, rather than JSON.
What you can do, to enforce the JSON response is either apply `[Produces("application/json")]` attribute on your action or simply remove the `TextOutputFormatter` from the default list of output formatters configured on MVC options.
