### ISSUE TITLE
code analysis is running at runtime or deployed app

### ISSUE THREAD

**Issue by fatagun** [aspnet/AspNetCore#4251]
Below is an attachment for memory snaphot of an app using Kestrel.

![e01jc](https://user-images.githubusercontent.com/987005/49088089-8347cd00-f226-11e8-837f-97519b88d715.png)

Why code analysis enable in a running process? How is it useful for me?

Why HttpRequestDelegate inclusive size is 160 MB. what is that doing?

When I deploy this app, it consumes around 600 MB memory without any traffic on it. 

How can I reduce runtime memory usage?

Is this by design?

**Comment by Eilon** [comment]
Hi @fatagun sorry for the delay. Everything to do with compilers (e.g. C# compiler, CSHTML/Razor compilers, etc.) is called "Code Analysis." If your app is doing runtime compilation of CSHTML files (that is, they are not pre-compiled), that would cause these DLLs to be loaded.

As far as other memory usage, it depends a lot on the details of the app. In general a .NET app using the "server GC" (which is what's typically used in ASP.NET apps) will use as much memory as possible because it is assumed it's the only app on the server. So, unless there is actual memory pressure, no time will be spent trying to free memory.
