### ISSUE TITLE
Two controller with the same name

### ISSUE THREAD

**Issue by clintnetwork** [aspnet/AspNetCore#4482]
I've a MVC project with two folders, Controllers\Dashboard  and Controllers\API, the API and the regular controllers has the same action names, and when i make a link by example to archive a campaign like this:
```html
<a asp-controller="Campaigns" asp-action="Archive">Archive Campaign</a>
```
It's the API that it's called, by example /api/campaigns/archive/uid?uid=60011969-6369-43a0-930a-ab7b686bbac0 and not the Dashboard controller.

What is the correct way to fix this problem ? it's not really a bug but there no documentation how to fix this kind of problems.

Thank you

**Comment by clintnetwork** [comment]
Additionally the tag helpers reference controller that are in specific area:

![image](https://user-images.githubusercontent.com/5221349/49615139-dea75700-f9ac-11e8-8331-3314c9a3950c.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @clintnetwork.
Controller names should be unique within an area. The issue your'e facing with is by design.
If, however, you're in a situation, where you can't change the controller type names, you could use ApplicationModel to override the name of controllers: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.2

**Comment by clintnetwork** [comment]
Thank you @mkArtakMSFT i will see your solution, but for me it's a problem the main projet tags detect controllers in a specific area
