### ISSUE TITLE
Endpoint Routing incompatible with API versioning

### ISSUE THREAD

**Issue by AdamWillden** [aspnet/AspNetCore#4502]
### Describe the bug
UrlHelpers cannot locate routes when controller route contains api version. 
>  InvalidOperationException: No route matches the supplied values.
> Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)

Disabling Endpoint Router restores correct behaviour.

### To Reproduce
Steps to reproduce the behaviour:
1. Get attached reproduction: [bug.zip](https://github.com/aspnet/AspNetCore/files/2657123/bug.zip)
2. Run the application
3. Navigate to http://localhost:5002/Bar (SUCCESS)
3. Navigate to http://localhost:5002/v1/Foo (FAIL)
4. Toggle `EnableEndpointRouting` in startup (see `.AddMvcCore(options => options.EnableEndpointRouting = true)`)
3. Navigate to http://localhost:5002/v1/Foo (SUCCESS)

**Comment by AdamWillden** [comment]
There's a simpler reproduction (without swagger etc) by @vanbukin here: https://github.com/Microsoft/aspnet-api-versioning/issues/409

**Comment by commonsensesoftware** [comment]
API Versioning 3.1 has been released and includes support for _Endpoint Routing_.

@AdamWillden unless you are continuing to observe issues, I believe this issue can now be closed.

cc: @Eilon

**Comment by AdamWillden** [comment]
As the issue and fix is in aspnet-api-versioning I believe this can be closed. I'll raise issues over there if I observe issues.

**Comment by AdamWillden** [comment]
Thanks for the mention and hard work to fix this @commonsensesoftware

**Comment by rynowak** [comment]
Awesome, thanks Chris!

**Comment by AdamWillden** [comment]
@commonsensesoftware when you next get a moment (no rush - it's Christmas 🎄)...

Can you download my reproduction from the first post, upgrade the package to `3.1.0` then navigate to http://localhost:5002/v1/Foo  as instructed. 

I'm still seeing the same issue. So, if now you've done your bit, there may be another issue somewhere else? Can you confirm I'm not being a moron please? 

I'll re-open this in the mean time.

**Comment by commonsensesoftware** [comment]
Two basic issues:

1. You're missing the API version route parameter in the link generation
2. You need to change the route parameter name to a legal identifier (e.g. `api-version` → `version`)

I changed your route template to: `v{version:apiVersion}/[controller]`. Updating the response is then trivial:

```c#
[HttpGet]
public IActionResult Create(ApiVersion apiVersion) =>
  CreatedAtAction(new Bar { Baz = Guid.NewGuid() }, apiVersion);

private IActionResult CreatedAtAction(Bar bar, ApiVersion apiVersion)
{
    return CreatedAtAction(
        nameof(GetByIdAsync),
        new { baz = bar.Baz, version = apiVersion.ToString() },
        bar);
}
```

Model binding support for **ApiVersion** is new 3.0. Its source is _special_ because it can come for any number of locations, even multiple places within the same request or not from the request at all. Since you're versioning by URL segment, you'll need to include the `version` route parameter. Alternatively, if your controller class only supports a single version, you can simply hardcode the route parameter value (e.g. `version = "1.0"`).

For your convenience, here's the [fixed repro](https://github.com/aspnet/AspNetCore/files/2707659/Fixed-Bug.zip) with the necessary changes. Merry Christmas!

**Comment by AdamWillden** [comment]
Wow, that's really kind of you. I'll try this out once the wine wears off 🍷 ... Maybe Friday 🙄 . I'll close as you've obviously sorted this for me.
