### ISSUE TITLE
Order of properties when dragging style reference onto editor

### ISSUE THREAD

**Issue by rswetnam** [aspnet/AspNetCore#4529]
For years, I have dragged style sheets onto the template _LayoutPages in.Net with the resulting line of code something like:
```<link href="~/css/custom.css" rel="stylesheet" /``` which start with the href property.

This is usually placed under the line of code in _Layout that starts with the rel property and looks like this:
```<link rel="stylesheet" href="~/css/site.css" />```

Like a little troll, I then dutifully change either the existing line of code or the new line of code so that both lines start with rel or href and I can more readily pick out the different files being referred to. I know this makes absolutely now difference in how the program runs - but as I was just looking at the new version of Visual Studio 2019, I got to wondering - is there something I am missing? Is Microsoft doing this deliberately to irritate the obsessive-compulsives amongst us, or might it want to take the opportunity of a new version of of Visual Studio to make the order of href and rel consistent between templates and program?

HI @rswetnam ... We won't be able to address that valuable feedback here on the docs repo, as we just use the templates for our sample apps mostly in the same form as we receive them from engineering. It sounds like you're making a suggestion for the templates. If so, I recommend opening an issue with that feedback on the aspnet/AspNetCore issues, where the engineers who work on the templates and other managers will see it.

**Comment by Eilon** [comment]
Hi @rswetnam ,

To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
