### ISSUE TITLE
Investigate reported change in link generation behaviour 

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4556]
See: https://github.com/aspnet/Docs/issues/9886#issuecomment-445507613

https://github.com/nimeshdhruve/WebAPIRoutingDemo

**Comment by mkArtakMSFT** [comment]
@JamesNK, can you please look into this? Thanks!

**Comment by JamesNK** [comment]
I'm having trouble compiling the routing solution. When that is solved then I'll look at link generation behaviour.

**Comment by nimeshdhruve** [comment]
@JamesNK, I have added [readme](https://github.com/nimeshdhruve/WebAPIRoutingDemo) explaining the issue, please let me know if you need more details.

**Comment by JamesNK** [comment]
Thanks. I'm looking into this now. I'll post an update with what I find.

**Comment by JamesNK** [comment]
@rynowak I think this is a situation where the pre-endpoint routing URL generator was generating an "invalid" route.

This route - `configureRoutes.MapRoute("ControllerOnlyRouteName", "api/{controller}");` - will never successfully match an action because of the lack of a required value. The application is relying on attribute routing to do the matching:

```cs
[Route("api/[controller]")]
public class MyAPI : Controller
{
    // GET: api/<controller>
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }
}
```

Because `ControllerOnlyRouteName` doesn't match anything, endpoint routing is returning null when it is used as the route name: `Url.RouteUrl("ControllerOnlyRouteName", new { controller = "MyApi" });`

**Comment by JamesNK** [comment]
Functional tests - https://github.com/aspnet/AspNetCore/commit/19979c53800d4466115e9be1cb480b3120da072b

**Comment by JamesNK** [comment]
@nimeshdhruve The reason you no longer get a URL returned is because endpoint routing no longer builds routes that don't map to an endpoint. Your "ControllerOnlyRouteName" could never match to an action because it does not have an action parameter or a default.

What you can do is add a name to the attribute route.

```cs
[Route("api/{controller}", Name = "ControllerOnlyRouteName_Attribute")]
public class MyAPI : Controller
{
    // GET: api/<controller>
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }
}
```

Note that `api/[controller]` has changed to `api/{controller}`. Attribute routes with the same name must have the same pattern, and the square bracket syntax modifies the pattern at runtime.

This will now work: `Url.RouteUrl("ControllerOnlyRouteName_Attribute", new { controller = "MyApi" });`

**Comment by rynowak** [comment]
Closing this because there's no action to take on our side.
