### ISSUE TITLE
Razor Content Change not Picked Up in 2.2

### ISSUE THREAD

**Issue by danjohnso** [aspnet/AspNetCore#4567]
### Describe the bug
When debugging, if I make a change to a razor file and refresh my browser page, the changes are not reflected.

### To Reproduce
1. Start debugging
2. Load page
3. Change razor content
4. Refresh page in browser

### Expected behavior
Content should be updated to match changes in razor file

### Additional context
If I set compatibility mode to 2_1, it works as expected where changes are reflected upon page reload.

`.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)`

**Comment by rynowak** [comment]
We made an intentional change in 2.2 - we now only listen to file changes for view recompilation when the environment is set to development. The file watcher was causing significant problems in containers, and other deployment environments where the file system isn't expected to change. 

https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs#L231
https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptionsSetup.cs#L63

You can set this option to true if you want to listen for file changes in all environments.

If you're using a tool like VS to launch in the debugger, then the environment should be set to development.  You can read more about environments [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)

**Comment by danjohnso** [comment]
Hmmm, we use "Local" when debugging locally from VS.  "Development" is a deployed environment name to us.  Didn't see any mention of this in any of the 2.2 posts, was there an issue in the release mentioning this change?  Looks like I can just change that conditional to use Local for our use case

**Comment by rynowak** [comment]
@danjohnso - you're right, I can't find an announcement of this. We'll get that fixed.
