### ISSUE TITLE
Razor Extension version is incorrect in latest insertion

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4585]
### Describe the bug
The latest RazorExtension insertion has a version of 3.0.0.1860703+COMMITHASh when it should be 16.0.XYZ. This indirectly causes issues when attempting to run the VSIX locally

### To Reproduce
1. Get d16.0stg
2. Open the About dialog

### Expected behavior
Razor extension version 16.0.XYZ

### Screenshots
![image](https://user-images.githubusercontent.com/2008729/49842183-61def900-fd6f-11e8-9f37-8c64956c2ddb.png)

**Comment by rynowak** [comment]
There are two issues here - and surprisingly the VSIX actually **does** have the correct version 😆 

1. The 'dev build' version number is *lower* than the version number of our official builds since it was generated like: `16.0.4242424.0`. See the bug? It's missing a digit.
2. The assembly information version (used by the about dialog) is wrong

The `.vsman` and `.vsixmanifest` both have the correct version.

**Comment by rynowak** [comment]
This was fixxxed
