### ISSUE TITLE
Move the AuthSamples to aspnet/samples

### ISSUE THREAD

**Issue by Meir017** [aspnet/AspNetCore#4590]
The directory `src/AuthSamples/` contains samples that should be in the https://github.com/aspnet/samples repository

**Comment by Eilon** [comment]
We ended up with the current arrangement because we use these samples as tests as well to verify functionality.

We did just add a pointer from the samples repo back to these samples to hopefully make it a bit easier to find: https://github.com/aspnet/samples/blob/master/samples/aspnetcore/security/README.md
