### ISSUE TITLE
Convert Https connection adapter to connection middleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4623]
As part of bedrock, connection adapters are going away and we should port the tls connection adapter to middleware. We don't want to break the public API of the existing extension method on ListenOptions so that will remain. 

The true TLS implementation should be in Microsoft.AspNetCore.Protocols.Tls and Kestrel.Tls should delegate to it in the implementation.

Edit: Also convert Logging connection adapter to middleware.

**Comment by davidfowl** [comment]
I'm going to take another stab at this.

**Comment by anurse** [comment]
Milestone: @davidfowl (aka whenever he gets to it)

**Comment by davidfowl** [comment]
Old version https://github.com/aspnet/KestrelHttpServer/pull/2849

**Comment by jkotalik** [comment]
@davidfowl should we add this to https://github.com/aspnet/AspNetCore/issues/10869?

**Comment by davidfowl** [comment]
Sure.

**Comment by fubar-coder** [comment]
My use case is a little more complicated, because I wanted to implement `AUTH TLS` for an FTP server. This stuff is quite crazy, as I have to do the following:

- Have a connection middleware that works in a "pass-through" mode by default
- Stop the receiving task without disposing anything (effectively pausing it)
- Send a response that the connection switches to `SslStream`
- Flush and stop the sending task without disposing anything (effectively pausing it)
- Do an `SslStream.AuthenticateAsServer`
- Start the sending task which now uses the `SslStream`
- Start the receiving task which now uses the `SslStream`

The other way (from `SslStream` to `pass-through`) needs to work too (`REIN` command).

**Comment by davidfowl** [comment]
This is done. I'll file another issue for exposing a pure TLS middleware, we did the bare minimum to migrate Kestrel's HTTPS IConnectionAdapter to middleware, it'll likely be identical to the TLS middleware (we'll build it on top).
