### ISSUE TITLE
xplat Integrated Windows Authentication (ntlm/Kerberos)

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#4662]
_From @evil-shrike on January 25, 2018 12:41_

I haven't found any ticket for tracking the xplat Windows-auth support in aspnet/dotnet core. 
I understand that currently we have only out-of-the-box Windows auth support in IIS/IISExpress and http.sys and only on Windows.

There's a decent article in docs https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?branch=pr-en-us-3622&tabs=aspnetcore2x on how to configure Windows auth. But it says nothing about non-Windows use-cases. 

There're many issues here on Github and questions around on sites like SO on "how to implement Windows authentication in aspnet core on Linux". But all issues are closed with reasoning like "Kestrel doesn't implement Windows auth currenly, use IIS or https.sys". This is understandable but it's unclear what to do if we need to host an app on Linux and support integrated Windows auth (in intranet networks).

So there are several points which need to be addressed:
* what options do exist currently (at the time of 2.0/2.1) for getting integrated Windows authentication on Linux and other *nix OSes?
* what are plans (if any) for improving/adding such functionality?

I understand that strictly speaking this issue is related to Kestrel project probably, but it's more easily to find it here though. Moreover it's implementation details where Windows-auth support should live. 

Anyway it should be some source of information describing what to do with aspnet core apps on Linux for adding Windows auth.

Some additional info:
* middleware for ntlm support - https://github.com/OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory (ntlm only, Windows only - "Achieving server-side NTLM handshaking depends the Windows platform due to interop, dependency on domain-joined machines and secur32.dll")
* it's possible to authenticate via Kerberos on Linux - https://technet.microsoft.com/en-us/library/2008.12.linux.aspx
* there's Application Proxy with Kerberos Constrained Delegation in Windows Server and Azure AD which seems to solve such problems - https://blogs.technet.microsoft.com/applicationproxyblog/2015/09/21/all-you-want-to-know-about-kerberos-constrained-delegation-kcd/ but it's complex
* there're modules for Nginx (http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ntlm) (requires commercial license) and Apache httpd (http://adldap.sourceforge.net/wiki/doku.php?id=mod_auth_ntlm_winbind) (it's unclear how stable it is) to add ntlm support
* It seems that Java has Kerberos support out-of-the-box - https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/single-signon.html
* Java implementation for app servers - http://spnego.sourceforge.net/  (not sure how it relates to the previous point)

_Copied from original issue: aspnet/Home#2824_

**Comment by Tratcher** [comment]
Design notes:
- NTLM and Kerberos are stateful connection bound protocols.
- They need somewhere to store connection specific state between requests.
- They MUST NOT be used behind IIS out-of-proc or similar reverse proxies that do not maintain a 1:1 connection map between their external and internal connections.
- They MUST NOT be used over HTTP/2, multiplexing breaks the stateful handshake ordering. Clients wouldn't normally attempt this anyways. If we issue the challenge over HTTP/2 will the client gracefully fall back to HTTP/1? Or is this a case where we should use the HTTP_1_1_REQUIRED error?
- Http.Sys already offers kernel mode auth. IIS offers both kernel mode and user mode.
- Any in app implementation would be user mode.
- The handshake requires multiple requests on arbitrary paths. This is unusual for our auth infrastructure.
- We're primarily interested in Kerberos xplat, but the libraries we'll be using also support NTLM and work on both unix and windows.
- Kerberos is a multi-machine protocol. Local machine flows all fall back to NTLM.

Preliminary conclusions:
- We'll need some new server features to manage the connection level state. https://github.com/aspnet/AspNetCore/issues/9213
- There's limited value to building an implementation that's works on Http.Sys or IIS (in-proc), they already have support.
- AuthenticationMiddleware does have a [step](https://github.com/aspnet/AspNetCore/blob/507a765dfb078f446c445318e7b55ad9f7f5cbe0/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L45-L47) where where an auth handler could run per request and terminate early. Most implementations sniff the request path before taking action. Kerberos/NTLM would need to sniff the auth headers and connection state for incomplete handshakes.
- Our implementation will be a pretty thin layer over the existing CoreFx implementation. https://github.com/dotnet/corefx/issues/36896
- We should make sure the our implementation can mock out the CoreFx layer for unit testing purposes.
- Functional testing of kerberos is going to be very difficult to automate since it requires multiple machines, a private domain, SPNs, etc.. However, at our layer NTLM and Kerberos are functionally indistinguishable so we can primarily test NTLM on a single machine.

**Comment by Eilon** [comment]
Setting milestone to preview6 so it's out of the generic 3.0.0 milestone.

**Comment by John0King** [comment]
Will it be a `Microsoft.AspNetCore.Authentications.<NTLM/Kerberos>` package or  implement on the `kestrel` server ?

**Comment by Tratcher** [comment]
@John0King my current prototype is as an auth package. Either way we need some new connection state features from the server, so it will only work with Kestrel.

**Comment by Tratcher** [comment]
FYI: There's a draft PR for this now at https://github.com/aspnet/AspNetCore/pull/9831.

**Comment by Tratcher** [comment]
Announcement:
Please try 3.0.0-preview5 System.Net.Security.NegotiateStream in your environments. NegotiateStream allows you to authenticate a TCP connection using NTLM or Kerberos. It will not get you HTTP auth, but it will let you know if you have correctly configured in your environments. 

In preview5 we [added](https://github.com/dotnet/corefx/pull/36827) support to NegotiateStream for server scenarios on Linux. In the next milestone we will implement HTTP server auth using the same underlying libraries.

**Comment by Tratcher** [comment]
Verified in SDK 3.0.100-preview6-012105-1 on Ubuntu.

**Comment by concretor91** [comment]
Now it is possible to use Kestrel with Nginx as reverse proxy and SPNEGO module to get Kerberos is working and i can use authorize attribute or get login using HttpContext.Current.User.Identity.Name?

**Comment by Tratcher** [comment]
Yes. Careful though:
"Credentials can be persisted across requests on a connection. *Negotiate authentication must not be used with proxies unless the proxy maintains a 1:1 connection affinity (a persistent connection) with Kestrel.*"

I don't think NGinx guarantees that.

**Comment by concretor91** [comment]
@Tratcher 

Suppose I want to experiment inside the company in which I work, but I do not understand the simplest thing. If I publish a simple web api application on Linux with Windows enabled and anonymous authentication and add the Authorize attribute to the controller, then the application throws an exception defaultscheme must be specify.
On iis, this problem is solved with a single line of code:
services.AddAuthentication (IISDefaults.AuthenticationScheme);
I do not understand how I should set up Kestrel.

Maybe some other opportunities to make Kerberos work on Linux with Kestrel, even if not official?

**Comment by durranitech** [comment]
@concretor91


Maybe you are missing this

services.AddAuthorization(options =>
            {
                options.FallbackPolicy = options.DefaultPolicy;
            });
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();ere the sample code @Tratcher put up
https://github.com/aspnet/AspNetCore/blob/40091e9a12491d4e4a97df940cb6e589c898f908/src/Security/Authentication/Negotiate/samples/NegotiateAuthSample/Startup.cs

**Comment by concretor91** [comment]
@durranitech 
Thanks, could not find this information

**Comment by Tratcher** [comment]
The docs for this are available here:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#kestrel
Let me know if you have trouble following them.

**Comment by valorl** [comment]
@Tratcher Thanks. Very glad this is coming in 3.0.

Are there any plans for including the AD groups in the identity ? 

With this package, the only claim included is `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name`, whereas when using the [SteveSyfuhs/Kerberos.NET](https://github.com/SteveSyfuhs/Kerberos.NET/) library, the `ClaimsPrincipal` has all the AD groups included as claims. IIRC, the claims should be included in the received Kerberos ticket.

**Comment by Tratcher** [comment]
> Are there any plans for including the AD groups in the identity?

Not in this release. Please open a new issue to track that ask.

So far we haven't even identified the APIs/libraries necessary to make that work on Linux. We don't process tickets directly, we rely on SChannel and GSS to handle that.

**Comment by valorl** [comment]
@Tratcher Sure, I've created #12938 to track this.

**Comment by nino96** [comment]
@blowdart In the following comment that you posted, can you explain how to achieve the third scenario in asp.net core mvc 2.1?
Basically I have a self-contained .net core mvc app deployed to linux and it needs to be able to connect to an SQL Server with integrated security, both the linux server and sql server being in a corporate intranet. Any help would be much appreciated! 
> @evil-shrike when you say "Windows Authentication" what do you mean?
> 
> Do you want
> 
> 1. "I want to use Windows Authentication to authenticate against a web site"
> 2. "I want to use Windows Authentication to authenticate against a web site and then I want to be able to impersonate that user so I can access network resources"
> 3. "I want to run my web site under a linux account that comes from a domain via kerberos and let it talk to SQL as that account"
> 
> Or something else altogether.
> 
> One thing to note up front - it's extremely unlikely we'd implement NTLM, that protocol needs to die and since Win2k it's Kerberos anyway.

**Comment by blowdart** [comment]
We have not implemented scenario 3. It’s in the backlog for now. The sql team has ways to configure the Linux client for integrated auth but that’s for a machine account, not via a delegated identity.

________________________________

**Comment by nino96** [comment]
@blowdart Ah okay, thanks for the quick reply. Any article/page on configuring for a machine account as you mentioned? Might be helpful for figuring out a workaround

**Comment by blowdart** [comment]
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-auth-overview?view=sql-server-2017

**Comment by nino96** [comment]
@blowdart Thanks!

**Comment by danielleiszen** [comment]
Hi, 

in my scenario the users log in from a Windows DC to their Windows OSs where they would use a browser based (TS) or desktop (.Net) client for accessing different services. The services and a central IdentityServer4 that issues the tokens and handles other authentication scenarios as well, runs in Linux based docker containers. My aim is to use SSO and authorize against the IdentityServer4 - LDAP using the already logged in Windows account for the user without prompting for user name and password. The IdentityServer4 is a linux based container - so I cannot use the documented and well known method.

Is this scenario possible with the mentioned NegotiateStream release?
There is not much documentation could anyone point me to the right direction with this?

Thank you

**Comment by Tratcher** [comment]
@danielleiszen the docs are here:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#kestrel

Little testing has been done in docker though. Let us know if the docs work for you.

**Comment by valorl** [comment]
@danielleiszen I'm not sure about the details of how IS4 does LDAP, but I'm assuming the requirement can essentially be reduced to having an ASP.NET Core (3.0) web service (your IS4) be capable to authenticate requests using Negotiate, _while running in a Linux container_.

As @Tratcher linked, since 3.0, Kestrel can do Negotiate in a Linux environment with the right prerequisites. These are basically:

- Having the Kerberos libs installed (e.g. `krb5-user` on debian)
- Having the right config (`/etc/krb5.conf`) for the libs
- Making sure there's always a valid Kerberos TGT available (by requesting/refreshing it using `kinit` and a keytab)

Setting this up is mostly explained in [this article](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller) which is also linked in the Kestrel guide. 

The issue when you want to do this from Docker, is that you essentially need to run 2 processes: your application and a process that keeps the TGT alive (using `kinit`). This is a bad practice to do in a container.

A better solution is to have a separate (sidecar) container running that keeps the TGT alive. Your app container and the sidecar container can then share the same Kerberos cache over e.g. a memory volume. Kubernetes helps here, as you can deploy a Pod with those two containers, which means the sidecar is isolated from other applications.

That being said, I would recommend using standard OAUTH and JWT if you can avoid using Kerberos as it adds a lot of complexity and is much harder to debug (the Kerberos mechanism is coupled to a lot of non-HTTP systems like AD and DNS).
