### ISSUE TITLE
breaking change preventing OData

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#4791]
https://github.com/OData/WebApi/issues/1707

**Comment by Eilon** [comment]
@JamesNK - any idea what work would be needed here? Not clear to me from the linked issue.

**Comment by JamesNK** [comment]
The ASP.NET Core OData library uses IRouter, and doesn't work with Endpoint routing. Until the OData library is updated users can continue to use it in 2.2 and 3.0 by disabling Endpoint routing:

> To only disable endpoint routing you can leave `CompatibilityVersion.Version_2_2` on, and set MvcOptions.EnableEndpointRouting = false.

https://github.com/OData/WebApi/issues/1707#issuecomment-448420529

Ryan and I are already providing advice for updating the library. No changes on our side are required.

Closing this issue because discussion is already happening in the linked issue.
