### ISSUE TITLE
Partial views path is incorectly resolved in ViewComponent

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4863]
_From @PavelBansky on November 19, 2017 23:13_

I have a ViewComponent called PagerViewComponent with corresponding View(s) stored in the `Views/Shared/Components/Pager`

The content of the directory is this:
```
/Views
  /Shared
    /Components
      /Pager
        _Pager.cshtml
        Default.cshtml
        Search.cshtml
```

Content of `Default.cshtml` is this
```csharp
@model MyApp.ViewModel.PagedResultBase

@Html.Partial("_Pager", Model)
```

It all ends with runtime exception:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: The partial view '_Pager' was not found. The following locations were searched:
/Views/Blog/_Pager.cshtml
/Views/Shared/_Pager.cshtml

Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper+<RenderPartialCoreAsync>d__60.MoveNext()
```

**Razor would not look to resolve the partial view inside the ViewComponent directory** `Views/Shared/Components/Pager`
When I move the `_Pager.cshtml` into `Views/Shared` directory it all works..

OS: Windows 10 x64
.Net Core: 2.0
Microsoft.AspNetCore.All Version="2.0.0" 
Microsoft.VisualStudio.Web.CodeGeneration.Tools Version="2.0.0" 

_Copied from original issue: aspnet/Razor#1779_

**Comment by pranavkm** [comment]
The View engine treats things as path if it looks like one i.e. if the view name starts with a `/` or ends in `.cshtml`. In this case, the passed in value is `_Pager` and it's treated as a view name to be looked up using search paths. Changing the behavior to additionally look for a relative file next to the executing view might be a fix, but it'd be a fairly risky fix since it changes the lookup semantics.
