### ISSUE TITLE
Would we simplify the process of WebApi ?

### ISSUE THREAD

**Issue by NMSAzulX** [aspnet/AspNetCore#4884]
Sometimes we dont need the Razor、View etc.. It is no use for the simple or WebApi-Interface-Services.
So we can remove some services from the function of UseMvc().
Such as:
[https://github.com/NMSAzulX/WebApiMiddleware/blob/master/WebApiMiddleware/WebApiExtentsion.cs](https://github.com/NMSAzulX/WebApiMiddleware/blob/master/WebApiMiddleware/WebApiExtentsion.cs)

**Comment by Yves57** [comment]
After little tests, please find some additional information:
I created two differents test cases (ASP.NET Core 3.0 Preview):

"Full MVC":
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Latest);
}
```

"MVC Light":
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvcCore()
        .AddApiExplorer()
        .AddFormatterMappings()
        .AddDataAnnotations()
        .AddCors()
        .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Latest);
}
```

The controller is the same:
```
    [ApiController]
    public class TestController : ControllerBase
    {
        [HttpGet("/test")]
        public string Get() => GC.GetTotalMemory(true).ToString();
    }
```

And I made the Startup class as lightweight as possible.

Results:

| | IServiceCollection.Count after init | GC.GetTotalMemory(true) |
| - | - | - |
| Full | 227 | ~1.37 MB |
| Light | 126 | ~1.04 MB |

So if I'm not wrong, adding Razor features seems to be not free. I understand that it is possible to do this work manually, but it would be nice to simply have a `AddMvcApiOnly` method (and maybe a class that would contain a subset of `Controller`).

**Comment by rynowak** [comment]
It's something we're thinking about for 3.0.0 - for anyone else following what's your proposed set of features that would be included by default?

 For instance if we made a method like `services.AddControllers()` that included:
- CORS
- Auth
- API Explorer (Swagger/OpenAPI)
- Data Annotations

Is this the right set? Would any of you be surprised for these things to be included, or for something else to be excluded?

**Comment by Yves57** [comment]
Nice!
For information, adding "Authorization" adds 9 services (135 services instead of 126 services).

In the `Controller` class, the last lines may be as useful as in the "full" MVC (`Json()`, `IActionFilter, IAsyncActionFilter, IDisposable` implementations). But in this case a new `ApiController` class (already with the `[ApiController]` attribute?) would be necessary. Maybe too much?

**Comment by rynowak** [comment]
> For information, adding "Authorization" adds 9 services (135 services instead of 126 services).

I think it would be really surprising if we gave people a **new and recommended** way of configuring MVC but it didn't include authorization by default. Authorization works because you put attributes on your controllers we recognize those attributes... without `AddAuthorization()` this would just silently no-op. 

Compare this to something like calling `View()` from a controller without adding the services related to views - this will throw an exception and you will immediately know about the problem. 

Data Annotations is similar - it has a very minimal cost if you don't use it, but if it's not included then stuff just no-ops.

**Comment by Yves57** [comment]
I agree! The remark about the number of services for "Authorization" was just an information :-).

**Comment by nvmkpk** [comment]
I think Razor and MVC should be completely independent of each other. Then Razor could be just a file provider (with additional details about model, view bag etc.).

**Comment by glennc** [comment]
I hope to do this in 3.0.0, just not 100% sure when yet. @rynowak and I need to get together to design it more and then get it done in a milestone. Hopefully around preview5.

**Comment by mkArtakMSFT** [comment]
@glennc should this move to preview4?
/cc @rynowak

**Comment by rynowak** [comment]
We've added an `AddControllers()` extension method in preview 4. Expect to see some more details about this part of the preview 4 announcement.
