### ISSUE TITLE
AsyncValidationAttribute

### ISSUE THREAD

**Issue by GeorgePetri** [aspnet/AspNetCore#4897]
As others have said #786, #7791, I think adding AsyncValidationAttribute would be beneficial.

This feature would allow doing non blocking validation logic in the attributes which are highly composable and reusable.

Thanks

**Comment by scalablecory** [comment]
Is there any progress on this?

I began working on this, but found I needed to make a large amount of changes and code duplication due to the amount of synchronous public interfaces that are involved in validation.

I'm not comfortable making such sweeping changes without input first -- if one of the .NET crew is able to provide some direction, I'd be happy to put in the work. Is duplication the best path, or is it okay to make this a breaking change to keep things cleaner?

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
