### ISSUE TITLE
Provide a hook for RazorPage.ExecuteAsync()

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#4905]
Feature request:
I can define a base class for the views, but there is no hook to execute some code before the view is executed. There is a method `ExecuteAsync` but it's not called on the base class.

My suggestion is to either call the base class `ExecuteAsync()` if there is one which is not abstract, or provide a new method that can be implemented by base view classes.

**Comment by mkArtakMSFT** [comment]
Closing this as there is no much community ask for this. Sorry @sebastienros :)

**Comment by ctorx** [comment]
I second the request by @sebastienros.  There should exist a method for calling async methods on a custom RazorPage base class somewhere in the request lifecycle so that async operations can be performed before any RazorPage is rendered.  One example of this would be data necessary for various aspects of an application but that is not specific to a given page.
