### ISSUE TITLE
Linked Views not working in WebApplication

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#5043]
_From @reaction1989 on February 9, 2018 8:50_

Hello,

i am trying to share the _Layout.cshtml over multiple projects. I created links in each project, but the application won't run.

I am getting this exception: 

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The layout view '_Layout' could not be located. The following locations were searched:
/Views/Account/_Layout.de.cshtml
/Views/Account/_Layout.cshtml
/Views/Shared/_Layout.de.cshtml
/Views/Shared/_Layout.cshtml
```
While googling i found this old entry on stackoverflow
https://stackoverflow.com/questions/24075105/can-i-use-views-in-folders-linked-from-other-projects

_Copied from original issue: dotnet/project-system#3232_

**Comment by pranavkm** [comment]
For 3.0, build time compilation using RazorSDK is the default workflow and linked views work out of the box. Runtime compilation which was re-introduced as feature in 3.0.0-preview3 does not recognize the project file, it does support multiple `IFileProvider` instances. It's conceivable to configure it to point to the content root of additional projects if runtime compilation needs to also support these files. Closing since no additional runtime work needs to be done here.
