### ISSUE TITLE
Razor Language Service does not appear to work with cshtml files in fsproj project

### ISSUE THREAD

**Issue by TheJayMann** [aspnet/AspNetCore#5085]
I have noticed for a while now that when attempting to use Giraffe.Razor to make views for a Giraffe web application, the cshtml files themselves have no intellisense or formatting outside of basic html.  After playing around a bit with adding ProjectCapability elements directly to the fsproj, I noticed if I add CSharp as a project capability and reopening the project in Visual Studio (as adding this capability tends to crash Visual Studio the moment a cshtml file is open, or immediately if one is already open), the cshtml file now gets basic razor formatting in addition to the html formatting, but no csharp intellisense, and all fs files only get basic fsharp formatting with no intellisense.

I would like to request that somehow Razor Language Service could somehow be made to work for this situation.  Having the design time editor treat the files as simply html files with no knowledge of how the razor or csharp bits work makes the use of Razor templates nearly worthless to me.

**Comment by danroth27** [comment]
I don't think we can realistically make this work. Razor files (cshtml) compile to C# files, which then get built with the project. As far as I know you can't add arbitrary C# files to an F# project and expect them to compile (nor can you add F# files to a C# project). If this ever worked in the past it was because the Razor files were being compiled at runtime, but we have been moving away from runtime compilation and instead plan to rely more on the Razor SDK to build Razor files at build time.

That said, what you should be able to do is have your F# project reference a Razor Class Library with all of your Razor files. I would propose that we should refactor the F# basd ASP.NET Core tempaltes to be structured this way. @TheJayMann Would that satisfy your needs?

**Comment by TheJayMann** [comment]
This is the conclusion I had come to.  It works well for large projects (as it could be said they need to be structured this way to add necessary separation), but tends to be a bit much for smaller applications, as this would require a minimum of three projects; one for the web application logic, one for the razor views, and one for the domain shared by the web application logic and the razor views.

I can understand the possibility that trying to get the csharp compiler to work with the fsharp compiler on a single project to allow cshtml and fs files to work together to have a higher cost than yield, and, should that be the case, I can live with multiple project proposal as being the chosen solution to this case.

**Comment by danroth27** [comment]
At this point we have no plans to support tooling for Razor files in anything but C# based projects. Since we don't have any plans to try to support Razor in other projects, I'm going to go ahead and close this issue.
