### ISSUE TITLE
UseStartup on GenericWebHostBuilder should fail when Startup.ConfigureServices returns an IServiceProvider

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#5149]
Right now it's being ignored and it should throw instead.

Program.cs

```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace WebApplication44
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateWebHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(builder =>
                {
                    builder.UseStartup<Startup>();
                });
    }
}
```

Startup.cs

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication44
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            return services.BuildServiceProvider();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }
}
```

Here's the code that supposed to do that check.

https://github.com/aspnet/AspNetCore/blob/cc899e2be729364589ba7f4392bce9942e4faca4/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L245-L249

**Comment by davidfowl** [comment]
cc @Tratcher

**Comment by buvinghausen** [comment]
@davidfowl I hate to bug you on a legitimate issue here but I don't want to log another issue and this is by far and away the most contextually relevant thread I can find to my question.

I'm setting up a POC for the Generic Host so that when 3.0 comes out we can adopt it quickly but I ran into all sorts of trouble trying to get the configuration stuff to work with the DI.  I had to tap out on Options entirely and I wound up having to chain it up as a Singleton as demonstrated here: [Program](https://github.com/buvinghausen/GenericWebHost/blob/master/Program.cs)

Am I completely off the reservation and is there a better way to accomplish what I'm trying to accomplish?

Thanks for all your hard work on this and I hope you have/had a happy holiday season.

**Comment by HassanHashemi** [comment]
@Tratcher Might i ask why should it throw?

**Comment by davidfowl** [comment]
@buvinghausen You really should file a new issue.

**Comment by davidfowl** [comment]
@HassanHashemi Returning an IServiceProvider from Startup.ConfigureServices does not compose with other calls to ConfigureServices. That pattern is the reason it was so difficult to implement allowing test services to override services added in Startup. It's also the reason why ConfigureContainer *only* works if you don't directly return the IServiceProvider from the ConfigureSevices.

**Comment by vincentparrett** [comment]
Since we can no longer use IStartup, and can't inject services into Startup, is there some other way that I can provide a startup instance. With 2.2 I'm creating my startup instance and passing in some instances I need, and then registering it with 

````c#
.ConfigureServices(services =>  
{
	services.AddSingleton(startup);
})
````
Seems like it's very restrictive (and I still need to figure out how to use autofac since that is broken now too).

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
