### ISSUE TITLE
Webpack 3 compatibility

### ISSUE THREAD

**Issue by michaldudak** [aspnet/AspNetCore#5172]
Please consider making the `aspnet-webpack` package (and others such as `aspnet-webpack-react`) compatible with webpack 3. Currently yarn issues the following warnings:

```
warning "aspnet-webpack@2.0.1" has incorrect peer dependency "webpack@^1.13.2 || ^2.1.0-beta".
warning "aspnet-webpack-react@3.0.0" has incorrect peer dependency "webpack@^2.2.0".
```

However, despite these warnings, the packages seem to be working fine (although I have not tested them extensively).

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, is there anything else to be done here?

**Comment by ryanbrandenburg** [comment]
@SteveSandersonMS could you link the PR/commit that resolved this issue for "aspnet-webpack" so I can better understand what I'm looking at/for?

**Comment by SteveSandersonMS** [comment]
@ryanbrandenburg It was this one: https://github.com/aspnet/JavaScriptServices/pull/1606/files

We should also discuss when or if it will be time to deprecate `aspnet-webpack-react` and the other NPM packages in https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/SpaServices/src/npm. AFAIK, none of them are used out of the box in the templates since ASP.NET Core 2.1 a year ago. Likewise there are .NET-side SPA middleware APIs in the `SpaServices` namespace that are no longer used out of the box, nor are relevant with more recent third-party SPA frameworks (this does *not* include `SpaServices.Extensions` - that is still central to the current templates). I'm not saying we *can't* maintain them, but it makes sense to have a defined plan about what our longer-term support intentions are and to focus efforts appropriately.

cc @mkArtakMSFT @danroth27

**Comment by ryanbrandenburg** [comment]
@SteveSandersonMS totally agree WRT long term plan and focusing effort.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
