### ISSUE TITLE
Question about implementi VueJs Cli integration

### ISSUE THREAD

**Issue by valeriob** [aspnet/AspNetCore#5214]
Hi,
i would like to use vuejs cli with aspnet core projects.
I tried to use UseAngularCliServer with vue command and it "almost" worked as is !
 app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "clientApp";
                spa.UseAngularCliServer("serve");
            });

The only line i had to change is this line, what do you think ? Would you accept a pull request for this feature ? Since i just had to change a line, would you like to configure it ? but then the whole api would not reflect the support for vue, so maybe maybe refactor it out is a better choice (CliBuilder/CliMiddleware and AngularCliMiddlewareExtension, VueJsCliMiddlewareExtension)

![image](https://user-images.githubusercontent.com/1522516/42328511-bb2b6ee0-806e-11e8-8ad1-3130c3adb1cf.png)

**Comment by alexeyzimarev** [comment]
I believe the `ReactDevelopmentServerMiddleware` is a good start. It waits for npm to output `Starting the development server` and for Vue I needed to change it to `Starting development server`. Ideally, it would be `App running at`, otherwise the middleware tries to proxy the first request to the server that hasn't started yet. Everything else is the same.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @valeriob .
This is indeed going to be addressed as part of https://github.com/aspnet/AspNetCore/issues/5182
