### ISSUE TITLE
Forms and validation

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5460]

**Comment by TheCakeMonster** [comment]
Would it not be wise to build an implementation based on one of the existing rich client UI patterns, such as IDataErrorInfo? It feels like you'd be rather reinventing the wheel if you didn't look at reusing an existing pattern. The only question would be which pattern I suppose!

**Comment by TheCakeMonster** [comment]
I would be uncomfortable with rules having to be defined in the template. In my experience, this leads to a lot of duplication, as you often need to test validity on both sides of an API boundary, or on multiple UIs.
People have become more comfortable with rules on the model, made more popular by DataAnnotations on MVC.
Rules in the template is akin to what we had in WebForms, and it was a pain. That almost always resulted in duplication of rules.
Rules should be as low down in your application as you can comfortably push them, to achieve consistency.
ViewModels can be used by those who feel that applying rules to the model itself is to be avoided. Personally, it's not something I worry about, but ViewModels help for those who do.

**Comment by rockfordlhotka** [comment]
There are a couple philosophies on validation rules, and I think it is important to keep them in mind when considering validation features in any UI framework.

One philosophy says that validation rules aren't _real_ business rules, and they can (and should) be enforced by the UI, not by an official business layer. And I get that, especially in the js-based web world where the business layer is almost always in .NET/Java on a server, and whatever is running in the browser is (at best) a shadow copy of the real rules.

Another philosophy, widely used in the smart client frameworks over the past 20+ years, is that the UI shouldn't embody the rules at all, but rather should provide interfaces or events or something such that the business layer can report to the UI what is good/bad and the UI can decide how to display that information to the user.

I'm a strong advocate of the second philosophy, because I'm a strong advocate of separation of concerns and having an official business layer separate from the presentation. To make such separation possible it is necessary to have some abstraction so all the rules (including validation) run in the business layer, but have immediate results displayed to the user.

XAML is amazingly good at this via a combination of interfaces (`IDataErrorInfo`) and data binding to _anything_ - including types that provide clean abstractions between sophisticated business logic and the presentation layer.

So my plea is that if you go down the road of building validation do-dads into the UI framework (as I suspect is inevitable), that you _also_ make sure to support the more powerful model of keeping all business logic in a business layer and provide an abstraction layer so the results of rules can be displayed to the user by the presentation layer immediately.

After all, what we're talking about here is running the business layer (or parts of it) in the browser directly via wasm - so the direct analogy is to WPF. Having something comparable to the rich data binding and `IDataErrorInfo` concepts in WPF, but logically translated to Blazor and HTML is critical.
