### ISSUE TITLE
Solution for accumulation of Disposable transient services

### ISSUE THREAD

**Issue by rstropek** [aspnet/AspNetCore#5496]
Given a service:

```
public class Repository : IRepository, IDisposable { ... }
```

It is injected as a transient:

```
static void Main(string[] args)
{
    var serviceProvider = new BrowserServiceProvider(configure =>
    {
        configure.Add(ServiceDescriptor.Transient<IRepository, Repository>());
    });

    new BrowserRenderer(serviceProvider).AddComponent<App>("app");
}
```

If this service is injected into a component, it is never disposed even when navigating away from the component:

```
@page "/"
@inject IRepository Repository
...
```

Is this a bug or is there a functionality available to dispose injected services implementing `IDisposable`?

**Comment by danroth27** [comment]
We're concerned about the potential for memory leaks here with transients. Circuit lifetime is arbitrarily long. We need to think about this.

**Comment by rynowak** [comment]
## Summary

The solutions to this will require a new DI feature *or* will required going outside the DI system entirely.

The problem is that the DI system will **track** transient values. This means that anything you resolve as a transient is kept in memory until the DI scope is disposed.

There are a few approaches to this that we've outlined so far:

## Self-serve unregistration

This is the proposal from DI: https://github.com/aspnet/Extensions/issues/1785 - in this model each service that wants to support early disposal has to be aware of it. 

```C#
public class SelfDisposer : IDisposable
{
    public SelfDisposer(IServiceCollectionNotifyDisposed notify)
    {
    }

    void IDisposable.Dispose() => _notify.NotifyDisposed(this);
}
```

## Handles

This model allows requestors to resolve a `Handle<>` from DI. The handle matches the lifetime *for the consumer's usage of the service*. When you're done consuming the service you can dispose your handle:
- If the service is transient it will be disposed and removed from memory
- If the service is scoped, disposing the handle does nothing (disposed along with scope)
- If the service is a singleton, disposing the handle does nothing (disposed along with container)

You can think of this as a non-owning handle - like `std::shared_ptr<>`.

```C#
public sealed class Handle<T> : IDisposable
{
    public Handle(T service, bool ownsLifetime)
    {
    }

    public void Dispose()
    {
        if (_ownsLifetime && service is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
```

## Owing handlers

This model allows requestors to resolve an `OwningHandle<>` from DI. All services are created *as-if* they are transients, and their lifetime is owned by the handle - they are disposed when the handle is disposed. There are cases where this won't work or won't work correctly. For instance if the service is registered an an instance then this is an error - or if the service is created by a factory function then there are no guarantees. 

The reason why `OwningHandle<>` is required at all is to allow callers to specify whether they want to control the lifetime or not.

```C#
public sealed class OwningHandle<T> : IDisposable
{
    public Handle(T service)
    {
    }

    public void Dispose()
    {
        if (service is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}

**Comment by divega** [comment]
@rynowak I am curious how the two handle-based approaches would work when an IDisposable service depends on other IDisposable service(es) (or a tree of them). At first glance, it seems to me that in order for the memory to be released, each IDisposable service would need to be changed to start only depending on other handles, and never on other IDisposable services directly. I.e. isn’t it kind of viral?

Also, isn’t it a bit strange that the the handles themselves are IDisposable but need to break the rules of how IDisposable services work in order to release any memory? I.e. to remove their owned service (and possible themselves) from the container’s disposable list, wouldn’t they need the feature you describe as self-serve unregistration?

In summary, assuming I am not missing anything:

1. Self-serve unregistration could be the basic building block. Any IDisposable service that is aware of it can use it directly and continue to be consumed with no changes on consuming code enjoy the benefit of early memory release.

2. Handlers (any of the two variations) can be used to optimize existing IDisposable services without requiring modifications, but only if they don’t depend on other IDisposable services.

3. If you have a tree of IDisposable services that you want to optimize, you will have to change the code of the service one way or the other. You face the choice of having to wrap every IDisposable  into a handle, or you can make all of them self-unregistering, with the latter providing a nicer experience for consumers of the service.

**Comment by dazinator** [comment]
Why couldn't Blazor follow the asp.net core Request middleware example (as also mentioned by @rstropek ) -  create an `IServiceScope` and using that scoped IServiceProvider to activate it's pages / components. Dispose of that scop when the page / component is disposed. Are there difficulties in that approach that has lead to the above suggestion with this new wrapper tactic?

**Comment by smartprogrammer93** [comment]
So for now. do i have to dispose of every transient IDisposable Service in the dispose function of the component?

I believe this should be a high priority issue. Thank you for your hard work

**Comment by rynowak** [comment]
Added a utility component for this. Will updated docs as part of the release.
