### ISSUE TITLE
Route precedence 

### ISSUE THREAD

**Issue by marcusbooyah** [aspnet/AspNetCore#5542]
I have an app with two routes:

`@page "/{multiple}/catalog/new"`
`@page "/{multiple}/catalog/{catalogId}"`

When accessing the /{multiple}/catalog/new URL, the router seems to be taking me to the /{multiple}/catalog/{catalogId} route. This used to work the other way around for me. Is this a bug, or am I doing something wrong?

This is on Blazor 0.5.0-preview1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @marcusbooyah.
We're tracking this as part of #5489

**Comment by iron9light** [comment]
@mkArtakMSFT Was this feature implemented?
If YES, I wanna feature below. Can I do it?
> Support subfix with catch-all routing.
> Something like this: "{controller}/{**path}/{action}"
If NO, please reopen this issue.

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
