### ISSUE TITLE
One single route is reported as 'The following routes are ambiguous'

### ISSUE THREAD

**Issue by dustgrinder** [aspnet/AspNetCore#5548]
I repeatedly get errors such as this:

`Error: System.InvalidOperationException: Failed to compare two elements in the array. --->` `System.InvalidOperationException: The following routes are ambiguous:`
`'admin/product/{ProductUrl}' in 'X.Client.AdminWide.UpdateProduct'`
`'admin/product/{ProductUrl}' in 'X.Client.AdminWide.UpdateProduct'`

I have only one route 'admin/product/{ProductUrl}' in that page. Also, that page has been working for a while, but only shows that errors after I create a new page with a dynamic url ("/user/{UserName}/orders"), which really has nothing related to it.

The error only happens if the url is like "/admin/product" and doesn't happen when it's "/admin".

The oddest thing is, *sometimes* I would edit the route of a wholly unrelated page into "/x/y" and a random other page would break.

What could be the case here?

**Comment by springy76** [comment]
I just reached that show stopper, too.

**Comment by springy76** [comment]
BTW: Show-stopping means that when this happens then the `Router` component fails to initialize it's route dictionary and you will see absolutely nothing (but an error message scrolling by in server console).

**Comment by springy76** [comment]
Do you need more feedback or will this bug just be part of 3.0 release?

**Comment by McHeff** [comment]
So this has just happened to me as well... 

Very strange, I have two pages, Users, and EditUser... 

On my editUser page, that's where it's complaining about "The following routes are ambiguous" error... 

What's interesting though is this only happened when I put 

`  <input type="text" bind="@searchValues" />`

without the binding like this it works fine... 

`  <input type="text"  />`

Basically, with binding I get the ambiguous routes, take the binding away and it works just fine... 

I have a discord server for Blazor if ya'll interested: https://discord.gg/Xg9ja5s

**Comment by springy76** [comment]
Since src/Components/Components/src/Routing/RouteTable.cs has not been modified since mid of January this problem will always happen randomly after adding new routes or changing existing routes.

The problem is that generic `Comparer<T>` cannot do `if (x==y) return 0` internally because `T` is neither `struct` nor `class`. `RouteTable.RouteComparison` has to do this itself.

This problem is so random because IMHO it only happens on special bucket state edge cases during quick sort (`routes.OrderBy(id => id, RoutePrecedence)`).

**Comment by pranavkm** [comment]
@springy76 could you share a sample that reproduces the error?

**Comment by pranavkm** [comment]
Feel free to reopen once you have an application to share.

**Comment by springy76** [comment]
I don't know if someone at dotnetcore fixed some comparer code, but if not: My fix -- which I already posted twice -- would suppress this error: `if (x == y) return 0;`

**Comment by pranavkm** [comment]
@springy76 it is an error condition to have two identical routes. Making the change you suggested, particularly without knowing the root cause, is problematical

**Comment by springy76** [comment]
@pranavkm then use `if (object.ReferenceEquals(x,y)) return 0;`. There are no identical routes when the non-struct object instances are the same.

**Comment by springy76** [comment]
I now sacrificed 95% of my after-work-hours (Feierabend) in order to (try) reproduce the exact constellation of Jan-31 against preview4. Either I missed something or -- since I did not see this problem for long this is more likely -- meanwhile someone at netcore fixed something in comparison code or LINQ-OrderBy code which prevents that `x` and `y` are exactly the same instance.

But I still say: Adding `if (object.ReferenceEquals(x,y)) return 0;` as a short circuit would not do any harm but prevent such nonsense error in future, whatever was/is/will-be the cause for that.

**Comment by peteralbanese** [comment]
I just ran into this error also. Its as if I can only have x number of routes in my app and then i can't add any additional razor components. please help!

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
