### ISSUE TITLE
Unpredictable No element is currently associated with component {ComponentId} 

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#5592]
**Edited to remove the false-positives**

Reproducable : https://github.com/aspnet/Blazor/issues/1412#issuecomment-439267547

Using Blazor Server Side
From time to time Blazor throws the following error:
`No element is currently associated with component {ComponentId}`

The error is always thrown on the first load after a `StateHasChanged`, if you hard refresh the page the error doesn't happen anymore.

- Is there a way to see which component has which id?
- Is this a known issue?

For me this is quite vague and it happends for no certain reason, only from time to time.

**Comment by Gaulomatic** [comment]
I am getting this error as well. I have declared multiple components (entrypoints) in the Startup.cs:

`
app.AddComponent<GetInvolved>("app-1");
app.AddComponent<ActionCallList>("app-2");
`

I include them on different locations on the website. However, this makes this error appear. Only if I include all declared components all the time, the error does not occur (It does at some point if navigation events take place, but in my case this isn't happening). May be this helps to track down the cause.

**Comment by gulbanana** [comment]
I'm currently using a workaround - I have a custom version of blazor.server.js where the renderer gives up trying to apply the edit and just returns, rather than throwing an error which will break the websocket connection. this isn't suitable for production, since it still means that some component just doesn't update and you have to try the state change again, but it's ok for demos and prototyping

**Comment by CobraCalle** [comment]
Hello,

I've got this error too, but I think the problem is another than discussed until now…

We are developing a blazor version of our 3D product configuration application at the moment and we use xml3d to build the scene in html with blazor (works like a charm by the way :-) ). Here we define the required materials first and later we reference the materials in the geometries... at some point of the development we had the situation that some geometries were rendered with the wrong material or with no material... but the material elements where correct. So we hat a look how the material elements where changed while configuring (for example changing the color of the product). 

And I think what we saw is the underlying problem here: When we added a material that was not the last in the material list (we sorted the elements by their id), the DOM was correctly changed… BUT the "instances" where changed mixed up… example…

<Material id="a" src="x"/>
<Material id="c" src="y"/>

Then we add: <Material id="b" src="z"/>

Result:
<Material id="a" src="x"/>
<Material id="b" src="z"/>
<Material id="c" src="y"/>

On the first look, that is correct… BUT the former material "c" was changed to "b" and a new element with id "c" was added (you can see this in dev mode of chrome)… and that was the problem! We fixed it by making sure that we only add new elements to the end and never remove elements (in this example a,c,b) and that works. But of course this only works in this special scenario and we have the lots of problems with "no elements etc." too, but I think this gives us an interesting hint, why the event handles stop working…

Lets adapt the scenario from above to an other sample...
When we have a list of components that are clickable…
<div onclick="handler (click component 1)">Product A</div>
<div onclick="handler (click component 2)">Product B</div>

now we remove product B and add Product C... then we expect that the html-element of product B is removed and a new element for product C is created… but that is not the case… it "updates" the existing element for product B to match the required element for product C. And in this case the event handler IS NOT updated to macht the event handler for product C... result:

<div onclick="handler (click component 1)">Product A</div>
<div onclick="handler (click component 2)">Product C</div>

When you click on product C the server creates an exception "no element assigned to 2" because the sever "thinks" the element for product B (2) was removed and a new for product C (3) was created… but that is not the case.

When you now create a button that toggles the rendering of the product list and click it to remove all elements and click it again to rerender the list, everything is working again… 

I hope this helps to get rid of this annoying bug…

Carl

**Comment by SteveSandersonMS** [comment]
@CobraCalle Your issue sounds unrelated to the one being originally reported here. I think your issue is that you need to preserve DOM element identity through edits because of the 3rd party library that's also interacting with the DOM. This requirement is handled by specifying `key`, however it's not yet implemented (tracked in #5455). Until we implement `key`, you'll need to continue using your current workaround.

**Comment by DeanRoddey** [comment]
You know, thinking about this just now as it was happening to me again... I wonder if it's as simple as just not reliably getting rid of element/component references when the things referenced go away. Given that, for us, it always happens after we invoke a modal, and then render those bits away when the modal is dismissed. The stuff is obviously gone, because it doesn't get drawn anymore and StateHasChanged has to be called to make that happen, but then we get the problem after that in certain subsequent popups. 

It's as though some internal refs to the things that got rendered away are still there.

**Comment by DaleCam** [comment]
For me - I can replicate this AS SOON AS I inject a HttpClient in my page:
`[Inject] private HttpClient Http { get; set; }`
And as soon as I take it out, the page works again. I hope that helps narrow it down!

**Comment by vertonghenb** [comment]
Sometines this can also be caused if your App is throwing a null ref. exception and you're not catching it.

**Comment by DaleCam** [comment]
> Ok it took a lot of elimination, but for me - I can replicate this Issue as soon as I inject a HttpClient in my page. I dont even have to use it. Just inject it:
> `[Inject] private HttpClient Http { get; set; }`
> And as soon as I take this line out, the page works again. I hope that helps narrow it down!
> (It also explains why the Server Side Template Project still works as none of the pages use HTTPClient...)

Further to this its actually when i simply Inject ANYTHING on the page. I created a skeleton class, injected it into my page, and I got the "No element is currently associated with component {id}" error. I remove the inject, it loads again.

**Comment by DaleCam** [comment]
I was just able to solve this (for my project anyway) by following the fantastic idea in this git:
https://github.com/Suchiman/BlazorDualMode

**Comment by vertonghenb** [comment]
Seems to be fixed in Preview-2

**Comment by dynamiclynk** [comment]
I received this error because I was trying to @inject the wrong type and this was the general error that was thrown instead of a relevant error relating to finding the service in the collection\container.
