### ISSUE TITLE
TypedArray fail to serialize

### ISSUE THREAD

**Issue by galvesribeiro** [aspnet/AspNetCore#5619]
Hello folks!

While I was implementing [Blazor.Extensions.WebUSB](
https://github.com/BlazorExtensions/WebUSB), I had to send/receive buffers to the USB device connected. In C#, I was sending `byte[]` down to JS and it was working perfectly fine. However, when I was sending a buffer back from JS to C#, it fail without any errors since it was unable to deserialize the `Uint8Array` into a `byte[]`. It just hang on the `resolve(array)` call.

After a day trying to figure out what is going on, I noticed that if I convert it to a regular array it works perfectly with `Array.prototype.slice.call(new Uint8Array(out.data.buffer))`. That is very inefficient... 

The reason for that (looks like) is because we don't have support to deserialize [`TypedArray`s](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) on SimpleJson...

The same problem happens on [Blazor.Extensions.SignalR](https://github.com/BlazorExtensions/SignalR) when we have a callback that expects a `byte[]`.

Look at the examples [here](https://github.com/BlazorExtensions/WebUSB/blob/master/src/Blazor.Extensions.WebUSB.JS/src/USBManager.ts#L184) and [here](https://github.com/BlazorExtensions/SignalR/blob/master/src/Blazor.Extensions.SignalR.JS/src/HubConnectionManager.ts#L100).

Do we have a less hacky/slow alternative to this?

Thanks!

**Comment by SteveSandersonMS** [comment]
Check how Blazor's WebAssembly HTTP client deals with returning a large byte array from JS to C#.

Fundamentally you do have to copy the data at least once, because a JavaScript object isn't a .NET object and can't participate in the GC system directly. So for HTTP, the JS code asks the .NET code to allocate a `byte[]` of the desired size, then it copies the data into the .NET memory heap at that location.
