### ISSUE TITLE
Component does not update DOM on a specific scenario

### ISSUE THREAD

**Issue by rodolfograve** [aspnet/AspNetCore#5656]
With the following component I'm trying to apply a transformation to the value in the input. The actual use case is more complicated and makes more sense but this is the simplest repro I could come up with.

Reproduction steps:

1. Enter a lowercase string in the input, e.g. "asd"
1. Result: the string in the input is turned into its uppercase equivalent and the Message is updated correctly.
1. Enter the **same** lowercase string in the input. _Notice that entering any other string works as expected._

Expected:
The string in the input **is turned into its uppercase equivalent** and the message is updated correctly.

Actual:
The string in the input **remains unchanged** and the message is updated correctly.

```
@page "/repro"
<input type="text" bind="@RawValue" />
<div>
    Message: @Message
</div>
@functions
{
    protected string Message { get; set; }
    protected int Count { get; set; }

    private string _rawValue;
    protected string RawValue
    {
        get => _rawValue;
        set
        {
            _rawValue = value?.ToUpperInvariant();
            Message = $"_rawValue was set to {_rawValue}. {Count++}";
            StateHasChanged(); // I don't think this is necessary but I've added it trying to solve the problem. It still doesn't work without this line.
        }
    }
}
```

It seems to me there is something wrong but please let me know if it's by design, in which case, could you also please explain how to achieve the behavior I want.

**Comment by SteveSandersonMS** [comment]
@enetstudio is correct. The diffing system has no way to know that it should write an update to the DOM, because as far as it knows, the value you're rendering is the same as was last written to the DOM already.

To achieve the behavior you want, I'd recommend separating your "binding" from your "value transformation". If you use `bind-value-oninput`, then Blazor will get a notification on each keystroke, so it will see the intermediate non-transformed values (e.g., lowercase `asd`). Separately, since you only want to transform to uppercase (or convert `£` to `GBP`, etc.) when the user tabs out, put that in an `onblur`:

```cshtml
<input type="text" bind-value-oninput="@RawValue" onblur="@ConvertValue" />
<div>
    Message: @Message
</div>
@functions
{
    protected string Message { get; set; }
    protected int Count { get; set; }
    protected string RawValue { get; set; }

    void ConvertValue()
    {
        RawValue = RawValue.ToUpperInvariant();
        Message = $"RawValue was set to {RawValue}. {Count++}";
    }
}
```
