### ISSUE TITLE
Populate JSRuntime.Current before invoking Startup.ConfigureServices

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#5664]
I have a library project that needs to do some initialization is the host project's Startup.cs that includes using javascript. This used to work prior to the JS syntax change. Now, however, JSRuntime.Current is null. I created a reproduction of the problem here: https://github.com/chanan/JSRuntimeRepro

**Comment by Lelelo1** [comment]
I am looking to use a javascript library from Xamarin and was hoping I could use `JSRuntime`. I'ts null though and has to initialised somehow.

**Comment by SteveSandersonMS** [comment]
This issue is obsolete since we removed JSRuntime.Current. 

@Lelelo1 I’m not sure what your scenario is. If you can post a new issue with full repro steps we can give a better response. Thanks!

**Comment by Lelelo1** [comment]
I attempted adding a Razor library to a Xamarin solution - to consume a javascript library via a `.razor` file.  Using `@inject IJSRuntime JSRuntime`, the JSRuntime remains null.

I assume this is due to the steps you @SteveSandersonMS described has to be made - or else a web application has to be started up.
