### ISSUE TITLE
Referenced Component can not be used in a cascading value

### ISSUE THREAD

**Issue by ckbeatty** [aspnet/AspNetCore#5675]
When using a combination of both a component reference and cascading value, that value is not sent to child elements

Example
```
@inherits BlazorLayoutComponent


<div class="sidebar">
    <NavMenu/>
</div>

<Modal ref="modalTest"/>

<div class="main">
    <CascadingValue Value="@modalTest">
        <div class="content px-4">
            @Body
        </div>
    </CascadingValue>
</div>

@functions
{
    Modal modalTest;
}
```
When accessing the modal in the following component, I am always getting a null reference exception
```
@page "/Admin"
@inject HttpClient Http
<h3>Students</h3>

@functions
{
    IList<Models.Student> _students;
    
    [CascadingParameter] Modal _modal { get; set; }

    protected override async Task OnInitAsync()
    {
        _students = await Http.GetJsonAsync<IList<Models.Student>>("api/Student/GetStudentsWithGoalsAndAvailableAnswers");
    }

    protected override void OnAfterRender()
    {
        _modal.ElementId = "This is a test";
    }
}
```

The only thing that would not make this throw an error was to define the modal in the following way in the layout `Modal modalTest = new Modal`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ckbeatty.
@SteveSandersonMS what can we do regarding:
> @SteveSandersonMS maybe it is possible to change the design and initialize reference variable immediately after the child component is rendered

**Comment by SteveSandersonMS** [comment]
> initialize reference variable immediately after the child component is rendered

We already do. The problem is that you're trying to pass the value to a child before the rendering has even finished.

Overall I would recommend you adjust your design so that the thing you cascade isn't another component instance, but rather is an instance of some other (non-component) class of your own.

The `ref` feature is only a way for a component to get a reference to one of its own children *after* its rendering cycle completes. It's not a feature that can be used for scenarios where you want access to a child *before* the rendering cycle completes, since the child doesn't necessarily exist at that stage.
