### ISSUE TITLE
You can easily get into a mess with social logins

### ISSUE THREAD

**Issue by rtpHarry** [aspnet/AspNetCore#5728]
Social logins doesn't seem very well supported. I've enabled the facebook logins and its working ok but the way it works feels like it's going to confuse a lot of customers.

  1. The register page doesn't show the active external services.
  1. The log in page automatically registers a new account if you "log in" with a new external service. There is no way to prevent this.
  1. The is no way to merge accounts once you have accidentally ended up with two accounts because of this.
  1. Once that external service has a made that new account going to your real local account and trying to add the social login shows a forbidden page.
  1. There is no way to delete your accounts.

Ideally I would like to be able to use the facebook login button and if the returned account matches an existing local account I should be given the opportunity to merge the social login onto the local login account. 

Or alternatively some way to stop the mess from happening. So a setting that means you can only log in with social accounts not register a new account.

**Comment by kanadaj** [comment]
@blowdart Just run into an issue with this one as well, more specifically with account deletion.

Normally, we ask users to re-enter their password before deleting their account to protect our users. The problem is, when someone registers via an external login, they have no password. Is there any way to force a re-authentication with a social account in this case?

If not, the only available method is to send an email to the associated email address retrieved from their social account. It'd be nice if Identity supported this scenario natively, and generally account deletion, what the GDPR requiring it and all that.

**Comment by blowdart** [comment]
Identity creates its own user when you create via social, and should prompt for a local password, and details, including email addresses.

**Comment by RemiBou** [comment]
I don't understand why do we need local password or local email if logging via social ? isn't it the point ? Local username ok. I don't think I ever saw this kind of experience somewhere with social login.

**Comment by kanadaj** [comment]
You can use the social email address as the local email (as you should, otherwise we're back to the whole email confirmation loop that social login is meant to avoid). Local password though, yeah, you shouldn't ask for a password for an account made for social login...

**Comment by blowdart** [comment]
Closing as by design
