### ISSUE TITLE
Social login provider options don't show up in register

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#5766]
* With a social login provider enabled, go to register.
* No social login provider is displayed.
* It shows up in the login view.

**Comment by HaoK** [comment]
@ajcvickers @blowdart here's what the current change looks like, basically just copied over the login div and changed the text to register instead of login, I can submit a PR if this is good enough

![image](https://user-images.githubusercontent.com/6537861/51715944-a2c56100-1fef-11e9-8867-a3254874eb0c.png)

**Comment by ajcvickers** [comment]
I defer to @blowdart

**Comment by blowdart** [comment]
That's good enough

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/7002
