### ISSUE TITLE
Make ExternalLoginsPageFilter accessible

### ISSUE THREAD

**Issue by natelaff** [aspnet/AspNetCore#5801]
Scaffold identity, but want to remove the "Identity" area folder. Have to add Razor page options to new area. Would be nice if we didn't have to duplicate ExternalLoginsPageFilter because its internal to UI. If we're scaffolding identity, one can assume we'd want this filter, too.

**Comment by blowdart** [comment]
We've having a hard time understanding what you want to do here. Is it moving the scaffolding to a different area to the default?

**Comment by natelaff** [comment]
@blowdart I don't quite remember this exact flow, but the problem was I scaffolded identity pages to customize them, but I didn't want them in the /Identity area. When you do this, you have to grab all that identity "sugar" for config. The problem was this filter was not accessible to use, so I had to go into GitHub grab the source for it and duplicate it in my own code. However, it didn't appear like it actually did anything.

**Comment by blowdart** [comment]
@javiercn Is this a good idea? We think this was your area.

**Comment by javiercn** [comment]
I think this talks about things done in AddDefaultIdentity?

There were differences introduced in there on 2.1 and 2.2 compared to regular AddIdentity.

Of those things, none are related to adddefaultui afaik

**Comment by javiercn** [comment]
That filter is an implementation detail from the UI. You can achieve the same thing with 1 line of code
in _ManageNav.cshtml we do it with a filter due to limitations on how Razor Pages handle generics, but you are not constrained by those, so it's easier to simply write 
`await _signInManager.GetExternalAuthenticationSchemesAsync()).Any()` in your _ManageNav.cshtml file.
