### ISSUE TITLE
Analyze default request buffer size

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5850]
A 4kb buffer is currently allocated to receive each request. Http.Sys will fill this with the request headers, url, etc., including any of the body that has already arrived.  If the buffer is not large enough, Http.Sys will tell us what size it needs and we'll create a new buffer.

Questions: is 4kb too large?  How large is an average request?  What's the added cost if your average request doesn't fit and needs an expanded buffer? Should this default be configurable?

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
