### ISSUE TITLE
Can the request buffer be freed sooner?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5851]
A 4kb buffer is allocated to accept each request. The request holds onto this buffer for its entire lifetime, and lazily reads fields from it (headers, etc.).  The lifetime of this buffer is problematic for long running requests, such as WebSocket requests.

Consider tracking how much information has been copied out of the buffer and, if it reaches a certain threshold, drain the remaining data and discarding the buffer.  This may be especially relevant during a WebSocket upgrade.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
