### ISSUE TITLE
Kernel response buffering

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5852]
Http.Sys supports internal response buffering for better response performance.  WebSockets already enables this by default.  However, enabling this prevents the developer from doing multiple concurrent writes.

Consider enabling this by default, and allowing it to be configured per server and/or per-request.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.

**Comment by mgravell** [comment]
This is merged for full release in net8
