### ISSUE TITLE
Advanced auth config

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5853]
Http.Sys's native auth implementation supports several advanced features that have not yet been exposed. See HTTP_SERVER_AUTHENTICATION_INFO:
            // NTLM auth sharing (on by default?) DisableNTLMCredentialCaching
            // Kerberos auth sharing (off by default?) HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING
            // Mutual Auth - ReceiveMutualAuth
            // Digest domain and realm - HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS
            // Basic realm - HTTP_SERVER_AUTHENTICATION_BASIC_PARAMS

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
