### ISSUE TITLE
Clear memory after a WebSocket upgrade

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5854]
After a WebSocket upgrade very few of the request members will ever be used again (headers, path, query, etc.). Applications can greatly increase their server density if they're able to reduce their per-connection memory usage.  We should clean up what we can automatically and allow the remainder to be cleaned up manually.

Clear automatically:
- The 4k request buffer: https://github.com/aspnet/WebListener/issues/40
- Request & response streams

Allow clearing manually:
- Request & Response headers (`Clear()`)
- Uri fields
- Method
- IPs

Maybe just have a public `CleanupNonWebSocketResources` method that deletes everything.

Note that customers are already doing this kind of cleanup via private reflection. Make it so they don't have to.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
