### ISSUE TITLE
Make StandardFeatureCollection mutable

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5858]
Hosting no longer wraps the servers's feature collection by default, so WebListener creates a FeatureCollection wrapping the StandardFeatureCollection. Just find a way to make StandardFeatureCollection mutable.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
