### ISSUE TITLE
Enable setting the queue name

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5859]
Enable manually set the http.sys queue name for the application. This helps detect potential application-level problems by monitoring the queue-length counter.

Moved from https://github.com/aspnet/Home/issues/1417

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
