### ISSUE TITLE
Support PHTTPLOGDATA 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5860]
Add the ability to write http.sys logs for all requests. (Available via the PHTTPLOGDATA parameter in the HttpSendHttpResponse of the HTTP Server API.)

Moved from https://github.com/aspnet/Home/issues/1417

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
