### ISSUE TITLE
Update TLS Token binding to v1.0 of the spec

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5862]
See https://github.com/aspnet/WebListener/issues/230
https://datatracker.ietf.org/wg/tokbind/documents/
Contact: Pranav Kukreja

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
