### ISSUE TITLE
Support creating a request queue with ACLS

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5867]
HttpCreateRequestQueue supports creating a request queue that takes credentials. This allows a process to access a prefix registration using credentials different from those of the process.

Filing for future investigation, recommend Backlog.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
