### ISSUE TITLE
More graceful shutdown

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5868]
The current shutdown procedure is to:
- Mark as shutting down
- stop message pump loops
- 503 any new requests
- wait (for at timeout) for active requests to drain
- stop/dispose the listener

Since the packages/layers were merged maybe this could be more graceful. It may be possible to detach the urlgroup from the request queue and still let requests drain gracefully. Then Http.Sys will be the one to send 503s for new requests. Note we can't shut down the request queue without it canceling requests in flight.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
