### ISSUE TITLE
Look for new perf optimizations as a result of the layer merging

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5870]
In https://github.com/aspnet/HttpSysServer/issues/283 we merged the packages and layers and hid the lower level API. Profile and see what optimizations can be made now that there's no strict layering boundary.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
