### ISSUE TITLE
End-to-end latency under load is much higher than HttpListener when using windows auth

### ISSUE THREAD

**Issue by davidmatson** [aspnet/AspNetCore#5871]
See #333 for more details of the setup. Testing client request latency under load (at 200-400 requests/sec), with multiple clients HttpListener (again, see #333 for the exact code used) provides much lower latency than WebListener (HttpSysServer) does. For example, with three clients loading the server using WebListener, end-to-end latency for an authenticate request was 80% between 500ms and 1sec. With an IServer calling the OWIN HttpListener, 99% of requests complete in less than 500ms. Stated another way, I can get clients to issue requests and wait for complete responses at ~400 request/sec with OWIN HttpListener and at ~200 requests/sec with WebListener.

(Let me know if you're not able to replicate this problem easily, and I can work on a minimal repro.)

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
