### ISSUE TITLE
Mirror Kestrel's BadHttpRequestException feature error status codes

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5873]
Kestrel has a feature that uses its special [BadHttpRequestException](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions.clientcertificates(v=vs.110).aspx) type to determine what status code to return to the user. E.g. if this exception is thrown (as the InnerException) from the request stream read APIs (e.g. due to length limits), and that exception goes unhandled all the way back up the app pipeline to kestrel again, then kestrel will return a predetermined status code (e.g. 413) from the exception to the user in place of the default 500 error.

It's a little strange to rely on an exception flowing through the users stack and back to you, but it does give the user the opportunity to intercept it and send their own response.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
