### ISSUE TITLE
Allow challenging individual auth types

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5875]
WebListener 1.0 registered its auth types schemes that could be challenged individually. In 2.0 they are all combine as one "Windows" scheme. See if we can find a way to optionally challenge for individual types again. This may or may not involve registering additional schemes.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
