### ISSUE TITLE
Consider an options to allow setting the "DisplayName" of the windows authentication scheme

### ISSUE THREAD

**Issue by brockallen** [aspnet/AspNetCore#5876]
Much like is allowed in the IIS Integration server implementation with `IISOptions.AuthenticationDisplayName`.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
