### ISSUE TITLE
Examine the perf of AsyncAcceptContext memory management

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5880]
Back in Sept Justin refactoed Http.Sys and introduced a memory leak in AsyncAcceptContext https://github.com/aspnet/HttpSysServer/commit/231cbffe1a5cc0abce11e2d0685683ed74fc7ad5
This was fixed around 11/2 by https://github.com/aspnet/HttpSysServer/commit/02331040a127954eadaa859777379af77f419183 and https://github.com/aspnet/HttpSysServer/commit/936f82874ab1e706c39d5940c97752c01ef1cbef

Interestingly the code was 10% faster with the leak. There may be an opportunity to optimize this cleanup code.

![image](https://user-images.githubusercontent.com/1821173/32508507-6d9ed0b8-c39f-11e7-86ab-12f176ac40d5.png)

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
