### ISSUE TITLE
Write / WriteAsync with count = 0 can cause response body to be sent - problematic for 304 Not Modified responses

### ISSUE THREAD

**Issue by davidni** [aspnet/AspNetCore#5882]
**Context:** There is a bug in `MemoryStream.CopyToAsync` and that method will call `WriteAsync` on the destination stream even if there are no bytes to copy, in which case it passes `count = 0` (see [coreclr #15057](https://github.com/dotnet/coreclr/issues/15057)).

I came across this while building a reverse proxy on ASP.NET Core. When proxying HTTP Status Code 304 from an upstream service, the HTTP specs mandate that there must be no response body. Due to this bug, however, I end up with a chunked response of zero length on the wire (that is, the response body has exactly one chunk fragment, of size 0. This is in violation of the HTTP specs, and breaks the connection when the next request is made.

It seems to me that `0`-length writes should be considered no-ops. That way things would still be fine despite the problem with `MemoryStream.CopyToAsync`.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
