### ISSUE TITLE
Use BindingAddress instead of UrlPrefix

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#5883]
[HttpAbstractions has a new type](https://github.com/aspnet/HttpAbstractions/commit/150bb3faf413226d053777bbc72618fb284a6970) that will be consumed for using the IServerAddressFeature. This would replace the UrlPrefix type https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/UrlPrefix.cs.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
