### ISSUE TITLE
Support Memory<byte> and Span<byte> overloads on body streams

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#5886]
This requires a little bit of design so that we can take advantage of the fact that we are given a `Memory<byte>`

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
