### ISSUE TITLE
Investigate HTTP/2 behavior for RequestAborted and Abort

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5887]
For Http/1.x RequestAborted is used to detect early disconnects and Abort is used to force them.

For HTTP/2 requests can be multiplexed over a single connection and it's possible to terminate individual requests while leaving the connection active. Investigate how Http.Sys surfaces this behavior and if RequestAborted and Abort can be adapted accordingly. We may also need to introduce a lower level connection Abort API to kill the underlying connection (if Http.Sys allows that).

Mirror of https://github.com/aspnet/IISIntegration/issues/753

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
