### ISSUE TITLE
Support W3C format for distributed trace context propagation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [aspnet/AspNetCore#5925]
## Motivation

Support extraction and injection of distributed tracing context in a format of [W3C headers](https://github.com/w3c/distributed-tracing).

Support for new headers in ASP.NET depend on [support](https://github.com/dotnet/corefx/issues/30331) for `tracestate` collection in `Activity` class of `DiagnosticsSource`.

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

**Comment by muratg** [comment]
cc @shirhatti @davidfowl @Tratcher

**Comment by discostu105** [comment]
Please consider the case of "multiple" tracecontext users/providers in one process. This will be the use-case for the Dynatrace .NET Agent.

Challenge:
* Currently, the Dynatrace .NET Agent would auto-instrument itself into various methods (asp.net core middleware for incoming HTTP, HttpClient for outgoing HTTP). At these places, it would
   * read HTTP headers (`traceparent` & `tracestate`), keep it's state, propagate that state in-process. If no `traceparent` was present, it would create it's own `traceId`.
   * For an outgoing HTTP call, the Agent would add HTTP headers (traceparent & tracestate) itself. It would take care of properly changing tracestate (keep other entries, satisfy the spec).
* Now, if .NET Core / ASP.NET Core / DiagnosticSource would support TraceContext natively, a few things would change (IMHO, please correct if wrong):
   * DiagnosticSource would also read `traceparent` & `tracestate`. It would remember them (via DiagnosticSource Activity).
   * In case no `traceparent` was present, would it create it's own `traceId`?
   * In case of an outgoing HTTP call, DiagnosticSource would take care of placing `traceparent` and `tracestate` HTTP headers.

I see these problems:
* `traceId` generation. Both DiagnosticSource and Dynatrace Agent would create one.
* `traceparent` generation. Who will decide upon new SpanId, TraceOptions flags?
* `tracestate` handling. For this case, I guess the Dynatrace Agent just needs to become aware of DiagnosticSource and re-use it's TraceState collection, rather than writing the whole `tracestate` HTTP header itself. That's doable.

Add OpenCensus, OpenTracing into the mix. Who controls id's and who ultimately writes HTTP headers?

**Comment by anurse** [comment]
Epic https://github.com/aspnet/AspNetCore/issues/8924

**Comment by lmolkova** [comment]
Fixed with https://github.com/aspnet/AspNetCore/pull/8495, https://github.com/dotnet/corefx/pull/35882, https://github.com/dotnet/corefx/pull/33207

**Comment by anurse** [comment]
@SergeyKanzhelev as far as you know, is there further work needed in ASP.NET Core here? (Catching up on stuff, sorry if this has been discussed before :))

(cc @glennc)

**Comment by SergeyKanzhelev** [comment]
@anurse there are other issues for different aspects of distributed tracing. This issue is OK to close.

**Comment by anurse** [comment]
Thanks @SergeyKanzhelev !

**Comment by mmayr-at** [comment]
> Please consider the case of "multiple" tracecontext users/providers in one process. This will be the use-case for the Dynatrace .NET Agent.
> 
> Challenge:
> 
> * Currently, the Dynatrace .NET Agent would auto-instrument itself into various methods (asp.net core middleware for incoming HTTP, HttpClient for outgoing HTTP). At these places, it would
>   
>   * read HTTP headers (`traceparent` & `tracestate`), keep it's state, propagate that state in-process. If no `traceparent` was present, it would create it's own `traceId`.
>   * For an outgoing HTTP call, the Agent would add HTTP headers (traceparent & tracestate) itself. It would take care of properly changing tracestate (keep other entries, satisfy the spec).
> * Now, if .NET Core / ASP.NET Core / DiagnosticSource would support TraceContext natively, a few things would change (IMHO, please correct if wrong):
>   
>   * DiagnosticSource would also read `traceparent` & `tracestate`. It would remember them (via DiagnosticSource Activity).
>   * In case no `traceparent` was present, would it create it's own `traceId`?
>   * In case of an outgoing HTTP call, DiagnosticSource would take care of placing `traceparent` and `tracestate` HTTP headers.
> 
> I see these problems:
> 
> * `traceId` generation. Both DiagnosticSource and Dynatrace Agent would create one.
> * `traceparent` generation. Who will decide upon new SpanId, TraceOptions flags?
> * `tracestate` handling. For this case, I guess the Dynatrace Agent just needs to become aware of DiagnosticSource and re-use it's TraceState collection, rather than writing the whole `tracestate` HTTP header itself. That's doable.
> 
> Add OpenCensus, OpenTracing into the mix. Who controls id's and who ultimately writes HTTP headers?

@davidfowl Here the issue with the question from @discostu105  I was mentioning today during our conversation in the NDC workshop.
