### ISSUE TITLE
Rename JwtBearerOptionsConfiguration to (AzureAD|AzureADB2C)JwtBearerOptionsConfiguration

### ISSUE THREAD

**Issue by jmather** [aspnet/AspNetCore#6024]
Currently as it stands, these two helpers cannot be used together because (so far as I can figure) one will overwrite the other, since they both have the same logical namespace path: `Microsoft.AspNetCore.Authentication.JwtBearerOptionsConfiguration`

**Comment by Eilon** [comment]
It seems most likely that the real cause of this is what's described here: https://github.com/aspnet/AspNetCore/issues/6033

Though unfortunately the workaround described there might not work in your case, so you'll either need to come up with your own workaround, or wait for a fix. One ugly workaround is to copy out the built-in registration code and change the calls to TryAddSingleton to just AddSingleton and we think that will work.

As for the two type names colliding, that is an ugly internal detail, but shouldn't cause any technical problem because types of the same name in different assemblies are not considered the same. But, I logged https://github.com/aspnet/AspNetCore/issues/6580 to fix that too.
