### ISSUE TITLE
IHostedService in generic host can inject scoped dependencies, while IHostedService in webhost cannot

### ISSUE THREAD

**Issue by GoGus85** [aspnet/AspNetCore#6057]
### Describe the bug
IHostedServic implementation in generic host can inject scoped dependencies, while IHostedService in webhost crashes. 

### To Reproduce
.net core 2.2
Inject a scoped dependency in a ihostedservice implementation in a generic host, the service starts and the dependency is available for use. 
```
            var host = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services.Configure<HostOptions>(option =>
                    {
                        option.ShutdownTimeout = System.TimeSpan.FromSeconds(20);
                    });

                    services.AddScoped(typeof(ScopedDependency));
                    services.AddHostedService<Service>();
                })
                .Build();

            host.Run();
```
Inject a scoped dependency in a ihostedservice implementation in a webhost, the host crashes on startup.  
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddScoped(typeof(ScopedDependency));
            services.AddHostedService<Service>();
        }
```

### Expected behavior
I would expect the IHostedService under a webhost to function the same way as in a generic host.

**Comment by davidfowl** [comment]
A singleton can't depend on a scoped service, that leads to horrible leaks. The reason it "works" in the generic host case is because `WebHost.CreateDefaultBuilder` sets this up https://github.com/aspnet/AspNetCore/blob/85f1f3d893d3c2b776cd81504f1b07282a86c163/src/DefaultBuilder/src/WebHost.cs#L191-L194.

We've just added this similar functionality in 3.0:

https://github.com/aspnet/Extensions/blob/67d565dedbb9b8c1ef85391aaf92a3498d066293/src/Hosting/Hosting/src/Host.cs#L60-L63

So it'll fail just as magically in 3.0 in both cases.
