### ISSUE TITLE
Supporting different versions of Microsoft.AspNetCore.* packages in class libraries

### ISSUE THREAD

**Issue by cwoolum** [aspnet/AspNetCore#6087]
We are going through our internal libraries and we are having some conceptual questions about how our projects should be structured. Prior to 2.2, most of our libraries targeted `netstandard2.0` so they could be used flexibly across projects. We are now converting our libraries to support both 2.1 and 2.2 so that the apps built on them can be upgraded on their own schedule. The issue I am running into is that when a class library targets `netstandard2.0`, it's not possible to allow it to work with both 2.1 and 2.2 versions of `Microsoft.AspNetCore.*` packages because you cannot use msbuild conditionals to pull the correct package. One solution is to change the lib to use `<targetframeworks>netcoreapp2.1;netcoreapp2.2</targetframeworks>` but that means that consumers of these libs can not longer target `netstandard2.0`.

I have a couple questions. 

1. Why do Microsoft.AspNetCore libraries specify `netstandard2.0` as a dependency if they are actually bound to a specific `netcoreapp` version?

2. What is the recommended approach for supporting both AspNet Core 2.1 and 2.2 from `netstandard`?

**Comment by davidfowl** [comment]
> The issue I am running into is that when a class library targets netstandard2.0, it's not possible to allow it to work with both 2.1 and 2.2 versions of Microsoft.AspNetCore.* packages because you cannot use msbuild conditionals to pull the correct package. 

I'm not sure what you mean. What exactly are the differences between these packages? Are you taking advantage of new APIs? If yes, which ones. I'd like to understand a concrete example.

If you need new APIs then you need 2 different packages. MyPackage.AspNetCore21 and MyPackage.AspNetCore22. If you don't need new APIs then just target 2.1 packages and it'll work on both.

> Why do Microsoft.AspNetCore libraries specify netstandard2.0 as a dependency if they are actually bound to a specific netcoreapp version?

Because they aren't bound to netcoreapp until 3.0. They are netstandard and run on .NET Framework and .NET Core (and any other netstandard platform).

> What is the recommended approach for supporting both AspNet Core 2.1 and 2.2 from netstandard?

What i said, before, you need 2 different packages if you want to take advantage of new APIs added in 2.2 and have a 2.1 compatible package as well. The other option is to try to use nuget versions but that's much harder as you'll need a versioning scheme that maps to our scheme (for e.g. your 1.x maps to 2.1 and 2.x maps to >= 2.2, then you need to think about how you describe your own changes).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
