### ISSUE TITLE
Token replacement should not be hard coded

### ISSUE THREAD

**Issue by sadqiang** [aspnet/AspNetCore#6099]
IMHO, the hard coded string in 
`[Route("[controller]/[action]")]`
is not type safe or error prone.

```
[Route("[controller]/[action]")]
public class ProductsController : Controller
{
    [HttpGet] // Matches '/Products/List'
    public IActionResult List() {
        // ...
    }

    [HttpGet("{id}")] // Matches '/Products/Edit/{id}'
    public IActionResult Edit(int id) {
        // ...
    }
}
```

There should be any better way to avoid this.

**Comment by Eilon** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
Hi @sadqiang

.NET attributes allow a very small subset of primitive types as arguments. That limits the options for creating a strongly typed API at this point. If you don't like having that route pattern in every controller you have a couple of options:

* Use conventional routing instead of attribute routing. That centralizes routing rules. Example: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#setting-up-routing-middleware
* Have a const string and use it with RouteAttribute. That would reduce the chance of a typo in a controller file. Example: `[Route(Constants.ControllerBaseRoute)]`
