### ISSUE TITLE
Component compilation support needs to add diagnostics for markup errors

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6217]
The Blazor compiler adds diagnostics for things like missing end tags, and mismatched start/end tags. We don't have that support yet for the new component compiler.

This should probably done in the IR lowering phase.

Please find a few skipped tests in the aspnet/AspNetCore-Tooling repo that refer to this issue.

**Comment by DNF-SaS** [comment]
@rynowak General Question about the repo-merge of Blazor into the AspNetCore-Repo: how can one distinct issues related to blazor from all the other ones? (in this case, this one was only found because I knew that you're closely related to Blazor - looking at labels/projects/whatever, I don't see any blazor-specific classifier)
Sorry for being off-topic and thanks for your answer!

**Comment by rynowak** [comment]
Thanks for asking, I think we'll probably end up using a label like `area-Components` or `area-Blazor`. Right now it's still the holidays here so the dust hasn't quite settled yet 😆

**Comment by rynowak** [comment]
You can also look at https://github.com/orgs/aspnet/projects/19 where we're tracking the components productization work
