### ISSUE TITLE
[Suggestion] Accessibility for input fields required

### ISSUE THREAD

**Issue by JulioJu** [aspnet/AspNetCore#6329]
### Is your feature request related to a problem? Please describe.

Actually, when JavaScript is disabled in the Browser, or if the Browser doesn't support JavaScript, nothing says that an `<input>` field is "required" in client side.  Not cool for Accessibility in HTML5 : http://www.clarissapeterson.com/2012/11/html5-accessibility/

As the author of the link below said, simply generate an input like below could be cool:
```html
<input class="form-control" data-val="true" 
     data-val-required="The FavoriteColor field is required." 
     name="FavoriteColor" type="text" id="favoritecolor" 
     required aria-required="true" />
```

The author says that have the `aria-required` attribute could be cool for old screen readers, even if for modern screen readers it's redundant. 

See also https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#required

https://www.w3.org/TR/using-aria/#some-examples-of-redundant-aria

### Describe the solution you'd like
Change `RequiredAttributeAdapter.AddValidation` to also emit at least "required" html attribute in the input tag

Under:
https://github.com/aspnet/AspNetCore/blob/afb92018f07bf81c7be092ce93ae36cf1aca5365/src/Mvc/src/Microsoft.AspNetCore.Mvc.DataAnnotations/RequiredAttributeAdapter.cs#L34,L35

Maybe simply add:
```cs
MergeAttribute(context.Attributes, "required", "required"); // (at least)
// and maybe:
MergeAttribute(context.Attributes, "required-aria", "true");
```

**Comment by JulioJu** [comment]
The main author of this file is @pranavkm , what do you think about this :-) ?

**Comment by pranavkm** [comment]
cc @dougbu

**Comment by dougbu** [comment]
I see no obvious reason _not_ to add the `required` attribute. But, we should test a bit to understand how page behaviours change when JavaScript is enabled. Like our addition of the `max-length` attribute (not to long ago), this could be a breaking change -- hopefully a slight one.

The https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute and https://www.w3.org/TR/using-aria/#some-examples-of-redundant-aria pages disagree on the utility of `aria-required` together with `required`. I lean toward leaving the Aria attribute out because there aren't many interactive user agents i.e. browsers left that don't support HTML 5 and developers can include the redundant attribute if they wish.

**Comment by dougbu** [comment]
Just checked https://www.w3schools.com/tags/att_input_required.asp and https://www.w3schools.com/tags/att_textarea_required.asp. Since Opera doesn't support `required` on the `<textarea>` attribute, `aria-required` may be useful on that element.

In addition, https://www.deque.com/blog/aria-requiredtrue-wcag-2-compliance-practice/ describes a few cases where `aria-required='true'` may be disruptive e.g. when the word "required" (which might be spoken when using an assistive browser) is already associated with a field. I suspect the same applies to the `required` attribute if used primarily for accessibility. We probably need a way to disable emitting either attribute.

**Comment by JulioJu** [comment]
@dougbu I've tested a little.

I've found a first bug.

You could see it already thanks the official example RPmovieSearch. 

We see at https://github.com/aspnet/Docs/blob/83731be928167d2bdcaaa2aa795564e5968be636/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSearch/Models/Movie.cs#L13,L14
there isn't the `[Required]` decorator.

```cs
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
```

But we could see in the following code that it emits `data-val-required` 

```html
<input class="form-control" type="date" data-val="true" 
      data-val-required="The Release Date field is required." 
      id="Movie_ReleaseDate" name="Movie.ReleaseDate" 
     value="2019-01-15">
```

It's a big problem. This date input file should not be marked as required with the attribute `data-val-required=` !!! 

I've tried to search why there is this bug, without success. 

@dougbu what do you think about that ?

Thanks in advance !

**Comment by dougbu** [comment]
@JulioJu this behaviour is expected. The `DateTime` type is a `struct` and a `[Required]` attribute is therefore added automatically, specifically for client-side validation.

In any case, what problem does the `data-val-required` attribute cause?

**Comment by JulioJu** [comment]
@dougbu ok sorry. I'm a newbie. I must simply replace `DateTime` to `DateTime?`. Sorry for the newbies question.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by JulioJu** [comment]
@dougbu you seem interested to my suggestion, therefore maybe you could open this issue again :-) ?

**Comment by dougbu** [comment]
As I said
> `aria-required` **may** be useful on that element

I also mentioned potential problems including that attribute. Given that, I won't be reopening this issue.

----
> simply replace `DateTime` to `DateTime?`

If you do not want the value to be required in the form, yes.
