### ISSUE TITLE
Improve logging/error reporting for External Authentication

### ISSUE THREAD

**Issue by kanadaj** [aspnet/AspNetCore#6340]
As discussed in https://github.com/aspnet/AspNetCore/issues/6069, errors logged from External Login providers are vague and ambigious:
```
Correlation failed
```

```
The oauth state was missing or invalid.
```

Neither of those is really helpful to know what's actually sent or not sent to the server; and at which point is the handshake failing. Even with Sentry, which logs the data from the request with the error, at best I have an encrypted token that's completely meaningless to me. I imagine Fiddler is about the same.

It'd be nice to have a log trail for External Login that can be correlated with the error, and more info for the actual error as well.

**Comment by kanadaj** [comment]
@Tratcher

**Comment by Tratcher** [comment]
@kanadaj the challenge with these is that they're related to the absence of required data. There's little else in the current request that will be of use in diagnosing them. Here's how we usually debug them:

- Capture a Fiddler trace showing the entire login flow.
- Verify the fields and associated cookies were sent from server to client on initial challenge response. (not usually a problem).
- Check for cookie fields that commonly affect client behavior like SameSite. If these are wrong then the client is the one that excludes the required information from future requests.
- Verify that the return url is as expected. Incorrect proxy config can cause the wrong return url to be generated.
- Follow the flow to the remote auth server and back.
- Make sure all the expected fields and cookies are sent back to the application server. It's common for the cookies to be missing due to issues like the IOS11 client.
- Make sure the signin generates the expected app cookie, removes the temp cookies, and redirects back to the application endpoint.

The most critical logs in this flow would be the full response headers from the challenge response on the request before the error was reported. Especially the Location and Set-Cookie headers.

**Comment by blowdart** [comment]
Also the vagueness ensures we don't leak tokens, or sensitive responses.

**Comment by kanadaj** [comment]
@blowdart I don't believe you would leak anything not already in the Fiddler traces when debugging these issues, so I don't see that as a problem.

**Comment by kanadaj** [comment]
@Tratcher Fiddler traces only include information that the server receives as well, doesn't it? In that case, some things could be validated in the pipeline and logged appropriately, like SameSite; as well as exactly which cookie is missing if any.

**Comment by Eilon** [comment]
Let's add some logging for Location and Set-Cookie for OAuth and OIDC.

**Comment by Eilon** [comment]
LogLevel = Debug

**Comment by HaoK** [comment]
Adding additional optional logging to the existing challenge log message with the following format: 

`AuthenticationScheme: {AuthenticationScheme} was challenged. {ExtraData}`

Where ExtraData is empty by default but for OIDC/OAuth will add:
```
Location: [https://accounts.goo....] Set-Cookie: [.AspNetCore.Correlatio...expires=Tue, 08 Jan 2019 01:12:52 GMT; path=/signin-google; secure; httponly]
```
