### ISSUE TITLE
Clipboard copy through JS interop doesn't work.

### ISSUE THREAD

**Issue by RFDominguez** [aspnet/AspNetCore#6354]
### Describe the bug
I've been trying to copy text from an htmlElement (input) to the clipboard but this never works.
I get no errors or messages. Maybe this is not supported yet?

### To Reproduce
JS **********
window.copyToClipboard = (htmlElementId) => {
            var htmlElem = document.getElementById(htmlElementId);
            console.dir(htmlElem);
            htmlElem.select();
            document.execCommand("copy");
            return 'Ok';
        };

File.cshtml ***************
    async Task CopyToClipBoard(string hmlElementId)
    {     
        var jsResult = await JSRuntime.Current.InvokeAsync<string>("copyToClipboard", hmlElementId);             
    }

### Expected behavior
Value should be copied to clipboard

### Additional context
Blazor 0.7.0 - Server Side

**Comment by RFDominguez** [comment]
I guess the problem is caused by the fact that the "copy" command must be executed directly from a user action/event and the JS interop adds an extra layer making the call 'invalid?'
If I call the JS method directly the copy works as expected.

`<button class="btn btn-info d-inline" onclick="**copyToClipboard('awsCommand'**)">Copy to clipboard</button>`

**Comment by enetstudio** [comment]
@RFDominguez, perahps you need to call the focus() method before calling select(). See here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select#Notes

Also, did you try using elementRef instead of the element id ? This may make a difference... Who knows...

**Comment by enetstudio** [comment]
@RFDominguez, perahps you need to call the focus() method before calling select(). See here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select#Notes

Also, did you try using elementRef instead of the element id ? This may make a difference... Who knows...

**Comment by enetstudio** [comment]
@RFDominguez, perahps you need to call the focus() method before calling select(). See here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select#Notes

Also, did you try using elementRef instead of the element id ? This may make a difference... Who knows...

**Comment by SteveSandersonMS** [comment]
`Document.execCommand('copy')` is a difficult API to invoke because browsers only honor it when called synchronously in response to user action. This means it won't do anything when called via asynchronous JS interop.

The workaround, unfortunately, is to do what you've already done: trigger the call directly using a JavaScript event handler. I know this falls outside the desired Blazor programming model, but is a limitation faced by any server-side code. Client-side Blazor performing synchronous JS interop doesn't have any such limitation.

I hope that you're able to fit this into your preferred UI design. If you having trouble finding some way to trigger the call via a JS event handler, please describe your situation more and I'd be happy to help. The basic limitation is just that the action can't be initiated by server-side .NET code.
