### ISSUE TITLE
Razor Components support in VSCode

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6356]

**Comment by gulbanana** [comment]
i’ve written a blazor app in vscode on a mac and the experience wasn’t too bad - the biggest pain point is that without the tooling understanding how components cshtml should work it gets indentation wrong a lot

features like refactoring are missing, but this isn’t as big an issue in practice because you don’t typically refer to the component types defined by .cshtml from .cs files, or vice versa

**Comment by RemiBou** [comment]
for me the biggest problem was autocompletion au using directive generation in cshtml : the namespace on the last release (0.7) don't match the github repo so we have to go to a c#, type the class, let VSCode find the namespace and copy/paste it.

**Comment by danroth27** [comment]
The work here is done!

**Comment by RemiBou** [comment]
Thanks Dan, do you have any release date ?

**Comment by danroth27** [comment]
Hopefully some time next week.
