### ISSUE TITLE
Include the area in ControllerBase.IUrlHelper Action and RouteUrl methods

### ISSUE THREAD

**Issue by jimerino** [aspnet/AspNetCore#6426]
Hi!

I've found that you can't specify the area when you generate a Link inside a Controller with ControllerBase.IUrlHelper. The only way is "hacking" the host value in the Action method to include the area:

        // The route is POST: api/Identity/Register
        [AllowAnonymous]
        [HttpPost("Register")]
        public async Task<RegistrationRet> Register([FromBody] RegistrationParams registrationParams)
        {
            var linkToConfirm = Url.Action("ConfirmEmail", "Account", new { userId = "aaa", code = "code" }, Request.Scheme, Request.Host.Value + "/Identity");
            ...

This generate the full link:
http://somehost.com/Identity/Account/ConfirmEmail?userId=aaa&code=code

I think would be necessary include the area to generate links in a controller of another areas

Regards,
Jose I. Merino

**Comment by rynowak** [comment]
Hi @jimerino 

The way to specify an area is by passing it in the route values.

```
// The route is POST: api/Identity/Register
    [AllowAnonymous]
    [HttpPost("Register")]
    public async Task<RegistrationRet> Register([FromBody] RegistrationParams registrationParams)
    {
        var linkToConfirm = Url.Action("ConfirmEmail", "Account", new { area = "Identity", userId = "aaa", code = "code" });
    }
```
You can find documentation about this here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#areas

---

Since I think I answered the question I'm going to close this. If this isn't what you need please open a new issue and provide more information about what's not working.
