### ISSUE TITLE
Enforce English language for bug reports and feature requests in this repository

### ISSUE THREAD

**Issue by wanton7** [aspnet/AspNetCore#6438]
### Is your feature request related to a problem? Please describe.
There are now Chinese language bug reports/feature requests https://github.com/aspnet/AspNetCore/issues/6429 and https://github.com/aspnet/AspNetCore/issues/6428

### Describe the solution you'd like
Enforce that feature requests and bug reports needs to be written in English and if they are written in some other language they are deleted.

### Describe alternatives you've considered
Writing my future bug reports and feature requests in Finnish.

**Comment by 199621616** [comment]
Electron热了，Flutter来了。中文也来了。先生，你到需要学习中文的时候了。

**Comment by Eilon** [comment]
Hi @wanton7 , we try to encourage everyone to open issues in the best way they can, and if that happens to be in a language other than English, we will do our best. We have folks on the team who know a wide variety of languages so along with machine translation we hope we can address the largest number of issues. Of course, English is the team's most common language, so that makes things easiest, but that might not be true for the person logging the issue, and we wouldn't want to miss out on a quality bug report or feature request just because of a language barrier.

So, while I recommend that for anyone comfortable writing a bug report in English do it in English, because it'll get attention more quickly, I wouldn't want to block anyone from logging a good issue in any language.
