### ISSUE TITLE
Move WebHostFactoryResolver to aspnet/Extensions

### ISSUE THREAD

**Issue by bricelam** [aspnet/AspNetCore#6460]
EF Core depends on the `Internal.WebHostBuilderFactory.Sources` package. It needs to move to the [aspnet/Extensions](https://github.com/aspnet/Extensions) repo to avoid a circular dependency.

cc @ajcvickers

**Comment by natemcmaster** [comment]
Ah, the perennial EF <-> AspNetCore coupling issue arises again.

When @Tratcher and I talked about this sources package last year, our thinking was that moving this source code to Extensions would be a pain because it is used in AspNet Hosting. Also, it would be the only .Sources package produce from aspnet/Extensions which is not also used and tested in aspnet/Extensions, so it seemed strange to have it in a different repo.

That said, yes, technically this is a cyclical dependency. I don't think it's a particularly severe one because EFCore is no longer in the shared framework and could use a LKG version of this .Sources package.

Here are two other solutions to consider for solving this problem.
* We add an API in Microsoft.Extensions.Hosting
* EF Core copies this code into its repo. It's not much: https://github.com/aspnet/AspNetCore/tree/master/src/Shared/Hosting.WebHostBuilderFactory

**Comment by Tratcher** [comment]
Actually, the resolver was never coupled to AspNetCore.Hosting, it was coupled the arbitrary layout choices of Program.cs in the templates.

**Comment by bricelam** [comment]
This has all been working wonderfully throughout the 2.x release. Let's please not derail it in 3.x.

There are too many legitimate engineering issues with it being in AspNetCore to worry about the minor taste issues of it being in Extensions.

**Comment by bricelam** [comment]
+1 the choices were arbitrary, but this package is what turns that pattern into a contract for design-time tools like EF Core and ASP.NET Core test interception.

**Comment by Tratcher** [comment]
You can't run real tests from Extensions.

**Comment by bricelam** [comment]
That's fine. It has test coverage in both the EntityFrameworkCore and AspNetCore repos.

**Comment by bricelam** [comment]
Let's be pragmatic, not dogmatic.

**Comment by Tratcher** [comment]
Since I have to re-write this for the new Extensions.Hosing based templates, I can move it to Extensions and write tests there for the Extensions scenario. We can leave the old tests in AspNetCore to cover the legacy scenarios (or use 2.x dependencies?)
