### ISSUE TITLE
Blazor onscroll event isn't working.

### ISSUE THREAD

**Issue by arivera12** [aspnet/AspNetCore#6462]
I wrapped one page inside a div and placed the onscroll event on it and never gets fired.

**Comment by arivera12** [comment]
@mkArtakMSFT @SteveSandersonMS 
I digged a little deep into this and I can confirm that the scroll event is working but in the current blazor template is not working. The problem its that the body is scrolling instead of the page div. To make this working we need to fix the css on the template. Take a look of this https://stackoverflow.com/questions/9280258/prevent-body-scrolling-but-allow-overlay-scrolling

**Comment by arivera12** [comment]
There is something I haven't figure yet cause I am not a css expert but to make a content scrollable first of all it has to be scrollable itself like this` overflow-y: scroll; position:fixed; top: 0; right: 0; bottom: 0; left: 0;`. The body as to be non scrollable `overflow: hidden`. I placed this style on body and a div but layout gets all distorted :disappointed:

**Comment by mkArtakMSFT** [comment]
Thanks for your investigation, @arivera12.
@javiercn suggestions regarding how to fix the template?

**Comment by Andrzej-W** [comment]
I think it is not a bug and we don't have to fix anything here. It is "by design". SPA application doesn't necessary mean that it have to be full browser width/height application. In case of default Blazor template whole document is scrollable and that is correct. You can subscribe to window scroll events in JavaScript and then call C# from JS. You can also design full width/height layout and then subscribe to scroll events in C#. You can have more than one scrollable region and subscribe individually to all of them if necessary. You can also have scrollable whole page and scrollable regions on that page - this is design decision, not a bug.

@arivera12 I feel your pain. I'm a desktop developer and I'm learning CSS - it is not always easy. If you want to start from default Blazor template and use Bootstrap you have to master CSS Flexbox:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout
https://weblog.west-wind.com/posts/2017/Nov/11/Flexing-your-HTML-Layout-Muscles-with-Flexbox
Before you start messing up with `position` `overflow` etc. read this:
https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model
If this is new for you read this three times and try to understand every sentence. Otherwise you will fall into depression soon.

**Comment by arivera12** [comment]
@Andrzej-W I thougth for a moment I thought it was a bug but I reply then after that it was not a bug and was regarding on the design of the template and I also understand all those point and I thanks you for the clarifications about the scroll different types of cases. In my case I am still looking to listen to the onscroll event on the end of a list (li tag) or bottom of the page. But will dig a little more on this to fix this issue of scroll via css.
