### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered

### ISSUE THREAD

**Issue by RoboBurned** [aspnet/AspNetCore#6602]
### Describe the bug
Application cannot be started after following the steps from [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/ru-ru/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#call-configurekestrel-instead-of-usekestrel) article

### To Reproduce
1. Try to migrate ASP NET Core application from NET Core 2.1 to 2.2 by using the guide.
https://docs.microsoft.com/ru-ru/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio
2. Following the step https://docs.microsoft.com/ru-ru/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#call-configurekestrel-instead-of-usekestrel
Replace call to UseKestrel with call to ConfigureKestrel
NET Core 2.1
```
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
	.UseKestrel()
        .Build();

    host.Run();
}
```
NET Core 2.2
```
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .ConfigureKestrel((context, options) => { })
        .Build();

    host.Run();
}
```
3. Start the project
```
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
### Expected behavior
Application started

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by jkotalik** [comment]
Yeah the docs are a bit incorrect here. TL;DR You still need to call UseKestrel() before calling ConfigureKestrel() if you aren't use WebHost.CreateDefaultBuilder(). We recommend call ConfigureKestrel to configure Kestrel rather than UseKestrel(). UseKestrel adds the server which ConfigureKestrel() configures it.  

Let me explain the problem the docs are trying to highlight.

In 2.2, we added a new server type, IIS In-process. This will insert a server conditionally if it is loaded in the w3wp/iisexpress process. Calling UseKestrel() will always add a server, no matter the ordering. If customers are using  WebHost.CreateDefaultBuilder(), that will already call UseKestrel() by default. So when running IIS In-Process, if someone calls UseKestrel to configure kestrel, IIS-Inprocess will always fail to load. Therefore, in that scenario, we recommend calling ConfigureKestrel() because it will work with both IIS In-process and Kestrel.

@guardrex can you update that section to state to only call ConfigureKestrel if either they are using  WebHost.CreateDefaultBuilder() or if they already called UseKestrel()?
