### ISSUE TITLE
Add scaffolding for Vue.js SPA

### ISSUE THREAD

**Issue by livarcocc** [aspnet/AspNetCore#6762]
_From @snobu on January 16, 2019 11:40_

Please consider adding [Vue.js ](https://vuejs.org/) SPA scaffolding. Vue is popular enough to deserve its own scaffolding entry in the dotnet CLI. Right now only React and Angular SPAs are being generated.

```bash
$ dotnet new | grep SPA
ASP.NET Core with Angular                      angular            [C#]          Web/MVC/SPA
ASP.NET Core with React.js                     react              [C#]          Web/MVC/SPA
ASP.NET Core with React.js and Redux           reactredux         [C#]          Web/MVC/SPA
```

_Copied from original issue: dotnet/cli#10615_

**Comment by awulkan** [comment]
Not that stars on GitHub matter a lot, but Vue has surpassed both React and Angular now. And with the upcoming Vue 3 I think it will only keep on rising.

If I remember correctly they removed Vue due to lack of time for maintaining it. It would be awesome if it was available though since it would help a lot of people getting started! I hope it will at least be considered as a possibility.

**Comment by jmazouri** [comment]
Templates for Vue (as well as Aurelia and Knockout) previously existed as part of the `Microsoft.AspNetCore.SpaTemplates` package (which is still available on Nuget, though quite out of date). They were removed [back in February ](https://github.com/aspnet/Announcements/issues/289), with the stipulation that
>In the long term, if another JavaScript SPA framework becomes dominant, we will of course consider adding a template for it to the SDK templates package.

I hope the team reconsiders their position, at least for Vue, as it has grown in popularity considerably since the decision was made to remove it.

**Comment by snobu** [comment]
@sdras, can you maintain this if it gets greenlight?

**Comment by awulkan** [comment]
I think the are a lot of people that would help maintaining it. I could probably dedicate some of my time to it as well.

**Comment by alexeyzimarev** [comment]
We need #7046 to get through to have a proper Vue CLI support for development. The template itself will become rather trivial since the differences with the React template would be marginal.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, folks.
We have no plans to add `Vue.js` template. But, we're interested enabling the `Vue.js` community to build and maintain a template as a package so that other members can use that for creating new `Vue.js` apps hosted on ASP.NET Core.
As part of this effort we're working on making an experience for using templates acquired from NuGet in VS better. Also, we're considering looking at making some improvements in the `SPA services` area to enable better integration with any JS based frameworks - including Vue.js.
