### ISSUE TITLE
Multiple @inherits not working with Blazor

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore#6800]
I’m attempting to re-jig some layouts and following our ethos of splitting out the functions into components (and in this instance it makes good sense because I want to use one of the functions in more than 1 cshtml page).

The issue is you can only have 1 @Inherits on a cshtml page, which seems like a big draw back to me.

On our main Layout page we:

@inherits BlazorLayoutComponent. 

This is required because in here is where the @Body is defined.

I want to have this page use some of our functions, but I cannot add:

@inherits MyMenuFunctions for example because I already have one. So the issue is we need to be able to do multiple inheritance.

**Comment by RemiBou** [comment]
Multiple inheritance does not exists in C#, and Blazor template generates c# class, so it's not possible.

- You can make you MyMenuFunction inherit from BlazorLayoutComponent
- Inject your MyMenuFunction if you are not using any lifecyle method 

If you post a repo containing your code maybe I can help a bit further

**Comment by Matthew-Bonner** [comment]
I've asked my colleague to post the code he is having a problem with and he will be in touch on here to discuss the problem he is having. Thanks.

**Comment by bilpor** [comment]
This is what I was trying to do:

```
@inherits BlazorLayoutComponent
@inherits Evaluate.Pharma.Blazor.Web.Functions.MenuFunctions

<div class="sidebar">
    <NavMenu />
</div>
<div class="main">
    <div class="pl-4  navbar navbar-dark">
        <button class="navbar-toggler navbar-brand collapse main-button" title="MENU" onclick=@ToggleNavMenu>
            MENU
        </button>
    </div>
    <div class="top-row px-4">
        <a href="http://blazor.net" target="_blank" class="ml-md-auto">About</a>
        <NavLink class="nav-link pull-right" href="logout">
            <span class="oi oi-account-logout" aria-hidden="true"></span> Logout
        </NavLink>
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>

Instead I had to move :
`<div class="pl-4  navbar navbar-dark">
        <button class="navbar-toggler navbar-brand collapse main-button" title="MENU" onclick=@ToggleNavMenu>
            MENU
        </button>
    </div>`

into it's own component along with the second inherits. then place the component in it's place. Although this works, there are times when I would rather be able to just inherit as per my original code.

```

**Comment by bilpor** [comment]
I have also Tried using an interface against the function

 `public class MenuFunctions : BlazorComponet, IMenuFunctions`

 and instead of using @inherits using @inject on the cshtml pages. This results in the pages not loading. If I remove the interface declaration on the method leave the @inject declaration on the page and then in startup add the following:

 `services.AddSingleton<MenuFunctions>();` 

The page loads, but again original functionality. If I add the interface back on the class declaration and change the above line to be:

`services.AddSingleton<IMenuFunctions,MenuFunctions();`

again the page doesn't load.

**Comment by bilpor** [comment]
Here is the full code so far:

```
public class MenuFunctions : BlazorComponent //, IMenuFunctions
 {
  public bool CollapseNavMenu
    {
        get ; set;

    }

    public void ToggleNavMenu()
    {
        CollapseNavMenu = !CollapseNavMenu;
    }
}

```
**The main button on NavMenuToggleComponent.cshtml:**
```
@inject MenuFunctions mf

<div class="pl-4  navbar navbar-dark">
   <button class="navbar-toggler navbar-brand main-button" title="MENU" onclick=@mf.ToggleNavMenu>
    MENU
   </button>
</div>

```

my **NavMenu.cshtml** file:
```
@inject MenuFunctions mf


<div class="@(mf.CollapseNavMenu ? "collapse" : null)" onclick=@mf.ToggleNavMenu>
<ul class="nav flex-column">
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="home">
            <span class="oi oi-home" aria-hidden="true"></span> Home
        </NavLink>
    </li>
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="frontpage">
            <span class="oi oi-home" aria-hidden="true"></span> Front Page
        </NavLink>
    </li>
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="counter">
            <span class="oi oi-plus" aria-hidden="true"></span> Counter
        </NavLink>
    </li>
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="" Match=NavLinkMatch.All>
            <span class="oi oi-account-login" aria-hidden="true"></span> Login
        </NavLink>
    </li>
</ul>
</div>

```
putting it all together in my **MainLayout.cshtml**
```
@inherits BlazorLayoutComponent

<NavMenuToggleComponent></NavMenuToggleComponent>
<div class="sidebar">
   <NavMenu />
</div>

<div class="main">

<div class="top-row px-4">
    <a href="http://blazor.net" target="_blank" class="ml-md-auto">About</a>
    <NavLink class="nav-link pull-right" href="logout">
        <span class="oi oi-account-logout" aria-hidden="true"></span> Logout
    </NavLink>
</div>

<div class="content px-4">
    @Body
</div>
</div>

```
so when I click the button in NavMenuToggleComponent.cshtml I want the CollapseNavMenu to react in the NavMenu.cshtml file.

**Comment by Matthew-Bonner** [comment]
I think the main problem here is that the state is not being updated across the components, so if I've correctly understood the problem, @bilpor could you take a look at https://github.com/aspnet/AspNetCore/issues/5467 and see if the information contained in that issue allows us to progress?

**Comment by bilpor** [comment]
Hi Matt,

 

Looking at this link, the closest we have with this is the ChangeDetectionBLazorWebApplication example all the others are using React, redux etc.

 

This example falls down for us because we are extracting the functions from the page and placing them in our own components. The Index.cshtml page in the pages folder of the example implements the changedetection, but because we cannot use implements here only inherits or inject it would fail for us I think. 

 

I’ll Try and take a more indepth look at this solution when I’m back on the blazor project to see if I might be able to re-jig parts to try and make it work into our solution. I’ve implemented similar but on a single page already (the login page for the messages informing the user that email and password must be entered – the red writing below the input boxes). 

 

It would be much nicer if the Team could come up with a solution such as the suggestion in this post where we simply have an [Observable] decorator available to us.

 

Thanks

Will

**Comment by bilpor** [comment]
When I receive the 'blank' page there is no HTML in the page.

**Comment by rynowak** [comment]
Hi, as you know C# does not support mutliple class inheritance. You can implement an interface with the `@implements` directive. If you need something else please open an issue and provide a clear repro
