### ISSUE TITLE
Unclear source of truth / rules for ClaimsIssuer

### ISSUE THREAD

**Issue by syndicatedshannon** [aspnet/AspNetCore#6813]
ISSUE: I believe it is currently very difficult to understand the source of ClaimsIssuer in most RemoteAuthentication scenarios. Further, I believe that has significant security consequences, and deserves clarification, despite the lack of a quick fix or even a clear symptom.

I apologize for this non-standard and non-trivial defect presentation. I've been digging through Identity source code for many weeks now and feel it's an important issue. I will do my best to make my issue clear and concise, though it is not so in my head.

I see many places where ClaimsIssuer can be set, but it is not documented what the outcome is if multiple are set. Possible sources include:

- AuthenticationHandler.ClaimsIssuer (it has no mandatory effect in derived classes, but does in OAuthHandler and descendants. it is coalesced from the following)
   - AuthenticationScheme.Name (which itself has multiple sources)
   - AuthenticationSchemeOptions.ClaimsIssuer
- OAuthCreatingTicketContext.RunClaimActions (via a duplicate coalesce to that performed above)
- ClaimsIdentity.DefaultIssuer (via TicketSerializer ReadWithDefault/WriteWithDefault logic that allows Issuer to automatically change between cluster hosts, which I don't understand and doesn't seem safe)
- Claim CTORs without Issuer parameters and all consumers (such as SignInManager, although I'm unclear how this value matches ClaimsIdentity.DefaultIssuer; there must be a duplicate const in there)
- ClaimAction.Run (and derivatives, however note that DeleteClaimAction does not respect this)

I feel like I've missed a couple constructors as well. Other OEM change points may exist, such as serialization and deserialization of claims, claims factory/transformer injected by default, etc. I couldn't find such, but the lack of clearly-stated pattern leads to my suspicion/confusion about this.

I think the most important near-term fix to this is a formal statement of the intended functionality (e.g. documentation). I think reducing the number of points of truth would also be helpful, given that ASP.NET Core consumers today are somewhat obligated to refer to source for functional comprehension.

**Comment by syndicatedshannon** [comment]
I'd like to explain a little why I think this is important.
 - ASP.NET Core Identity is designed to be highly extensible, and even simple examples include extending authentication schemes in ASP.NET Core. It concerns me when I need / my team needs to write security code against APIs I don't / my team doesn't understand.
 - I use extension libraries that plug into these extension points. It concerns using third party security libraries that depend on confusing implementations
 - I worry about the compatibility of various efforts; what if one library serializes a NameIdentifier with a DefaultIssuer and another library deserializes it?
 - The Claim class documentation for this includes dead links, and the referenced IssuerNameRegistry isn't used by any of the code I reviewed above. What ensures Issuer is unique across extension libraries?

I'm especially sensitive to this because I've frequently seen confusion over the definition of Claims.Issuer. It would be easy for a developer to perceive that a claim was issued by the host that composed the "Claim object", rather than the host that made the "security claim".

**Comment by blowdart** [comment]
Some thoughts;

asp.net identity and oauth/external authentication and the Claims class are all separate things, so yes, there are going to be multiple entry points to setting a claims issuer. However none of the code that ships as part of ASP.NET relies on issuer in any way, so it's truthiness isn't a concern _by default_.

For the authentication providers that are shipped with ASP.NET there the ClaimsIssuer property in the AuthenticationSchemeOptions would be the place to _override_ the defaults.

When identity comes into the mix at the end of the day, if you are persisting claims from a third party the issuer doesn't matter, because once you've put them into the identity database the issuer is asp.net core identity, it's not the original source.

The intended functionality here, well, it depends on _you_. The claims class comes from Windows Identity which was part of WSFed support bolted on back in the .NET days. It's been merged, but things that might be considered vestigial still exist. For the majority of users it probably doesn't mean a lot. If you have multiple identities on a single principal in a single request then it can be used to figure out which identity came from which auth handler.

As for third party code, well, unfortunately that due diligence falls on the user.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
