### ISSUE TITLE
TestHost with HTTP2 features

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#6880]
Related: https://github.com/aspnet/AspNetCore/issues/6871

Attempting to use HTTP2 features in the test website with TestHost...

```cs
httpContext.Response.AppendTrailer("grpc-status", ((int)StatusCode.OK).ToString());
```

...results in an error: `Message: System.InvalidOperationException : Trailers are not supported for this response.`

This is the first error I encountered when using HTTP2 - I'm going to see if I can work around it in the test website - but I suspect there is other issues to fix to HTTP2-erize TestHost.

// @davidfowl @Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http.Abstractions/src/Extensions/ResponseTrailerExtensions.cs#L44-L47

This is a more interesting problem for TestServer than it was for just DefaultHttpContext. What client API are you using to send requests? HttpClient I assume. That doesn't have an object model to represent trailers yet. You'd have to use the TestServer API that lets you directly interact with the HttpContext in order to see any response trailers.

As to how TestServer should decide if it's in HTTP/2 mode or supports trailers (e.g. adds the feature) is another question. It could key it based on the protocol version on the request (which HttpClient now defaults to HTTP/2).

**Comment by anurse** [comment]
Assuming we don't try to add support for HttpClient, is the work item here just to initialize the trailers feature so that the client can access that? Seems straightforward. There will likely be a reaction needed when (if?) HttpClient adds trailer support.

**Comment by JamesNK** [comment]
HttpClient has already added trailer support for 3.0. It is in the latest SDK.

**Comment by JamesNK** [comment]
https://github.com/dotnet/corefx/pull/36128 and https://github.com/dotnet/corefx/pull/36128
