### ISSUE TITLE
Update Index.html in Razor Component template to be a Razor Page (Index.cshtml)

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6885]

**Comment by SteveSandersonMS** [comment]
This is not just a template change - it can only be done once we have a replacement for the SPA fallback routing that currently serves `index.html`. We *could* configure the `Index.cshtml` to match all URLs, but that isn't an exact equivalent to the existing behavior, since it will not exclude requests that look like requests for static files, which we do today.

@javiercn is working on the updated startup code and prerequisite middleware. Javier, how much of this are you expecting to include in Preview 3? Will we have the necessary bits to let us use `Index.cshtml` as a fallback route?

@javiercn If you are working on the necessary middleware, would it be reasonable for you also to update the template to use it (and change `index.html` to `Index.cshtml`) once that is done? As in, can I assign this to you?

If the prerequisite middleware isn't going to land for preview 3, we should move this issue and #6886 out to preview 4.

**Comment by rynowak** [comment]
> since it will not exclude requests that look like requests for static files, which we do today.

Is this really needed? We always put static files ahead of MVC in templates - it's exceedingly common for users to write their own *catch-all* routes.

**Comment by SteveSandersonMS** [comment]
Unfortunately it's more complicated than that:

 * If we put the catch-all `Index.cshtml` before `UseRazorComponents`, then we can no longer serve `components.server.js`, because it returns the `Index.cshtml` contents instead
 * If we put them the other way around, then the SPA fallback routing inside `UseRazorComponents` throws because it can't find an `index.html` to route to.

We need a proper replacement to the SPA fallback routing logic, unless I'm missing some trick.

**Comment by javiercn** [comment]
@rynowak can we plug-in transparently through services something that serves component.server.js without us having to make a gesture also on app.UseRouting?

My idea is that AddComponents can add an endpoint data source that uses the static files middleware to serve the components.server.js. That way it plays into routing and has higher precedence than the catch-all for Index.cshtml.

> it's exceedingly common for users to write their own _catch-all_ routes.

This is another reason why I want to integrate the client routes into the router. So that the main component only serves the client paths.

**Comment by rynowak** [comment]
I would prefer if we teach static files how to know about other file providers, and plug into that. 

I don't want anything showing up in routing without a gesture if we can avoid it. So far we have been able to avoid it. 


I think overall you're on the right track, using middleware to solve this problem has worked so far, but it's really inflexible.

**Comment by SteveSandersonMS** [comment]
On the subject of catch-all routes:

Whatever approach we use for the Razor Components template, we will still want a better version of SPA fallback routing that can deal with falling back to a Razor page, instead of being hardcoded to look for `index.html`. In the "Blazor Hosted" scenario, you may want `Index.cshtml` instead of `index.html`, but you don't necessarily want prerendering or even to load the client app assemblies inside the server app.

**Comment by SteveSandersonMS** [comment]
Ping again on these questions, since it determines what gets included or pushed out from preview 3:

@javiercn is working on the updated startup code and prerequisite middleware. Javier, how much of this are you expecting to include in Preview 3? Will we have the necessary bits to let us use `Index.cshtml` as a fallback route?

@javiercn If you are working on the necessary middleware, would it be reasonable for you also to update the template to use it (and change `index.html` to `Index.cshtml`) once that is done? As in, can I assign this to you?

**Comment by javiercn** [comment]
This was done as part of the prerrendering startup experience
