### ISSUE TITLE
In the Razor Components project template consider bringing scripts & styles in using the environment specific helpers

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6886]

**Comment by SteveSandersonMS** [comment]
Considered.

Result of consideration: I don't think there's any compelling benefit. We don't have a built-in system for building static resources, and without one, there's no sense in which your production resources are different from your development-time ones. Developers who set up a static resources build system will have all kinds of different requirements for how the right ones get loaded at runtime. Typically it's solved via the static resources build system, not by environment-specific helpers.

@danroth27 I propose closing this.

**Comment by SteveSandersonMS** [comment]
I would use the minified version of Bootstrap libs in development too. No good reason not to, that I'm aware of.

**Comment by SteveSandersonMS** [comment]
I suppose the "get it from CDN" aspect is something you'd only want in production. However it's *not* something you'd want if you set up a static resources build system, since you'd have your own tree-shaken version of Bootstrap.

Overall I guess whatever design we're using for Bootstrap in the non-Razor Components templates should also be used in the Razor Components template, even if it's not to my taste personally.

**Comment by Andrzej-W** [comment]
I think that environment specific helpers are useful for JS and CSS files. In production I want to get files from CDN but during development I want to have them on my local disk in not minified state. There are at least two reasons for this configuration:
- during development I often want to clear browser's cache and I don't want to download all CSS/JS files from CDN again and again
- I can press F12 and goto CSS class definition - I don't want to build Bootstrap myself but sometimes I want to check something in source code

Currently F12 doesn't work, but hopefully the bug is already fixed:
https://developercommunity.visualstudio.com/content/problem/314314/html-tools-peek-go-to-definition-for-class-names-f.html

**Comment by SteveSandersonMS** [comment]
Blocked waiting for #6885

**Comment by javiercn** [comment]
This is unblocked now

**Comment by SteveSandersonMS** [comment]
Done in #7859
