### ISSUE TITLE
How to setup a fallback resource file for Views

### ISSUE THREAD

**Issue by pratishthap** [aspnet/AspNetCore#6909]
I have a requirement where i need to use shared resource file as a fallback if the key does not exist in the local resx file. How do i configure it in the startup so that i can use local file and the shared file as a fallback for Localization

**Comment by pranavkm** [comment]
cc @ryanbrandenburg

**Comment by hishamco** [comment]
AFAIK the culture fallback to its parent and if the key isn't exist the requested key will be returned, so according to my knowledge there's no way to fallback as you mentioned above

**Comment by ryanbrandenburg** [comment]
Like @hishamco said, what you're requesting is not something that can be done strictly within the confines of our Localization system. My suggestions are as follows:

- Use the built in fallback instead. When a resource isn't found for the current culture we look for it in the parent culture (like @hishamco said). If that isn't found we keep walking up the parent chain. If NO resx contains the resource the KEY is returned. So if you tried to do:
```
var name = localizer["This is a key!"]
```
and there were no applicable resx with that key, "name" would be assigned `This is a key!`

- Reconsider your requirement. What is the scenario under which it makes sense to have a shared resource which contains keys and values for all resources, given that there's the key fallback above and the parent chain?
- As a last resort, write your own IStringLocalizer. If you've thought about the above two and they still won't solve your problems you'll have to write your own IStringLocalizer and use it instead of the default one. Be careful if doing this, there are a lot of pitfalls. Consult [our implementation](https://github.com/aspnet/Extensions/blob/master/src/Localization/Localization/src/ResourceManagerStringLocalizer.cs).

Let us know either way if that solves your problem.

**Comment by hishamco** [comment]
@ryanbrandenburg I think this is answer and need to close
