### ISSUE TITLE
Blazor Get binary data from js?

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/AspNetCore#6912]
Js interop function can receive byte[] from dotnet as parameter.
Vice versa is not working, I can't call dotnet function passing arraybuffer (Uint8Array) as parameter and receive byte[] in dotnet, giving error.

I am forced to do extra job, in js convert received binary to base64string and pass to dotnet function, then convert back it to byte array.

Is it possible to get binary data from js?

**Comment by Lupusa87** [comment]
I figured this out [here](https://github.com/Lupusa87/BlazorWebSocketHelper/blob/master/content/BwsJsInterop.js) after advise from gitter to follow links below but it was hard and suffering.

Can we make this simpler somehow?

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Blazor/src/Http/WebAssemblyHttpMessageHandler.cs

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Browser.JS/src/Services/Http.ts
     
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Browser.JS/src/Platform/Mono/MonoPlatform.ts

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS any recommendations here? Thanks

**Comment by SteveSandersonMS** [comment]
From the links you posted, it looks like you've figured out how to use the unmarshalled interop APIs to transfer the binary data directly.

We don't expect to add support for binary serialization into the marshalled interop APIs, because they use JSON as a transfer format (because developers understand well what that means for .NET/JS conversions), and JSON itself doesn't have a binary blob primitive.

If we get more requests to simplify this in the unmarshalled case we could consider it, but for now this looks like a pretty rare requirement so it's not likely we'd want to build in a feature for it. Anybody could create a simplified API for this and ship it in a NuGet package, so that would be the best way forwards for now.

**Comment by Mercurial** [comment]
im using blazor jsinterop to pass ArrayUint8 to byte[] but it gives me json error :(

**Comment by mkArtakMSFT** [comment]
Hi.

**It looks like you are posting on a closed issue!**
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

**Comment by Mercurial** [comment]
> Hi.
> 
> **It looks like you are posting on a closed issue!**
> We're very likely to lose track of your bug/feedback/question unless you:
> 
> 1. Open a new issue
> 2. Explain very clearly what you need help with
> 3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

thanks!

**Comment by dradovic** [comment]
One easy workaround when dealing with [Blobs](https://developer.mozilla.org/en-US/docs/Web/API/Blob) is to [create a URL in the browser](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) for the Blob and then in Blazor use the standard `HttpClient` to get the binary by data calling `GetByteArrayAsync` on the created blob URL (as suggested on [SO](https://stackoverflow.com/a/52410044/331281).
