### ISSUE TITLE
SpaServices can't host multiple apps

### ISSUE THREAD

**Issue by joshfriend** [aspnet/AspNetCore#6988]
### Is your feature request related to a problem? Please describe.
I am trying to localize an Angular app served by ASP.NET but SpaServices is not capable of hosting more than one SPA at a time.

### Describe the solution you'd like
* Enable SpaServices to serve any number of js packages from a given base path. For example, serve the compiled english app from `/en` and the compiled spanish app from `/es`. This would be useful for other cases besides just localization
* Even better, automatically serve the app package that best matches the user agent's `Accept-Language` header so the language does not have to be embedded in the url.
* If this is something that is already supported, more docs about how to configure it would be appreciated.

### Describe alternatives you've considered
I managed to put together a working implementation using some classes i found on an archived issue here: https://github.com/aspnet/JavaScriptServices/issues/1491

However, I was never able to get that solution working with `ng serve` so my `Startup.cs` contains a check for if the server is running in dev mode which falls back to using `app.UseSpa` and `spa.UseAngularCliServer` for a single language.

### Additional context
I read a _lot_ of docs and the internal code for SpaServices and only found [this one place where it is implied that serving multiple SPAs is already possible](https://github.com/aspnet/AspNetCore/blob/7269dbb73f4aa0ebf5ebb8bc07a076ee181851be/src/Middleware/SpaServices.Extensions/src/StaticFiles/SpaStaticFilesExtensions.cs#L91). I found a potential solution [on stackoverflow](https://stackoverflow.com/a/48465664/1255482) but it used serverside rendering, which I did not want.

**Comment by federicobarera** [comment]
Hi josh,

I had to look into it recently as well, but for what concerns react.

The implementation provided [here](https://github.com/nickwesselman/SpaServicesMultiSpa) actually works for embedding any SPA under a route, there are few tweaks that need to be applied in the react/angular land of course.

Namely, somehow the react app created by `create-react-app` , lost the option to embed from relative paths in development, which apparently they working on re-activating now: (https://github.com/facebook/create-react-app/pull/1887)

I got to a workable state, but unfortunately I had few problems with hot reloading not working when the app is proxied by dotnet.
It seems to me thought that is a problem in the webpack devserver area rather than here.

**Comment by joshfriend** [comment]
Ha, I actually did end up adapting @nickwesselman's solution for my app.

Still has a few shortcomings though, namely:
* each app has to live at a separate url path
* No automatic redirection from `/` to the appropriate app based on `Accept-Language`

But I don't think it was actually designed for localization purposes...

**Comment by federicobarera** [comment]
Regarding the `/` redirection that seems app logic, you could simply put a redirect middleware in the pipeline

```
app.Run(async context => {
  ...
  context.Response.Redirect("/en");
});
```

**Comment by joshfriend** [comment]
That's actually exactly what I did 😆

**Comment by mkArtakMSFT** [comment]
Thanks for helping out each other, folks.

**Comment by joshfriend** [comment]
Please reopen, I do not consider the solutions posted here an acceptable workaround long term. There are still limitations which I [mentioned here](https://github.com/aspnet/AspNetCore/issues/6988#issuecomment-476009155)
