### ISSUE TITLE
[FromRoute] binding fails in 2.2 (but not 2.1) when parameter name and property name are the same. Additionally, [ApiController] attributes hides MVC1004 warning. 

### ISSUE THREAD

**Issue by captain-keystone** [aspnet/AspNetCore#7038]
### Describe the bug
Based on aspnet/Mvc#7753 it appears that this type of binding working in 2.1 may have not been intended (as it looks like it would not have worked with other types of complex binding), but 'correcting' it is a very insidious breaking change-  particularly given that the analyzer warning appears to be suppressed when the controller is decorated with the `[ApiController]` attribute.

I don't believe this is directly related to #6945, but wanted to reference it here as it deals with another issue with the same analyzer warning (`MVC1004`).
```cs

[ApiController]
public class ApiController : ControllerBase
{
    //No bind when using 2.2
    [HttpGet("/api/nobind/{value}/{subValue}")]
    public IActionResult NoBind([FromRoute] RouteModel value)
    {
        return Ok(value);
    }
    [HttpGet("/api/bind/{value}/{subValue}")]
    public IActionResult Index([FromRoute] RouteModel value1)
    {
        return Ok(value1);
    }

}
public class RouteModel
{
    public string Value { get; set; }
    public string SubValue { get; set; }
}

```

Can anyone confirm that his behavior was either not intended to be supported in 2.1 or that is was intentionally changed for 2.2? 

From the discussion in aspnet/Mvc#8231 it appears there is a good deal of complexity associated with making this work when the attribute is used, but this seems like a pretty nasty breaking change that could be quite difficult to track down(trust me!) without the analyzer warning.

**Comment by pranavkm** [comment]
@captain-keystone the model binding behavior hasn't changed for a fair bit of time. For instance, https://github.com/aspnet/Mvc/issues/3735 goes all the way back to 1.0. Can you confirm your no bind scenario worked in 2.1?

The analyzer attempts to do provide best effort guidance for when users could encounter this issue. Typically this is occurs when binding complex types. For `ApiControllers`, complex types bind from the body by default which is why we chose not to run it there. Additionally the analyzer no-ops if you have any model binding related attribute. It's a bit difficult to tell how a model binding attribute is configured or what it may by simply inspecting it at build time.

**Comment by mkArtakMSFT** [comment]
Closing this as answered. In the meantime we'll make sure the analyzer will have a note about this behavior.
