### ISSUE TITLE
StreamPipeWriter.Complete should throw if there's unflushed data

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#7102]
StreamPipeWriter wraps a stream and pretends to be a pipe, but it buffers everything in memory. On a normal Pipe if you call Complete then the data would be available to the consumer, but for StreamPipeWriter the data is all still sitting in the buffers. 

Throw an InvalidOperationException if FlushAsync is not called to flush the buffered data before Complete is called.

@jkotalik

**Comment by davidfowl** [comment]
@jkotalik @Tratcher just tried this change out and it throws in a way that makes it really hard to debug what went wrong. The developer exception page can't handle the error since it's thrown deep in the server.  We need to re-think where we throw here and we need to decide if we can make it better.

```C#
app.UseRouting(routes =>
{
	routes.MapGet("/", context =>
	{
		context.Response.BodyPipe.Write(Encoding.UTF8.GetBytes("Hello World"));
		return Task.CompletedTask;
	});
});
```


Here's what it looks like on IIS in-proc:

![image](https://user-images.githubusercontent.com/95136/52041426-441c4d80-24ef-11e9-8bcd-915d28225699.png)

And in Kestrel, the screen is white and the logs show the exception.

![image](https://user-images.githubusercontent.com/95136/52041506-7928a000-24ef-11e9-88cf-cea7dd5988e7.png)

**Comment by Tratcher** [comment]
Actual problem: Why does Dispose call Complete? That's way too late.

**Comment by Tratcher** [comment]
That said, it's the only way you're going to discover this error.

Note that the error you showed is actually better than most response body related exceptions. In most cases once you've started the headers any exception will cause the client to see a truncated 200 response. The developer exception page never works for response body related exceptions.

**Comment by jkotalik** [comment]
Who is responsible for calling Complete on the StreamPipeWriter? Is Complete required to be called before Dispose?
