### ISSUE TITLE
Component libraries are broken in 3.0.0 Preview 2

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#7127]
### Describe the bug
Component Libraries cannot be used with 3.0.0 p-2 Razor Components

### To Reproduce
1. Install the SDK 3.0.0 Preview 2
2. Install VS 2019 Preview 2
3. Run the commands
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates`
`dotnet new blazorlib`
4. Reference the Blazor Lib from the `.App` project
5. Add a taghelper in `_viewimports` (on the root level, not in the `pages` folder. 
 `@addTagHelper *, LibName`
6. Try to use the component from the library in the `counter.cshtml` component (which doesn't work)

### Expected behavior
Just as in 2.1, make sure the components can be used coming from another lib.

**Comment by danroth27** [comment]
Thanks for reporting this issue!

There is a known problem with Razor Components apps that they don't yet support picking up static assets from class libraries like they do in Blazor. This is because we wanted to first do a design review of the current approach before we brought it into .NET Core. The issue tracking this problem is here: #https://github.com/aspnet/AspNetCore/issues/6349.

Components in class libraries do actually get picked up, but not their associated static assets. As you can see below, Component1 does get rendered, but it's CSS and background image are missing:

![image](https://user-images.githubusercontent.com/1874516/51984576-a182b100-2493-11e9-9271-3d7dd0bac837.png)

Since we are tracking this issue elsewhere, I'm going to close this one as a dup. I hope that's ok!

**Comment by vertonghenb** [comment]
Mmm the issue was that I was using the wrong version of Blazor, since the update notes said:
Run `dotnet new -i Microsoft.AspNetCore.Blazor.Templates`
and it should have been:
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19075-0444`

**Comment by legistek** [comment]
I'm running into this as a problem now. So is there no way to have global styles or other resources in a component library at present?

**Comment by danroth27** [comment]
@legistek You can continue to use the existing Blazor mechanism with Blazor apps, but we haven't enabled the same mechanism in Razor Component apps yet.

**Comment by SQL-MisterMagoo** [comment]
@vertonghenb , @legistek 
Until the Microsoft team get this working, I have written a project that brings this functionality back for Razor Components [BlazorEmbedLibrary](https://www.nuget.org/packages/BlazorEmbedLibrary/)
If you add this to your App, it will embed the static CSS and JS files at runtime into the head of your app using browser blob storage. 
You might find it useful as a workaround.
