### ISSUE TITLE
Blazor using old SignalR verion

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#7156]
Please update the Blazor SignalR reference to with the SignalR v1.1.0 at present Blazor server side is using older version which is preventing developer having background HostStartup use new SignalR to connection hubs etc that perform updates of the UI in bacground.

**Comment by pranavkm** [comment]
The 3.0.0-preview2 version of ASP.NET Core Components is built with and consequently references the 3.0 version of SignalR packages. See https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Server/3.0.0-preview-19075-0444

**Comment by grahamehorner** [comment]
Q: the BlazorHub has a number of methods all have comments that they are for framework use only, with this in mind how would a background task inform the active component circuits that something has changed with regards to some shared state without using these methods but reusing the signalR communication channel?

**Comment by SteveSandersonMS** [comment]
> would a background task inform the active component circuits that something has changed with regards to some shared state without using these methods but reusing the signalR communication channel

The SignalR communications channel is an internal implementation detail for Razor Components. It's not something that application code sees or should be interacting with.

With Razor Components, components can notify that state has changed by calling `StateHasChanged` (e.g., in response to a background event). The framework will take care of re-rendering and sending the updates to the browser.

Since the original issue posted here (updating to newer SignalR) is something we've already done, I'll close this.

**Comment by grahamehorner** [comment]
@SteveSandersonMS I’ll open a separate issue for the above and provide more detail as I’m not 100% sure or clear how a background task can trigger the clients to render a component when then background task determines some condition or state changes
