### ISSUE TITLE
modifying application parts at runtime

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#7219]
Suppose on start-up I load some plugin assemblies from a plugins folder, as application parts, containing controllers, views etc.

Suppose I create a page where an Admin user can upload a zip file containing a plugin, and my application will extract this to it's plugin  directory.

Is there anyway to load the new application part at runtime without restarting the whole application?

**Comment by Eilon** [comment]
@javiercn / @sebastienros - any ideas or thoughts on this?

I suspect the answer is that it isn't supported using ApplicationParts. But a more full-featured system such as Orchard 2 might support some concept like this.

**Comment by sebastienros** [comment]
Orchard Core cheats by reloading the DI and middleware pipeline when there is a new module enabled. The application doesn't have to restart, so it's fast (<500ms) and because it doesn't happen a lot and mostly at design time it's good enough.

But OC doesn't load assemblies dynamically, they have to be statically linked. Only the decision for which ones must be activated is taken dynamically. The main issue with dynamically loading "plugins" will be that most ASP.NET components do their initialization when the application starts. And also based on compiled assets (compiled views) and some deps files issues might happen.

**Comment by dazinator** [comment]
I'm using https://github.com/natemcmaster/DotNetCorePlugins to handle loading assemblies dynamically into an application load context (I used to handle this logic myself but natemcmaster does a much better job than I did). This handles many edge cases explained in the readme.

Assembly Load Contexts are gaining a long awaited ability to be "unloaded" / disposed - which is .net core's answer to the old AppDomain Unload. So it's natural with the advent of this new capability with ALC's to want to take this to asp.net core mvc and dynamically unload / reload mvc application parts assemblies at runtime by disposing the underlying ALC from whence they were loaded. However my assumption is that it will need the asp.net core mvc team to look at the parts system and go it can can tie in with ALC unload.
