### ISSUE TITLE
ViewCompilation / Razor SDK in ASP.NET Core 2.1 targeting .NET Framework 4.7.2

### ISSUE THREAD

**Issue by drauch** [aspnet/AspNetCore#7264]
How does one enable/disable view compilation for an ASP.NET Core MVC 2.1 app targeting the full .NET framework 4.7.2?

In the earlier days it was disabled by default for full .NET framework, you had to reference "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" as an explicit development dependency to enable it. It seems that now view compilation is the default when targeting .NET framework as well?

* Is that true? Since which version?
* How to disable/enable view compilation for ASP.NET Core MVC 2.1?

**Comment by pranavkm** [comment]
1. Build time compilation is enabled by default since 2.1. We deprecated the ViewCompilation tool in the same release, and a 3.0 version of it will not be published.
2. Per https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2#properties,

The following properties control the Razor's SDK behavior as part of a project build:

`RazorCompileOnBuild` – When true, compiles and emits the Razor assembly as part of building the project. Defaults to true.
`RazorCompileOnPublish` – When true, compiles and emits the Razor assembly as part of publishing the project. Defaults to true.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
