### ISSUE TITLE
Blazor app getting ERR_CONNECTION_RESET on dll file

### ISSUE THREAD

**Issue by lrente** [aspnet/AspNetCore#7303]
I have a blazor app that sometimes gets a ERR_CONNECTION_RESET on a specific dll and fails to launch.

This does not happen in every machine, and sometimes in the same browser but on different machines, it does not open also.

The dll in question is in the correct directory.

What troubles me more is the "randomness" of the error, since we are unable to find why in some machines it works and others it does not.

Here is a pic of the error.
![image](https://user-images.githubusercontent.com/708986/52350457-8dedc200-2a20-11e9-9cb0-c382ecba3018.png)

Thanks to everyone that can help.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lrente.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, is this something you've seen in the past?

**Comment by SteveSandersonMS** [comment]
No, this sounds unrelated to Blazor. It sounds like the web server is failing to return a certain static file sometimes, but Blazor doesn't have any control over that.

I'll close this because there's nothing we can do to influence how the web server returns static files. However, if you're able to track this down to something you think Blazor could influence, please let us know!
