### ISSUE TITLE
Failed to gracefully shutdown application (IIS Hang)

### ISSUE THREAD

**Issue by FlorianRainer** [aspnet/AspNetCore#7367]
on application pool recycle (automatic by duration) and under high load i often get the following entry in event log `Failed to gracefully shutdown application 'MACHINE/WEBROOT/APPHOST/WEBNAME'.`

this was already happen in 2.1 with outproc, but now i've updated to 2.2 with hostingModel="InProcess", but i get a additional eventlog entry:

```Application: w3wp.exe
CoreCLR Version: 4.6.27207.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The handle is invalid
   at System.ConsolePal.WindowsConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<>c__DisplayClass6_0.<AttachCtrlcSigtermShutdown>g__Shutdown|0()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<>c__DisplayClass6_0.<AttachCtrlcSigtermShutdown>b__1(Object sender, EventArgs eventArgs)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.AppContext.OnProcessExit(Object sender, EventArgs e)
```

I use overlapped recycling, the new process is already stated, but i need to recycle manualy else the IIS is not processing requests anymore, they just timed out.

Setup:
- Windows Server 2012 R2
- IIS 8.5
- .net core runtime and hosting bundle 2.2.1
- overlapped recycling enabled
- web: preload enabled = true
- application pool: start mode always running
- 32bit application

any idea why this exception happens?
the related code should be this https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L142 (this Console.Log)

**Comment by serenata-keith-mifsud** [comment]
this is happening to us as well. we are load balanced, and as soon as one instance fails from this, the others shortly fail as well. This issue is happening during high traffic hours

**Comment by shram2k** [comment]
I am also facing the same issue. I have hosted Asp.Net Core 2.2 API project InProcess (IIS) and frequently getting "Failed to gracefully shutdown process". Any solution?

**Comment by shram2k** [comment]
> I am also facing the same issue. I have hosted Asp.Net Core 2.2 API project InProcess (IIS) and frequently getting "Failed to gracefully shutdown process". Any solution?

Any update?

**Comment by FlorianRainer** [comment]
We have managed to avoid this Problem by optimizing the http response time.

The main reason for the problem (i n my case) was a quite long request queue in IIS, ans some long running requests ~30sec.

If the IIS Worker triggered the recycle the process will try to conclude all requests in queue, if this will not be able until the IIS recycle timeout value is reached the process will get in this state (and this exception appears).

If the request processing is fast enougth, it would be no problem, but i think the Problem should be resolved in a proper way, even if we have long queues

**Comment by muratg** [comment]
Looks similar to our other test failures

**Comment by muratg** [comment]
This isn't likely to be an issue in 3.0. We've moved to logger from Console.WriteLine in the new generic host

**Comment by anurse** [comment]
We believe we've made significant improvements on shutdown in preview4. If you're still hitting this after preview 4 is released (and you've updated), let us know.

**Comment by deanward81** [comment]
This is affecting us quite badly during local development under 2.2. We're running under IIS using the in-process model and everytime the app pool needs to recycle (usually due to actual changes made during development) a build fails because files are locked by the process crash being handled.

We have to stop the app pool in IIS, build and then restart - this is painful! Are there any known workarounds in 2.2?

**Comment by NickCraver** [comment]
To expand on what @deanward81 said:
What are the chances of this getting fixed in 2.2? 3.0 is great, and we're trialing the preview in some areas, but this is **crashing the process** on the latest stable version.

This is affecting every application we're porting at Stack Overflow. While we'll upgrade to 3.0 as soon as is reasonable, troubleshooting, logging, monitoring, or anything to do with process crashes and event logs is a very high noise to signal ratio and triggers every build.

Can we please get a fix for this in 2.2? By fix I mean something where the process doesn't crash every shutdown, it doesn't have to be fancy. Right now we can't alert on process crashes because every deploy would have `n` of them, and that makes the platform a risky proposition to move to. The impact of this issue has become more of an issue the bigger the service and when debugging anything, so we now consider this a blocker to any further production deploys. Even a hacky workaround on current bits would be very much appreciated - anything to unblock our moves.

**Comment by jkotalik** [comment]
> This is affecting us quite badly during local development under 2.2. We're running under IIS using the in-process model and everytime the app pool needs to recycle (usually due to actual changes made during development) a build fails because files are locked by the process crash being handled.

If you are using the VS IIS development tools, you shouldn't be hitting this issue. @BillHiebert  to confirm?

**Comment by jkotalik** [comment]
We are going to consider fixing this bug in 2.2.

**Comment by Tratcher** [comment]
Three variants:
2.2 web host: https://github.com/aspnet/AspNetCore/pull/12518/files
3.0 web host: https://github.com/aspnet/AspNetCore/blob/f3f9a1cdbcd06b298035b523732b9f45b1408461/src/Hosting/Hosting/src/Internal/WebHostLifetime.cs#L69
3.0 generic host: https://github.com/aspnet/Extensions/blob/45647cef001961bd82c8ac4c112d24d4254e44cf/src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs#L84 (Ensure the logger doesn't throw after disposed on shutdown)

**Comment by anurse** [comment]
This should be fixed in the next patch release (2.2.7).

**Comment by tongleiyw** [comment]
do we have the estimated release date for 2.2.7? our application crashes in production causing the transaction failures...

**Comment by leecow** [comment]
Targetting next week to get 2.2.7 out.

**Comment by tongleiyw** [comment]
Thank you very much for your quick response!
