### ISSUE TITLE
Revisit making Response.BodyPipe.Complete() actually complete the PipeWriter for Http2

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7370]
In the Http1 and Http2 output producers, we currently make Complete effectively noop. For Http1 we can't call PipeWriter.Complete() as that is the connection pipe and there isn't a notion of a response pipe. For Http2, we CAN call Complete() as there is a Data pipe available. However, there are issue with creating a well formatted response if we do support Complete.

- Do we require users to call StartAsync() before calling Complete(). This will guarantee that headers are committed.
- How do we handle Trailers? ProduceEnd?

**Comment by Tratcher** [comment]
This would prevent middleware from adding trailers.

**Comment by Tratcher** [comment]
Isn't this superseded by CompleteAsync?

**Comment by halter73** [comment]
> Isn't this superseded by CompleteAsync?

No. CompleteAsync is preferred b/c it allows the app to observe back pressure while also signalling response completion. Had it not been for the back pressure issue, there wouldn't be a need for both Response.BodyPipe.Complete and CompleteAsync.

**Comment by Tratcher** [comment]
BodyPipe.Complete also stops working as soon as you use a middleware that replaces the response stream (e.g. response compression) and the pipe auto-replaces with an adapter. We're going to implement CompleteAsync there too. CompleteAsync will be more reliable for apps to call than BodyPipe.Complete.

**Comment by Tratcher** [comment]
To that end, we should not have Complete close the response, only CompleteAsync, so devs always get a consistent experience with and without the adapters.

**Comment by halter73** [comment]
> Disposing the response body has never completed the response either.

Exactly. We could have made disposing the response body  stream exhibit reasonable behavior if we didn't have to continue supporting the broken behavior from 1.0. Notice how no tests failed except for two that explicitly expected this not to throw. Without the albatross of backwards-compatibility, we can finally make a nice API.

The fact that middleware that replaces the response stream has to think about the CompleteAsync scenario isn't new at all. Like you said they have to replace CompleteAsync already, which as far as I'm aware nothing does yet, so you can fix both things together.

Finally, I didn't really have much choice in the matter. Once I fixed the issue so client-aborted HTTP/2 frames wouldn't cause writes to throw an InvalidOperationException, the test that verified an InvalidOperationException was thrown for writes after CompleteAsync started failing. The test was relying on the buggy behavior and only passed to pass because the test wrote to the response body using the PipeWriter not the Stream. So I had to fix CompleteAsync, so it actually poisoned the response body.
