### ISSUE TITLE
Make Mvc consistent with repository layout

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7482]
I started working on producing reference assemblies for projects in AspNetCore and Extensions that are required for .net core 3.0 targeting pack work.

The folder structure used by coreclr/corefx and now Extensions repo is the following:

```
.../ProjectA/src/ProjectA.csproj - implementation assembly A
.../ProjectA/ref/ProjectA.csproj - reference assembly A
.../ProjectB/src/ProjectB.csproj - implementation assembly B
.../ProjectB/ref/ProjectB.csproj - reference assembly B
```

With the current rules and Mvc project structure:

```
../Mvc/src/ProjectA/ProjectA.csproj
../Mvc/src/ProjectB/ProjectB.csproj
```

all ref projects end up in one location:

```
../Mvc/src/ref/ProjectA.csproj
../Mvc/src/ref/ProjectB.csproj
```

which is hardly desirable and just wrong.

We have two options here:

1. Get Mvc consistent with rest of the repos
2. Special case Mvc project structure in generation and consumption of reference assemblies.

cc @mkArtakMSFT @Eilon @muratg @natemcmaster

**Comment by natemcmaster** [comment]
cc @ajaybhargavb

**Comment by natemcmaster** [comment]
This wasn't done in the first place when we did #4246 because @ajaybhargavb told me it was going to be difficult. There are apparently a bunch of tests which depend on the source code layout to function correctly. This is a general problem which needs to be addressed anyways in order to make tests work in Helix, so I would recommend prioritizing this work.

**Comment by ajaybhargavb** [comment]
Yup this has been in my list of things to do. Given this is blocking Helix, I'll make this my top priority now 👍
