### ISSUE TITLE
Not refreshing saved Blazor cshtml in Visual Studio 2019 preview

### ISSUE THREAD

**Issue by thainbreese** [aspnet/AspNetCore#7520]
I have created a new blazor 0.8.0 component project in Visual Studio 2019 preview.
The solution includes two projects. {projectName}.App and {projectName}.Server

If I run the project, change cshtml files on client app project, and refresh the browser, it isn't updated.
What's wrong?

**Comment by chucker** [comment]
Hot reload is known to be broken in Blazor 0.8. (I believe I saw Dan mention this somewhere.)

You may be able to work around it by placing this in the server's `csproj` (thanks srowan):

```xml
<ItemGroup>
  <Watch Include="..\**\*.cshtml" />
</ItemGroup>
```

And running `dotnet watch run` from the server project folder.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @thainbreese.
This is going to be fixed in the first update of VS 2019.
As a workaround you can choose to use out-of-proc hosting model by modifying your `csproj` file as described here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#in-process-hosting-model
