### ISSUE TITLE
[Components] Support for IntelliSense on components and their parameters

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#7547]
I am trying to consume a third-party component in my project. However, it (apparently) currently has no way of exposing IntelliSense/XML documentation:

* for the component itself, there simply is no obvious syntax. You never explicitly specify the class name (it is inferred from the file name); therefore, the typical approach of annotating that name with documentation doesn't work.

* for its parameters inside a `@functions` block, normal C# syntax will work. However, parameters aren't designed to be public, so this doesn't get exported to XML documentation either. The `.cshtml.g.cs` files do not appear to retain XML comments.

### Describe the solution you'd like
* there should be syntax for declaring a component's documentation. For example, a new `@doc` directive would do the trick:

```csharp
@inherits ComponentBase

@doc {
/// <summary>
/// This is an exciting example Razor Component!
/// </summary>
}
```

* as part of the components build process, XML should be emitted

* the Razor parser should pick these up on the consuming side:

```xml
<MyExampleComponent />
<!-- hovering over the above should show "This is an exciting example Razor Component!" -->
```

### Describe alternatives you've considered
To avoid introducing new syntax, the documentation could perhaps also be placed inside a separate partial class.

However, this would be more cumbersome, and it appears the tooling still wouldn't pick this up anyway.

### Additional context
One concrete example is [BlazorStrap](https://github.com/chanan/BlazorStrap/), a Bootstrap port to Razor Components. Consuming the components would feel more natural if additional documentation were provided as part of IntelliSense.

**Comment by rynowak** [comment]
The documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#recommendations) says that non-public methods can still have documentation. If this isn't correct in practice when we should fix that.

Even if generated documentation requires public I don't think we should take any specific here because the guidance is that component parameters should not have a **public SET** method. It's fine to use a public getter. 

Lastly for classes, it's our plan to generate component classes as `partial` so that you can have a code-behind file. This should be a fine place for class-level documentation.
