### ISSUE TITLE
Trim Async suffix on SignalR Hub method names

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#7554]
See https://github.com/aspnet/AspNetCore/pull/7420

@muratg We'll probably want to do this sooner than later since it's breaking.

**Comment by muratg** [comment]
Thanks @halter73.  @bradygaster FYI.

**Comment by anurse** [comment]
Should we do this in SignalR? I don't think it makes the same kind of sense here, since SignalR is RPC, but MVC is a URL pattern.

In MVC, it makes a lot of sense, because you may have an action like:

```csharp
public class CustomersController
{
    public async Task GetAllAsync()
    {
    }
}
```

And you want to access it at `/Customers/GetAll`, **not** `/Customers/GetAllAsync`. This makes total sense to me.

However, in SignalR you are **calling** a method, rather than sending a request to a URL. So if you have a Hub method:

```csharp
public class CustomersHub
{
    public async Task GetAllAsync()
    {
    }
}
```

The code you want to write on the .NET client would definitely be:

```csharp
var customers = /* Get Hub Connection */;
// Assume we had perfect client generation, etc.
var customers = await customers.GetAllAsync();
```

Stripping `Async` from the method name doesn't make as much sense there for me.

I realize it's not a perfect analogy, since JavaScript, Java and C++ are all viable clients and don't have this pattern. However, in this case, I think we should **not** be stripping suffixes from method names since the user is defining a method *which will be called like a method* rather than defining a method that ends up generating a URL pattern.

**Comment by halter73** [comment]
Good point @anurse about RPC. The real benefit of this change seems to be related to the default way MVC does routing based on action names.

**Comment by halter73** [comment]
If we were to do this at all, the Async suffix probably should be optional, but I'd rather keep things simple and have one true name for every hub method.

**Comment by anurse** [comment]
Triage Decision: This doesn't make sense for SignalR, let's close.
