### ISSUE TITLE
HtmlHelperOptions.ClientValidationEnabled = false is ignored

### ISSUE THREAD

**Issue by Ponant** [aspnet/AspNetCore#7576]
`services.AddMvc().AddViewOptions(o =>
            {
                if (_env.IsDevelopment())
                {
                    o.HtmlHelperOptions.ClientValidationEnabled = false;
                }
            })`
is currently not working on the register page of the asp.net identity template.

**Comment by Ponant** [comment]
@muratg , is that expected not to work on razor pages and be applicable only to traditional mvc views?

**Comment by muratg** [comment]
@Ponant I don't know. 

cc @danroth27

**Comment by Rick-Anderson** [comment]
@rynowak

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Ponant.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
This is a product bug.

The issue is that PageActionInvokerProvider takes in `IOptions<HtmlHelperOptions>` directly in the constructor instead of `IOptions<MvcViewOptions>` as it should.

https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.RazorPages/src/Infrastructure/PageActionInvokerProvider.cs#L55

The impact is that htmloptions set in mvcviewoptions are not respected for pages.
There are several trivial workarounds for it:
1) Set the option in _ViewStart.cshtml
2) Set the option in both places by additionally calling `services.Configure<HtmlHelperOptions>(o=> o.ClientValidationEnabled = false)`

The fix for 3.0 is to make a breaking change and have the constructor take in the right parameter.

The fix for downlevel versions, should we  choose to implement it, is to modify createactioninvoker to pass in the right options.

The risk of this downlevel fix is that someone might have workaround it using option 2, and then we would break them.

We could consider this for patching, but my personal take is that we don't, given that there is a trivial workaround, the scenario is not very common and that we would risk breaking other people that has workaround it.

```csharp
            var properOptions = actionContext.HttpContext.RequestServices.GetRequiredService<IOptions<MvcViewOptions>>()

            return new PageActionInvoker(
                _selector,
                _diagnosticListener,
                _logger,
                _actionContextAccessor,
                _mapper,
                pageContext,
                filters,
                cacheEntry,
                _parameterBinder,
                _tempDataFactory,
                properOptions.Value.HtmlHelperOptions);
```

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/9289

**Comment by Ponant** [comment]
Still not working in .Net Core 3.,0 Preview4
`
            services.AddRazorPages().AddViewOptions(x => x.HtmlHelperOptions.ClientValidationEnabled = false)
                .AddNewtonsoftJson();`

**Comment by javiercn** [comment]
This is fixed in preview5.
