### ISSUE TITLE
Debug mode very slow

### ISSUE THREAD

**Issue by Urki57** [aspnet/AspNetCore#7621]
Starting VS with a simple ASP.NET project can take up to 30 seconds

**Comment by Eilon** [comment]
To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
