### ISSUE TITLE
Adding .npmproj files to a solution

### ISSUE THREAD

**Issue by wicked-sick** [aspnet/AspNetCore#7676]
Can you share some light around custom project types like `.npmproj`, e.g.:

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Browser.JS/src/Microsoft.AspNetCore.Components.Browser.JS.npmproj

and how they can be referenced as a dependency in Visual Studio solution? I am trying to attach all the source code dependencies of Blazor to the solution of a sample project in order to debug the actual source code, but the dependency on Microsoft.AspNetCore.Components.Browser.JS.npmproj cannot be added by "Add existing project" due to the unsupported project extension in the menu. 

Similar scenarios for JS are created as `.csproj` files, which allows them to be added without any issues:
https://github.com/dotnet/jsinterop/tree/master/src/Microsoft.JSInterop.JS

@natemcmaster 
Looking at the [commit](https://github.com/aspnet/AspNetCore/commits/master/src/Components/Browser.JS/src/Microsoft.AspNetCore.Components.Browser.JS.npmproj) that introduced the `*.npmproj`, can you add some details on what is the workflow when working with this project in order to attach the source code to a project for debugging?

**Comment by natemcmaster** [comment]
.npmproj files are only meant to be used for command line builds and are not a supported by Visual Studio. We do not use .csproj for these projects because they do not contain C#.

Adding @pranavkm and @SteveSandersonMS  to comment on how they go about debugging JS. I use VS Code for all of my dev work, but they may have other solutions.

**Comment by wicked-sick** [comment]
Yes, debugging this from command line and VS Code will work, I was wondering if and what is the "workaround" for doing this in Visual Studio.

**Comment by natemcmaster** [comment]
_Build Team Triage:_ closing as we don't plan to support adding .npmproj files to Visual Studio. VS doesn't support custom project types. I spend sometime trying to hack around this, but didn't find anything that works well and is sustainable in the long run. Also, we're considering removing npmproj files completely as a part of #7280. We're moving our repo to a new build system which would not allow for custom project types.

> I want to clarify that my main goal is to replace the installed NuGet packages ... with its source code project.

Hopefully you were able to make that work. This is not something we generally support because the project files in this repo have a bunch of extra, custom targets in them. These targets are necessary and unusual because this repo builds .NET Core itself, which introduces many new requirements to what needs to happen with our code.

Closing as there is no plan to address this.
