### ISSUE TITLE
Re-enable AppVerifier and crash dump collection in Helix

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7774]
It's hard to debug crashes without the crash dump.

**Comment by anurse** [comment]
Useful for IIS crashes and for hanging tests.

**Comment by anurse** [comment]
Also, it would be good to be able to extract our test logs as well as xunit diagnostic logs

**Comment by jkotalik** [comment]
Let's try to prioritize this work. There is a service with Helix called Dumpling that we can potentially use to capture crash dumps. @anurse and I agree the goal E2E experience would be to have:
- Test failures link to all crash dumps that occurred during a test run.
- All pdbs are also linked to debug said crash dumps

There are many scenarios we are missing because of this. There was an IIS crash I had to debug on aspnetci because it was the only place that had dumps.

**Comment by pakrym** [comment]
> All pdbs are also linked to debug said crash dumps

You can get pdbs from VSTS artifacts.

**Comment by jkotalik** [comment]
>You can get pdbs from VSTS artifacts.

Yep, just a direct link to them in the RAAS issue.

**Comment by pakrym** [comment]
Also https://github.com/dotnet/arcade/pull/2103

**Comment by natemcmaster** [comment]
@anurse this looks like a feature-team item, but I'm not 100% sure what work is involved here so lmk if you need build team to help. Moving to area-servers.

**Comment by jkotalik** [comment]
I think this issue should be retitled: Get Crash Dumps in Helix. Today there is no way to collect dumps at all. The appverifier stuff isn't relevant to the underlying issue.

**Comment by anurse** [comment]
@jkotalik does the download task added in https://github.com/dotnet/arcade/pull/2103 cover our needs here? IIRC we just needed to find a way to get the files back from Helix, then we can add the crash dump collection logic.

> this looks like a feature-team item

I mostly agree, though I would definitely want the build team involved since it will likely affect every Helix run. We'll probably be putting some commands before and after the test run to set up dump collection, grab any dumps generated, and use `DownloadFilesFromResults` to pull them back to AzDO and publish them as artifacts.

**Comment by anurse** [comment]
Closing in lieu of https://github.com/aspnet/AspNetCore-Internal/issues/2079
