### ISSUE TITLE
Non-Kestrel servers flushes when StartAsync is called

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#7780]
To mimic the Kestrel behaviour, a `IHttpResponseStartFeature` needs to be added by the TestServer. Otherwise it falls back to the flushing behaviour: https://github.com/aspnet/AspNetCore/blob/4646ed56189a8ee36ced6397dd4f86fce9e6a8e8/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L154-L159.

**Comment by jkotalik** [comment]
So a few questions:
- Do you agree that flushing if the StartFeature isn't implemented is desired behavior?
- If so, why do you need TestServer to implement the IHttpResponseStartFeature? Are you trying to verify that StartAsync doesn't flush headers to the client?

I agree that having inconsistent behavior based on if the feature is implemented isn't great. Maybe we should throw if the feature isn't implemented instead.

**Comment by JamesNK** [comment]
This area came up when when upgraded gRPC to the latest version of preview 3. A combination of circumstances combined:

* We had heard that StartAsync is required before using Response.BodyPipe and that calling it multiple times is fine because the feature will no-op once the response has started
* We changed our write message code to start with a call StartAsync
* We have a unit test that does buffering and calls write message multiple times
* Because our test is running in TestServer there was no IHttpResponseStartFeature so writing a message would flush previous messages

The main problem here is the difference in behavour between a real server and the TestServer. The test server is flushing each time StartAsync is called. That could be solved by https://github.com/aspnet/AspNetCore/issues/7778

**Comment by Tratcher** [comment]
The fallback behavior is OK, but we should go ahead and implement `IHttpResponseStartFeature` and pipes.  There's already a response body pipe.

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/issues/7815

**Comment by muratg** [comment]
Triage: We won't be doing this. Instead we'll do #7779

**Comment by JunTaoLuo** [comment]
Why are we not adding the feature to TestServer?

**Comment by JunTaoLuo** [comment]
I think I named the issue poorly and it was misunderstood? We should still add the feature to the test server.

**Comment by JamesNK** [comment]
Related: TestServer should be using real pipes instead of the stream adapters

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/issues/7815
