### ISSUE TITLE
[Blazor] String parameters are not recognized for generic components

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#7785]
### Describe the bug
I have a generic component that I want it to be able to use any value type(int, string, enum, etc). It is working for all types but for strings I have to write it in a specific way.

### To Reproduce
**SelectItem.cshtml**
```
@typeparam TValue
<option value="@Value">@ChildContent</option>
@functions{
    [Parameter] protected TValue Value { get; set; }
    [Parameter] protected RenderFragment ChildContent { get; set; }
}
```
### Screenshots and Usage
![image](https://user-images.githubusercontent.com/900302/53154592-75061480-35bb-11e9-99b1-1f9d2a9fecf0.png)

### Expected behavior
As seen in the screenshot if I write the string in quotation it will not be recognized as string but instead it will try to look for a variable named `George`. When I write it with **"@("abc")"** it is working.

**Comment by rynowak** [comment]
Thanks for the report. This is expected for now, but it's possible that we'll try to fix it in the future if we find a way.

**Explanation:**

Tag Helpers (and Components) have a feature where a string-typed property allows you to type in a string *directly* - without the need for quotes and an explicit expression `@(...)`. 

However, this is a **parser** feature because it results in a different syntax tree depending on whether an attribute is mapped to a string-typed property or not. 

However, when we're doing the code generation for generics, we usually do not know the type at all in the compiler. For instance in your `SelectItem<T>` component, we never know in the compiler what type `T`. So not only is it too late for for us to go back and reparse the attribute as a string if we need to, we don't even have that information.

**Comment by stsrki** [comment]
In a regular C# it is perfectly fine to create a class that inherits a generic class, that have a predefined value type.

eg.
```
public class SelectEdit<TValue>
{
    public TValue Value { get; set; }
}

public class SelectEdit : SelectEdit<string>
{
}
```

**Usage:**
```
var s1 = new SelectEdit(); // default is always string
var s2 = new SelectEdit<int>();
var s3 = new SelectEdit<decimal>();
```

There is not a way that I can do this in Blazor, at least I'm not aware of it.

It would be great if there is a way to define a default data type when creating a generic component.

**Solution:**
`@typeparam TValue, string`

Where the second parameter could be a _default_ value type

**Comment by mkArtakMSFT** [comment]
We looked at potentially changing how strings and parameters work and have decided the user impact in that case would be unacceptable.
