### ISSUE TITLE
EmailSender should throw NotImplementedException

### ISSUE THREAD

**Issue by mariusGundersen** [aspnet/AspNetCore#7787]
### Describe the bug
The [implementation](https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/UI/src/Areas/Identity/Services/EmailSender.cs) of `IEmailSender` should throw `NotImplementedException` with a short description and a link to further documentation of how to implement it. Currently it returns a `Task.CompletedTask` so three is no indication that it isn't doing anything at all. It looks like the code is ready for production, but it is not, and it is impossible to find out what is wrong without looking at the source code on github.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run `dotnet new webapp --auth Individual`
3. Run `dotnet run` and go to `https://localhost:5001` in a browser
4. Register a new user
5. Log out
6. Click on 'Forgot your password?' and enter the email
7. No error is shown, but no email has been sent. 

### Expected behavior
There should be some indication that this part of the code isn't implemented and needs to be implemented by the developer. For example, there is a text and link about adding external authentication services, so it's clear that this isn't built in yet. But there is no such message about the email sending. 

I think it would be better if the EmailSender threw an exception and the razor page cought the exception and showed a red error box with a description that EmailSender hasn't been implemented and a link to relevant documentation. The closes to useful documentation I could find was [this article](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio), but ther should probably be a shorter article with a simpler example of how to use SmtpClient to send an email.

**Comment by blowdart** [comment]
This is more complicated than you think, as it needs UI changes. User creation attempts to confirm email addresses, but that's hidden, and if we throw then you can't register at all... I'm going to backlog this because frankly identity UI needs a redesign which won't happen in 3.0 but I don't want this forgotten.

**Comment by blowdart** [comment]
See https://github.com/aspnet/AspNetCore/issues/8356

We won't be throwing exceptions, instead the flow is going to change, so the default scaffolded flow will have a nice warning page during registration to say you're using the no-op email sender you silly goose, please change this before production. This page also enables us to give a click through experience to emulate what would be in the email. We're taking this approach because we believe that File -> New should produce runnable code.
