### ISSUE TITLE
Remove unneeded dependencies from Components.sln

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#7799]
`Components.sln` has references to virtually everything we produce through `Microsoft.AspNet` (metapackages). This means that you need to do a full build on the repo before opening the solution - and things like building after updating the source code of the repo don't work correctly because we have dependencies that aren't in the solution.

This isn't the way our stuff is designed to work, and it seems like we don't have a *product* reason to include so many dependencies.

Here's basically what would need to change:
- Get rid of `Microsoft.AspNet` usage in the Blazor CLI tool - use lower level primitives directly
- Get rid of `WebHost.CreateDefault` usage in test projects ([example](https://github.com/aspnet/Mvc/blob/master/test/WebSites/BasicWebSite/Program.cs#L10) of how to fix)
- Get rid of MVC usage in test projects and replace with simple middleware

**Comment by pakrym** [comment]
cc @Tratcher for  "`WebHost.CreateDefault` usage in test projects ([example](https://github.com/aspnet/Mvc/blob/master/test/WebSites/BasicWebSite/Program.cs#L10) of how to fix)"

**Comment by Tratcher** [comment]
> virtually everything we produce through `Microsoft.AspNet`

`Microsoft.AspNetCore` is the 'small' meta package, it only has startup stuff like hosting and servers.

> This means that you need to do a full build on the repo before opening the solution

No, only a restore. It's not often you need to build the whole repo.

> and things like building after updating the source code of the repo don't work correctly because we have dependencies that aren't in the solution.

This is a known nuget issue that was supposed to be fixed in vs 2019. I'm still hitting it and the workaround is to disable nuget auto-restore in vs.

> * Get rid of `WebHost.CreateDefault` usage in test projects ([example](https://github.com/aspnet/Mvc/blob/master/test/WebSites/BasicWebSite/Program.cs#L10) of how to fix)

We've been going the other direction actually, adding WebHost.CreateDefault to samples to simplify them. E.g. most Security samples now do this.

Your [BasicWebSite](https://github.com/aspnet/Mvc/blob/04ce6cae44fb0cb11470c21769d41e3f8088e8aa/test/WebSites/BasicWebSite/BasicWebSite.csproj#L23-L29) example only has a few less dependencies from this repo than the [metapackage](https://github.com/aspnet/AspNetCore/blob/e5f4400257212f7f0db61a4451b2915439c6bd77/src/DefaultBuilder/src/Microsoft.AspNetCore.csproj#L13-L19) does. In fact, the only ones the metapackage adds beyond BasicWebSite are Microsoft.AspNetCore.Server.IIS and Microsoft.AspNetCore.HostFiltering. You're not saving yourself many dependencies, you're writing more code, and you're diverging from how normal apps work.

> Get rid of MVC usage in test projects and replace with simple middleware

I can't argue with that one, most samples avoid MVC for simplicity sake.

**Comment by rynowak** [comment]
> No, only a restore. It's not often you need to build the whole repo.

Was this fixed recently? I just had a long email discussion with @pakrym and @natemcmaster about my cool experiences with the native IIS code needing to be build before launching the solution.

**Comment by natemcmaster** [comment]
> supposed to be fixed in vs 2019. I'm still hitting it

@jainaashish merged a fix to NuGet for NU1105 a while ago (https://github.com/NuGet/NuGet.Client/pull/2521). I'm surprised it hasn't shown up in VS 2019 yet. Maybe the change doesn't cover our scenarios?

**Comment by rynowak** [comment]
> 12>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4558,5): error MSB3030: Could not copy the file "C:\src\aspnet\AspNetCore\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\bin\Debug\x64\aspnetcorev2_inprocess.dll" because it was not found.
12>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4558,5): error MSB3030: Could not copy the file "C:\src\aspnet\AspNetCore\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\bin\Debug\Win32\aspnetcorev2_inprocess.dll" because it was not found.

These were my errors

**Comment by Tratcher** [comment]
The native IIS bits only need to be built once, they rarely change. Just don't `git clean`.

**Comment by rynowak** [comment]
> This means that you need to do a full build on the repo before opening the solution 

So we're back here. I really don't think that's good enough. @natemcmaster is building the repo before opening in VS the plan of record?

**Comment by natemcmaster** [comment]
> is building the repo before opening in VS the plan of record?

No. Sort of defeats the purpose of an IDE.  @jkotalik @pakrym what do you think about making the project refs to C++ optional when building inside Visual Studio?

**Comment by pakrym** [comment]
I'm fine with that if it keeps working correctly in IISIntegration solution.

**Comment by danroth27** [comment]
We decide there's really no action here.
