### ISSUE TITLE
LoginWith2faModel to LoginWith2FaModel

### ISSUE THREAD

**Issue by XzaR90** [aspnet/AspNetCore#7885]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	S101	Rename class 'LoginWith2faModel' to match camel case naming rules, consider using 'LoginWith2FaModel'.	...Areas\Identity\Pages\Account\LoginWith2fa.cshtml.cs	16	Active

**Comment by Eilon** [comment]
Looks like a warning from https://github.com/SonarSource/sonar-dotnet ?

Unfortunately I suspect there's little point in changing the identity/template code because there could always be some new analyzer out there with some new rules and I can imagine it'd be a lot of work to try to satisfy every analyzer out there.

Recommend won't fix.
