### ISSUE TITLE
[Blazor] StateHasChanged with initial values

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#7898]
### Describe the bug
I cannot decide is this a bug or is it meant to work like this. I have a problem when I use StateHasChanged on `Validation` component.

My `Validation` component is doing a **StateHasChanged** when the input inside of it pass or fail the validation rule. The problem is if I give the input a default value by just writing it to the component parameter it will not work as expected. The initial value will **always** reset for the Text parameter, in this case value "a". So, every time validation fail, it will do a **StateHasChanged**, TextEdit will again be set to initial value("a") and validation will succeed because now it is again "not empty".

### Not working
```
<Validation Validator="@ValidationRule.IsNotEmpty">
    <TextEdit Text="a">
        <Feedback>
            <ValidationError>error</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>
```

### Working
```
<Validation Validator="@ValidationRule.IsNotEmpty">
    <TextEdit bind-Text="@textValue">
        <Feedback>
            <ValidationError>error</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>
@functions{
    string textValue = "a";
}
```

Validation is working as expected only if I use **variable** for the component parameters.

### Expected behavior
Initial value should be just that, an initial value that I have defined as the component value. It should not be used later no mater how many times I hit refresh(StateHasChanged).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stsrki.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
I'm afraid I can't investigate or take any action on this, because there's not enough information to know what's going on.

@stsrki, your `<Validation>`, `<TextEdit>`, and `<Feedback>` components are all custom components, so I have no idea what they do or in what way they might be responsible for the behavior you're seeing.

For us to investigate, could you please post a complete and minimal repro of the issue? I'm not looking for the complete source code of your custom components, but rather the smallest amount of code that reproduces whatever behavior you are questioning. Thanks!

**Comment by stsrki** [comment]
@SteveSandersonMS I have created test project with the minimal amount of code for you to test. 

**How to test:**

1. Run the project
2. Navigate to /test page
3. on text input hit backspace until its empty

After the input has cleared it will be reset to the initial value.

You can find the source on https://github.com/stsrki/BlazorSHCIssueExample

**Comment by SteveSandersonMS** [comment]
The problem is that your parent component, `TestPage`, is hard-coded to supply the parameter `Text="hello"`. Every time it refreshes its children, this is the parameter it will pass, and it's up to the child components to do what they want with that information. The logic in your `TextEdit` (specifically in the setter for the `Text` property) accepts the parameter and uses it as the current value of the textbox.

So, every time the parent re-renders, the child will once again be told to set `Text="hello"`, and that's what it does. The fact that this only happens when you change the validation status is because your `Validation` component is coded to re-render itself only when the validation status changes. Everything is doing what it's been told to do.

To get the behavior you want, either:

 * Don't keep passing a fixed value for `Text`. Use `bind-Text` and wire it up to some property on the parent component whose value can change to whatever the user types.
 * Or, change the logic in `TextEdit` so that it only pays attention to the *initial* value of `Text`, and ignores subsequent changes from the parent. Example:

```cshtml
<input type="text" value="@CurrentText" oninput="@HandleOnInput" />
@functions{
    string _currentText;
    string CurrentText
    {
        get => _currentText;
        set
        {
            _currentText = value;
            ParentValidation?.UpdateInputValue(_currentText);
        }
    }

    protected override void OnInit()
    {
        _currentText = Text;
        ParentValidation?.InitInputValue( _currentText );

        base.OnInit();
    }

    void HandleOnInput( UIChangeEventArgs e )
    {
        CurrentText = e?.Value?.ToString();
        TextChanged?.Invoke( CurrentText );
    }

    [Parameter]
    string Text { get; set; }

    [Parameter] Action<string> TextChanged { get; set; }
    [CascadingParameter] protected Validation ParentValidation { get; set; }
}
```

Of these two options, it's better to use `bind-Text` and keep the parent/child values in sync. The technique of "only paying attention to the initial value" will cause you other problems if you genuinely do want the parent to be able to modify the value.

**Comment by stsrki** [comment]
Neither solution works perfectly for my case. 

What I propose is to modify **RenderTreeBuilder** when there is a default value specified. When the "generator" detect the usage of default value instead of **bind-*** or **by-variable** parameter set then it should automatically generate new variable and set it to the component attribute.

**Instead of:**
```
builder.OpenComponent<Blazorise.TextEdit>(25);
builder.AddAttribute(26, "Text", "hello");
builder.CloseComponent();
```

**Proposed:**
```
builder.OpenComponent<Blazorise.TextEdit>(102);
builder.AddAttribute(103, "Text", Microsoft.AspNetCore.Components.RuntimeHelpers.TypeCheck<System.String>(someAutoGeneratedVariableName101));
builder.AddAttribute(104, "TextChanged", Microsoft.AspNetCore.Components.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, (v)=> {someAutoGeneratedVariableName101 = v; })));
builder.CloseComponent();

string someAutoGeneratedVariableName101 = "hello";
```

**Comment by SteveSandersonMS** [comment]
There's already a way of doing what you propose, which is to use the binding system. That's basically exactly what your proposed code does.

It's not the default because it's even more common *not* to want two-way binding for any given parameter.

**Comment by stsrki** [comment]
Yes I know its two-way binding, that's why I proposed it. I think by generating it automatically to use two-way binding it should work as expected. The default value would be set **internally** with the auto-generated variable and it wouldn't be reseted to default value on StateHasChanged.

I come from window-apps background and this behaviour is expected for text-boxes. The internal value for each of the control should be managed internally no matter how I initially set it and how I later refresh the parent container or dialog.

That's just my $0.2. If you think this is expected behavior than its OK.
