### ISSUE TITLE
Please tell me what the method GetEventHandlerValue does and what it is used for

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#7948]
public static MulticastDelegate GetEventHandlerValue<T>(Action value)
            where T : UIEventArgs
        {
            return value;
        }

Source: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/BindMethods.cs

**Comment by rynowak** [comment]
This is used by the generated code to allow you to pass an `Action` instead of an `Action<T>` for an event handler. 

```
<button onclick="@(() => { ... })" />
```

VS

```
<button onclick="@((e) => { ... })" />
```

There's a variety of different signatures we allow for event handlers, and they are resolved by the C# compiler using overload resolution. The code we generated (in 0.8 and earlier) looks like:
```
builder.AddAttribute(1, "onclick", BindMethods.GetEventHandlerValue<UIMouseEventArgs>(<your code here>));
```

**Comment by enetstudio** [comment]
I got it...Thanks...
