### ISSUE TITLE
[Blazor] Template is not working in both Visual Studio 2019 preview 3.0 and VS Code

### ISSUE THREAD

**Issue by arun-cm** [aspnet/AspNetCore#7952]
### Describe the bug
Blazor is not working on Both Visual Studio 2019 Preview 3.0 and VS Code

### To Reproduce
1. Install Visual Studio 2019 Preview 3.0
2. Install .NET Core SDK 3.0 Preview
3. Install the latest Blazor Language Services extension from the Visual Studio Marketplace. This step makes Blazor templates available to Visual Studio.
4. Make the Blazor templates available for use with the .NET Core CLI by running the following command in a command shell `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04`
5. Select File > New Project > Web > ASP.NET Core Web Application.
6. Make sure .NET Core and ASP.NET Core 3.0 are selected at the top.
7. Choose the Blazor template (standalone or with .netcore) and select OK.

### Error
App will throw an error on building/running the app like below ;-
`The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)`

### Additional context
If we are using `dotnet new -i Microsoft.AspNetCore.Blazor.Templates` instead of `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04` Blazor will work in VS Code 

Same error will throw in VS Code also

[Get started with Blazor ](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)

**Comment by MikeYeager** [comment]
I'm having this issue. VS 2019 RC2, ASP.NET Core 30 Preview 3. I followed all the steps [here](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio). 

I've installed .NET Core 3.0 Preview 3 SDK.

I've installed the [language extension](https://marketplace.visualstudio.com/items?itemName=aspnet.blazor)

I've run: dotnet add package Microsoft.AspNetCore.Blazor.Templates --version 0.9.0-preview3-19154-02
Later, I also tried: I've run: dotnet new -i Microsoft.AspNetCore.Blazor.Templates 

I've run: dotnet add package Microsoft.AspNetCore.Blazor.Server --version 0.9.0 (since the .Server project seems to have missing NuGet packages).

I've chosen both the Blazor template which gives this error: NU1202	Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

The .csproj file looks like this:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <RestoreAdditionalProjectSources>
      https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
      https://dotnet.myget.org/F/blazor-dev/api/v3/index.json;
    </RestoreAdditionalProjectSources>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.9.0-preview3-19154-02" PrivateAssets="all" />

    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.9.0-preview3-19154-02" />
  </ItemGroup>

</Project>
```
I've tried the Blazor (ASP.NET Core hosted) template which shows all of the NuGet packages missing in the .Server project and has the CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) error in the Client project.

Any help would be appreciated. I can't seem to get anything at all to work.

Mike

**Comment by Sir-N** [comment]
You need to enable preview's of .NET Core. See https://github.com/aspnet/AspNetCore/issues/8074#issuecomment-469333300

**Comment by arun-cm** [comment]
> You need to enable previews of .NET Core. See [#8074 (comment)](https://github.com/aspnet/AspNetCore/issues/8074#issuecomment-469333300)

Already checked, not working.

**Comment by MikeYeager** [comment]
Thank you!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arun-cm.
This should be working with the Blazor 0.9 release. If you still face this issue, with it, please reopen a new issue with updated details and a repro.

**Comment by FerasInfeeny01** [comment]
Did you use App as part of the project's name ? because when i named the project Abc.App (for example), i faced the same problem because there were a conflict in the name that caused this message, so you have to use either the full name of the App class generated automatically or change the project name to avoid creating this namespace, so the issue was not related to Blazor but is related to the usage of the App name with the fully qualified name
