### ISSUE TITLE
Allow robust reconnects when client do not perform graceful disconnects

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8003]
The renderer goes in a “buffering” mode when the client disconnects and spits it back out once it reconnects. In the most common case where the client has a transient network failure, this is what it would look like:

 ```txt
Connection
    | Send diff 1
    | Send diff 2
    | Send diff 3
Disconnected (client network error)
    | Send diff 4
    | Send diff 5
SignalR OnDisconnected is executed
   | Buffer diff 6 
Client reconnected
   | Send diff 6
   | Send diff 7
 ```

SignalR \ Kestrel do not complain if a websocket send failed due to a client error. Consequently, there will be a gap where the server thinks it successfully sent the diffs to the client, but it ended up in the ether. 
 
The fix for this will be that we're going to queue the render batches on the server, and hold onto them until the client can `ACK` each one.

**Comment by pranavkm** [comment]
@SteveSandersonMS: 
> 
> This is definitely a difficult and important problem to solve. Unfortunately, even when we know that some diffs have been lost, recovery is not as simple as “render the affected components again” (e.g., by keeping them in the queue until we get an ACK), because by that stage we have lost the “before” state that the client last knew about, so subsequent diffs will be based on the wrong starting point.
>  
> It’s also not enough to say “well just re-render everything from scratch, and have the client rebuild the UI completely”. This would lead to broken scenarios, e.g., when people are using JS interop to interact with 3rd-party JS libraries. We can’t replay the sequence of calls they have made to the JS libraries, and hence can’t ever reliably recreate the state of the client from scratch. We can only safely do diffs from the known previous state.
>  
> We already do have a system for knowing when the client has acknowledged receipt of a given render batch. We put this in so that we’d know when it was safe to dispose event handlers (we can only do that *after* the client acknowledges that it’s removed all its own references to a given event handler ID, so we know it’s definitely not going to try to raise more events for that handler ID).
>  
> We might end up needing to solve this by actually buffering the binary renderbatch data in a queue that we only remove from when we receive the client’s acknowledgements that it applied each batch. Then on reconnect, we replay everything the client hasn’t yet acknowledged. We’d probably need to introduce some notion of a batch sequence number, so the client can skip repeats of batches it already did apply when it’s the ACK that was lost, not the batch itself.
>  
> Even if we do this, it’s still valuable to have the server switch into a “client is offline, so I don’t do more renders until it comes back” mode, so that we can save memory and CPU time by not actually doing renders and expanding the renderbatch buffer once we know we’re not able to send. So Pranav’s current work is definitely not wasted effort.
>  
> Summary: I think we can solve this, it just needs some more machinery. And I’d be fine with Pranav’s current PR only handling the case where the disconnection was “clean” (i.e., there were no batches in flight, and the server found out about the disconnection before its next render attempt). We’ll have to not promise to customers that the current reconnection logic is robust.
>  
> Maybe with Pranav’s PR we should add a sequence number to render batches so that we can at least detect the “lost diffs” case on the client, and not just have corrupted behaviour in that case.

@javiercn:

> 
> I actually think this is the most straightforward solution. I would draw a parallel with how TCP works:
> •	Batches are stored and sent to the client with a sequence number and the client is responsible for applying them in order and sending acks (which as you mention already does).
> •	The server retries sending  a batch X times before giving up.
> •	We keep a window size Y for each renderer and we put batch entries in that window until we fill it. (At which point we prevent new renders from happening).
> •	When the client acks the next batch in the sequence we slide the window and new space is opened for pending renders to continue.
> 
> For prerendering you simply start disconnected and capture the initial batches. When the client reconnects, from the prerendered state (which we'll do by imprinting the circuit id into the selector tag, retrieving it on the JS side and resuming the connection) you start sending the batches.
> 
> The window ensures limits how much memory we use (framework, individual batch size is always up to the app) and also makes it easy to establish a total memory limit on the set of rendered batches.
> 
>

**Comment by mkArtakMSFT** [comment]
Let's re-evaluate what we want to do here in the future.

**Comment by danroth27** [comment]
We think we're fixing this in preview7 in collaboration with the SignalR folks.

**Comment by javiercn** [comment]
**Render batches**
I believe there are three things that need to happen here.
* Implement queuing for acks in render batches on the client.
  * This is just a matter of queuing and retrying acks from the client.

**JS interop**
* Implement queuing on the server for JS interop calls
  * This is can be done at the RemoteJSRuntime layer.
  * We need to capture "DotNet.jsCallDispatcher.endInvokeDotNetFromJS" calls and queue them.
  * We don't need an ack for them since SignalR is technically guaranteeing that things get delivered in order, and that if a message doesn't get delivered we will know, so processing the messages in a loop should be enough.
  * At some point we need to decide when to give up completely on the circuit if too many calls fail.

**Comment by SteveSandersonMS** [comment]
> This is just a matter of queuing and retrying acks from the client.

It's sufficient to do this only as part of reconnection, isn't it? That is, whenever we first (re)connect, we also send all the ACKs for batches we haven't yet definitely successfully sent an ACK. If so, sounds good!

> We need to capture "DotNet.jsCallDispatcher.endInvokeDotNetFromJS" calls and queue them.

I'm not sure how to interpret this. The responses don't have to be delivered in order, since async calls are meant to be allowed to complete out of order. They must *start* executing in dispatch order, but they can *complete* executing in any order. What do we get from queuing them?

**Comment by javiercn** [comment]
> I'm not sure how to interpret this. The responses don't have to be delivered in order, since async calls are meant to be allowed to complete out of order. They must _start_ executing in dispatch order, but they can _complete_ executing in any order. What do we get from queuing them?

> we also send all the ACKs for batches we haven't yet definitely successfully sent an ACK. If so, sounds good

I believe so


> DotNet.jsCallDispatcher.endInvokeDotNetFromJS

This is the thing that signals the client that the call to a dotnet method has completed (delivers the result) given that all calls are asynchronous they can be delivered in any order (do we simulate sync calls somehow?) but I don't think there's any issue with queuing them and delivering them in the order they arrived (as in the end we need to keep a list of them).

Does that make sense? What I'm trying to say, is that it is an implementation choice.

**Comment by SteveSandersonMS** [comment]
> but I don't think there's any issue with queuing them and delivering them in the order they arrived (as in the end we need to keep a list of them).

I would only add a queuing mechanism if we require it. If you're agreeing that we don't need ordered delivery of these messages, let's not add any unnecessary mechanism for ordering them.

> as in the end we need to keep a list of them

Do we though? I thought that JS interop calls interrupted by a network connection loss would fail, and would deliver an exception (i.e., failed task/promise) back to the caller. We don't want these calls just to hang indefinitely in case they complete minutes later.

**Comment by javiercn** [comment]
> Do we though? I thought that JS interop calls interrupted by a network connection loss would fail, and would deliver an exception (i.e., failed task/promise) back to the caller. We don't want these calls just to hang indefinitely in case they complete minutes later.

I guess we might not need a queue if they get delivered one at a time, but can we have many in flight?

For example:
* async JSInterop call on the client happens server goes and does stuff.
* another async JSInterop call on the client happens, server goes and does stuff.
* Connection goes down while server is busy processing calls. (Messages were delivered, so for all intents and purposes, the client thinks it succeeded on the invocation).
* we try to send completion for A and fail (cuz connection is down)
* we try to send completion for B and fail (cuz connection is down)
* Upon reconection, don't we have to send the completions for A and B?

**Comment by SteveSandersonMS** [comment]
> but can we have many in flight?

Yes, there can certainly be many in flight. We definitely don't want to force async interop to run in a serial way (as in, we wait for completion of A before dispatching unrelated call B), as that would harm perf for no functional benefit.

> Upon reconection, don't we have to send the completions for A and B?

As long as the "connection goes down" event causes the promises/tasks for A and B to fail, either immediately or after a short enough timeout by default, then I think we've covered it correctly already. Sending further messages saying "oh actually BTW it did work" isn't useful because the caller has no way to receive them (their promise/task already finished).

**Comment by javiercn** [comment]
Then it is a matter of adding a timeout to calls on the server and simply throwing an exception that will eventually get rid of the circuit? That seems brittle to me. For example,
JS invokes a dotnet method, connection goes down temporarily, server simply fails to return the result, throws an exception and gets rid of the circuit?
If that's the case, why do we retry resending batches in the first place?

I think it is ok for a JS to dotnet call to fail when sending a message because there is no connectivity, but I don't think it is ok for the server to simply give up if the connection gets lost when its about to return the results. I think the same reasoning applies as for render-batches, where we need to queue "results" and send them back upon re connection.

Otherwise, a simple network drop in a JS interop call leaves you with undefined state or completely crashes the app.

Calling JS from DotNet should follow a similar pattern, perform an invocation with a timeout, if by that time the circuit is connected and hasn't received the response, throw the timeout on the server. (And allow clients to configure the timeout period by passing in a cancellation token or a timeout per call)

If i'm not interpreting this correctly, then, I would ask the question, how resilient do we want to be to connection interruptions.

IMO we want to be able to recover from network interruptions while there are pending renders and while there are JavaScript interop calls in either direction, with a clear timeout for both while the circuit is connected and a timeout when the circuit is disconnected. (After which we clean the circuit on the server)

**Comment by javiercn** [comment]
I've been thinking a bit more about this. I think I've come to realize we don't need to worry that much about the JS interop bits for now.

Having robust rendering reconnects is crucial because the client has no way to get involved in them, as it is the server the one who is in charge of the rendering process.

For the client is not the same though, for a couple of reasons.
* The calls the framework does through JS interop are not important and can be safely retried.
  * Navigation. (If navigation fails you can always "navigate" again.)
  * Dispatching events. (If you fail to deliver a click or a submit, the result is that you get to click again)
* The calls the developer does through JS interop can always be surrounded with a try catch to avoid connectivity errors.
  * On the server you are going to get a timeout after 60 seconds if the call doesn't go through, so you need the try catch.
  * On the client you can always do the same.
  * The biggest disadvantage is that if you make a JS interop call that modifies state and that call throws an exception, you can't be sure that the call went trough. That said, there are a couple of things you can do about it.
  * Design your JS interop operations in pairs of method calls.
    * One that queries the state on the other side of the wire.
    * Other that updates it in an idempotent way.
  * Design your own ack mechanism on top of the connection.

While none of these things is ideal, we can always improve this situation in the future by implementing it at the framework level, and without any breaking change.

With this, what I want to say, is that we should focus simply on making the render reliable and leave the JS interop to the developers.

**Comment by rynowak** [comment]
> Design your JS interop operations in pairs of method calls.
> One that queries the state on the other side of the wire.
> Other that updates it in an idempotent way.
> Design your own ack mechanism on top of the connection.

These all sound like things that will super not happen 😆 - or perhaps shouldn't happen. 

I started by writing about how I think there's a big difference between applications that treat JS interop as:
- A useful tool for building UI interations vs
- A magic teleporter for application state and data

But then I realized that they are often the same thing. If you're using a component library like MatBlazor - what do you do if the call to show a dialog fails, or times out? 

JS Interop can equally be:
- An implementation detail of anything you interact with (you don't know its there)
- On the critical path for your actual experience (showing/hiding a dialog)

I'm not sure how an application author can really reason about JS interop calls that go off into the void when they have been initiated from .NET

**Comment by mkArtakMSFT** [comment]
@javiercn `Done`?

**Comment by javiercn** [comment]
Yes
