### ISSUE TITLE
Blazor (ASP.NET Core Hosted) template fails to load when running in VS with IIS Express

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8060]
Repro steps:
- Create a new Blazor (ASP.NET Core Hosted) template in VS
- Ctrl-F5 the .Server project with IIS Express

Expect result:
- App runs

Actual result:
- Static "Loading..." text appears but the app never loads

Workaround:
- Run with Kestrel instead of IIS Express

**Comment by SteveSandersonMS** [comment]
I was able to repro this and investigated. I believe what happens is that, when you have loaded the Blazor extension (VSIX) into VS, our auto-rebuild mechanism is now causing massive problems. Something in VS/IISExpress must have changed such that our previous logic is now wrong.

Our VSIX now wrecks IISExpress so that it can only handle one or two requests before hanging for 5+ seconds, then each subsequent request makes it hang even longer. Since the Blazor app needs to do about 30 HTTP requests to start up, this would take almost forever.

Plus, this doesn’t just affect Blazor – it affects all ASP.NET Core apps once you’ve loaded the Blazor extension into VS.

We should try to fix it, but if this is deeply nontrivial, we could drop the “Blazor Hosted” auto-rebuild feature for 0.9.0. It didn’t work in 0.8.0 either (though caused less disruption).

**Comment by mkArtakMSFT** [comment]
Closing as this seems to be resolved already.
