### ISSUE TITLE
Slow startup time running a Blazor app from the command line

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8061]
I’m seeing exceptionally long startup times for 0.9.0 Blazor apps that I run from the command-line (~12sec).

SDK version: 3.0.100-preview3-010404
Blazor templates version: 0.9.0-preview3-19128-02

Repro steps:
-	dotnet new blazor
-	dotnet run

On my machine it takes ~10-12sec before the Blazor dev server starts up.

If I instead do ` dotnet blazor serve bin\Debug\netstandard2.0\dist` the app starts up in just a second or two.

I'm seeing similar slow startups for other project types, including console and empty web projects, on the order of 3-5sec, but Blazor stand-alone projects seem to be especially slow to start.

**Comment by SteveSandersonMS** [comment]
Is this really a bug?

It does take ~10s on my machine to do the first build-and-link. Subsequent builds of the same project only take a couple of seconds (on my machine). The subsequent faster builds rely on the Razor Compiler staying in memory and some parts of the build process not having to repeat.

AFAIK, this is no different from how it was in 0.8.0 or before. And is not really a problem because it's only the first build for a given project.

**Comment by danroth27** [comment]
This was reproducing for me consistently on the first blazor project I created with the new bits, but after forcing a non incremental build (`dotnet build --no-incremental`) the problem went away. Subsequent runs only take about 4-5sec on my machine. The time delta does match up with the amount of time or takes to run the linker.   I can only repro this now on the first build of new projects. If we've always been this slow on first run then I think we can close this one as I can't reproduce the original issue anymore.

**Comment by SteveSandersonMS** [comment]
OK, let's close then!
