### ISSUE TITLE
No intellisense for new component parameter in Razor Components template

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8064]
Repro steps:
- Create a new Razor Components project
- Add `IncrementAmount` parameter to `Counter` component
- Try adding a `Counter` to the `Index` component and set the `IncrementAmount` parameter.

Actual results:

![image](https://user-images.githubusercontent.com/1874516/53621911-fefe4080-3bac-11e9-85b3-38ef1a296cc6.png)

This is with VS2019 RC.

**Comment by danroth27** [comment]
The Blazor 0.9.0 templates using .cshtml files don't seem to have this issue.

**Comment by danroth27** [comment]
Workaround is to rebuild the project.

**Comment by SteveSandersonMS** [comment]
Unfortunate, but too late to fix. Not a devastating issue because people will just rebuild.

![image](https://user-images.githubusercontent.com/1101362/53650042-8397a000-3c3b-11e9-89e1-32a9a4bb44ae.png)

**Comment by rynowak** [comment]
We need to update this to include `.razor` files https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs#L106

As well as https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorDynamicFileInfoProvider.cs#L16

We weren't seeing the SFG trigger for components because that was moved into the design time targets, but the design time targets only update when VS ships. 

Compare: 
[release/vs16.0-preview4](https://github.com/aspnet/AspNetCore-Tooling/blob/release/vs16.0-preview4/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets)
[master](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets)

Whomever does this work needs to verify end to end that the fix solves the problem in 16.1 😆

**Comment by NTaylorMullen** [comment]
Will take this on. It's impacting the VSCode experience as well since I share the same code.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore-Tooling/commit/6a83ed13fcb127cae7e89414e878e075352fdbe4
