### ISSUE TITLE
Blazor (ASP.NET Core hosted) 在Azure上发布为“独立”模式异常

### ISSUE THREAD

**Issue by 199621616** [aspnet/AspNetCore#8120]
### Describe the bug
新建一个Blazor(ASP.Net Core hosted)项目，直接使用Azure App Service服务发布配置文件发布此项目，出现以下错误：
未能找到元数据文件“E:\Core30Web\AppHISP40\AppHISP40.Client\bin\Release\netstandard2.0\win-x86\AppHISP40.Client.dll”

### To Reproduce
1. 使用VS2019RC新建Blazor(ASP.NetCore hosted)项目
2. 发布此项目，导入Azure App Service服务发布配置文件
3. 发布——设置——部署模式，修改为“独立”，目标运行时选择“win-x86”,保存、发布
4. 出现以上错误

### Expected behavior
应当可正常发布并自动打开浏览器，展现此项目的正常运行结果 

### Screenshots

![image](https://user-images.githubusercontent.com/25498672/53677487-7508c180-3ceb-11e9-8ced-1f8d19f7a2d9.png)

### Additional context
.NetCore SDK 3.0.100.10184

**Comment by mkArtakMSFT** [comment]
=== Translated using Google Translate ===
### Describe the bug
Create a new Blazor (ASP.Net Core hosted) project and publish the project directly using the Azure App Service service release configuration file with the following error:
Failed to find metadata file "E:\Core30Web\AppHISP40\AppHISP40.Client\bin\Release\netstandard2.0\win-x86\AppHISP40.Client.dll"

### To Reproduce
Steps to reproduce the behavior:
1. Create a new Blazor (ASP.NetCore hosted) project using VS2019RC
2. Publish this project and import the Azure App Service service publishing configuration file.
3. Release - set - deployment mode, modified to "independent", select "win-x86" when the target is running, save, release
4. The above error occurred

### Expected behavior
Should be able to publish and automatically open the browser to show the normal operation results of this project

### Screenshots

![image](https://user-images.githubusercontent.com/25498672/53677487-7508c180-3ceb-11e9-8ced-1f8d19f7a2d9.png)



### Additional context
.NetCore SDK 3.0.100.10184

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @199621616.
What is the `deployment mode` of the application, when you publish it?
You can find the `Deployment mode` setting in the `Publish` dialog, see sample at: https://msdnshared.blob.core.windows.net/media/2018/09/image97.png

**Comment by 199621616** [comment]
![default](https://user-images.githubusercontent.com/25498672/53693180-d908b400-3dd7-11e9-86b1-7207457e425d.png)
@mkArtakMSFT 感谢您回复了这个情况。我说的重现中第3条，就是这个发布窗口
3.发布 - 设置 - 部署模式，修改为“独立”，目标运行时选择“win-x86”，保存，发布
发布的目标框架：netcoreapp3.0并且没有其它可选项，您上面发布窗口目标框架是netcoreapp2.1。
部署模式：独立
目标运行时：win-x86

**Comment by 199621616** [comment]
Blazor 0.8.0发布后，这个项目就一直不能正常发布到Azure。无论是使用VS2019的预览版本还是使用刚刚发布的VS2019 RC。
Razor Components可以正常发布。

**Comment by 199621616** [comment]
更新VS2019 RC1 SVC1、.NetCore 3.0.100.10431、Blazor 0.9.0后，此问题仍然存在。

![default](https://user-images.githubusercontent.com/25498672/54017153-17c7b100-41c0-11e9-9731-5aca86d0fbb4.png)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by 199621616** [comment]
![image](https://user-images.githubusercontent.com/25498672/57498782-d498d400-730f-11e9-8be4-a50bffce8bbb.png)

Asp.Net Core 3.0 Preview5仍然不能正常发布

**Comment by 199621616** [comment]
tmpD091.tmp的内容为：
2019-05-10 10:34:55
System.AggregateException: 发生一个或多个错误。 ---> System.Exception: 生成失败。检查输出窗口了解更多详细信息。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 Microsoft.WebTools.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__3()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__176.MoveNext()
---> (内部异常 #0) System.Exception: 生成失败。检查输出窗口了解更多详细信息。<---

===================

**Comment by 199621616** [comment]
今天发现，即便发布到本地文件选择部署模式为“独立”模式时，同样发生此情况。

重现行为的步骤：
1、使用VS 16.1.0 Preview 3.0新建Blazor（ASP.NetCore托管）项目
2、发布 - 设置 - 部署模式，修改为“独立”，目标运行时选择“赢-86”，保存，发布
出现以上情况
