### ISSUE TITLE
[Blazor] Get the detailed response body when SendJsonAsync failed

### ISSUE THREAD

**Issue by sunshiyun** [aspnet/AspNetCore#8148]
I'm am trying to pass error messages from server to client when the model value is invalid or other server error occurs, but I'm not sure if it is possible using GetJsonAsync/PostJsonAsync/PutJsonAsync.

For example, I tried this:

        protected async Add SaveEmployee()
        {
            var res = new HttpResponseMessage();
            res = await Http.PostJsonAsync<HttpResponseMessage>($"employee/{EmployeeModel.EmployeeControllerName}", employee);
            if (res.IsSuccessStatusCode)
            {
                UriHelper.NavigateTo($"employeelist?company={companyId}");
            }
            else
            {
                var message = await res.Content.ReadAsStringAsync();
                // Show the message
            }
        }

But the response seems not able to be parsed as a HttpResponseMessage object.
Should I serialize json everytime and use SendAsync instead of SendJsonAsync? Or is there any better way?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sunshiyun.
You're actually on the right track:
 >Should I serialize json everytime and use SendAsync instead of SendJsonAsync?
That's exactly how you should do it.

**Comment by dga711** [comment]
Sorry to reopen this, but I now hit this thing too and I don't understand why it is that way. What is the thinking behind it? In my opinion it leads to bad practices when it is the promoted way of doing things.

Often when an API returns error codes (and not 200) it provides details in the body. An error without explanation is bad practice imo.

Now i have two options:

1. The one which is the "solution" provided in this issue
2. Many blogs on the web promote to have a response object which contains a property like "statusCode". BUT the response header will then still be 200. Which I think is bad API design if it is also public facing.

**Comment by AaronLS** [comment]
This has been a problem going back to WCF.  I support alot of legacy web services and when external clients get a failure like "content-type expected" and they can't see the real response, troubleshooting is difficult.  Asking people to run fiddler on a production server so they can capture their client requests or change code to log the response is difficult.  I really wish just shoving the actual raw response into the exception message was standard.  Maybe truncated at a certain number characters, you'd at least get some hint of the real reaponse.

Depending on the type of request, getting the raw response requires alot of extra code.  Sometimes you have to seek to the beginning of the response stream to pull the raw response.  You might get additional exceptions in this code, so you need nested try/catch to avoid a second exception being thrown that would prevent the first from bubbling up to be logged properly.

These days any client/server interaction I write usually I end up spending more time with the code to handle an exception and gather enough information into logs to be able to see raw responses.

Yes response could contain sensitive information, but exceptions already have the potential to contain sensitive information.  It's up to the developer to ensure exception detail isn't bubbled out to a context where it is revealed.  Since that's already an exception, we already know to trap exceptions at the user edge, log them, and show a generic error.

Adding the raw response into an exception, doesn't reveal any sensitive information.  You're in the context of the client, the response already exists within the client in so me form, and adding it to the exception doesn't expose that information to any new context it isn't already available in.  It just saves us from having extra code to pull it out and make sure it's logged so we can troubleshoot properly.

**Comment by AaronLS** [comment]
If the answer is, don't use the Json flavor of the method and do json deserialization as a second step, why even have the json method?  We should be able to write the code properly using the intended approach, but have a mechanism to easily get the raw response whenever a json parse failure occurs.
