### ISSUE TITLE
UseAngularCliServer adds --port {portnumber} to script by default!

### ISSUE THREAD

**Issue by Ahmed-Habbachi** [aspnet/AspNetCore#8162]
### Describe the bug
UseAngularCliServer adds --port {portnumber} to script by default!
this should be an option not an obligation, i want to run my npm script without adding --port at the end of my script

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Ahmed-Habbachi.
Can you please share more details regarding where do you specify the port yourself?
The logic in the Angular middleware automatically finds an available port and uses that for starting the Angular CLI behind the scene.

**Comment by Ahmed-Habbachi** [comment]
i use it in an electron + angular + asp.net core project for UI stuff and i have a ready to use script that allow me to start angular and electron and this UseAngularCliServer i use it as a work around to run my script. as i didn't find any way to do it differently.
my script is: 
"start": "npm run postinstall:electron && npm-run-all -p ng:serve electron:serve"
so at the end of the command UseAngularCliServer adds --port {portnumber} wich is unneeded for me.

**Comment by Ahmed-Habbachi** [comment]
i found a work around to use the passed --port to my built script and use it to start my electron project

**Comment by mkArtak** [comment]
Glad you found a way to solve the problem you are facing. Should this issue be closed then?

**Comment by Ahmed-Habbachi** [comment]
yes sure it can be closed, but it is nice i think to make it optional to add or not, maybe someone want to use the default 4200 and it is hard coded in his settings.

**Comment by flensrocker** [comment]
My usecase for a specific port for `UseAngularCliServer`:

I have one multi-tenant Angular-app which is served on different base-urls, so each tenant has its own url like http://localhost/tenant-1 and http://localhost/tenant-2.

Since the `index.html` is generated by `ng` I have to read it from the ng-server to serve it with a MVC controller on the different routes. I can't use the from a `ng build` pre-generated `ClientApp/dist/tenant/index.html` because on `ng serve` there are only script tags like `runtime.js` instead of `runtime-es5.js` and `runtime-es2015.js`.

The `index.html` contains no base href, it is generated at runtime by the angular app with `{ provide: APP_BASE_HREF, useValue: "/" + (window.location.pathname.split("/")[1] || "") }`

The correct urls for the script-tags are ensured with a `"deployUrl": "/tenant/"` in `angular.json` and there's also the port-setting in `serve:options`.

```
routes.MapRoute(
   name: "tenantapp",
   template: "{urlprefix}/{*urlargs}",
   defaults: new { controller = "View", action = "Index" });

...

private IHostingEnvironment _env;

public async Task<IActionResult> Index(string urlprefix, string urlargs)
{
  if (_env.IsDevelopment())
  {
    var proxy = new System.Net.Http.HttpClient();
    var index = await proxy.GetAsync("http://localhost:4302/tenant/index.html");
    var indexStream = await index.Content.ReadAsStreamAsync();
    return File(indexStream, "text/html");
  }
  return PhysicalFile(System.IO.Path.Combine(_env.ContentRootPath, "ClientApp", "dist", "tenant", "index.html"), "text/html");
}
```
Currently this only works with `UseProxyToSpaDevelopmentServer` where I can define the specific port.

Additionally there are more Angular apps in this project, which are all served on there own ports.

At least disabling the use of a dynamic port would help.
