### ISSUE TITLE
Update the health check endpoint route builder extensions to make the endpoint display name configurable.

### ISSUE THREAD

**Issue by CBaud** [aspnet/AspNetCore#8359]
### Is your feature request related to a problem? Please describe.
In ASP.NET Core 3.0 Preview 3, the health check endpoint route builder extensions specify a common display name ("Health checks") for all health check endpoints.

### Describe the solution you'd like
It would be helpful if the extensions allowed the display name to be configurable by the service. For example, a service running on Kubernetes may have two separate health check endpoints for the liveness and readiness probes.

### Describe alternatives you've considered
The alternative would be to manually configure the health check endpoints in my service.

**Comment by rynowak** [comment]
Thanks @CBaud 

FYI I'm not sure you saw my follow up PR - we decided to make this part of the builder returned from `MapHealthChecks`. So this is uniform across all endpoint routing stuff and won't be missed when we add future router-ware. Just mentioning because we ended up not going with your fix. I appreciate that you make the effort and I don't want you to think we don't appreciate it.
