### ISSUE TITLE
Centralize Java aquisition/usage

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#8417]
The installation of Java on a machine is a constant pain for us. Java updates seem to delete all the jdks every time they run, making JAVA_HOME and the PATH out of date. Some scripts seem to expect JAVA_HOME to be set to "%PROGRAMFILES%\Java" while others expect "%PROGRAMFILES%\Java\jdk-[version]". But then we also need it on the path for selenium tests. Coordinating this across our different CI systems and feature areas has not been working, so we need to come up with a coherent plan.

I would suggest that if at all possible we stop assuming any machine state related to java. Any process which needs Java should depend on some "EnsureJava" target which downloads the proper jdk and returns the directory it's in. Where possible we shouldn't (permanently) edit the PATH.

**Comment by natemcmaster** [comment]
_Build Team Triage_: closing as we don't plan to take additional action on this. The master branch already contains a script, InstallJdk.ps1, which Azure Pipelines builds already invoke, and users can run if they don't want to rely on on a machine-wide version of Java. We welcome PRs to improve this script if it's insufficient for your needs.

Updating our other CI systems that use a repo-local version of Java instead of machine-wide is tracked in https://github.com/aspnet/AspNetCore-Internal/issues/1946
