### ISSUE TITLE
ASP.NET Core 3 Preview 3 React template does not handle token expiry

### ISSUE THREAD

**Issue by loop-evgeny** [aspnet/AspNetCore#8432]
### Describe the bug
If you log into an app based on the "SPA with authentication" (React) template in ASP.NET Core 3.0 Preview 3 and let the token expire (which takes an hour) the client-side app does not handle this well - it displays "Loading..." forever.

### To Reproduce

1. Follow the steps in #8405 including fixing the `populateWeatherData()` code.
2. Run the app, create an account and log in.
3. Stop the app for over an hour.
4. Run the app again and click on Fetch data.

The page shows "*Loading...*" forever and the developer console displays the same 2 errors as in #8405. However, this time the response headers are different:

`WWW-Authenticate: Bearer error="invalid_token", error_description="The token is expired"`

(I've also seen: `WWW-Authenticate: Bearer error="invalid_token", error_description="The signature is invalid"` but haven't been able to repro that one.)

### Expected behavior
1. When the request fails for any reason an error is displayed on the page instead of "Loading..."
2. The request does not fail due to the token expiring - either it's refreshed automatically or the user is prompted to log in.

### Screenshots
Same as in #8405

**Comment by loop-evgeny** [comment]
Interestingly, I can still view my user profile and download personal data from /Identity/Account/Manage/PersonalData - this doesn't seem to send a Bearer authentication token. I guess it relies on the cookie instead.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @loop-evgeny.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
> (I've also seen: `WWW-Authenticate: Bearer error="invalid_token", error_description="The signature is invalid"` but haven't been able to repro that one.)

This is probably because you cleaned up your repo. We store the development key by default in the obj folder so that it doesn't get checked-in by accident so if you clean the repo you need to reauthenticate.

In general, on every call-site where you use the token you need to handle possible 401s as in real scenarios keys rotate, tokens get repudiated, etc. We don't include code in the template to specifically handle this scenario, but we would gladly accept a PR for it.

The flow is as follows:
1. Send the request including the token.
2. If the response comes back 401.
    2.1 Save any current state on the page you want to preserve.
    2.2 Redirect to the login component ``window.location.href = `${ApplicationPaths.Login}?${QueryParameterNames.ReturnUrl}=${encodeURI(window.location.href)}`; ``
3. When you come back from the login flow you should have a new valid token.
   3.1 Reissue the request and it should succeed
