### ISSUE TITLE
T4 templates not working as they did with full framework

### ISSUE THREAD

**Issue by AndersMalmgren** [aspnet/AspNetCore#8456]
### Describe the bug
Accesing types in Core class library with t4 templates.  Using VisualStudio helper you could do in .NET framwork class library

VisualStudioHelper		
		.CodeModel
		.GetAllCodeElementsOfType(project.CodeModel.CodeElements, EnvDTE.vsCMElement.vsCMElementClass, false)

Which would give you all declared classes in  that project. This does not work in core you need to set the boolean to true

/// <param name="includeExternalTypes">If set to true objects that are not part of this solution are retrieved, too. E.g. the INotifyPropertyChanged interface from the System.ComponentModel namespace.</param>

This iterates the entire solution and is crazy slow. It shouldnt be required to access the types in your defined project.

The VisualStudio helper is part of the Tangible T4 Editor
But the source can also be found here

https://github.com/AndersMalmgren/T4TemplateExample/blob/master/MyApp.Web/VisualStudioHelper.ttinclude

Or are there better ways of templating things at desgintime (not runtime) in ASP Core?

**Comment by Eilon** [comment]
Hi @AndersMalmgren ,

To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by AndersMalmgren** [comment]
I dont think its a problem with VS but the types under the EnvDTE namespace does not work correctly when you target a Core project.

**Comment by Eilon** [comment]
Hi @AndersMalmgren ,

The EnvtDTE namespace and the project system used for .NET Core projects is all part of Visual Studio, so I think it would still be the right place.

**Comment by AndersMalmgren** [comment]
I created a cli project instead. works good
