### ISSUE TITLE
Logged-in state is not consistent between Fetch data page and account management pages in React app with authentication in ASP.NET Core 3 Preview 3

### ISSUE THREAD

**Issue by loop-evgeny** [aspnet/AspNetCore#8468]
### Describe the bug

In a React app with authentication created using ASP.NET Core 3 Preview 3 when I click "Logout" on my account profile page I seem to be logged out there, but still logged in on the home page and "Fetch data" page.

### To Reproduce

1. Using ASP.NET Core 3.0 Preview 3 create a new project with `dotnet new react --auth Individual`
2. Apply the various workarounds at https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md
3. Run the app.
4. Click "Register" and complete the registration form (or log in with an existing account).
5. Click on "Hello youremail@..." in the header to go to /Identity/Account/Manage
6. Click "Logout" in the header on that page. You should be redirected back the homepage.
7. Observe that the header still says "Hello youremail@..." and shows a "Logout" link.
8. Click "Fetch data" in the header - the Weather forecast page is displayed, so you are indeed still logged in.
9. Click on "Hello youremail@..." in the header again. You are now prompted to log in, so you are not logged in on /Identity/Account/Manage.

### Expected behavior
When I click "Logout" on any page I am logged out for the entire application.

Note that the reverse is not true - when I log out from the home page and browse to /Identity/Account/Manage I am prompted to log in, as expected.

**Comment by guyng** [comment]
Had similar issue regarding token expiry but with the angular auth template (issue #8598).
Looking forward to hear news regarding this issue from asp.net team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @loop-evgeny.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
This is by design.

The app and the IdP happen to be on the same domain, but from a security point of view are independent.

When you log out from /Identity/Account/Manage you are logging out from identity compared to when you are logging out from the SPA where you are loging out from the SPA which in turn logs you out from the IdP.

This is similar to what happens when you log in through google/fb into a site and then go to Facebook/google and logout from the site.

After that you are no longer logged in on google/fb but if you go to the original site you are still logged in.

Hope this helps.

**Comment by loop-evgeny** [comment]
OK, that makes sense now that you explain it, but it was completely non-obvious before. I'm sure I won't be the only one confused by this. It might be helpful to distinguish these in the UI somehow, e.g. label the links "Logout from (app)" and "Logout from IdP" or something like that.
