### ISSUE TITLE
Make it easier to return Problem Details responses for server errors

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#8537]
Add a set of new Problem helper methods on `ControllerBase`, that populates a `ProblemDetails` type with relevant values for simple returning of errors through the MVC response pipeline, e.g.:

``` csharp
private ObjectResult Problem()
{
    return Problem(detail: null);
}
 
private ObjectResult Problem(string detail)
{
    var problemDetails = new ProblemDetails
    {
        Title = "An error occurred while processing your request.",
        Detail = detail,
        Status = 500
    };
 
    problemDetails.Extensions.Add("traceId", Activity.Current?.Id ?? HttpContext.TraceIdentifier);
    return Problem(problemDetails);
}
 
private ObjectResult Problem(ProblemDetails problemDetails)
{
    return new ObjectResult(problemDetails) { StatusCode = problemDetails.Status };
}
```

@rynowak

**Comment by thomaslevesque** [comment]
I was looking for something like this today.

Currently, there's no convenient way to return a problem details response with the ability to specify the title/detail/instance/etc. Methods like `NotFound()`, ` BadRequest()`, etc produce a `ProblemDetails` with a default title and no detail.

A `Problem()` method would indeed be very useful. I think an overload that accepts the status code would be useful too, since you might want to return problem details for errors other than 500.

---

**Suggestion:** also create a `ProblemDetailsResult` class, which could handle things like:
- adding a `traceId`
- setting appropriate content types (`"application/problem+json"` and `"application/problem+xml"`)
- setting `title` and `type` to default values if they're not set

All these things are currently done in the default `InvalidModelStateResponseFactory` and in `ProblemDetailsClientErrorFactory`

---

**Comment by thomaslevesque** [comment]
BTW, I'm interested in implementing this, if there isn't someone already working on it.

**Comment by khellang** [comment]
> * setting appropriate content types (`"application/problem+json"` and `"application/problem+xml"`)

This is already done for you, if you use an `ObjectResult`:

https://github.com/aspnet/AspNetCore/blob/5ca92305c2e6452e2add9a2eb115963896c6fe85/src/Mvc/Mvc.Core/src/Infrastructure/ObjectResultExecutor.cs#L135-L139

**Comment by thomaslevesque** [comment]
Oh, nice! Thanks @khellang
