### ISSUE TITLE
SelectTagHelper sets 'multiple' property to true when asp-items is IEnumerable.

### ISSUE THREAD

**Issue by SRQcoder** [aspnet/AspNetCore#8579]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by SRQcoder** [comment]
When binding the select tag helper with `asp-items` set to an` IEnumerable` (a list of items for example), the resulting html code generates `multiple="multiple"`. While this allows for a multiple selection of items, it doesn't afford the more common use of just wanting to select one item from the list.

The property multiple should be optional. And just because there are multiple inputs, (IEnumerable), that doesn't mean we want to select multiple items.

**Here is the code:**
![image](https://user-images.githubusercontent.com/8331811/54465569-3135a380-4752-11e9-9202-851503307668.png)


**Here is the output** (using bootstrap 4 css library)
![image](https://user-images.githubusercontent.com/8331811/54465531-f6cc0680-4751-11e9-8c99-2c40d5905fc1.png)

I believe the output should look identical - but it's impossible to remove the `multiple = "multiple"` property.

It seems like this is the wrong usage for `multiple`. 

![image](https://user-images.githubusercontent.com/8331811/54465640-883b7880-4752-11e9-832d-b8ab931c6d2d.png)

**Comment by SRQcoder** [comment]
Sorry, hit the wrong button -- first time user

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SRQcoder.

The `asp-for` attribute is intended for getting the selected item(s) back from the client on a post back. 
If you intend to have a single-only selection option, the `asp-for` should refer to a non-enumerable property: a `string` as an example, which will include the value of the selected item on the post-back.
Otherwise, if you intend to allow multiple select (and this is what you're doing in your code above) `asp-for` should point to a property of `IEnumerable` type. As this is intended to represent the list of selected items, in a multi-selection mode that must be an enumerable.
Hope this helps.

**Comment by SRQcoder** [comment]
Yes, this did help. I did not realize 'asp-for' mapped to the return type. Thank you for your help.
