### ISSUE TITLE
Identity Library fail to choose the Data context class and User Class in Add Identity Window

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#8617]
### Describe the bug
Identity Library fail to choose the Data context class and User Class in Add Identity Window while add scaffold.

### To Reproduce
1. Using this version of ASP.NET Core '2.1'
2. VS 2017 -> Create a new Asp.Net Core Web Application(MVC)
3. Add new class below:

`ApplicationDbContext`
```
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
```
`ApplicationUser`
```
    public class ApplicationUser : IdentityUser
    {
    }
```

4. Right Click Project->Add Scaffold->Identity->Check Data context class select and User Class

5. There are no `ApplicationDbContext` for  Data context class  and `ApplicationUser` for User Class

### Expected behavior
I could choose `ApplicationDbContext` and `ApplicationUser` to generate the identity files.

### Screenshots
![image](https://user-images.githubusercontent.com/16079555/54509430-7b9e6680-4984-11e9-9453-b7a5a411cd89.png)

**Comment by blowdart** [comment]
@Eilon can you move this to tooling please?

**Comment by Eilon** [comment]
To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
