### ISSUE TITLE
Add docker file in VS2019 preview 4.2 adds the wrong image

### ISSUE THREAD

**Issue by regisbsb** [aspnet/AspNetCore#8621]
### Describe the bug
A clear and concise description of what the bug is when you click add Docker to ASP.net core website in Visual Studio 2019 preview 4.2 it adds a old docker hub images

### To Reproduce
1. Using this version of ASP.NET Core 3.0 preview 3
2. Add docker
3. Adds old docker hub not mcr

### Expected behavior
The new docker file to have mcr addreses

### Additional context
Include the output of `dotnet --info`

**Comment by muratg** [comment]
@glennc @shirhatti do you guys know where docker tooling bugs go to?

**Comment by Eilon** [comment]
To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
