### ISSUE TITLE
Adding Identity breaks Authentication using OAuth

### ISSUE THREAD

**Issue by jessehallam** [aspnet/AspNetCore#8651]
### Describe the bug

When `IServiceCollection.AddAuthentication().AddFacebook()` is used, the user is populated with Facebook details after a Challenge sequence. When `IServiceCollection.AddIdentity()` is put in the mix, this breaks OAuth completely.

### To Reproduce
1. ASP.NET Core 2.1 or greater
2. [Minimal example](https://github.com/jessehallam/aspnetcore-oauth-with-identity-bug-report)

### Expected behavior
When `services.AddIdentity` is omitted, the JSON output for route `/` is predictably the following:

    {"isAuthenticated":true,"name":Jesse Hallam,"authenticationType":"Facebook"}

### Unexpected behavior
When `services.AddIdentity` is put back in the mix, this "breaks" the OAuth flow in some undocumented way, and the JSON output is becomes:

    {"isAuthenticated":false,"name":null,"authenticationType":null}

**Comment by jessehallam** [comment]
When Identity is in, a (Facebook) OAuth flow results in an `Identity.External` cookie being sent. Is there something specific that should be done to get the external user out of the cookie?

**Comment by blowdart** [comment]
Without seeing a minimal example of what you're doing here, or indeed what you're expecting its rather hard to help.

But identity is meant to be (nearly) the sole source of truth in an app. Facebook users would have to register a local account into identity in the default scenarios, and then the login flow would go through identity again to map to the local user, rather than have external auth providers.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
