### ISSUE TITLE
Razor Components: How to reason about Client Connections?

### ISSUE THREAD

**Issue by dom3d** [aspnet/AspNetCore#8684]
**### Is your feature request related to a problem?**
It's probably a **feature request** unless there is a way to achieve this and I haven't found it yet.

**### Describe the problem**
I'd like to create real-time multi-user experiences using Razor Components. I found a way to get the real-time aspect working but not how to understand (from within components or services) who is connected and who is currently running the component rendering pass. With 'who' i mean something like a 'Client Connection ID'.

Moreover I didn't find public hooks to listen for disconnects and reconnects.

I don't need this to work in a multi-server setup, i am more interested in single server (prototyping anyways) and I feel the multi-server setup is something I could solve and I don't need the framework to handle it magically for me.

**### Describe the solution you'd like**
Ability to query:
- Who is connected (list of IDs, e.g. Circuit IDs)
- Who is disconnected
- What is the client ID currently executing the component, so I can get or update data stored services by using the client ID as key
- Idle time per connected client
- Disconnected time per client

Ability to listen to events for
- new connections
- reconnections
- disconnections
e.g. from a service and getting the connection ID passed into the event handler

**### Describe alternatives you've considered**
I tried to use the object hash from the component instance being rendered in order to assign IDs to viewers but that's not a reliable option.

I am new to ASP and Razor Components. I searched the web for examples, but didn't find any. Plus I looked at the sources and I see **_CircuitRegistry_** and **_CircuitHandler_** seem to deal with these aspects but they also seem for internal use only.

I had a look at a roadmap-issue here posted on github and multi-user aspects doesn't seem to be listed there, thus i am posting here.

**### Additional context**
I am using Services to in-memory cache data between users. I am using timers / StateChanged to refresh changes from any user interacting with the page/component, so it updates in real-time to all users. That works nicely with very little code. Feels like an API that allows me to query client information would allow at lot of cool stuff with little code.

The requested API would be useful for
- fast prototyping of any idea including multi-user and real-time
- scenarios:  multi user games, all kind of collaborative real-time tool

**Comment by SteveSandersonMS** [comment]
You can know if a user has connected because your root component's `Init` will be called, and you'll know if they have disconnected when your root component's `Dispose` is called. Using these you can track the total number of connected users, track them all in a list, have them all subscribe to some global event, assign each of them a unique ID, etc.

Do you think this covers your scenarios? If there are cases where there's absolutely no way to do what you want, please let us know. Or if there are cases where you can technically do something but it's not as convenient as if the system did it for you automatically, that's also worth knowing.

I'll close this because I think the mechanisms already exist, but we can reconsider if I'm misjudging this.
