### ISSUE TITLE
Vsix project based on .net core ?

### ISSUE THREAD

**Issue by mustafasaaed** [aspnet/AspNetCore#8741]
Is there a vsix project that is based on .net core?
If not can I used the already existed vsix project to reference a .net core projects ?

Thanks in advance

**Comment by Eilon** [comment]
Hi @mustafasaaed , this repo is about ASP.NET Core.

To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
