### ISSUE TITLE
Blazor: IJSRuntime.InvokeAsync serialization broken for arrays of objects

### ISSUE THREAD

**Issue by oliversturm** [aspnet/AspNetCore#8743]
I have a simple JavaScript helper:

```js
window.debugOut = (content) => {
  console.dir(content);
}
```

On the Blazor side I have this type:

```cs
public class City
{
  public string CityName { get; set; }
  public int Population { get; set; }
}
```

If I call the JavaScript `debugOut` and pass a `List<City>`, this arrives correctly on the browser side:

```cs
await Js.InvokeAsync<bool>("debugOut", new List<City> {
  new City{CityName="London",Population=8000000 },
  new City{CityName="Edinburgh", Population=400000 }
});
```

![image](https://user-images.githubusercontent.com/4730969/54839437-c42a8c80-4cc2-11e9-97be-88592d62b101.png)

**But if I use an array type instead, the browser only sees the first object:**

```cs
await Js.InvokeAsync<bool>("debugOut", new City[] {
  new City{CityName="London",Population=8000000 },
  new City{CityName="Edinburgh", Population=400000 }
});
```

![image](https://user-images.githubusercontent.com/4730969/54839532-f0dea400-4cc2-11e9-8fe0-5d29305178c8.png)

Serialization works correctly with an array of simple values. **The problem seems to occur only with arrays of objects.**

```cs
await Js.InvokeAsync<bool>("debugOut", new int[] { 1, 2, 3 });
```

![image](https://user-images.githubusercontent.com/4730969/54839621-2f745e80-4cc3-11e9-8b1a-d72a2cbe4f62.png)

**Comment by SteveSandersonMS** [comment]
This is because `InvokeAsync` accepts `params object[] args`, and since you're passing an array, the compiler treats it as if you want each array entry to be a separate top-level entry in `args`. What you want instead is for `args` to be an array containing only one top-level entry, which itself is your array.

This is the nature of `params` in C# in general. For more info, see https://stackoverflow.com/questions/36350/how-to-pass-a-single-object-to-a-params-object

To override what the compiler does here, consider casting to `object`, e.g.:

```csharp
await Js.InvokeAsync<bool>("debugOut", (object) new City[] {
  new City{CityName="London",Population=8000000 },
  new City{CityName="Edinburgh", Population=400000 }
});
```

This will have no runtime cost and will give the parameter filling behavior you want.

**Comment by oliversturm** [comment]
Nice one, I didn't think of that. I guess I don't work with arrays much in real life :)
