### ISSUE TITLE
Unexpected asset names for some of ASP .Net Targeting Pack assets

### ISSUE THREAD

**Issue by johnbeisner** [aspnet/AspNetCore#8835]
At the aspnetcore "3.0.0-preview4-19172-03" blob storage drop point: https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/3.0.0-preview4-19172-03

Some assets appear to be inconsistent with current naming conventions:
aspnetcore-targeting-pack-3.0.0-preview4-19172-03.deb
aspnetcore-targeting-pack-3.0.0-preview4-19172-03.tar.gz
aspnetcore-targeting-pack-3.0.0-preview4-19172-03.zip

I expected the assets' names to be:
aspnetcore-targeting-pack-3.0.0-preview4-19172-03-x64.deb [see the RPM asset name]
aspnetcore-targeting-pack-3.0.0-preview4-19172-03-linux-x64.tar.gz
aspnetcore-targeting-pack-3.0.0-preview4-19172-03-win-x64.zip
aspnetcore-targeting-pack-3.0.0-preview4-19172-03-win-x86.zip

**Comment by JunTaoLuo** [comment]
cc @dougbu @mkArtakMSFT can you guys please assign?

**Comment by dougbu** [comment]
@johnbeisner this issue is similar to #8806. Could you please help us understand the priority and urgency of this issue?

**Comment by johnbeisner** [comment]
@dougbu
There is no urgency for this as we have implemented a work-around: https://github.com/dotnet/core-sdk/pull/1122

**Comment by dougbu** [comment]
@anurse or @mkArtakMSFT I suggest we put this into a late-ish 3.0 milestone as a P1 or P2 bug.

**Comment by nguerrera** [comment]
I don't think it should be necessary to separate the targeting pack installers on non-Windows by RID / architecture. On Windows, the whole `dotnet` directory installs to different locations based on architecture, but I don't think we ever have this situation on non-Windows.

**Comment by nguerrera** [comment]
It is weird, though, if RPM and deb have different conventions.

**Comment by wli3** [comment]
On another side. Since there is no "feed" and we only have a flat folder with installers. The only way to discover the latest aspnet produced installers is by naming convention. It is extra complexity for some aspnet deb file has "x64" and some doesn't even though the content is agnostic.

**Comment by dagood** [comment]
I think making the change in this direction is the wrong way. The Windows installers are the odd ones, due to side-by-side x86/64 installs. Core-Setup should change instead.

Adding `x64` to the names of the arch-agnostic artifacts (in particular Linux) could even go all the way to confuse end users. If someone wants to install an `arm` SDK from `deb` files, they would have to grab the deb named `aspnetcore-targeting-pack-3.0.0-preview4-19172-03-x64.deb`. They might assume `x64` is a typo and look for an `arm` artifact which doesn't exist. (Then complain.)

Instead, I think we should drop the arch in Core-Setup for non-Windows Targeting Pack installers/packages. Not that I think it's urgent in that direction either.

**Comment by natemcmaster** [comment]
Triage: Closing as won't fix. The naming here is intentional. Targeting packs are not RID, or even CPU arch, specific, so the RID was not included in the file name.

If targeting packs for NETCore.App or WindowsDesktop have RIDs in the file name, I would recommend they be removed for consistency.

cc @dagood

**Comment by natemcmaster** [comment]
Forgot to mention -- I'm fixing the RPM for aspnetcore so it doesn't include "-x64". See https://github.com/aspnet/AspNetCore/pull/10593
