### ISSUE TITLE
Optional parameters signalr

### ISSUE THREAD

**Issue by BlueDragon709** [aspnet/AspNetCore#8853]
Using AspNetCore 2.2.

I have a server side function that accepts a optional parameter.
But when iI call this function from the client and not implementing this parameter i get a error:

`
Failed to invoke hub method "MethodThatIamCalling"
System.IO.InvalidDataException: Invocation provides 1 argument(s) but target expects 2.
 at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JArray args, IReadOnlyList'1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
`

And the function isn't completed.

Even though C# allows for optional parameters.

**Comment by mikaelm12** [comment]
We don't currently have plans to support optional parameters on the client. The hub protocol layer on the clients currently require an exact match of parameters otherwise you'll get the argument binding failure that you posted above. A solution for this could be to create your own data type and pass that around. Then you can include/exclude what ever you want without having to create separate client handlers.
