### ISSUE TITLE
Razor Components: OnParametersSet gets invoked again and again when parameters of non-trivial types exist

### ISSUE THREAD

**Issue by springy76** [aspnet/AspNetCore#8872]
Using 3.0 preview-3 and this sample: https://github.com/springy76/RazorComponentsProblems/blob/problem/OnParametersSetGetsInvokedTooOften/WebApp/Components/Pages/Counter.razor

Problem:
Clicking the "click me" button on the counter page shows that non-related components bound to unchanged values get triggered their `OnParameterSet` method when the `[Parameter]` attributed property is of non "non-trivial" types,

Works (only **one** initial OnParameterSet):
bool, bool?, byte, byte?, sbyte, sbyte?, char, char?, decimal, decimal?, double, double?, float, float?, int, int?, uint, uint?, long, long?, ulong, ulong?, short, short?, ushort, ushort?, string, System.DateType, Nullable<System.DateType>.

Works **not** (OnParametersSet gets called **again and again and again** for every `StateHasChanged()` of the **surrounding** component):
Everything else, no matter if the class or struct implements `IComparable<T>`, `IComparable`, `IEquatable<T>`, `IConvertible`, `IFormattable` or overrides `GetHashCode()` or static == and != operators -- or all of them.

Surprisingly System.DateTime -- which is not an integral/aliased type -- works without hassle , and all nullables of such simple types work too, including string.

**Comment by SteveSandersonMS** [comment]
This is precisely the design. For any parameter type where we can't guarantee that the value hasn't mutated, we have the recipient re-render (because the output may change).

There is a method you can override on your component - `ShouldRender` - to override the logic about whether the parameter values should be treated as different or not.

**Comment by springy76** [comment]
How should ShouldRender know when to return true or false without managing dirty flags for every single parameter, including backing fields for every parameter property? Not to speak that this would not be aware of 1001 other reasons for a StateHasChanged to occur (message bus messages, etc.).

Further `ShouldRender` is the absolutely wrong candidate when I use `OnParametersSetAsync` to load complex data from other servers.

With the use of `IEquatable<T>` or `IComparable<T>` this could be implemented in one single place and it would not lead to surprises that `DateTime` works well while `TimeSpan` does not.

**Comment by SteveSandersonMS** [comment]
How would IEquatable/IComparable help? When an object mutates, its older state no longer exists to compare against.

You’re right that implementing ShouldRender may involve maintaining snapshots of your parameter values so you can compare them against the values on subsequent calls. But only your code can do that, not the framework, because only you know how or if your types can be cloned. The framework’s default therefore is to be conservative and treat all values as potentially changed (except some special cases with known primitives), and this is the extension point where you can plug in more sophisticated handling if you want and need the perf optimisation.

**Comment by springy76** [comment]
> When an object mutates, its older state no longer exists to compare against.

Now I wonder how the "special cases with known primitives" work. Can you give me a hint where and how these known primitives are handled? Does it happen at runtime or at .razor->.cs pre-compilation time?

**Comment by SteveSandersonMS** [comment]
It’s here: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/ChangeDetection.cs
