### ISSUE TITLE
Align TestHost.WebSocketClient with System.Net.WebSockets.ClientWebSocket

### ISSUE THREAD

**Issue by damianh** [aspnet/AspNetCore#8951]
When using TestHost, we use a real `HtppClient`. This means that "outside-in" testing code is exercised against the same type in tests that is used in real world. (Yes, internally, the indirection is handled via a custom handler). This makes testing between two services easier as the HttpClient code used in service A to call service B, is essentially the same that used in service B's tests. This is nice symmetry and also allows in-memory behavior integration testing with environmental dependency i.e. port ( https://github.com/damianh/ProxyKit#26-testing )

However, TestHost's `WebSocketClient` is completely unrelated  to the real one `System.Net.WebSockets.ClientWebSocket`. So now client code that uses the latter is not the same as test code that uses the former. I am unable to use it in the aforementioned  And looking through the sources, there are differences that might mean different behaiour?

It's clear that `ClientWebSocket` doesn't have the same concept as `HttpClient`s `HttpMessageHandler` so I have no suggestion as to how this might be achieved unfortunately except perhaps adding an interface that both implementations conform to.

**Comment by Tratcher** [comment]
Either way you end up with a WebSocket so Send, Receive, Close, and Abort are all shared APIs.

Connect and Options are the largest points of divergence. ClientWebSocket's APIs are not virtual, nor is it straightforward to retroactively add an interface to netstandardX.X.

I think the only way you'd get a common API is with a unifying wrapper and a factory.

**Comment by damianh** [comment]
Assembly neutral interface? 😄 

I can do that, but it's not going to be adopted unless that unifying wrapper / interface is in corefx or shipped from aspnet core team.

**Comment by Tratcher** [comment]
Understood. It'd help if you could do a rough draft of the API though. Connect is easy to abstract but the options look messy.

**Comment by damianh** [comment]
I'll see if I can take a look

**Comment by anurse** [comment]
Agree with @Tratcher here, it'd help a lot to get an idea of the API for this wrapper. This is something that SignalR has to deal with too so it might be worth a look. It's not possible to run the SignalR client through `TestServer` right now because it creates a `ClientWebSocket`. If there was an abstraction over the connection behavior, that could be used in the SignalR client to allow both `ClientWebSocket` and `WebSocketClient` which would enable the `TestServer` scenario there.

Adding `area-signalr` label since this is relevant there (and pinging some SignalR folks for their thoughts @halter73 @mikaelm12 @BrennanConroy). I don't think we have the capacity to do this for 3.0, but it seems interesting.

**Comment by damianh** [comment]
> It's not possible to run the SignalR client through TestServer right now because it creates a ClientWebSocket

This is precisely the reason I created this - was trying SignalR testing with ProxyKit via TestServer...

**Comment by anurse** [comment]
I think #11888 covers the main scenarios we're looking at here. Unifying TestHost's WebSocket client with the "real" type is challenging because the connection semantics are very different. Some improvements here might happen as we design the way in which SignalR will integrate with TestHost.
