### ISSUE TITLE
Supporting calling non-generic instance methods on generic types 

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#9061]
### Describe the bug
I have a generic component wich need some Js interaction. My component is an autocomplete wich listen on the keypress event to launch research. Whe  i try invoke c# method from Js, I have this following Js error 
"Error: System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
"
#### create a generic component, which contain an input type text 

```razor
@typeparam TItem 
@inherits AutoCompleteViewModel<TItem>
<input type="text" id="@Id" class="form-control" value="@Value"> `
```

#### register js on render
```csharp
 protected override async Task OnAfterRenderAsync()
        {
            this.JsRuntime.InvokeAsync<object>("listenAutoComplete", this.Id, new DotNetObjectRef(this));
            await base.OnAfterRenderAsync();
        }

[JSInvokable]
        public void SynchroniseValue(string value)
        {
            if(this.Value != value)
            {
                this.Value = value;
                this.LaunchResearch();
            }
        }
```

```js
function listenAutoComplete(id, control) {
    $("#" + id).keyup(function () {
        var value = $(this).val();
        control.invokeMethodAsync('SynchroniseValue', value);
    });
}
```

### Expected behavior
Have a way to call C# method without error 

### Additional context
My first idea was to use the key-* event of razor, but i was unable to have a satisfaying behavior with ths events (unable to retrieve the current value of my input, binding seem only fire when control lost focus), so i decided to switch on js.
If you have another solution, i take it ;-)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @julienGrd.
You're facing this issue because we currently don't support JSInterop from a generic type.

**Comment by mrpmorris** [comment]
@mkArtakMSFT This PR on the old repo would have fixed it. If I can get approval then I will reimplement it on this repo instead - but I don't want to do that if there is no chance of it being merged in...

https://github.com/dotnet/jsinterop/pull/6

**Comment by SteveSandersonMS** [comment]
@mrpmorris I'd recommend holding off on reimplementing the PR. The reason is that, if we're only supporting calling methods on generic types if it's an *instance* method and the method itself has no generic args [1], then my gut sense is that it should be an extremely small change, on the order of a few lines of code. The previous PR involved some extensive refactoring which I would hope we can avoid.

[1] I do agree this is probably the right restriction, since you probably don't want to let client-side code pass arbitrary type args. There would be security implications if it can force the server to load types (and execute static constructors, etc.) that you never expected it to load.

**Comment by mrpmorris** [comment]
@SteveSandersonMS Hi Steve.
The code was mostly refactored. I extracted out your code for holding lookups so we could have one for static methods and one for instance methods. The lookup method was different because static must have unique names per DLL, but for instance we couldn't do this because we need to allow duplicate names in the DLL that are unique based on hierarchy.

Most of the code is actually test classes.

**Comment by SQL-MisterMagoo** [comment]
FYI - for a workaround, I have found that using a child component to handle the JS Interop works, then I just wired up some Action parameters so the child can notify the Generic parent when something happens.

**Comment by littlejohnjt** [comment]
I am having a similar issue but not necessarily to a component.  I want to basically process JS promises back in C# by passing an instance method to JS to call when a promise succeeds (kind of a promise handler) which would populate a TaskCompletionSource<T> object and return it to C#.  I could then await the call.  So am I to understand that we'll have JS invocation of an instance method from a generic class in Preview 7?  Thanks in advance, BTW you guys rock!

**Comment by lertoo** [comment]
JS invokeMethod to .NET GenericClass<T>.Method() cause TargetException: Object does not match target type, even the parameter is not generic/T.

**Comment by SteveSandersonMS** [comment]
@pranavkm You're already doing/done this, right? Do you want to self-assign and perhaps close as done?

**Comment by pranavkm** [comment]
Merged as part of https://github.com/aspnet/Extensions/pull/2342. I'll keep this open to add a couple of E2E tests with Blazor.
