### ISSUE TITLE
@if in foreach not evaluating correctly

### ISSUE THREAD

**Issue by mxmissile** [aspnet/AspNetCore#9070]
I'm wondering why this `@`if statement is not evaluating correctly.

This code should demonstrate the question:
```
@{
    var list = new List<string> { "test 0", "test 1" };
    var i = 0;
}
@foreach (var item in list)
{
    <div index="@i" item="@if (i == 0){ @i }"></div>
    i++;
}
```
Renders:
```
<div index="0" item=""></div>
<div index="1" item=""></div>
```

Expected:
```
<div index="0" item="0"></div>
<div index="1" item=""></div>
```

Additional, putting a breakpoint on the `<div> @if` shows `i = 2` on the first hit. #confused This is on a razor page if that makes a difference.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mxmissile.
@ajaybhargavb can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@mxmissile please provide a repro project so we can investigate this.

**Comment by mxmissile** [comment]
Added a repo for the project: https://github.com/mxmissile/IfRazorTest

Pages/Index.cshtml contains the above code

Created in Visual Studio 2017 Add New Project

**Comment by ajaybhargavb** [comment]
@mxmissile, this is by design. Because of how we buffer attribute values in Razor, the value of `i` inside the expression in an attribute value is not the same as what it is outside it because it is not evaluated in place. This behavior has existed in all Asp.Net Core releases. We recommend capturing the value outside and render it in the attribute value. So in your case,
```cshtml
@foreach (var item in list)
{
    var value = i == 0 ? i.ToString() : "";
    <div index="@i" item="@value">
    </div>
    i++;
}
```
should produce the expected output.
