### ISSUE TITLE
Getting a "The call is ambiguous between the following methods"

### ISSUE THREAD

**Issue by McHeff** [aspnet/AspNetCore#9113]
So, I have VS2019-Preview, I created a new project (Blazor template), copied a page from my 0.7 project to my 0.9 project, fixed the nuget issues, got everything to run. 

But when I copied over the rest of my pages, I am getting this now: 

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'RuntimeHelpers.TypeCheck<T>(T)' and 'RuntimeHelpers.TypeCheck<T>(Func<Task>)'	PSLM	C:\Users\James\source\repos\PSLM\PSLM\obj\Debug\netstandard2.0\Razor\Pages\Spinner Operations\Search Bale Results\SearchBalesResults.cshtml.g.cs	96	Active"

Line 96 in my html code is this: 

![image](https://user-images.githubusercontent.com/47241975/55631185-b8a58e00-57b7-11e9-9e4b-5f9d4528c72e.png)

It's literally just part of my HTML table?

**Comment by rynowak** [comment]
This is a bug in preview3 that will be fixed in the next release. Perhaps we can find a workaround for this... 

It's strange that line is causing a problem. What's the type of `@lots.ExpiryDate` ? Is it `object`? If that's the case then you probably fix it by using a strong type or adding a cast. 

If you want to pasted in the generated code from `obj\Debug\$tfm\Razor\$pathtoyourfile.g.cs` that might help figure out what you could do to get past this.

**Comment by danroth27** [comment]
No response, so closing
