### ISSUE TITLE
How to connect a .net Corev2.2 Web API to .net Identity Framework?

### ISSUE THREAD

**Issue by wewald** [aspnet/AspNetCore#9295]
For websites that already use .net Identity Management, can't we pass a U&P in a Web API header over TSL to authenticate a user?   If so, can someone provide some snippets and assembly versions?

**Comment by blowdart** [comment]
I'd like to try to unpack this, so I'd like some confirmation of some things

1. Do you mean ASP.NET Core Identity when you say .NET Identity Management?
1. U&P would be username and password?

If those are correct, it would be possible I guess, but we'd never recommend anything like that because you're holding a password in the client beyond the initial authentication. One of the reasons OAuth and OIDC became popular was to get around this sort of practice, which is why in 3.0 we have Identity Server in the API templates for individual authentication, to restrict password entry to one place, and to issue an industry standard API token, a JWT.

**Comment by wewald** [comment]
Hi Barry,


1.1. Regarding Identity, here what it was pre-core<%0dAdding%20ASP.NET%20Identity%20to%20an%20Empty%20or%20Existing%20Web%20Forms%20Project%20...%0dhttps:/docs.microsoft.com/.../aspnet/.../adding-aspnet-identity-to-an-empty-or-existing...%0d>
Adding ASP.NET Identity to an Empty or Existing Web Forms Project ...<%0dAdding%20ASP.NET%20Identity%20to%20an%20Empty%20or%20Existing%20Web%20Forms%20Project%20...%0dhttps:/docs.microsoft.com/.../aspnet/.../adding-aspnet-identity-to-an-empty-or-existing...%0d>
https://docs.microsoft.com/.../aspnet/.../adding-aspnet-identity-to-an-empty-or-existing...<%0dAdding%20ASP.NET%20Identity%20to%20an%20Empty%20or%20Existing%20Web%20Forms%20Project%20...%0dhttps:/docs.microsoft.com/.../aspnet/.../adding-aspnet-identity-to-an-empty-or-existing...%0d>
Jan 21, 2019 - NET Identity Framework has added extension methods on System.Security.Principal.IIdentity that allows you to get the UserName and UserId ...

2.       Yes, U&P is username and password.

Regarding the architecture, our Web API calls are for one block of data to be sent to us so we want to keep it simple which means we don’t need to build a whole new system to just accept the U&P.

Walter

**Comment by blowdart** [comment]
There are [SignInAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.signinasync?view=aspnetcore-2.2) functions that would allow you to do this, but considering this is not anywhere close to a standard it's not something we (Microsoft) would want to write a sample for. Even in .NET Framework we didn't have username and password flows to APIs, and the world has obviously moved on from WebForms, so that really can't be used as a comparison.

**Comment by wewald** [comment]
Isn’t passing a U&P through a Web API header over TSL the same as passing the U&P to a regular website over TSL?

**Comment by blowdart** [comment]
No it's not, because you'd be passing it with every request, and you are having to gather it on the client side. A form post on a server means it remains secret from the client and exchanged for a token or a cookie.

**Comment by wewald** [comment]
Let me try to clarify my question.   Say a user is logged into their company website called "A".   They type in their U&P into A and then it sends the U&P in a header over TSL to the Rest API for a different company called "B".   B then authenticates the user and returns information.

Where is there a security issue as its certainly a much simpler architecture?

**Comment by blowdart** [comment]
It's still a custom architecture, so no, we have no plans for any of this. Instead there's ODIC and on-behalf of functionality
