### ISSUE TITLE
typeof(string).GetMethod("Contains") exception

### ISSUE THREAD

**Issue by NigelYu** [aspnet/AspNetCore#9330]
System.Reflection.AmbiguousMatchException:“Ambiguous match found.” in asp.net core

**Comment by davidfowl** [comment]
This isn't an ASP.NET Core specific issue but that's by design. There are multiple overloads of Contains in .NET Core 2.1 and up and you need to be more specific about which one you want (https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?redirectedfrom=MSDN&view=netcore-2.1#overloads)
