### ISSUE TITLE
Move OnActionExecuting to ControllerBase

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/AspNetCore#9379]
### Is your feature request related to a problem? Please describe.
I am building an API so naturally I would like to derive my controller from the `ControllerBase` class.

In all of my my actions I would like to read claims from the `User`. To avoid code duplication in every action method I would like to read the claims once and store it in a field that I can refer to from my actions.

```cs
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class ContainerController : Controller
    {
        private string _container;

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            _container = context.HttpContext.User.FindFirstValue("container");
        }
    }
```

But the `OnActionExecuting` method is not in the `ControllerBase` class, so I have to inherit from the `Controller` class.

### Describe the solution you'd like
Consider moving the `OnActionExecuting` method from `Controller` class to the `ControllerBase` class.

### Describe alternatives you've considered
I've resorted to having my API controllers derive from the `Controller` class instead of the `ControllerBase` class.

**Comment by rynowak** [comment]
You can implement `IActionFilter` on your classes and then implement that method. There's nothing special about the `OnActionExecuting` method on `Controller` - it's just an implementation of `IActionFilter`.

These methods are present on `Controller` for historical/compat reasons and come with some overhead whether you use them or not. We chose to make them truly opt-in on `ControllerBase` since we were starting fresh.
