### ISSUE TITLE
Fix "Invalid Host/Origin" on Firefox in Angular template

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#9400]

**Comment by ryanbrandenburg** [comment]
The one way I've found to do this so far is by passing `--disable-host-check` in the `ng serve` command. That has security implications though, so I'm going to see if I can get it to work in a way that's safer.

**Comment by ryanbrandenburg** [comment]
I've found no way to make this work without the `--disable-host-check` command, and to the best of my knowledge this is purely a problem between webpack-dev-server and Firefox (it seems [Firefox doesn't send the Origin header](https://github.com/webpack/webpack-dev-server/issues/1604#issuecomment-449491014) in this case which is expected by webpack-dev-server).

I talked it over with @blowdart and we agreed that applying the `--disable-host-check` setting in the templates would be bad. The plan for now is to wait for `webpack-dev-server` to fix this and for that to bubble up through Angular.

Options for people experiencing this issue:
1. Ignore it (it only affects Hot-Module reloading, regular site functionality still works).
2. Use a different browser.
3. Set the `--disable-host-check` on your ng serve command (Be sure you don't put this setting in production as it has security implications, and also be sure to revert this when the fix is available).

**Comment by mkArtakMSFT** [comment]
Dupe of https://github.com/aspnet/AspNetCore/issues/7812

**Comment by ryanbrandenburg** [comment]
Not really. You created this issue to separate the Firefox "Invalid Host/Origin" thing from https://github.com/aspnet/AspNetCore/issues/7812, which now tracks the `WebSocket connection to 'ws://localhost:4568/ws/379/lsb17jhg/websocket?X....' failed: WebSocket is closed before the connection is established` error.

I do think we should close this issue though as we have no plan to take an action (except eventually take a new version of Angular, which will happen anyway).
