### ISSUE TITLE
Consider tracing span id and trace id separately in the log

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#9491]
Seems to like open census:

https://github.com/census-instrumentation/opencensus-specs/blob/c3fd41b28fed96ceffc8c35af280d74cacea3ab2/trace/LogCorrelation.md#key-names-for-tracing-data

cc: @SergeyKanzhelev @lmolkova

**Comment by lmolkova** [comment]
We should use [W3C trace context](https://w3c.github.io/trace-context/) notions (OpenCensus names are the same) probably in CamelCase as other scopes. 

To make it useful we need to log parent-id as well otherwise we lose causation in the logs. When an incoming request is received, it gets `TraceId` and `ParentId` in the headers. New `SpanId` is generated. 
So I propose to log all three.

Also, assuming we keep Activity default behavior (which is Request-Id if there is no incoming w3c header), we have to map legacy format to these names. 
- `TraceId` is  `Activity.RootId`
- `ParentId` is `Activity.ParentId`
- `SpanId` is `Activity.Id` // This is likely very confusing.

**Comment by davidfowl** [comment]
Verifying this is blocked on #11404

**Comment by davidfowl** [comment]
![image](https://user-images.githubusercontent.com/95136/60241252-b22f2b80-9867-11e9-8209-767a38312c96.png)

**Comment by davidfowl** [comment]
Verified in 3.0.0-preview7.19326.6
