### ISSUE TITLE
Update SignalR client to Target .Net Standard 2.1

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#9525]
We are currently cross targeting to netcoreapp3.0 for `IAsyncEnmerable` support. It's included in .Net Standard https://github.com/dotnet/standard/pull/1017 we should move to cross target that instead

https://github.com/aspnet/AspNetCore/blob/507a765dfb078f446c445318e7b55ad9f7f5cbe0/src/SignalR/clients/csharp/Client.Core/src/Microsoft.AspNetCore.SignalR.Client.Core.csproj#L5

**Comment by anurse** [comment]
This bit of code will cause some problems (and may already be a problem with our current cross-targeting):

https://github.com/aspnet/AspNetCore/blob/efa9a4e530b2e9ebafe672a78b5ecae2e346d19f/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs#L587-L605

The first problem is that right now it means that if you are running the SignalR 3.0 Client on .NET Core 2.1 (a **supported scenario** since we target .NET Standard 2.0) then we will no longer use WebSockets on Windows 7, despite there being a managed implementation.

The second problem is that if we cross target `netstandard2.1` instead of `netcoreapp`, we lose the ability to do this at all (via `#if`). We may need to do runtime detection here instead. There's no clean API for that though: https://github.com/dotnet/corefx/issues/17452

**Comment by BrennanConroy** [comment]
Moving to preview7

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [ ] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [VERSION]
            * ASP.NET Core Runtime: [VERSION]
            * .NET Core Runtime: [VERSION]
        * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [Microsoft.AspNetCore.SignalR.Client.Core] [3.0.0-preview7.19326.10]
