### ISSUE TITLE
Scaffolding Identity UI gives wrong code in Logout.cshtml.cs

### ISSUE THREAD

**Issue by Ponant** [aspnet/AspNetCore#9545]
.Net core 3.0 Preview4
Scaffolding Identity UI razor pages.
Logout.cshtml.cs has this
`            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return Page();
            }`
whereas it should `RedirectToPage();` instead as found here indeed.
https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Logout.cshtml.cs

**Comment by blowdart** [comment]
@HaoK you were syncing with scaffolding? Can you look at this?

**Comment by HaoK** [comment]
Yep this already is fixed in the scaffolding code 

https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Logout.cs.cshtml#L58

and 

https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Logout.cs.cshtml#L58

**Comment by HaoK** [comment]
That said I'm not sure when scaffolding fixes show up in builds since the fixes are on the VS side
