### ISSUE TITLE
Need the ability to authorize every request

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#9583]
It's a common application requirement to require authorization on all requests, or on all requests past a certain point in the pipeline (maybe after your static files). People have been doing things like this for a long time via global authorization filters on MVC so they didn't have to add `[Authorize]` to every controller.

I'd expect the Authorization middleware to be able to do this, but no, it only works with endpoints, it ignores other requests. Even when working with endpoints there's no current way to apply an auth policy to every endpoint, you have to mark them all individually.

There was briefly in 3.0 a RequiredPolicy that fulfilled this scenario, but it was removed. https://github.com/aspnet/AspNetCore/pull/9399

Sample:
```
            services.AddAuthorization(options =>
            {
                options.RequiredPolicy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
            });
... 
            // Endpoint definitions go here //
            app.Use(UnrestrictedMiddleware);
            app.UseAuthentication();
            app.UseAuthorization();
            app.Use(RestrictedMiddleware);
```

@blowdart

**Comment by Tratcher** [comment]
Workaround: Add your own middleware that does this:
```
            var result = await context.AuthenticateAsync();
            if (!result.Succeeded || !result.Principal.Identity.IsAuthenticated)
            {
                await context.ChallengeAsync();
                return;
            }
            context.User = result.Principal;
```

**Comment by blowdart** [comment]
OK, this sounds simple. To start with. Authorize all the things.

Question for @rynowak - is everything meant to go pipelines?

Then you say "After static files" so now it's "Authorize everything configured after this point".

Would we expect conditionals (Authorize everything but this path)? Or would that be covered via a virtual scheme?

How do we express this so it works if people mix endpoints and other stuff? What is the other stuff?

**Comment by davidfowl** [comment]
Why can’t this be an option on the authorization middleware?

**Comment by Tratcher** [comment]
> Would we expect conditionals (Authorize everything but this path)? Or would that be covered via a virtual scheme?

That'd be covered by AllowAnonymous for endpoints, same as today. For non-endpoints you'd use pipeline ordering (see below).

> How do we express this so it works if people mix endpoints and other stuff? What is the other stuff?

The other stuff is any middleware after UseAuthorization. StaticFiles is an easy example (even if we do play to adapt it to endpoints eventually). If it's before UseAuthorization then it's not restricted, if it's after then it is restricted.

> Why can’t this be an option on the authorization middleware?

That's the proposal, configured via a RequiredPolicy for flexibility rather than just using a bool.

**Comment by davidfowl** [comment]
@Tratcher Can you add the actual proposal to the issue? The APIs and a sample usage to the above? I'm not exactly sure what it would look like and how it would interact with endpoints.

**Comment by Tratcher** [comment]
The feature they just deleted already covered these scenarios (https://github.com/aspnet/AspNetCore/pull/9399/files). 

Apparently it was deleted due to confusion over it's naming.

**Comment by Tratcher** [comment]
I added a sample above.

**Comment by blowdart** [comment]
RequiredPolicy is not a good name. Strop saying that :)

**Comment by blowdart** [comment]
Static files is a great example, because it probably needs more. Static files needs its own policy, so you can have different rules per "directory". Which then throws an overall policy out the window.

**Comment by Tratcher** [comment]
A policy gets to examine the resource. I'd expect the resource to be the request object, so yes it could authorize by directory if needed.

I think you're overlooking the key ask here. Simple scenarios exist and deserve simple solutions. Yes complex scenarios also exist, but they shouldn't prevent us from providing simple solutions alongside the complex ones.

**Comment by blowdart** [comment]
Of course, but it'd be nice to come up with something that extends

**Comment by rynowak** [comment]
I'm a little confused because my intent was that `DefaultPolicy` would handle this. I'm not pushing back on these requirements, I thought we already did this. 

Here's what I expected the logic to look like:
1.  Do I have an endpoint?
    1a. Does the endpoint have allow anonymous? **let it through**
    1b. Does the endpoint have it's own policy metadata? **use that**
    1c. (endpoint did not replace the policy) **use DefaultPolicy**
2. (I don't have an endpoint) **use DefaultPolicy**

It's called `DefaultPolicy` because it's the policy that gets applied unless there's something more specific to do.

----

If this isn't what `AuthorizeMiddleware` does we should change it to do this. I don't think another feature is needed. The same logic should apply to CORS.

Any other thoughts? Is there a mistake in my reasoning?

**Comment by Tratcher** [comment]
That is not what `AuthorizeMiddleware` is doing, it only has step 1.
https://github.com/aspnet/AspNetCore/blob/667f7ca49104e8a727926efffee869c79bc5f254/src/Security/Authorization/Core/src/Policy/AuthorizationMiddleware.cs#L48-L56

**Comment by rynowak** [comment]
OK. I'm going to send a PR then.

**Comment by davidfowl** [comment]
.Count() == 0, ZOMG 😄

**Comment by rynowak** [comment]
OK. I dug into the code here and I think I understand why there's confusion. 

`DefaultPolicy` *actually means* "use this policy in place of an `[Authorize]` attribute. This setting has been around for a long time (since 2.1 or earlier) and is already defined as `.RequireAuthenticatedUser()`. 

It's not really what you want to use `DefaultPolicy` for what I described above because it **changes the meaning** of `[Authorize]`.

Furthermore, I think the right thing to do is make this new setting part of the middleware instead of part of the existing options class. 

There were two problems with require policy (from my point of view):
- The name feels bad (because the good name was already taken)
- It was on the global options, but it can't be implemented by MVC/SignalR - it's specific to the middleware

The problem that I see with @Tratcher 's proposed API (first post) is reusing `AuthorizationOptions` for the middleware. The `IAuthorizationPolicyProvider` is tied to the options instance that comes from DI. If we stick `AuthorizationOptions` in the middleware you'll end up with a wierd situation where there are two sources of truth.

**Comment by HaoK** [comment]
Resolved by https://github.com/aspnet/AspNetCore/pull/9759 and the new FallbackPolicy
