### ISSUE TITLE
Blazor Server Side does not render Bootstrap correctly

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#9606]
Hello;
If I run the following code in a regular HTML page the navbar renders properly, but if I put it in the index.razor and run it, the navbar renders incorrectly.

```html
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Books</a>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Course</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Price</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Fact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul>
        </nav>
    </div>
```

![code](https://user-images.githubusercontent.com/7861196/56462677-4f1ba700-6395-11e9-8a5a-c79fed9b9a1a.png)

![nav](https://user-images.githubusercontent.com/7861196/56462662-17146400-6395-11e9-8be9-c9fdec480b39.png)

UPDATE 1: As I've done more tests, it seems like most of the problems relate to Navs and Navbar classes/component, so far. I'm testing more BS components to which ones have issues and I will add more UPDATES.

UPDATE 2: Seems like those components that rely on the BS jQuery, do not render correctly, which makes sense as MSFT is no longer using jQuery. Is this the correct understanding and the reason for the render problems?

**Comment by Andrzej-W** [comment]
@BenHayat your regular HTML page probably contains reference to Bootstrap CSS file only. Default Blazor template have these two lines:
```html
<link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
<link href="css/site.css" rel="stylesheet" />
```
As you can see there is `site.css` which is second and definitions from this file override definitions from `bootstrap.css` file. Default Blazor application has vertical menu and you can find a lot of overrides for navbar and nav-item classes in `site.css`. One of them is
```css
.nav-item:first-of-type {
        padding-top: 1rem;
    }
```
and this is the reason why `Home` menu item is not correctly positioned in you horizontal menu. If you want to use more traditional Bootstrap layout you should probably remove almost all definitions from `site.css` file.

### Summary
It is not a bug and it is not related to jQuery. Of course you have to take into account that all dynamic Bootstrap features require JavaScript/jQuery. One of those features is dropdown menu. Usually you can relatively easy reimplement this JavaScript/jQuery functionality in pure Blazor because Bootstrap simply adds/removes some CSS class in response to `onclick` or similar events. There are already some projects where people try recreate this for you. Look here: https://github.com/AdrienTorris/awesome-blazor for all of them, and especially this:
https://bootstrapdemo.blazorise.com/
https://github.com/stsrki/Blazorise

**Comment by BenHayat** [comment]
@Andrzej-W;
You are correct sir, and I'm glad it's not a bug.
I will check out the links and close this issue.
Thank you!!!
