### ISSUE TITLE
typeparam bind error

### ISSUE THREAD

**Issue by cores-system** [aspnet/AspNetCore#9632]
Hi, in Blazor 0.10 such code stopped working

```
@typeparam TItem

<input bind="@line" />

@functions{
    [Parameter]
    TItem line { get; set; }
}
```

This is a build error of version 0.10 or is the ability to typeparam bind removed ?, is there an alternative solution to the problem?

**Comment by cores-system** [comment]
Type of error at build time
`CS0029 C# Cannot implicitly convert type 'string' to`

```
dotnet --version
3.0.100-preview4-011223
```

```
Microsoft Visual Studio Enterprise 2019 Preview 
16.1.0 Preview 1.0
```

**Comment by rynowak** [comment]
This is definitely an issue, but I'm not sure that I'm totally convinced this ever worked unless `TItem` is limited to enums. 

We used to have a generic overload of the binding functionality that didn't use the enum type constraint. It would throw for non-enum types. https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview4-19216-03/src/Components/Components/src/BindMethods.cs#L273

The new methods have a similar method but with the enum constraint. https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/EventCallbackFactoryBinderExtensions.cs#L595

I think we need to address this in general though since we have enums in our programming model. This means we'll need to add a general-purpose bind/converter.

**Comment by rynowak** [comment]
Example of the generated code:

```C#
#pragma checksum "C:\Users\rynowak\source\repos\Blazor1\Blazor1.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "49595bbe8c7c44c17ab89283a7e51479d3e64ea6"
// <auto-generated/>
#pragma warning disable 1591
namespace Blazor1
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Components.Forms;
    using Microsoft.AspNetCore.Components.Layouts;
    using Microsoft.AspNetCore.Components.Routing;
    using Microsoft.JSInterop;
    using Blazor1.Shared;
    public class Blazor1<T> : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            builder.AddMarkupContent(0, "<h3>Blazor1</h3>\r\n\r\n");
            builder.OpenElement(1, "input");
            builder.AddAttribute(2, "type", "text");
            builder.AddAttribute(3, "value", Microsoft.AspNetCore.Components.BindMethods.GetValue(value));

            // There is no generic version of CreateBinder 
            builder.AddAttribute(4, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => value = __value, value));
            builder.CloseElement();
        }
        #pragma warning restore 1998
#line 7 "C:\Users\rynowak\source\repos\Blazor1\Blazor1.razor"
            
    T value;

#line default
#line hidden
    }
}
#pragma warning restore 1591
```

**Comment by rynowak** [comment]
This has been added in **preview 7** - https://github.com/aspnet/AspNetCore/pull/10730
Note that **preview 6** is the next release so you will have to wait a few weeks.
