### ISSUE TITLE
Figure out how runtime compilation + VS \ file watcher works

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9641]
Runtime compilation does watching on it's own. We need to figure out how to disable file watching  from dotnet-watch and VS when the feature is enabled.

Related: #8323

**Comment by natemcmaster** [comment]
No changes to dotnet-watch are required since dotnet-watch is extensible using the `<Watch>` item group. You can use MSbuild conditions to control what it watches. For example, you could put something like this in the WebSDK or a NuGet package (variables are a placeholder for whatever the real-thing is) 

```xml
<ItemGroup Condition="'$(ICanHazNetCoreAppVerison)' &gt;= 3.0 AND '$(ICanHazRuntimeCompilation)' == 'false'">
   <Watch Include="$(MSBuildProjectDirectory)\**\*.cshtml" />
</ItemGroup>
```

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe of https://github.com/aspnet/AspNetCore/issues/9644
