### ISSUE TITLE
Bug with _Import.razor file

### ISSUE THREAD

**Issue by darren-zdc** [aspnet/AspNetCore#9681]
### Describe the bug
I realize in preview 4, _viewimport.cshtml has been changed to _Import.razor file. I used to include `@using Microsoft.JSInterop` inside the _viewImport.cshtml file, but now it seems to not working anymore after I place that inside the _Import.razor file. I have to include the code `@using Microsoft.JSInterop` inside every of my component class. 

### To Reproduce
1. Use the Blazor server-side template
2. Add `@inject IJSRuntime JSRuntime` at the beginning of the `Counter.razor`
3. Then, it is not happy, even _Import.razor file has `@using Microsoft.JSInterop`

Hope they are some examples of using the _Import.razor file.

**Comment by darren-zdc** [comment]
The visual studio seems not to recognize the syntax.
I downloaded the latest template. And upgraded the visual studio to 16.0.2

**Comment by rjmr97** [comment]
I'm also having problems related to _Imports.razor.
No problems building or running the application though.

Below are some examples of what happens when using the blazor (client-side) template on Visual Studio 2019 16.0.2:

![image](https://user-images.githubusercontent.com/30321188/56602397-49240100-65f5-11e9-96c0-1d0dae3d42c5.png)

![image](https://user-images.githubusercontent.com/30321188/56602622-d23b3800-65f5-11e9-9dfe-e2797faac828.png)


And it shows me none of the `@using` are needed:
![image](https://user-images.githubusercontent.com/30321188/56602920-74f3b680-65f6-11e9-805a-2c3726d533a0.png)

**Comment by SteveSandersonMS** [comment]
You need to use a VS16.1 preview release for current versions of Blazor.

**Comment by niconico49** [comment]
the problem is.... I have already the VS16.1 preview release!!!!!

**Comment by rjmr97** [comment]
Installed version 16.1 preview 2 and everything works now, thanks!
