### ISSUE TITLE
.csproj .razor .cshtml reference

### ISSUE THREAD

**Issue by Janisku7** [aspnet/AspNetCore#9724]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example. I'm am trying to do [...] but [...]
as Continue to use Blazor components with .cshtml extension you used to had `<_RazorComponentsInclude>`tag 
### Describe the solution you'd like
so if there was way to do that with razor pages and views like so `<_RazorPagesInclude>` & `<_RazorViewsInclude>` would make able to direct those to .razor file extension if user use .cshtml for blazor 

### Describe alternatives you've considered
for Blazor it could be `<_BlazorInclude>` or `<_BlazorComponentsInclude>` 

### Additional context
Those above would be when using `useMVC();` or have set `useBlazor();` `useRazorPages();`

**Comment by pranavkm** [comment]
The `_RazorComponentsInclude` flag existed as a stop-gap until tooling support for `.razor` files landed. The RazorSDK eventually stop using the flag. You may use the `RazorComponent` itemgroup to indicate component files and `RazorGenerate` itemgroup to indicate Razor view or Razor page files:

```xml
<ItemGroup>
   <RazorComponent Include="*\*.foo" />
   <RazorGenerate Include="*\*.baz" />
</ItemGroup>
```

Changing the extension for Razor component files should generally work since there isn't a runtime component that relies on the file extension. MVC's runtime compilation specifically looks for the `.cshtml` extension. You will have to author a custom view engine to reason about this. The Razor compiler hardcodes the `_ViewImports.cshtml` and `_Imports.razor` files. There isn't a way to change these.
