### ISSUE TITLE
[Blazor] Binding not working properly

### ISSUE THREAD

**Issue by tezine** [aspnet/AspNetCore#9745]
Hi, It seems Blazor change detection doesn't work properly. I have to call StateHasChanged() often in order to refresh the UI since even when a variable (bound) changes, the UI is not refreshed automatically.
Example: I have a component called MyButton as below:
```
<button onclick="@OnClicked">Text</button>

@functions{
    [Parameter] protected Action<UIMouseEventArgs> OnClicked { get; set; }        
    protected void BtnClicked(UIMouseEventArgs e) {
            OnClicked?.Invoke(e);
     }
}
```
If I use the component above in a Page like this:
```
@page "/mypage"
@if (loading) {
    <MyProgressBar></MyProgressBar>
}
<MyButton OnClicked="@OnBtnClicked"/>

@functions{
   protected bool loading=false;
    protected async void OnBtnClicked(UIMouseEventArgs args) {
	loading = true;
	ECoordinate eCoordinate= await gisService.GetAddressOfPostalCode(eBaseAddress.postalCode);
	loading = false;
 }
}
```
the component MyProgressBar appears whenever the user clicks, but it doesn't disappear when after the code `ECoordinate eCoordinate= await gisService.GetAddressOfPostalCode(eBaseAddress.postalCode);` is completed. 

This is quite annoying. If I set the returned value into a Input, the Input is not refreshed with the returned value.
If I render the button using RenderTreeBuilder, it gets even worse. The progress never appears when I click on the button.

**Environment**
Blazor 0.9.0-preview3-19154-02 on Windows 10 64bits and dotnet 3.0.100-preview3-010431.

**Comment by rjmr97** [comment]
For this to work without a `StateHasChanged()` call, your event handler needs to return a Task.

This means changing your `Action<>` into a `Func<>`, example below:

```
<button onclick="@OnClicked">Text</button>

@functions{
    [Parameter]
    protected Func<UIMouseEventArgs, Task> OnClicked { get; set; }
}
```

```
@if (loading)
{
    <div>LOADING</div>
}

<MyButton OnClicked="@OnBtnClicked" />

@functions{
    protected bool loading = false;

    private async Task OnBtnClicked(UIMouseEventArgs args)
    {
        loading = true;

        await Task.Delay(2000);

        loading = false;
    }
}
```

**Comment by enetstudio** [comment]
@tezine, this line: 
`<button onclick="@OnClicked">Text</button>`

Should be :
'<button onclick="@BtnClicked">Text</button>'

The value assigned to the onclick attribute should be the name of the method to call, not the Action delegate OnClicked. This is also why you can't access the UIMouseEventArgs  parameter.

Incidentally, I believe that it is preferable to use the EventCallback<UIMouseEventArgs > rather than Action<UIMouseEventArgs >

Hope this helps...

**Comment by enetstudio** [comment]
@tezine, this line:
<button onclick="@OnClicked">Text</button>

Should be :
`<button onclick="@BtnClicked">Text</button>`

The value assigned to the onclick attribute should be the name of the method to call, not the Action delegate OnClicked. This is also why you can't access the UIMouseEventArgs parameter.

Incidentally, I believe that it is preferable to use the EventCallback rather than Action

Hope this helps...

**Comment by enetstudio** [comment]
@tezine, this line:
`<button onclick="@OnClicked">Text</button>`

Should be :
<button onclick="@BtnClicked">Text</button>

The value assigned to the onclick attribute should be the name of the method to call, not the Action delegate OnClicked. This is also why you can't access the UIMouseEventArgs parameter.

Incidentally, I believe that it is preferable to use the EventCallback rather than Action

Hope this helps...

**Comment by enetstudio** [comment]
@tezine, this line:
`<button onclick="@OnClicked">Text</button>`

Should be :
`<button onclick="@BtnClicked">Text</button>`

The value assigned to the onclick attribute should be the name of the method to call, not the Action delegate OnClicked. This is also why you can't access the UIMouseEventArgs parameter.

Incidentally, I believe that it is preferable to use the EventCallback rather than Action

Hope this helps...

**Comment by enetstudio** [comment]
@rjmr97, the source of problem is entirely different,and so is the solution...

**Comment by tezine** [comment]
Hi @rjmr97, thank you for your response. It worked perfectly. 
I just think that it's cumbersome the way blazor data binding is working. In my opinion, it should have a better change detection mechanism without requiring the developer to use Func and Task in order to work properly. There are many cases where I just call StateHasChanged(), because change detection didn't work.

**Comment by rjmr97** [comment]
You're welcome! I don't know much about how events work but I would guess blazor listens for when the task completes and then calls StateHasChanged(). I don't know if they could have done it any other way.

If you're happy with the solution feel free to close the issue.

**Comment by danroth27** [comment]
@tezine We added support for `EventCallbacks` that should address this scenario: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#eventcallback. Use EventCallback<T> instead of Action<T> and then rerendering should get handled correctly for you.
