### ISSUE TITLE
.NetCore 2.2 not using ViewFeature or IRazorCompiledItemprovider

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#9748]
_From @ShaZeh on Wednesday, 24 April 2019 03:54:55_

.NetCore 2.2 not using ViewFeature or IRazorCompiledItemprovider

I recently made a custom IApplicationFeature for ControllerFeature which is added after adding MVC to the services 👍 

```c#
services.AddMvc()
.ConfigureApplicationPartManager(apm =>
 {
      apm.FeatureProviders.Add(new CustomControllerProvider(typeof(Startup).Assembly));
  // apm.FeatureProviders.Add(new CustomViewProvider(typeof(Startup).Assembly));
  // apm.ApplicationParts.Add(new CustomRazorViewProvider(typeof(Startup).Assembly)); 
})
```

While this appear to work fine for the ControllerFeature, .net core seems to ignore any changes made in in the ViewFeature or RazorCompiledItemProvider.

When using the ViewFeature provider, the code execute PopulateFeature multiple time (for each assembly I am assuming) and even if I clear the entire list of ViewDescriptors, the views appear to load fine as if no changes had been done. 

I thought it was perhaps because the ViewFeature is now marked as obsolete, so I have tried implementing the IRazorCompiledItemProvider as an application part as suggested. However the results are even worse, views are still loaded even if no items are returned by the CompiledItems property.

I am starting to believe that something silly might have been missed, do we need to do anything unusual within our controllers to obtain the views such as using dependency injection with a specific type or it should just works with the embedded View() method.

Sorry if I might have misunderstood how the feature should work, there is not much documentation about it. I haven't tested adding views yet , perhaps these implementations only support adding elements as opposed to the ControllerFeature which support both adds and removes. It would still be an issue regardless though.

_Copied from original issue: dotnet/core#2629_

**Comment by Eilon** [comment]
_From @Eilon on Wednesday, 24 April 2019 20:01:43_

@javiercn / @pranavkm - any ideas on this? Should we move this issue to AspNetCore?

**Comment by Eilon** [comment]
_From @pranavkm on Thursday, 25 April 2019 02:33:38_

> Should we move this issue to AspNetCore?

Yes please

**Comment by javiercn** [comment]
@pranavkm will know better. Also, we should kill the obsolete viewfeatureprovider.

**Comment by pranavkm** [comment]
> However the results are even worse, views are still loaded even if no items are returned by the CompiledItems property.

Could you explain what it is that you're trying to do? That should help us guide you better.

> Also, we should kill the obsolete viewfeatureprovider.

@javiercn it's been removed in 3.0.

**Comment by ShaZeh** [comment]
Simply removing views from the available collection, it really is a basic use case. Sometimes, an additional library has to modify how certain views are used and to allows that, the ones currently registered have to be removed to prevent conflicting with the newer ones. 

This works perfectly with controllers but is somehow a problem with views.

The reason why it appear to be worse using the new is because the collection is not passed over, it is only a read only property and in 2.2, there's isn't much. I remember finding the source code for what could be the RazorCompiledItemProvider that will implement interface and it only seemed to search within the current assembly . With the ViewFeature, all of the views accross all assemblies were already discovered.

**Comment by ShaZeh** [comment]
After investigation the source code, I ended up using a workaround and implementing an IViewCompilerProvider which does the filtering over there before sending them to the compiler. 

It makes more sense as well to process them after they have been found since they do not represent the final result.  I still don't understand why the feature would be populated differently for the ViewFeature vs the ControllerFeature though.

I guess the issue is more trivial now. I can understand that the logic is a little bit different for the views.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
