### ISSUE TITLE
Hosting SignalR Hub along Server Side Blazor

### ISSUE THREAD

**Issue by dodyg** [aspnet/AspNetCore#9801]
Is it still possible to host Server Blazor and SignalR Hub in the same system and then connect to the SignaR Hub via a Blazor Component? 

I used to be able to do it in Preview 3 but now it simply creates '
```
[2019-04-27T08:55:23.085Z] Error: Microsoft.AspNetCore.SignalR.HubException: Unable to complete handshake with the server due to an error: The protocol 'json' is not supported.
 ```

https://github.com/dodyg/practical-aspnetcore/tree/master/projects/blazor-ss/ChatR

**Comment by glent1** [comment]
It is definitely possible - I have a project working that does just that.  Unfortunately I've moved to preview5 so my code won't necessarily look like yours.  However I can tell you that in preview 5, json is supported without the need for the .AddNewtonsoftJsonProtocol(); - what happens if you remove that?

**Comment by simonziegler** [comment]
Hi @glent1, I'll be needing to do this on preview5 in the coming days. A cheeky question: do you have a sample project you can share? Thanks!

**Comment by BrennanConroy** [comment]
There was an issue in preview4 that broke this, it is fixed in preview5, for now you can apply the workaround detailed here: https://github.com/aspnet/AspNetCore/issues/9627#issuecomment-485500176
