### ISSUE TITLE
[Blazor] Could not execute because the specified command or file was not found.

### ISSUE THREAD

**Issue by jasonkuo41** [aspnet/AspNetCore#9822]
### Describe the bug
Unable to execute ASP.Net Core when shipped with Blazor (client) with an error message in runtime: Could not execute because the specified command or file was not found.

Note that this does not occur with ASP.Net Core 2.2.

### To Reproduce
Steps to reproduce the behavior: (Suspected)
1. Use the latest Blazor version (.Net Core 3 preview 4)
2. Have a space within your default dot-net folder
3. A runtime error occurs.

### Screenshots

![alt text](https://i.imgur.com/uQt0m3M.png)

It says: `dotnet-C:\Users\Jason does not exist.`
where the actual path should be `C:\Users\Jason Kuo`

### Additional context
Include the output of `dotnet --info`

**Comment by rjmr97** [comment]
This was happening to me, see https://github.com/aspnet/AspNetCore/issues/9597. There's an issue with user accounts having spaces in their names.

It was fixed in https://github.com/aspnet/AspNetCore/pull/9659 and will be available in 3.0.0-preview6 (I think).

I fixed my version by replacing the file `C:\Users\USER_NAME\.nuget\packages\microsoft.aspnetcore.blazor.devserver\3.0.0-preview4-19216-03\build\Microsoft.AspNetCore.Blazor.DevServer.props` with the one from the fix

**Comment by pranavkm** [comment]
Like @rjmr97 pointed, this is a dup of https://github.com/aspnet/AspNetCore/issues/9597

**Comment by gregowahoo** [comment]
Why is this closed it still is happening.
