### ISSUE TITLE
New razor files are automatically removed from watch list in *.csproj file

### ISSUE THREAD

**Issue by mansabbloch** [aspnet/AspNetCore#9922]
### Describe the bug
Visual Studio 2019 Preview 2 is automatically removing new `*.razor` files from watch list when explicitly defined to watch all `*.razor` files in `*.csproj`

### To Reproduce
1. Using this version of `ASP.NET Core '3.0 preview 4'` and `Visual Studio '2019 preview 2'`
2. Create Blazor (client) project
3. Add watch for `*.razor` files
```
<Project>
  ...
  <ItemGroup>
    <Watch Include="**\*.razor" />
  </ItemGroup>
</Project> 
```
4. Add new `*.razor` file by copy/past of an existing `*.razor` file.
5. Open `*.csproj` file and notice that new file is excluded from watch list.
```
<Project>
  ...
  <ItemGroup>
    <Watch Include="**\*.razor" />
  </ItemGroup>

  <ItemGroup>
    <Watch Remove="Pages\Index2.razor" />
  </ItemGroup>
</Project> 
```

### Expected behavior
The new `*.razor` files should not be automatically removed from watch list

**Comment by rynowak** [comment]
@Pilchie - related to our discussion the other day. 

@mkArtakMSFT @danroth This is a behavior of the VS project system when you define multiple itemgroups that use globbing to include the same file. In this case, Razor SDK maps `.razor` to `Content`. 

We're also already planning to fix the behavior of `dotnet watch` to watch `.razor` and `.cshtml` by default so that this won't be required. @pranavkm did that go in for preview 6?

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak.
The `dotnet watch` behavior is done. This should be fixed now.

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/AspNetCore/issues/9644
