### ISSUE TITLE
[Blazor Client-Side] Enabling a button with <input> tag binding

### ISSUE THREAD

**Issue by marcominerva** [aspnet/AspNetCore#9925]
I'm using Blazor on .NET Core 3.0.0-preview4 with Visual Studio 2019 16.1.0 Preview 2. I'm using the following code:

```
<input class="form-control" placeholder="Write something..." bind="@newItem" />
<button class="mt-3 btn btn-primary" onclick="@AddTodo" 
         disabled="@string.IsNullOrWhiteSpace(newItem)">Create</button>
 
@functions{
    private string newItem;
}
```

The page correctly starts with the button disabled. However, when I type something, nothing happens. Am I missing something?

**Comment by Andrzej-W** [comment]
This is expected behaviour. `newItem` will be updated in `OnChange` event  - you have to press `TAB` to move focus out of `input` element. You can change your binding to `bind-value-oninput` to see immediate updates after every keystroke. See here https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding

**Comment by marcominerva** [comment]
You're right, thank you for the clarification!
