### ISSUE TITLE
InvalidOperationException: Cannot provide a value for property 'Http' on type 'ej2_blazor_samples.Shared.MainLayout'. There is no registered service of type 'System.Net.Http.HttpClient'.

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#9941]
### Describe the bug
I have migrate my blazor client side samples in to server-side. When i am compile and run it, it will throws the error in browser window "InvalidOperationException: Cannot provide a value for property 'Http' on type 'ej2_blazor_samples.Shared.MainLayout'. There is no registered service of type 'System.Net.Http.HttpClient'."

### Screenshots
![image](https://user-images.githubusercontent.com/31958591/57128486-2e018000-6db1-11e9-897c-46f78d4c1cff.png)

![image](https://user-images.githubusercontent.com/31958591/57128518-4c677b80-6db1-11e9-90b9-16222456e80f.png)

### Additional context
![image](https://user-images.githubusercontent.com/31958591/57128667-c992f080-6db1-11e9-9142-10c446d9942a.png)

This is my startup.cs file:

![image](https://user-images.githubusercontent.com/31958591/57128710-e9c2af80-6db1-11e9-9234-a1220768abe1.png)
![image](https://user-images.githubusercontent.com/31958591/57128727-f3e4ae00-6db1-11e9-9f29-326f2ca642b7.png)

Please help me to resolve this?

**Comment by enetstudio** [comment]
I'm not completely certain, but I believe AddHttpClient has been removed. Anyhow, the HttpClient service is automatically made available to your application, and all you've got to do is to inject it into your components thus:

@inject HttpClient httpClient

**Comment by SteveSandersonMS** [comment]
For server side code, you would normally either make your own `new HttpClient` for each usage, or use `HttpClientFactory`. There isn't one in DI for server-side Blazor by default, and `services.AddHttpClient()` doesn't add one (though I appreciate the name of that is a bit misleading).

So, to fix this, don't do `@inject HttpClient` in your components on the server. Create your own `HttpClient` instances.

**Comment by ccit-spence** [comment]
Is there an example of doing this for Razor Components?  Since you are saying not to use `@inject HttpClient` within a Razor Component then you also lose the `SendJsonAsync` methods?

The examples provided here [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0) Show using Constructor injection in the context of a Razor Page.

How does Constructor Injection work for (small?) Razor Components?  Is the consensus at MS to require the use of Services for HTTP Calls within a Razor Component?

Why is there such a divergence in how Blazor and Razor Components work?

Please forgive the ignorance of my questions, just trying to understand through the docs how to get something to work.

**Comment by SteveSandersonMS** [comment]
> Is there an example of doing this for Razor Components? 

Yes, see the project template's default `FetchData.razor` page. It uses the same technique I mentioned in my previous comment.

> Why is there such a divergence in how Blazor and Razor Components work?

We try to keep them as aligned as possible. The difference for `@inject HttpClient` largely comes down to the fact that, for client-side Blazor, it's extremely common to be making HTTP requests back to your own hosting server, as with any other client-side SPA. For server-side Blazor, it's unlikely you want to do that because your code is already running on the server, so why would you use HTTP to interact with your own APIs on the same server?

**Comment by ccit-spence** [comment]
Thanks for the info, a view point I take with at least some Razor Components is that it would be handy to add them on top of an existing Pages/MVC app.  Then having the Client version of the HttpClient would be handy.  The called service may not actually be within the main application.

Again thanks for the info.

**Comment by SteveSandersonMS** [comment]
You can simply use `new HttpClient` instead of `@inject HttpClient`, or if you really want to use `@inject HttpClient`, register it in your DI container in `Startup.cs`. See ASP.NET Core docs for more information about configuring the DI container.
